### ISSUE TITLE
How To Use Fake Reply ?

### ISSUE THREAD

**Issue by albertstyles312** [Nurutomo/wabot-aq#1]

**Comment by MFarelS** [comment]
> return conn.fakeReply(m.chat, 'Your Text', '62xxxxx@s.whatsapp.net', 'Want Reply')

> return conn.fakeReply(m.chat, 'Ga Tag Admin Kick Loh Awokwaokwaok', '6282146164564@s.whatsapp.net', '*SUBSCRIBE DYMID PROW*')

**Comment by Nurutomo** [comment]
```js
// Group ID (optional) only works on private chat
conn.fakeReply('id chat', 'your text', 'number@s.whatsapp.net', 'wanted text', 'group id')
```

**Comment by agusydk3** [comment]
thank you

**Comment by albertstyles312** [comment]
> ```js
> // Group ID (optional) only works on private chat
> conn.fakeReply('id chat', 'your text', 'number@s.whatsapp.net', 'wanted text', 'group id')
> ```
> 
> Or using exec.js plugin feature by typing this directly on the chat
> `> conn.fakeReply(m.chat, 'text', 'number@s.whatsapp.net', 'fake text')`

how to stop send qris command #jadibot ?

**Comment by MFarelS** [comment]
close issue
