### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Andika856** [Nurutomo/wabot-aq#1006]
Temen gw lagi mencoba bot abang tapi enth knp dapat ini 
![IMG-20220105-WA0823](https://user-images.githubusercontent.com/78887981/148236551-5e322873-9b8d-4242-8574-f052f201291e.jpg)

**Comment by nadjieb08** [comment]
Dapat coy

**Comment by Cosmic-Bug** [comment]
> Temen gw lagi mencoba bot abang tapi enth knp dapat ini 
> ![IMG-20220105-WA0823](https://user-images.githubusercontent.com/78887981/148236551-5e322873-9b8d-4242-8574-f052f201291e.jpg)
> 

Remove the dot [.] after the = in the SHA value

**Comment by Andika856** [comment]
> > Temen gw lagi mencoba bot abang tapi enth knp dapat ini
> > ![IMG-20220105-WA0823](https://user-images.githubusercontent.com/78887981/148236551-5e322873-9b8d-4242-8574-f052f201291e.jpg)
> 
> Remove the dot [.] after the = in the SHA value

Where

**Comment by Cosmic-Bug** [comment]
Bro try a fresh install by cloning again

**Comment by Cosmic-Bug** [comment]
> > > Temen gw lagi mencoba bot abang tapi enth knp dapat ini
> > > ![IMG-20220105-WA0823](https://user-images.githubusercontent.com/78887981/148236551-5e322873-9b8d-4242-8574-f052f201291e.jpg)
> > 
> > Remove the dot [.] after the = in the SHA value
> 
> Where

Try a fresh install by cloning again
