### ISSUE TITLE
Fitur blokir pas telpon kok skrg gada?

### ISSUE THREAD

**Issue by Andika856** [Nurutomo/wabot-aq#1007]
Fitur dmn bot blokir kan nomor pas di telpon kok skrg gada y? Saya tadi coba tes telpon bot tapi bot ga blokir saya

**Comment by Uhdahlah** [comment]
> Fitur dmn bot blokir kan nomor pas di telpon kok skrg gada y? Saya tadi coba tes telpon bot tapi bot ga blokir saya

Karena mungkin untuk beberapa user bot merasa terganggu akan adanya fitur autoblock apalagi user yang masih pelajar pastinya bakal di telponin sama gurunya

**Comment by Andika856** [comment]
> > Fitur dmn bot blokir kan nomor pas di telpon kok skrg gada y? Saya tadi coba tes telpon bot tapi bot ga blokir saya
> 
> Karena mungkin untuk beberapa user bot merasa terganggu akan adanya fitur autoblock apalagi user yang masih pelajar pastinya bakal di telponin sama gurunya

Kalo gitu gmn w enable kan

**Comment by Cosmic-Bug** [comment]
> 

.enable anticall

**Comment by Cosmic-Bug** [comment]
> > > Fitur dmn bot blokir kan nomor pas di telpon kok skrg gada y? Saya tadi coba tes telpon bot tapi bot ga blokir saya
> > 
> > 
> > Karena mungkin untuk beberapa user bot merasa terganggu akan adanya fitur autoblock apalagi user yang masih pelajar pastinya bakal di telponin sama gurunya
> 
> Kalo gitu gmn w enable kan

.enable anticall

**Comment by frmdeveloper** [comment]
> It doesn't work on my bot, i enabled it and when i call it the bot still get the call.

Inggris nya keluar
