### ISSUE TITLE
Qrcode problem in termux

### ISSUE THREAD

**Issue by hnhn12** [Nurutomo/wabot-aq#1010]
My qrcode have spaces between qrCode layers 
![Uploading 16417045277221589246047155456388.jpg…]()

**Comment by Cosmic-Bug** [comment]
> My qrcode have spaces between qrCode layers 
> ![Uploading 16417045277221589246047155456388.jpg…]()
> 

Try again with reducing font size in termux or try with --big-qr parameter.

**Comment by hnhn12** [comment]
> with

Don't work at all

**Comment by Cosmic-Bug** [comment]
> 



> > with
> 
> Don't work at all

Try updating the colors module/dependency
