### ISSUE TITLE
Add WhatsApp Beta Support

### ISSUE THREAD

**Issue by TheKillerMax** [Nurutomo/wabot-aq#1022]
https://github.com/adiwajshing/Baileys/tree/multi-device

**Comment by DikaArdnt** [comment]
> https://github.com/adiwajshing/Baileys/tree/multi-device

Use plugins : https://github.com/ilmanhdyt/ShiraoriBOT-Md

Use Case : https://github.com/DikaArdnt/Hisoka-Morou

**Comment by TheKillerMax** [comment]
> > https://github.com/adiwajshing/Baileys/tree/multi-device
> 
> Use plugins : https://github.com/ilmanhdyt/ShiraoriBOT-Md
> 
> Use Case : https://github.com/DikaArdnt/Hisoka-Morou

I Need Jadibot
