### ISSUE TITLE
#Request Find Contact or Getcontact

### ISSUE THREAD

**Issue by Aidils60** [Nurutomo/wabot-aq#1026]
![IMG_20220126_143059](https://user-images.githubusercontent.com/38816724/151114832-96af096c-834d-4b23-a811-ef924c61cf9b.jpg)

Fitur yang memanfaatkan Bot Resmi dari Aplikasi Getcontact.

Hanya perlu mengirim nomor telepon dengan awalan kode negara +62 kemudian bot akan memberitahu nama asli dari pemilik nomor telepon tersebut.

ada yang bisa bikin gk bang? 🙏

jadi mungkin mekanismenya hampir sama dengan fitur !report atau !request, bot memforward pesan dari user ke nomor resmi bot Getcontact (+44 7990 653714).
setelah Getcontact memberitahu nama pemilik nomornya selanjutnya bot memforward kembali jawaban tersebut ke si user yang melakukan command.

**Comment by Bintang73** [comment]
bisa..

**Comment by algifarr** [comment]
getcontact kudu login user dlu dek
