### ISSUE TITLE
Kenapa gak pakek baileys 3.5.3 ?

### ISSUE THREAD

**Issue by frmdeveloper** [Nurutomo/wabot-aq#1027]
[Kenapa pakek baileys dari github melcanz ?<br><br>kenapa gak pakek baileys dari githubnya adiwajshing yang versi 3.5.3 ?
Kalok versi baru(4.0.0) kan beda metode, dan pasti error](https://translate.google.com/?sl=id&tl=en&text=Kenapa%20pakek%20baileys%20dari%20github%20melcanz%20%3F%0A%0Akenapa%20gak%20pakek%20baileys%20dari%20githubnya%20adiwajshing%20yang%20versi%203.5.3%20%3F%0AKalok%20versi%20baru(4.0.0)%20kan%20beda%20metode%2C%20dan%20pasti%20error&op=translate)

**Comment by BochilGaming** [comment]
> Leave a comment

knp gk pull req?

**Comment by Nikesyg** [comment]
> Leave a comment

lol lu dek

**Comment by frmdeveloper** [comment]
> lol lu dek

sekarang anda

**Comment by frmdeveloper** [comment]
> knp gk pull req?

Lagi gak ada otak

**Comment by SanzGantengz** [comment]
ikod komen ah

**Comment by botstylee** [comment]
> > Leave a comment
> 
> lol lu dek

Nih orang siapa si kok gak enak banget di lihat, kan dia hanya ingin nanya aja

**Comment by unx21** [comment]
> > > Leave a comment
> > 
> > 
> > lol lu dek
> 
> Nih orang siapa si kok gak enak banget di lihat, kan dia hanya ingin nanya aja

Gatau wkwkwkwk

**Comment by Nikesyg** [comment]
Oh

**Comment by frmdeveloper** [comment]
> @botstylee
> Nih orang siapa si kok gak enak banget di lihat, kan dia hanya ingin nanya aja

Nah iya, saya kan cuma nanya. Dia malah menghina saya

**Comment by frmdeveloper** [comment]
> @SanzGantengz
> ikod komen ah

Bang, wa lu kok mati semua. Bagi yang masih hidup

**Comment by frmdeveloper** [comment]
> @Nikesyg
> Oh

Kenapa lu balesnya lewat email ?
Kenapa gak langsung lewat github ?

**Comment by Nikesyg** [comment]
> > @Nikesyg
> > Oh
> 
> Kenapa lu balesnya lewat email ? Kenapa gak langsung lewat github ?

Njir wkwk

**Comment by frmdeveloper** [comment]
> @Nikesyg
> Njir wkwk

Kok malah wkwk ?
Jawab dong baaang

**Comment by Nikesyg** [comment]
Udah anj ☺️, makan aja gk tenang, lu udah makan belum

**Comment by frmdeveloper** [comment]
> @Nikesyg
> Udah anj ☺️, makan aja gk tenang, lu udah makan belum

Saya udah makan sore, saya baru saja pulang ngaji

**Comment by Nikesyg** [comment]
> > @Nikesyg
> > Udah anj ☺️, makan aja gk tenang, lu udah makan belum
> 
> Saya udah makan sore, saya baru saja pulang ngaji

Kgk makan malem bg?

**Comment by frmdeveloper** [comment]
> @Nikesyg
> Kgk makan malem bg?

Jarang. Saya makan malem kalok habis latihan silat.
Kalok gak latihan, gak makan malem

**Comment by Nikesyg** [comment]
> > @Nikesyg
> > Kgk makan malem bg?
> 
> Jarang. Saya makan malem kalok habis latihan silat. Kalok gak latihan, gak makan malem

Ngeri silat 😂, dulu saya minta di ajarin tapi gk ada waktu ;/

**Comment by frmdeveloper** [comment]
> @Nikesyg
> Ngeri silat 😂, dulu saya minta di ajarin tapi gk ada waktu ;/

Saya silatnya malam, habis isya sampai jam 12 malam.
Daripada dirumah gak ada kegiatan

**Comment by Nikesyg** [comment]
Iy gabut, saya mau tidur lanjut besok bang

**Comment by frmdeveloper** [comment]
> @Nikesyg
> Iy gabut, saya mau tidur lanjut besok bang

Bagi nomor wa lu

**Comment by hardianto-cpu** [comment]
> [Kenapa pakek baileys dari github melcanz ?kenapa gak pakek baileys dari githubnya adiwajshing yang versi 3.5.3 ? Kalok versi baru(4.0.0) kan beda metode, dan pasti error](https://translate.google.com/?sl=id&tl=en&text=Kenapa%20pakek%20baileys%20dari%20github%20melcanz%20%3F%0A%0Akenapa%20gak%20pakek%20baileys%20dari%20githubnya%20adiwajshing%20yang%20versi%203.5.3%20%3F%0AKalok%20versi%20baru(4.0.0)%20kan%20beda%20metode%2C%20dan%20pasti%20error&op=translate)

saya tidak tau info. tapi saya di sini cuma berargumen. sepertinya ada sedikit perubahan di baileys melcanz penyesuaian/renovasi atau implementasi dari sumber kode tersebut. yang tentu nya untuk wabot-aq tetap berjalan dengan normal

**Comment by frmdeveloper** [comment]
> @hardianto-cpu
> saya tidak tau info. tapi saya di sini cuma berargumen. sepertinya ada sedikit perubahan di baileys melcanz penyesuaian/renovasi atau implementasi dari sumber kode tersebut. yang tentu nya untuk wabot-aq tetap berjalan dengan normal

Nah, ini baru mastah

**Comment by Nikesyg** [comment]
> > @Nikesyg
> > Iy gabut, saya mau tidur lanjut besok bang
> 
> Bagi nomor wa lu

Ada di gc cari sendiri :)
