### ISSUE TITLE
ytmp4,MP3,play,play2 semua server tidak bisa

### ISSUE THREAD

**Issue by Andika856** [Nurutomo/wabot-aq#1041]
![Screenshot_2022-02-21-18-11-33-41](https://user-images.githubusercontent.com/78887981/154944648-55b06bc9-6036-41ae-92e7-03a28dc051e2.jpg)

**Comment by Andika856** [comment]
![Screenshot_2022-02-21-18-25-22-12](https://user-images.githubusercontent.com/78887981/154946339-0aa267cb-cd9a-4150-b6b9-71ec512bff36.jpg)

**Comment by unx21** [comment]
![Screenshot_20220221-192316_WhatsApp](https://user-images.githubusercontent.com/84166927/154946092-519081cf-026b-4487-82e9-469c5d1239cd.png)

_Aman nih bang 👍_
