### ISSUE TITLE
.pinterest eror 

### ISSUE THREAD

**Issue by Yhaaa12** [Nurutomo/wabot-aq#1050]
Pas menggunakan .pinterest itu sering eror, gk mau keluar gambar nya bang, itu gimana ya cara ngatasin nya

**Comment by unx21** [comment]
> Pas menggunakan .pinterest itu sering eror, gk mau keluar gambar nya bang, itu gimana ya cara ngatasin nya

Rest api nya kalo gak salah

**Comment by Kikii-XyZ** [comment]
> Pas menggunakan .pinterest itu sering eror, gk mau keluar gambar nya bang, itu gimana ya cara ngatasin nya

ada ss pas error gak?

**Comment by Yhaaa12** [comment]
Gk bisa ngirim ss nya bang jadi saya copy aj, nah ini yg keluar pas make fitur pinterest

request to https://api.zeks.xyz/api/pinimg?q=kurumi&apikey=#HIDDEN# failed, reason: getaddrinfo ENOTFOUND api.zeks.xyz

**Comment by Yhaaa12** [comment]
> > Pas menggunakan .pinterest itu sering eror, gk mau keluar gambar nya bang, itu gimana ya cara ngatasin nya
> 
> ada ss pas error gak?

Gk bisa ngirim ss nya bang jadi saya copy aj, nah ini yg keluar pas make fitur pinterest

request to https://api.zeks.xyz/api/pinimg?q=kurumi&apikey=#HIDDEN# failed, reason: getaddrinfo ENOTFOUND api.zeks.xyz

**Comment by Yhaaa12** [comment]
> > Pas menggunakan .pinterest itu sering eror, gk mau keluar gambar nya bang, itu gimana ya cara ngatasin nya
> 
> Rest api nya kalo gak salah

Api key?

**Comment by unx21** [comment]
> > > Pas menggunakan .pinterest itu sering eror, gk mau keluar gambar nya bang, itu gimana ya cara ngatasin nya
> > 
> > 
> > ada ss pas error gak?
> 
> Gk bisa ngirim ss nya bang jadi saya copy aj, nah ini yg keluar pas make fitur pinterest
> 
> request to https://api.zeks.xyz/api/pinimg?q=kurumi&apikey=#HIDDEN# failed, reason: getaddrinfo ENOTFOUND api.zeks.xyz

Domain web nya udah di ganti keknya

**Comment by Yhaaa12** [comment]
> > > > Pas menggunakan .pinterest itu sering eror, gk mau keluar gambar nya bang, itu gimana ya cara ngatasin nya
> > > 
> > > 
> > > ada ss pas error gak?
> > 
> > 
> > Gk bisa ngirim ss nya bang jadi saya copy aj, nah ini yg keluar pas make fitur pinterest
> > request to https://api.zeks.xyz/api/pinimg?q=kurumi&apikey=#HIDDEN# failed, reason: getaddrinfo ENOTFOUND api.zeks.xyz
> 
> Domain web nya udah di ganti keknya

Jadi gimana nih bang?

**Comment by aniq12** [comment]
> > > Pas menggunakan .pinterest itu sering eror, gk mau keluar gambar nya bang, itu gimana ya cara ngatasin nya
> > 
> > 
> > ada ss pas error gak?
> 
> Gk bisa ngirim ss nya bang jadi saya copy aj, nah ini yg keluar pas make fitur pinterest
> 
> request to https://api.zeks.xyz/api/pinimg?q=kurumi&apikey=#HIDDEN# failed, reason: getaddrinfo ENOTFOUND api.zeks.xyz

domain nya ganti jadi https://api.zeks.me

**Comment by Kikii-XyZ** [comment]
> > > > > Pas menggunakan .pinterest itu sering eror, gk mau keluar gambar nya bang, itu gimana ya cara ngatasin nya
> > > > 
> > > > 
> > > > ada ss pas error gak?
> > > 
> > > 
> > > Gk bisa ngirim ss nya bang jadi saya copy aj, nah ini yg keluar pas make fitur pinterest
> > > request to https://api.zeks.xyz/api/pinimg?q=kurumi&apikey=#HIDDEN# failed, reason: getaddrinfo ENOTFOUND api.zeks.xyz
> > 
> > 
> > Domain web nya udah di ganti keknya
> 
> Jadi gimana nih bang?

saran, pake module yg ada di npmjs

**Comment by Yhaaa12** [comment]
> > > > Pas menggunakan .pinterest itu sering eror, gk mau keluar gambar nya bang, itu gimana ya cara ngatasin nya
> > > 
> > > 
> > > ada ss pas error gak?
> > 
> > 
> > Gk bisa ngirim ss nya bang jadi saya copy aj, nah ini yg keluar pas make fitur pinterest
> > request to https://api.zeks.xyz/api/pinimg?q=kurumi&apikey=#HIDDEN# failed, reason: getaddrinfo ENOTFOUND api.zeks.xyz
> 
> domain nya ganti jadi https://api.zeks.me

Cara ganti domain nya gimana?

**Comment by Yhaaa12** [comment]
> > > > > > Pas menggunakan .pinterest itu sering eror, gk mau keluar gambar nya bang, itu gimana ya cara ngatasin nya
> > > > > 
> > > > > 
> > > > > ada ss pas error gak?
> > > > 
> > > > 
> > > > Gk bisa ngirim ss nya bang jadi saya copy aj, nah ini yg keluar pas make fitur pinterest
> > > > request to https://api.zeks.xyz/api/pinimg?q=kurumi&apikey=#HIDDEN# failed, reason: getaddrinfo ENOTFOUND api.zeks.xyz
> > > 
> > > 
> > > Domain web nya udah di ganti keknya
> > 
> > 
> > Jadi gimana nih bang?
> 
> saran, pake module yg ada di npmjs

Hmm

**Comment by aniq12** [comment]
> > > > > Pas menggunakan .pinterest itu sering eror, gk mau keluar gambar nya bang, itu gimana ya cara ngatasin nya
> > > > 
> > > > 
> > > > ada ss pas error gak?
> > > 
> > > 
> > > Gk bisa ngirim ss nya bang jadi saya copy aj, nah ini yg keluar pas make fitur pinterest
> > > request to https://api.zeks.xyz/api/pinimg?q=kurumi&apikey=#HIDDEN# failed, reason: getaddrinfo ENOTFOUND api.zeks.xyz
> > 
> > 
> > domain nya ganti jadi https://api.zeks.me
> 
> Cara ganti domain nya gimana?

config.js

**Comment by Yhaaa12** [comment]
> > > > > > Pas menggunakan .pinterest itu sering eror, gk mau keluar gambar nya bang, itu gimana ya cara ngatasin nya
> > > > > 
> > > > > 
> > > > > ada ss pas error gak?
> > > > 
> > > > 
> > > > Gk bisa ngirim ss nya bang jadi saya copy aj, nah ini yg keluar pas make fitur pinterest
> > > > request to https://api.zeks.xyz/api/pinimg?q=kurumi&apikey=#HIDDEN# failed, reason: getaddrinfo ENOTFOUND api.zeks.xyz
> > > 
> > > 
> > > domain nya ganti jadi https://api.zeks.me
> > 
> > 
> > Cara ganti domain nya gimana?
> 
> config.js

Yg global apikey?
