### ISSUE TITLE
Irulbotz 

### ISSUE THREAD

**Issue by Zairulkhaq** [Nurutomo/wabot-aq#1055]
**Describe the bug**

**To Reproduce**
4. See more

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Zairulkhaq** [comment]
Kalau mau sewa ketik.owner dan kita semua boleh sewa di Irul ganteng

**Comment by Zairulkhaq** [comment]
Hai kalia ketik.owner

**Comment by unx21** [comment]
Hah??

**Comment by Zairulkhaq** [comment]
Bntr owner masih Cass

**Comment by Zairulkhaq** [comment]
`

> 

>

**Comment by Lilithxdef** [comment]
> Maksudnya gimana yah bang ??
> 
> Saya ga paham

:'v

**Comment by unx21** [comment]
> > Maksudnya gimana yah bang ??
> > Saya ga paham
> 
> :'v

😔

**Comment by aniq12** [comment]
keren bang lanjutkan :v

**Comment by shinz-404** [comment]
stres

**Comment by ariffb25** [comment]
stfu
