### ISSUE TITLE
Gak bisa di scan QR

### ISSUE THREAD

**Issue by Wahyudianshar** [Nurutomo/wabot-aq#1057]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Wahyudianshar** [comment]
Help mastah kok gini terus setiap di scan QR :(

**Comment by aniq12** [comment]
gini gmn

**Comment by Wahyudianshar** [comment]
Kayak gitu trus :(

Pada tanggal Sel, 5 Apr 2022 11:19 aniq ***@***.*** menulis:

**Comment by Wahyudianshar** [comment]
Gini terus

**Comment by Wahyudianshar** [comment]
Gimana sih cara kirim screnshot disini

**Comment by Andika856** [comment]
> gini gmn

 fitur WhatsApp web ganti jadi mungkin ada beberapa perubahan keknya

**Comment by Andika856** [comment]
Tadi gw scan QR nya dan nanti malah disuruh scan QR lagi

**Comment by Andika856** [comment]
![Screenshot_2022-04-06-18-54-24-25_7352322957d4404136654ef4adb64504](https://user-images.githubusercontent.com/78887981/161969096-92e59dcc-dedd-434e-aac1-87b827b4b3d6.jpg)

**Comment by Andika856** [comment]
Gw dah lakuin ini berkali kali btw

**Comment by Wahyudianshar** [comment]
Nah akupun kayak gitu jg

Pada tanggal Rab, 6 Apr 2022 19:59 Andika856 ***@***.***
menulis:

**Comment by Wahyudianshar** [comment]
Nah akupun kayak gitu jg

**Comment by mizacg** [comment]
jadi gimana nih soalnya gw kayak gitu juga

**Comment by aniq12** [comment]
https://telegra.ph/file/4fb096de77ee183f82e35.jpg bagian Perangkat Tertaut/Linked Device nya harus gini, dan yg gw lingkarin harus blm join
Kalo bagian Perangkat Tertaut/Linked Device nya gini: https://telegra.ph/file/5547dd9564809e17c87b5.jpg
gabisa karna itu multi device/multi perangkat yg belum support di wabot-aq ini

**Comment by Wahyudianshar** [comment]
@aniq Jadi harus gimana biar perangkat tertaut/linked device nya kayak gitu?

**Comment by Wahyudianshar** [comment]
Tanpa harus menggunakan multi perangkat/device

**Comment by Nikesyg** [comment]
Package.json

**Comment by aniq12** [comment]
> @aniq Jadi harus gimana biar perangkat tertaut/linked device nya kayak gitu?

downgrade versi whatsapp

**Comment by ayamkv** [comment]
WhatsApp ver brp btw?

**Comment by aniq12** [comment]
> WhatsApp ver brp btw?

kurang tau saya kalo itu
