### ISSUE TITLE
Scan QR ga bekerja

### ISSUE THREAD

**Issue by Andika856** [Nurutomo/wabot-aq#1058]
![Screenshot_2022-04-06-18-54-24-25_7352322957d4404136654ef4adb64504](https://user-images.githubusercontent.com/78887981/161992513-09944c82-19d1-4968-9c8f-ebbd6e4a56be.jpg)
Gw udh lakukan ini berkali kali tapi hasil nya masih sama. WhatsApp web baru aja update jadi bisa wawebnya online walaupun hp yg link kan waweb offline. Tapi keknya itu bikin suatu masalah dengan wabot-aq.

**Comment by Kikii-XyZ** [comment]
pake yang versi md aja bro

**Comment by Andika856** [comment]
> pake yang versi md aja bro

Tutor dikit:v

**Comment by Kikii-XyZ** [comment]
> > pake yang versi md aja bro
> 
> Tutor dikit:v

jelajahin aja bro github,
ada kok wabot-aq versi md

**Comment by aniq12** [comment]
> ![Screenshot_2022-04-06-18-54-24-25_7352322957d4404136654ef4adb64504](https://user-images.githubusercontent.com/78887981/161992513-09944c82-19d1-4968-9c8f-ebbd6e4a56be.jpg) Gw udh lakukan ini berkali kali tapi hasil nya masih sama. WhatsApp web baru aja update jadi bisa wawebnya online walaupun hp yg link kan waweb offline. Tapi keknya itu bikin suatu masalah dengan wabot-aq.

iya itu bagian scan nya jadi md, tapi wabot-aq ini gk supp sama md

**Comment by Andika856** [comment]
> > ![Screenshot_2022-04-06-18-54-24-25_7352322957d4404136654ef4adb64504](https://user-images.githubusercontent.com/78887981/161992513-09944c82-19d1-4968-9c8f-ebbd6e4a56be.jpg) Gw udh lakukan ini berkali kali tapi hasil nya masih sama. WhatsApp web baru aja update jadi bisa wawebnya online walaupun hp yg link kan waweb offline. Tapi keknya itu bikin suatu masalah dengan wabot-aq.
> 
> iya itu bagian scan nya jadi md, tapi wabot-aq ini gk supp sama md

Punya solusi g?

**Comment by Andika856** [comment]
> > ![Screenshot_2022-04-06-18-54-24-25_7352322957d4404136654ef4adb64504](https://user-images.githubusercontent.com/78887981/161992513-09944c82-19d1-4968-9c8f-ebbd6e4a56be.jpg) Gw udh lakukan ini berkali kali tapi hasil nya masih sama. WhatsApp web baru aja update jadi bisa wawebnya online walaupun hp yg link kan waweb offline. Tapi keknya itu bikin suatu masalah dengan wabot-aq.
> 
> iya itu bagian scan nya jadi md, tapi wabot-aq ini gk supp sama md

Kalo gitu gmn gantinya

**Comment by Andika856** [comment]
> > ![Screenshot_2022-04-06-18-54-24-25_7352322957d4404136654ef4adb64504](https://user-images.githubusercontent.com/78887981/161992513-09944c82-19d1-4968-9c8f-ebbd6e4a56be.jpg) Gw udh lakukan ini berkali kali tapi hasil nya masih sama. WhatsApp web baru aja update jadi bisa wawebnya online walaupun hp yg link kan waweb offline. Tapi keknya itu bikin suatu masalah dengan wabot-aq.
> 
> iya itu bagian scan nya jadi md, tapi wabot-aq ini gk supp sama md

Bisa g bang jelaskan apa itu md? Kalo Abang jelasin saya jadi lebih paham nanti.
