### ISSUE TITLE
Update untuk fitur multi-device. 

### ISSUE THREAD

**Issue by primahagantha** [Nurutomo/wabot-aq#1059]
Karena WhatsApp saat ini udah haruskan namanya multi device. dari baileys juga sudah update

**Comment by aniq12** [comment]
> Iya bang, mohon bersabar. Pemilik repository ini belum kembali..

:v

**Comment by aniq12** [comment]
> > Iya bang, mohon bersabar. Pemilik repository ini belum kembali..
> 
> Tau, tapi aku perlu karena WhatsApp mendadak banget multidevice

cari aja, banyak kok md yg pake base nuru

**Comment by primahagantha** [comment]
> ![Screenshot_2022-04-13-22-57-57-038_com android chrome](https://user-images.githubusercontent.com/79745902/163221710-d67436f3-c218-4a7c-bca9-9788a3836ff6.jpg) Nih udah ada SC multi device, fitur udh ada 200+ dan fitur game udh ada 20+ 🙏

hmmmm kok di private

**Comment by ariffb25** [comment]
baca docs, knp ga bikin sendiri (?)

**Comment by primahagantha** [comment]
> baca docs, knp ga bikin sendiri (?)

masih pemula

**Comment by Aiinne** [comment]
https://github.com/Aiinne/Aine-MD

**Comment by marlos7** [comment]
I'm using this report, I recommend it!
https://github.com/jonalan7/Hydra-bot

**Comment by RC047** [comment]
> baca docs, knp ga bikin sendiri (?)

awoakakak
