### ISSUE TITLE
ga bisa menjalankan Bot

### ISSUE THREAD

**Issue by X3NNN** [Nurutomo/wabot-aq#1060]
![image](https://user-images.githubusercontent.com/93273094/162666297-6ab98519-413b-468d-a4b0-3842a34df17b.png)
ada yang tau ga ini kenapa ? setiap setelah jalankan npm start sellalu gini padahal sebelumnya tidak ada masalah apa apa

**Comment by aniq12** [comment]
coba scan ulang

**Comment by X3NNN** [comment]
gatau ngaruh atau gak, setelah di scan masih blum work juga, tapi pas nyoba update repository + hapus  file session.data (yang buat sesi login wa) langsung bisa, kalo hapus file ini bakal diminta scan barcode lagi...
![image](https://user-images.githubusercontent.com/93273094/163146218-d1704012-2c9f-48df-a617-31784770bccc.png)

**Comment by aniq12** [comment]
> gatau ngaruh atau gak, setelah di scan masih blum work juga, tapi pas nyoba update repository + hapus file session.data (yang buat sesi login wa) langsung bisa, kalo hapus file ini bakal diminta scan barcode lagi... ![image](https://user-images.githubusercontent.com/93273094/163146218-d1704012-2c9f-48df-a617-31784770bccc.png)

iya maksud saya gitu, apus file itu buat scan ulang..
