### ISSUE TITLE
UPDATE MULTI DEVICE MIN PLISS,YG LAIN UDAH PADA UPDATE,GW TETAP SETIA NUNGGU NI SC UPDATE 

### ISSUE THREAD

**Issue by Tsukasa-io** [Nurutomo/wabot-aq#1079]
Gw tetep nunggu ni SC update ke MD,dah 1 tahun lebih pake SC ini soalnya

**Comment by aniq12** [comment]
https://github.com/Nurutomo/mahbod
kalo sc wabot-aq ini kurang tau kapan jadi md atau mungkin gk akan jadi md

**Comment by Aiinne** [comment]
Gaasss...

**Comment by Aiinne** [comment]
https://github.com/Aiinne/Aine-MD

**Comment by Poks-A78** [comment]
> https://github.com/Aiinne/Aine-MD

Ini yang versi multidevice ya?

**Comment by marlos7** [comment]
I'm using this report, I recommend it!
https://github.com/jonalan7/Hydra-bot
