### ISSUE TITLE
Stiker Caption ga bisa, tapi kalo reply bisa

### ISSUE THREAD

**Issue by syahrularranger** [Nurutomo/wabot-aq#108]
Ini kok sticker caption nya ga bisa ya? Bisa nya reply.. 🙏🙏

**Comment by Nurutomo** [comment]
Kalo diri sendiri yang kirim gabisa, soalnya bot mendeteksi media yang belum diupload

**Comment by ariffb25** [comment]
kalo diri sendiri gabisa, kalo user yang ngirim bisa2 aja

**Comment by syahrularranger** [comment]
> Kalo diri sendiri yang kirim gabisa, soalnya bot mendeteksi media yang belum diupload

![Screenshot_20210312-140305~2](https://user-images.githubusercontent.com/74013086/110904783-0f208d00-833c-11eb-9e1d-33329e99477f.png)

**Comment by syahrularranger** [comment]
> kalo diri sendiri gabisa, kalo user yang ngirim bisa2 aja

Apa karena ini?.. tpi imagemagick, ffmepg, libwebp, udah diinstall smua
![Screenshot_20210312-140728~2](https://user-images.githubusercontent.com/74013086/110905063-776f6e80-833c-11eb-93d9-df06b1fcdc3b.png)

**Comment by Nurutomo** [comment]
Itu disuruh install imagemagick
