### ISSUE TITLE
Ini pakai API kita sendiri atau gimana mimin

### ISSUE THREAD

**Issue by h4cking-tutorial** [Nurutomo/wabot-aq#1109]
Ini pakai API kita sendiri atau gimana mimin aku bingung di README nya gak dijelasin tentang ini.

![Code_CnbLXAuCO4](https://user-images.githubusercontent.com/117315918/200133190-7d1fc6fd-2761-4582-bd47-473014e48eaf.png)

**Comment by Nurutomo** [comment]
ubahnya di config
