### ISSUE TITLE
bug lib/y2mate.js 

### ISSUE THREAD

**Issue by vinimods2** [Nurutomo/wabot-aq#1110]
bug lib/y2mate.js 
 no download mp3 audio

**Comment by HabustNyeh** [comment]
> bug lib/y2mate.js no download mp3 audio

Console log?

**Comment by vinimods2** [comment]
> > bug lib/y2mate.js no download mp3 audio
> 
> Console log?

![Screenshot_20221225-060612_Termux Mod By Kztutorial](https://user-images.githubusercontent.com/78501165/209462434-b2708081-b036-45eb-8539-9684490bba07.jpg)

**Comment by vinimods2** [comment]
this is the case mp3 error in parentelement

**Comment by HabustNyeh** [comment]
case 'mp3':
            list = {
                '128kbps': Object.fromEntries([...table.querySelectorAll('td > a[href="#"]')].filter(v => /\.3gp/.test(v.innerHTML)).map(v => [v.innerHTML.match(/.*?(?=\()/)[0].trim(), v.parentElement.nextSibling.nextSibling.innerHTML]))
            }
            break
