### ISSUE TITLE
Connect attempt X failed: error: unexpected server response 404 retrying

### ISSUE THREAD

**Issue by Xnuvers007** [Nurutomo/wabot-aq#1114]
![IMG_20230118_211013](https://user-images.githubusercontent.com/62522733/213193122-02a42f03-3f21-44d7-b1dc-4a789f5f9706.jpg)

**Comment by Xnuvers007** [comment]
Solusinya donk termux

**Comment by ApriyantoCsPro** [comment]
> ![IMG_20230118_211013](https://user-images.githubusercontent.com/62522733/213193122-02a42f03-3f21-44d7-b1dc-4a789f5f9706.jpg)

I have the same problem, how to fix it?
