### ISSUE TITLE
Ini knp bang? 

### ISSUE THREAD

**Issue by Lilithxdef** [Nurutomo/wabot-aq#1119]
WARN [2023-02-25 05:53:47.663 +0000] (11713): connect attempt 1 failed: Error: Unexpected server response: 404, retrying...
    class: "Baileys"
    error: {}
WARN [2023-02-25 05:53:51.910 +0000] (11713): connect attempt 2 failed: Error: Unexpected server response: 404, retrying...
    class: "Baileys"
    error: {}
WARN [2023-02-25 05:53:56.0

**Comment by adam321123** [comment]
bang udah bisa? solusinya donmgg
