### ISSUE TITLE
Update lagi??

### ISSUE THREAD

**Issue by Nurutomo** [Nurutomo/wabot-aq#1129]
- [ ] Ubah kode menjadi ESM `require` jadi `import`
- [ ] Menghindari penggunaan `global`
- [ ] Update versi baileys agar support via nomor
- [ ] Otomatis update kode yang diubah

**Comment by Aiinne** [comment]
GASS KAN

**Comment by Ftwrr** [comment]
aku bisa kerjain esm nya bang :3

**Comment by Nurutomo** [comment]
> aku bisa kerjain esm nya bang :3

Comtact me: +62 851-7685-4404
