### ISSUE TITLE
 Bagaimana saya bisa memberikan pengalaman kepada nomor / pengguna dari konsol atau dari grup?

### ISSUE THREAD

**Issue by Magick1an0** [Nurutomo/wabot-aq#113]

**Comment by elssword** [comment]
Untuk memberi exp ke pengguna lain
.pay (@user) (exp yg akan diberi)
Contoh: .pay @member 5000
Exp anda harus memiliki jumlah yg cukup agar bisa memberi ke pengguna yg lain

**Comment by Magick1an0** [comment]
> Untuk memberi exp ke pengguna lain
> .pay (@user) (exp yg akan diberi)
> Contoh: .pay @member 5000
> Exp anda harus memiliki jumlah yg cukup agar bisa memberi ke pengguna yg lain


Saya tidak bisa memberi bot exp tak terbatas atau perintah untuk menambahkan banyak pengalaman ke bot?

**Comment by elssword** [comment]
Cukup rubah data exp pada file database.json
Cari nomer anda kemudian rubah data anda
![Screenshot_2021-03-13-18-47-08-247_com termux](https://user-images.githubusercontent.com/48546605/111028942-8df4f300-842c-11eb-8fb8-76258f260e82.jpg)

**Comment by elssword** [comment]
Rubah data exp milik nomor bot anda menjadi 999999999999

**Comment by Magick1an0** [comment]
> Rubah data exp milik nomor bot anda menjadi 999999999999


Terima kasih banyak! <3

**Comment by elssword** [comment]
Sama sama
