### ISSUE TITLE
Maximum Limit

### ISSUE THREAD

**Issue by Nobuyaki** [Nurutomo/wabot-aq#116]
Bang Caranya Biar Limitnya Kalo udah 20 gabisa nambah/beli lagi gimana?

**Comment by RC047** [comment]
Kalo limit habis bisa ketik !buy <jumlah limit>

misal !buy 5

beli limit butuh exp (350XP = 1 Limit)
untuk dapetin expnya mainin math game (!math <mode>)

**Comment by Nobuyaki** [comment]
bukan gitu tapi max 20limit
jadi kalo limit  masih 20 gabisa beli/nambah lagi limitnya

**Comment by Nurutomo** [comment]
```js
if (limit > 20) throw 'Maksimal limit'
```
Logic di taruh di `buylimit.js`
