### ISSUE TITLE
Bagaimana saya melakukan ini? Kapanpun seseorang menjalankan perintah "Menu", apakah dia menampilkan Menu dan mengirim logo audio sesudahnya? Terima kasih!

### ISSUE THREAD

**Issue by lilnext01** [Nurutomo/wabot-aq#117]

**Comment by Nurutomo** [comment]
Saya tidak mengerti, bisa tunjukkan foto?

**Comment by RC047** [comment]
> 
> 
> Saya tidak mengerti, bisa tunjukkan foto?

Mungkin maksud dia gimana caranya agar muncul pesan audio saat ketik !menu

Btw dia org portugis,, jdi dia pke bhs translate :v

**Comment by lilnext01** [comment]
> Saya tidak mengerti, bisa tunjukkan foto?

Wait...

**Comment by lilnext01** [comment]
![Uploading 20210316_211921.jpg…]()

**Comment by lilnext01** [comment]
Jadi, setiap kali dia menampilkan Menu, dia juga mengirimkan audio yang mengatakan sesuatu, contoh: "Halo, Saya Bot ..."

**Comment by lilnext01** [comment]
> Jadi, setiap kali dia menampilkan Menu, dia juga mengirimkan audio yang mengatakan sesuatu, contoh: "Halo, Saya Bot ..."

![Uploading 20210316_212131.jpg…]()

**Comment by lilnext01** [comment]
> Jadi, setiap kali dia menampilkan Menu, dia juga mengirimkan audio yang mengatakan sesuatu, contoh: "Halo, Saya Bot ..."

![Uploading 20210316_212223.jpg…]()

**Comment by lilnext01** [comment]
![Uploading 20210316_212223.jpg…]()

**Comment by lilnext01** [comment]
![Uploading 20210316_212345.jpg…]()

**Comment by lilnext01** [comment]
![20210316_212345](https://user-images.githubusercontent.com/74841546/111396691-64db9900-869e-11eb-92b7-9c431b7ac8c9.jpg)

**Comment by Nurutomo** [comment]
Add this line below m.reply
```js
conn.sendFile(m.chat, 'path/to/audio', 'audio.mp3', null, m, true)
```

**Comment by lilnext01** [comment]
Thkss
