### ISSUE TITLE
mengirim audio dari ytmp3 sebagai vn

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#118]
gimana caranya biar audio yang di download dari ytmp3 dan play formatnya menjadi voice note

**Comment by LitRHap** [comment]
ptt : true

**Comment by Ftwrr** [comment]
> ptt : true

diketik di bagian mana?

**Comment by RC047** [comment]
coding sendirilah,, bisa makenya aja

**Comment by Ftwrr** [comment]
> coding sendirilah,, bisa makenya aja

okeh

**Comment by Nurutomo** [comment]
conn.sendFile(m.chat, urlblabalaba, 'filename.mp3', null, m, **true** )
