### ISSUE TITLE
FakeReply

### ISSUE THREAD

**Issue by Amaan31** [Nurutomo/wabot-aq#120]
Cara nambahin fake reply gimana

**Comment by Nobuyaki** [comment]
> Cara nambahin fake reply gimana

conn.fakeReply(m.chat, `Text`, '0@s.whatsapp.net', `Text Reply`, m.chat)

**Comment by Amaan31** [comment]
> > Cara nambahin fake reply gimana
> 
> conn.fakeReply(m.chat, `Text`, '[0@s.whatsapp.net](mailto:0@s.whatsapp.net)', `Text Reply`, m.chat)

Nambahin gambarnya?

**Comment by RC047** [comment]
> 
> 
> > > Cara nambahin fake reply gimana
> > 
> > 
> > conn.fakeReply(m.chat, `Text`, '[0@s.whatsapp.net](mailto:0@s.whatsapp.net)', `Text Reply`, m.chat)
> 
> Nambahin gambarnya?

conn.sendFile(m.chat, filegambar, 'gambar.jpg', 'teksnya', { key: { remoteJid: '0@s.whatsapp.net', fromMe: false }, message: { conversation: 'teks fakeReplynya', }}, m)
