### ISSUE TITLE
Cara Ngebuat Command Tanpa Prefix Gimana?

### ISSUE THREAD

**Issue by Miaweers** [Nurutomo/wabot-aq#129]

**Comment by syahrularranger** [comment]
Kasih ini dibawah

Contoh
handler.customPrefix = /^Assalamualaikum$/i
handler.command = /^$/i

**Comment by Miaweers** [comment]
> Kasih ini dibawah
> 
> Contoh
> handler.customPrefix = /^Assalamualaikum$/i
> handler.command = /^$/i

Makasih Ngab , Ternyata Work
