### ISSUE TITLE
Ubah Jadi Public

### ISSUE THREAD

**Issue by FauzyRahadian** [Nurutomo/wabot-aq#13]
Bang Nurutomo Cara Biar Gk Selfbot Gimana?

**Comment by FauzyRahadian** [comment]
Btw CMDnya Apa Gan?

**Comment by FauzyRahadian** [comment]
Sama Cara Ngaktifin Botnya Gimana node . [<session name>] (session name is optional) Maksudnya Ini Gimana Kasih Contoh Bg

**Comment by Nurutomo** [comment]
Itu sudah public

**Comment by Nurutomo** [comment]
#help
!help
??
.menu
dan masih banyak lagi prefixnya

**Comment by Nurutomo** [comment]
ngaktifin `node .`
kalo ada 2 bot berjalan pada 1 termux kasih nama
`node . user1` dan `node . user2`

**Comment by FauzyRahadian** [comment]
Sudah Beres
