### ISSUE TITLE
Gimana cara buat custom voice note?

### ISSUE THREAD

**Issue by Netsh1** [Nurutomo/wabot-aq#131]
Fitur semacam !tts tapi kita yang custom mp3nya misal mau bikin command thanks langsung dijawab sama bot pake sound effect your welcome

**Comment by Nurutomo** [comment]
Cara kirimnya:
```js
conn.sendFile(m.chat, 'path/to/audio', 'filename', null, m, true)
```

handlernya
```js
handler.command = new RegExp
handler.customPrefix = /thanks/i
```

**Comment by Nobuyaki** [comment]
> Cara kirimnya:
> 
> ```js
> conn.sendFile(m.chat, 'path/to/audio', 'filename', null, m, true)
> ```
> 
> handlernya
> 
> ```js
> handler.command = new RegExp
> handler.customPrefix = /thanks/i
> ```

Kalo Audio Nya Ngambil Dari Url Kok Ngabisa Di Play Bang?

**Comment by RC047** [comment]
Re

> 
> 
> > Cara kirimnya:
> > ```js
> > conn.sendFile(m.chat, 'path/to/audio', 'filename', null, m, true)
> > ```
> > 
> > 
> > handlernya
> > ```js
> > handler.command = new RegExp
> > handler.customPrefix = /thanks/i
> > ```
> 
> Kalo Audio Nya Ngambil Dari Url Kok Ngabisa Di Play Bang?

Responnya kayak gimana dulu?

**Comment by Nurutomo** [comment]
voice note

**Comment by MohHildanRefanov** [comment]
Itu file .mp3 nya ditaruh dimana ya?

**Comment by Netsh1** [comment]
TypeError: Cannot read property 'length' of undefined
    at WAConnection.handler 
Ini gmn.
"Path/to/audio" ku ganti nama 'thanks.mp3'  "filename" ku ganti 'thanks' (nama foldernya) bener gak?

**Comment by Ftwrr** [comment]
> Cara kirimnya:
> 
> ```js
> conn.sendFile(m.chat, 'path/to/audio', 'filename', null, m, true)
> ```
> 
> handlernya
> 
> ```js
> handler.command = new RegExp
> handler.customPrefix = /thanks/i
> ```

let handler = async (m, { conn }) => {
  conn.sendFile(m.chat, '.media/jancok.mp3', 'jancs.mp3', null, m, true)
}

(node:4780) UnhandledPromiseRejectionWarning: TypeError: Result is not a buffer
