### ISSUE TITLE
Cheat xp

### ISSUE THREAD

**Issue by Netsh1** [Nurutomo/wabot-aq#132]
Ada yg tau caranya gimana? Bisanya make !daily dan diubah xp yg didapat tapi itu harus nunggu besok lagi buat nge cheat. Cara biar make terus gimana?

**Comment by Nurutomo** [comment]
if nya dihapus

**Comment by RC047** [comment]
Bjir

**Comment by Netsh1** [comment]
> if nya dihapus

Masih sama jawabnya "anda telah mengklaim xp harian"

**Comment by Joseph92123** [comment]
gini caranya


> > if nya dihapus
> 
> Masih sama jawabnya "anda telah mengklaim xp harian"

gini caranya bentarr gw ambil sc buatan gw dulu 
`let handler = async (m, { conn }) => {
  if (global.DATABASE._data.users[m.sender]) {
    global.DATABASE._data.users[m.sender].exp += 5000
    m.reply('*HANYA OWNER*   ---> +5000XP bisa direfill sebelum 24 jam')
    global.DATABASE._data.users[m.sender].lastclaim = new Date * 1
  } else m.reply('Gagal menclaim XP...')
}
handler.help = ['freexp']
handler.tags = ['mods']
handler.command = /^freexp$/i
handler.owner = false
handler.mods = false
handler.premium = true
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null
handler.exp = 100

module.exports = handler

`
