### ISSUE TITLE
IGSTORY 

### ISSUE THREAD

**Issue by lilnext01** [Nurutomo/wabot-aq#137]
![20210322_090456](https://user-images.githubusercontent.com/74841546/111987475-0a06cf00-8aee-11eb-981a-00409241afc4.jpg)

**Comment by lilnext01** [comment]
Bagaimana cara menyembunyikannya? baginya untuk tidak menerapkannya dalam obrolan, saya pikir itu seharusnya tidak terjadi

**Comment by Nurutomo** [comment]
remove
```js
throw json
```
