### ISSUE TITLE
CASE JOIN NYA LORT

### ISSUE THREAD

**Issue by gakgratis** [Nurutomo/wabot-aq#138]
BAMGI LAH

**Comment by theazran** [comment]
> BAMGI LAH
Nih ngab

let handler = async (m, { conn, text}) => {
conn.query({
	json:["action", "invite", `${text.replace('https://chat.whatsapp.com/','')}`]
})
m.reply( `Berhasil Gabung ke grup`)
}
handler.help = ['join].map(v => v + 'link group')
handler.command = /^join$/i
module.exports = handler

**Comment by Nurutomo** [comment]
> > BAMGI LAH
> > Nih ngab
> 
> let handler = async (m, { conn, text}) => {
> conn.query({
> json:["action", "invite", `${text.replace('https://chat.whatsapp.com/','')}`]
> })
> m.reply( `Berhasil Gabung ke grup`)
> }
> handler.help = ['join].map(v => v + 'link group')
> handler.command = /^join$/i
> module.exports = handler

udh ada :|
