### ISSUE TITLE
Add AntiDelete?

### ISSUE THREAD

**Issue by lilnext01** [Nurutomo/wabot-aq#143]
![20210325_084956](https://user-images.githubusercontent.com/74841546/112468540-26517880-8d47-11eb-9113-f5b889744957.jpg)

**Comment by RC047** [comment]
Fitur itu emang udah ada dari dulu..

**Comment by lilnext01** [comment]
![20210326_172941](https://user-images.githubusercontent.com/74841546/112689403-fd210d00-8e58-11eb-82f0-8afe4b99f06e.jpg)

**Comment by lilnext01** [comment]
Saya pikir itu tidak berhasil
