### ISSUE TITLE
New Command 'tovideo'

### ISSUE THREAD

**Issue by lilnext01** [Nurutomo/wabot-aq#153]
![20210327_142952](https://user-images.githubusercontent.com/74841546/112729035-eb973e00-8f08-11eb-87f2-7cf7921bd51e.jpg)

**Comment by lilnext01** [comment]
Apakah mungkin menggunakan perintah yang sama untuk mengonversi stickergif ke video ukuran normal? jika ya, bagaimana cara melakukannya?

**Comment by lilnext01** [comment]
![20210327_155731](https://user-images.githubusercontent.com/74841546/112731318-39b23e80-8f15-11eb-8c55-ab70bd4418f2.jpg)

**Comment by RC047** [comment]
Hubungi saja saya

**Comment by lilnext01** [comment]
> Hubungi saja saya

I sent a message, look when you have time please, thanks.

**Comment by ariffb25** [comment]
I'll make a pull req for this :) just wait me okay
