### ISSUE TITLE
JadiBot Nya Eror

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#155]
Jadibot.js Eror Tidak bisa di gunakan !
jafiBot cannot be used

**Comment by RC047** [comment]
Coba ss

**Comment by Bintangp02** [comment]
![IMG_20210328_124109](https://user-images.githubusercontent.com/80300921/112743601-d67ee580-8fc2-11eb-951c-c20b2b1119b4.jpg)
Tolong Lah Di Fixx!
Please Fix it!

**Comment by Bintangp02** [comment]
Kagak Ada Comen Apa Pun Dari Jadibot!

**Comment by RC047** [comment]
Sinyalnya harus kuat yg utamanya mah

**Comment by Bintangp02** [comment]
Sinyal Bagus 789 Mbps
Kecepatan Dwonlod 800 Mbps 
Udah Cepat!

**Comment by RC047** [comment]
Mungkin dri si org yg numpangnya yg sinyalnya jelek

**Comment by Bintangp02** [comment]
Yang Numpang B
