### ISSUE TITLE
Bro nanya

### ISSUE THREAD

**Issue by elssword** [Nurutomo/wabot-aq#156]
![Screenshot_2021-03-28-09-34-51-738_com termux](https://user-images.githubusercontent.com/48546605/112740675-f5707e00-8fa8-11eb-9274-3383580b1035.jpg)
Bro biar supaya kalo pay ke nomor tertentu gagal gimana bro
Misal kusus pay ke si A pasti selalu gagal,kalo ke B tetep berhasil

**Comment by Nurutomo** [comment]
mungkin dia belum terdaftar dalam database
