### ISSUE TITLE
Tambahkan Fitur Grup Dan DiFix

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#159]
Tambahkan Menu Grup 
-Anti Link 
-Anti Virtex
Tambahkan Fitur lain Nya Dan Fix Fitur yang Eror Makasih [Narutomo](https://github.com/Nurutomo/wabot-aq#Makasih-Narutomo-thx-all-creator-dan-pengguna:))
Thx Semua !!

**Comment by RC047** [comment]
> 
> 
> Tambahkan Menu Grup
> -Anti Link
> -Anti Virtex
> Tambahkan Fitur lain Nya Dan Fix Fitur yang Eror Makasih [Narutomo](https://github.com/Nurutomo/wabot-aq#Makasih-Narutomo-thx-all-creator-dan-pengguna:))
> Thx Semua !!

Fitur antilink udh ada,, klo mau antivirtex cek github ane aja

**Comment by Bintangp02** [comment]
Tambahkan Fitur Grup Yang Kayak Bot Sekarang 
Fix Antilink Eror Soal Nya
Attp Eror
ttp Eror
Itu bot gue eror Di Leptop!

**Comment by meowcraftY** [comment]
f

**Comment by sofa-emha** [comment]
> Attp Eror
> ttp Eror
> Itu bot gue eror Di Leptop!

## Respon
![Screenshot from 2021-03-30 17-17-56](https://user-images.githubusercontent.com/75196975/112973825-ebeb3f80-917b-11eb-86be-66bd6974ed6c.png)

## Debug
![GITUP](https://user-images.githubusercontent.com/75196975/112975034-610b4480-917d-11eb-8bd3-9addc9d587cf.png)

## Keterangan
Kira-kira yang salah apanya ya?

**Comment by Nurutomo** [comment]
Gagal Upload Media
