### ISSUE TITLE
Cara masukin apikey simsimi

### ISSUE THREAD

**Issue by jauhari21** [Nurutomo/wabot-aq#163]
Cara nambahin apikey di simsimi gimana? Saya udah daftar x-team, udah masukin apikeynya juga tapi masih masih ga bisa. 
Jadi kek gini ,
{
  code: 403,
  status: false,
  message: 'Harap masukkan parameter APIKEY!'
}

**Comment by Kokoronationz** [comment]
Ada di config.js

**Comment by jauhari21** [comment]
> Ada di config.js

Bagian mananya gan yg harus diganti

**Comment by jauhari21** [comment]
> Ada di config.js

Oh oke gan dah bisa thanks info
