### ISSUE TITLE
Fitur welcome membernya ga aktif

### ISSUE THREAD

**Issue by jauhari21** [Nurutomo/wabot-aq#166]
Cara biar bisa aktifin fitur welcome  to group gimana? Udah ganti di .setwelcome tetep aja ga muncul chatnya pas ada yg join grup.

**Comment by Bintangp02** [comment]
Punya Saya Juga Sama Kita Tunggu aja Tangapan Dari [nurutomo](https://github.com/Nurutomo/wabot-aq/issues/170)

**Comment by elssword** [comment]
.enable welcome
Udah belum bro

**Comment by Bintangp02** [comment]
> .enable welcome
> Udah belum bro
> Udah Gue aktifkan Bro
