### ISSUE TITLE
Kok JadiBot Kok Lebih Dari 1 Jam Tolong Fix Keenakan Dong Kalau 1 jam Lebih..

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#168]
Jadi temen aku nyambung dari jam 12.00 Sampai jam 13.20 Kok Gak Putus sambungan nya Giamana Nih Tolong Fix Nurutomo 
Thx [nurutomo Dan Teman teman yang Fix eror](https://github.com/Nurutomo/wabot-aq/issues)

**Comment by Nurutomo** [comment]
uhh, memang fitur nya gitu
