### ISSUE TITLE
Fitur Promote + demote +antilink +welcome +toimg +ttp +attpEror..!

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#169]
![Screenshot_20210330_145858](https://user-images.githubusercontent.com/80300921/112954287-74f87b80-9168-11eb-9bf2-b28dee4a21f3.jpg)
Fitur Promote+demote+antilink+welcome+toimg Eror..!

**Comment by RC047** [comment]
> 
> 
> ![Screenshot_20210330_145858](https://user-images.githubusercontent.com/80300921/112954287-74f87b80-9168-11eb-9bf2-b28dee4a21f3.jpg)
> Fitur Promote+demote+antilink+welcome+toimg Eror..!

Untuk Fitur Group kyk kick, add, promote, dan demote nggak erorr.

Cuman gak diaktifin fiturnya,, klo mua biar aktif ketik $ node . --restrict-
Tapi itu resikonya bisa kena ban
