### ISSUE TITLE
Cara liat list data orang" yg udah register

### ISSUE THREAD

**Issue by jauhari21** [Nurutomo/wabot-aq#170]
Gimana cara liat data para member yg udab registrasi?

**Comment by RC047** [comment]
Cek dimenu.js itu kan ada let rtotalreg,, nah itu databse org yg udah terdaftar

**Comment by ariffb25** [comment]
```js
let handler = async (m,{conn}) => {

    let rtotalreg = Object.values(global.DATABASE._data.users).filter(user => user.registered == true).length
    let jawab = `${rtotalreg}`.trim()
    conn.reply(m.chat, jawab, m)
}
handler.help = ['totalreg']
handler.tags = ['']
handler.command = /^totalreg$/i

module.exports = handler
```

**Comment by jauhari21** [comment]
> 
> ```js
> let handler = async (m,{conn}) => {
> 
>     let rtotalreg = Object.values(global.DATABASE._data.users).filter(user => user.registered == true).length
>     let jawab = `${rtotalreg}`.trim()
>     conn.reply(m.chat, jawab, m)
> }
> handler.help = ['totalreg']
> handler.tags = ['']
> handler.command = /^totalreg$/i
> 
> module.exports = handler
> ```

Datanya bisa diubah ga gan?

**Comment by jauhari21** [comment]
Pengen ngubah nama member yg udah regist

**Comment by Nurutomo** [comment]
> Pengen ngubah nama member yg udah regist

```js
global.DATABASE._data.users[orangnya].name = 'Nama Custom'
```
