### ISSUE TITLE
Kirim file dalam media .gif [error]

### ISSUE THREAD

**Issue by lilnext01** [Nurutomo/wabot-aq#173]
Adakah yang bisa membantu saya dengan ini? Saya membuat kode, di mana setiap kali dijalankan, itu akan mengirim media dalam format (gif), tetapi, itu mengirim file dalam format (jpg), dan saya tidak tahu apa yang salah

**Comment by lilnext01** [comment]
![Uploading 20210330_125704.jpg…]()

**Comment by lilnext01** [comment]
![20210330_125704](https://user-images.githubusercontent.com/74841546/113019312-d6641e80-9157-11eb-8c5b-dbc31fd9b396.jpg)

**Comment by lilnext01** [comment]
![20210330_130104](https://user-images.githubusercontent.com/74841546/113019465-07445380-9158-11eb-8119-e437130bd369.jpg)

**Comment by RC047** [comment]
Pake cara kyk di sticker.js

**Comment by lilnext01** [comment]
> Pake cara kyk di sticker.js

Saya tidak mengerti :v

**Comment by ariffb25** [comment]
gue pernah baca di issue baileys, emng gif itu gabisa, trs ada orang ngasih saran diubah ke video aja pake fmpeg
