### ISSUE TITLE
Fix data Leaderboard

### ISSUE THREAD

**Issue by jauhari21** [Nurutomo/wabot-aq#177]
Data peringkat leaderboard ga nambah gitu" aja? Gimana ya cara fixnya?

**Comment by ariffb25** [comment]
maksud?

**Comment by jauhari21** [comment]
> maksud?

![IMG_20210331_105813](https://user-images.githubusercontent.com/81492529/113093150-88175400-9219-11eb-97a5-f0796421f11e.jpg)

**Comment by jauhari21** [comment]
Noh gitu terus ga ada yg berubah

**Comment by ariffb25** [comment]
oalah w masih pake leaderboard yg versi lama wkwk

**Comment by ariffb25** [comment]
```js
let handler = async (m, { conn, args }) => {
  let sortedExp = Object.entries(global.DATABASE.data.users).sort((a, b) => b[1].exp - a[1].exp)
  let sortedLim = Object.entries(global.DATABASE.data.users).sort((a, b) => b[1].limit - a[1].limit)
  let usersExp = sortedExp.map(v => v[0])
  let usersLim = sortedLim.map(v => v[0])
  let len = args[0] && args[0].length > 0 ? Math.min(1000, Math.max(parseInt(args[0]), 5)) : Math.min(3, sortedExp.length)
  let text = `
• *XP Leaderboard Top ${len}* •
Kamu: *${usersExp.indexOf(m.sender) + 1}* dari *${usersExp.length}*

${sortedExp.slice(0, len).map(([user, data], i) => (i + 1) + '. ' + conn.getName(user) + ': *' + data.exp + ' Exp*').join`\n`}

• *Apoin Leaderboard Top ${len}* •
Kamu: *${usersLim.indexOf(m.sender) + 1}* dari *${usersLim.length}*

${sortedLim.slice(0, len).map(([user, data], i) => (i + 1) + '. ' + conn.getName(user) + ': *' + data.limit + ' Apoin*').join`\n`}
`.trim()
  conn.reply(m.chat, text, m, {
    contextInfo: {
      mentionedJid: [...usersExp.slice(0, len), ...usersLim.slice(0, len)]
    }
  })
}
handler.help = ['leaderboard [jumlah user]', 'lb [jumlah user]']
handler.tags = ['xp']
handler.command = /^(leaderboard|lb)$/i
handler.owner = false
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null
handler.exp = 0

module.exports = handler


```

**Comment by jauhari21** [comment]
> oalah w masih pake leaderboard yg versi lama wkwk

Iya gua juga sih, pake yg lama soalnya yg baru eror. Makanya gua nanya

**Comment by RC047** [comment]
> > maksud?
> 
> ![IMG_20210331_105813](https://user-images.githubusercontent.com/81492529/113093150-88175400-9219-11eb-97a5-f0796421f11e.jpg)

Coba pake bot baru sama yg baru,, jangan digabungin yg lama sama yg baru,, jdinya gtu

**Comment by jauhari21** [comment]
Aing pake yg baru loh gan, sampe hapus data termux terus install bot baru dengan script yg baru ..pas coba ga bisa tetep aja ga masuk ke leaderboard. Yaudah gua ganti ke script leaderboard yg lama eh bisa kedetect semua.

**Comment by RC047** [comment]
> Aing pake yg baru loh gan, sampe hapus data termux terus install bot baru dengan script yg baru ..pas coba ga bisa tetep aja ga masuk ke leaderboard. Yaudah gua ganti ke script leaderboard yg lama eh bisa kedetect semua.

Brarti bug eta mah :v
