### ISSUE TITLE
google

### ISSUE THREAD

**Issue by Akbarsans** [Nurutomo/wabot-aq#18]
bang google nya cuma ngeluarin ss doang kagak ada link msg nya

**Comment by Nurutomo** [comment]
sana :|

**Comment by Akbarsans** [comment]
iya bang udh gua utak atik tetep aja gabisa keluar

**Comment by Nurutomo** [comment]
Dari modulenya rusak

**Comment by Nurutomo** [comment]
fixed by update google-it
