### ISSUE TITLE
Fix command Profile

### ISSUE THREAD

**Issue by jauhari21** [Nurutomo/wabot-aq#180]
![Screenshot_2021-03-31-20-44-06-12_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/81492529/113156702-6ee7c500-9264-11eb-9c5b-ca953ae50cae.jpg)

Bro ini kenapa ya? Pas coba #profile ga muncul, dicoba liat di termux ternyata eror tulisannya kek gini. Masalahnya dimana ya

**Comment by RC047** [comment]
> ![Screenshot_2021-03-31-20-44-06-12_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/81492529/113156702-6ee7c500-9264-11eb-9c5b-ca953ae50cae.jpg)
> 
> Bro ini kenapa ya? Pas coba #profile ga muncul, dicoba liat di termux ternyata eror tulisannya kek gini. Masalahnya dimana ya

Emg gitu,, fitur yg mengirim gambar jdi kdng erorr gara2 update Baileys

**Comment by jauhari21** [comment]
> > ![Screenshot_2021-03-31-20-44-06-12_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/81492529/113156702-6ee7c500-9264-11eb-9c5b-ca953ae50cae.jpg)
> > 
> > Bro ini kenapa ya? Pas coba #profile ga muncul, dicoba liat di termux ternyata eror tulisannya kek gini. Masalahnya dimana ya
> 
> Emg gitu,, fitur yg mengirim gambar jdi kdng erorr gara2 update Baileys

Oh gitu, okelah. Thanks info, kalo cara benerin fitur welcomr grup gimana gan? Aing dah aktifin setwelcome tapi tetep aja ga muncul pas ada member yg join grup
