### ISSUE TITLE
Tiktok tidak mengirimkan video

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#181]
![Screenshot_2021-04-01-08-29-39-06](https://user-images.githubusercontent.com/76021496/113227257-bdf02300-9281-11eb-8eea-58b9f88541d3.jpg)

let fetch = require('node-fetch')
let handler = async (m, { conn, args }) => {
  if (!args[0]) throw 'Uhm...url nya mana?'
  let res = await fetch(global.API('xteam', '/dl/tiktok', {
    url: args[0]
  }, 'APIKEY'))
  let json = await res.json()
  if (!json.result) throw json
  conn.sendFile(m.chat, json.result.url, 'tiktok.mp4', `
_*Username:*_ @${json.result.username}
`.trim(), m, false, {
    thumbnail
  })
}
handler.help = ['tiktok'].map(v => v + ' <url>')
handler.tags = ['downloader']

handler.command = /^(tiktok(dl)?)$/i

module.exports = handler

**Comment by Nurutomo** [comment]
ouwh

**Comment by ariffb25** [comment]
```
json.result.url
```
ganti jadi
```
json.server_2
```

**Comment by Bintang73** [comment]
Tiktok server_1
