### ISSUE TITLE
Tolong Antilink Nya Semua Link Dari Bit.ly Dan Tinyurl Dan Sebagainya..

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#183]
Tolong Bang Nurutomo Dan Team/Teman Teman Thx

**Comment by RC047** [comment]
> Tolong Bang Nurutomo Dan Team/Teman Teman Thx

tinggal edit di antilink.js yg link RegExp

**Comment by ariffb25** [comment]
[https://github.com/Nurutomo/wabot-aq/blob/d46c568a8efb1e4dc823a55b3d8b1ec5387f7128/plugins/_antilink.js#L3](https://github.com/Nurutomo/wabot-aq/blob/d46c568a8efb1e4dc823a55b3d8b1ec5387f7128/plugins/_antilink.js#L3
)

atur sendiri regex nya

**Comment by jauhari21** [comment]
> https://github.com/Nurutomo/wabot-aq/blob/d46c568a8efb1e4dc823a55b3d8b1ec5387f7128/plugins/_antilink.js#L3
> 
> atur sendiri regex nya

Kalo mau nambahin link lain tinggal kasih koma ya?

**Comment by Bintangp02** [comment]
Kalau Saya Copy Lagi Di bawah nya !!

**Comment by Nurutomo** [comment]
> > https://github.com/Nurutomo/wabot-aq/blob/d46c568a8efb1e4dc823a55b3d8b1ec5387f7128/plugins/_antilink.js#L3
> > 
> > atur sendiri regex nya
> 
> Kalo mau nambahin link lain tinggal kasih koma ya?

tanda `|`

**Comment by Bintangp02** [comment]
Contoh nya giamana bang Saya masih pemula..

**Comment by ariffb25** [comment]
```js
let linkRegex = /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_+.~#?&/=]*)/i
```
ini detect apapun url nya
