### ISSUE TITLE
Play error di nodejs v13

### ISSUE THREAD

**Issue by janganlahkau** [Nurutomo/wabot-aq#186]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Nurutomo** [comment]
pkg install node-lts

**Comment by janganlahkau** [comment]
G

> pkg install node-lts

@Nurutomo gk bisa di instal

**Comment by Nurutomo** [comment]
`pkg install nodejs-lts`
