### ISSUE TITLE
Search film lewat gambar

### ISSUE THREAD

**Issue by elssword** [Nurutomo/wabot-aq#187]
Buatin fitur what anime is this

**Comment by RC047** [comment]
Buat sendiri njerr,, bisa makenya aja lu :v

**Comment by elssword** [comment]
Wkwk gk bisa di imgbb nya

**Comment by elssword** [comment]
Wkwk gk bisa di imgbb nya

**Comment by elssword** [comment]
![Screenshot_2021-04-07-09-34-02-942_com yowhatsapp](https://user-images.githubusercontent.com/48546605/113802211-80f5c600-9784-11eb-90ab-ae99afff1a89.jpg)
Rusak bjir kecocokan kalo gw buat sendiri wkwkwk

**Comment by janganlahkau** [comment]
Akurasinya pake function biar gk kyk gitu:v
