### ISSUE TITLE
Cara dapet code qr lg gimana ya

### ISSUE THREAD

**Issue by jauhari21** [Nurutomo/wabot-aq#191]
Ini gimana ya gan, cara dapet qr code lagi biar ga eror. Yg sebelumnya dan aing berhentiin. 
![Screenshot_2021-04-08-21-24-41-20_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/81492529/114044052-11312980-98b1-11eb-9a9c-c48cabd3ef3d.jpg)

**Comment by Kokoronationz** [comment]
Hapus sessions nya

**Comment by jauhari21** [comment]
> Hapus sessions.json nya

Oke thanks gan, bisa hehe
