### ISSUE TITLE
Cara Nambahin Fitur itu Gimana Sih?

### ISSUE THREAD

**Issue by KazukoGans** [Nurutomo/wabot-aq#194]
Moga Moga Dijawab:v

**Comment by elssword** [comment]
Buat file tipe js terus masukin ke folder plugins

**Comment by JereGanz342** [comment]
Lu buat lah terus kalo dh buat nya jgn lupa taro node modules biar work terus simpan nama.js taro di plugins

**Comment by KazukoGans** [comment]
> Lu buat lah terus kalo dh buat nya jgn lupa taro node modules biar work terus simpan nama.js taro di plugins

W dh coba tpi kok gk muncul yak

**Comment by JereGanz342** [comment]
Elu kalik yg salah coding

**Comment by Gchan1319** [comment]
> Moga Moga Dijawab:v

Buat file baru, terus cari aja api yang mau di pakai,  tapi inget pelajari dulu syntax dasarnya
