### ISSUE TITLE
Situs Xteam jatuh ?!

### ISSUE THREAD

**Issue by lilnext01** [Nurutomo/wabot-aq#195]
![Screenshot_20210412-114849_Chrome](https://user-images.githubusercontent.com/74841546/114414289-0f06ed80-9b85-11eb-81ec-f7296bc853d5.jpg)

**Comment by janganlahkau** [comment]
Work in my phone
Check your connection maybe:v

**Comment by janganlahkau** [comment]
Work in my phone
Check your connection maybe:v
