### ISSUE TITLE
Leveling

### ISSUE THREAD

**Issue by janganlahkau** [Nurutomo/wabot-aq#196]
Bro levelingnya cuma buat yang ngetik !autolevelup dulu yang gk ngetik gak nambah levelnya gimana tuh??

**Comment by Kokoronationz** [comment]
Kalo mau levelnya naik tinggal !levelup, kalo mau otomatis tinggal !autolevelup 
!autolevelup bekerja ketika XP cukup buat up level

**Comment by jauhari21** [comment]
> Bro levelingnya cuma buat yang ngetik !autolevelup dulu yang gk ngetik gak nambah levelnya gimana tuh??

Atur aja di handler.js disitu ada autolevelup diubah aja jadi true

**Comment by janganlahkau** [comment]
Yg bener yg mna?

**Comment by BochilGaming** [comment]
> Yg bener yg mna?

Kalau mau 1 orang aja pakek !on autolevelup atau !enable autolevelup, kalau di ubah di handler.js itu jadi semua bisa autolevelup
