### ISSUE TITLE
Fitur ttp

### ISSUE THREAD

**Issue by janganlahkau** [Nurutomo/wabot-aq#198]
Error gk keluar stikernya cuman kosong dan bikin force close wa

**Comment by github835** [comment]
> 
> 
> Error gk keluar stikernya cuman kosong dan bikin force close wa

const { sticker2 } = require('../lib/sticker')
const { MessageType } = require('@adiwajshing/baileys')

let handler = async (m, { conn, text }) => {
if (text) {
let stiker = await sticker2(null, global.API('xteam', '/ttp', { file: '', text }))
conn.sendMessage(m.chat, stiker, MessageType.sticker, {
quoted: m
})
}
}
handler.help = ['ttp ']
handler.tags = ['sticker']
handler.command = /^ttp$/i
handler.owner = false
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null

module.exports = handler

**Comment by github835** [comment]
> 
> 
> Error gk keluar stikernya cuman kosong dan bikin force close wa

pakai script ini aja yang lama
