### ISSUE TITLE
Welcome

### ISSUE THREAD

**Issue by janganlahkau** [Nurutomo/wabot-aq#200]
Udh ketik /enable welcome tetap gk bisa:v

**Comment by syahrularranger** [comment]
Itu enable untuk 1 chat/group doang.. bukan untuk semua.. jadi harus manual satu" group di gituin.. 

alternatifnya ubah di handler.js di bagian welcome = false ganti menjadi true

**Comment by jauhari21** [comment]
> Itu enable untuk 1 chat/group doang.. bukan untuk semua.. jadi harus manual satu" group di gituin..
> 
> alternatifnya ubah di handler.js di bagian welcome = false ganti menjadi true

Tetep aja udah gua nyalain di handler pas ada yg join atau keluar ga muncul tu

**Comment by janganlahkau** [comment]
Semenjak update baileys gak nongol cuk error

**Comment by jauhari21** [comment]
> Semenjak update baileys gak nongol cuk error

Lu pake baileys yg versi lama ga , aing coba pake versi yang lama sama aja terep eror. Keknya harus pake script yg lama juga.

**Comment by Nurutomo** [comment]
fixed in new update
