### ISSUE TITLE
Send Video

### ISSUE THREAD

**Issue by Nobuyaki** [Nurutomo/wabot-aq#201]
Cara Kirim Video Pakek Link Gimana Bang Kok Eror
![Screenshot_2021-04-18-08-34-19](https://user-images.githubusercontent.com/72033395/115131269-0436d780-a021-11eb-98cf-3a83755f1323.png)

**Comment by jauhari21** [comment]
> Cara Kirim Video Pakek Link Gimana Bang Kok Eror
> ![Screenshot_2021-04-18-08-34-19](https://user-images.githubusercontent.com/72033395/115131269-0436d780-a021-11eb-98cf-3a83755f1323.png)

Bagi script waitnya gan

**Comment by Nobuyaki** [comment]
> > Cara Kirim Video Pakek Link Gimana Bang Kok Eror
> > ![Screenshot_2021-04-18-08-34-19](https://user-images.githubusercontent.com/72033395/115131269-0436d780-a021-11eb-98cf-3a83755f1323.png)
> 
> Bagi script waitnya gan

Cek Pull request
