### ISSUE TITLE
#sudo gk work

### ISSUE THREAD

**Issue by Miaweers** [Nurutomo/wabot-aq#204]

**Comment by janganlahkau** [comment]
Itu fitur apa sih

**Comment by Nurutomo** [comment]
semenjak update baileys

**Comment by Nurutomo** [comment]
> Itu fitur apa sih

lakukan command sebagai sesorang gitu

**Comment by JereGanzz** [comment]
> Itu fitur apa sih

Itu fitur semacam fitnah
