### ISSUE TITLE
fix ttp

### ISSUE THREAD

**Issue by github835** [Nurutomo/wabot-aq#206]
pas aku ketik ttp dengan teksnya malah stikernya gak ada

**Comment by jauhari21** [comment]
> pas aku ketik ttp dengan teksnya malah stikernya gak ada

Ganti aja script ttp.jsnya ke script ttp.js yg lama

`const { sticker2 } = require('../lib/sticker')
const { MessageType } = require('@adiwajshing/baileys')

let handler  = async (m, { conn, text }) => {
  if (text) {
    let stiker = await sticker2(null, global.API('xteam', '/ttp', { file: '', text }))
    conn.sendMessage(m.chat, stiker, MessageType.sticker, {
      quoted: m
    })
  }
}
handler.help = ['ttp <teks>']
handler.tags = ['sticker']
handler.command = /^ttp$/i
handler.owner = false
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null

module.exports = handler

`

**Comment by jauhari21** [comment]
const { sticker2 } = require('../lib/sticker')
const { MessageType } = require('@adiwajshing/baileys')

let handler  = async (m, { conn, text }) => {
  if (text) {
    let stiker = await sticker2(null, global.API('xteam', '/ttp', { file: '', text }))
    conn.sendMessage(m.chat, stiker, MessageType.sticker, {
      quoted: m
    })
  }
}
handler.help = ['ttp <teks>']
handler.tags = ['sticker']
handler.command = /^ttp$/i
handler.owner = false
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null

module.exports = handler

**Comment by github835** [comment]
> 
> 
> > pas aku ketik ttp dengan teksnya malah stikernya gak ada
> 
> Ganti aja script ttp.jsnya ke script ttp.js yg lama
> 
> const { sticker2 } = require('../lib/sticker')
> const { MessageType } = require('@adiwajshing/baileys')
> 
> let handler = async (m, { conn, text }) => {
> if (text) {
> let stiker = await sticker2(null, global.API('xteam', '/ttp', { file: '', text }))
> conn.sendMessage(m.chat, stiker, MessageType.sticker, {
> quoted: m
> })
> }
> }
> handler.help = ['ttp ']
> handler.tags = ['sticker']
> handler.command = /^ttp$/i
> handler.owner = false
> handler.mods = false
> handler.premium = false
> handler.group = false
> handler.private = false
> 
> handler.admin = false
> handler.botAdmin = false
> 
> handler.fail = null
> 
> module.exports = handler

oh ok
