### ISSUE TITLE
Cara install ffmepg gimana ?

### ISSUE THREAD

**Issue by github835** [Nurutomo/wabot-aq#207]
maksudnya don't forget to path apa

**Comment by janganlahkau** [comment]
pkg install ffmpeg

**Comment by ai-man-123** [comment]
Gi mana mau aktif kan bot lu

Pada 22 Apr 2021 8:31 PM, "janganlahkau" ***@***.***> menulis:

**Comment by ai-man-123** [comment]
Bang on bot bang:v

Pada 24 Apr 2021 8:10 AM, "Aiman 123" ***@***.***> menulis:

**Comment by JereGanzz** [comment]
pkg install ffmpeg or pkg install ffmpeg -y

**Comment by ariffb25** [comment]
path yang dimaksud itu ada di environment variables
1. cari aja ini
![image](https://user-images.githubusercontent.com/76026450/124556573-a1f0b480-de62-11eb-9e08-a2bda8b86e74.png)
2. klik yang ditunjuk
![image](https://user-images.githubusercontent.com/76026450/124556692-c77dbe00-de62-11eb-900d-260b97af251a.png)
3. ada 2 path, ya mending system aja
![image](https://user-images.githubusercontent.com/76026450/124556813-f431d580-de62-11eb-96a2-350c7833733e.png)
4. klik add, ketik ```C:\ffmpeg\bin``` tergantung kamu ekstrak ffmpegnya dimana jadi sesuaikan
![image](https://user-images.githubusercontent.com/76026450/124556930-1a577580-de63-11eb-964e-161bc3b44029.png)
5. kalo udah klik ok, udah gitu aja
