### ISSUE TITLE
fitur admin gk jalan

### ISSUE THREAD

**Issue by liteblog** [Nurutomo/wabot-aq#21]
min fitur admin kaya
.add
.kick
.promote
.demote
gk jalan, tapi kalo command buat onwer jalan .oadd dll.

**Comment by Nurutomo** [comment]
Memang aku nonaktifkan

**Comment by ariffb25** [comment]
aktifinnya gmn min?

**Comment by Nurutomo** [comment]
cari teks
```js
if (['admin'].includes(
```
hapus teks admin untuk aktifin

**Comment by ariffb25** [comment]
> cari teks
> 
> ```js
> if (['admin'].includes(
> ```
> 
> hapus teks admin untuk aktifin

```
let handler = async (m, { conn, text }) => {
  let users = text.split`,`.map(v => v.replace(/[^0-9]/g, '') + '@s.whatsapp.net').filter(v => v.length > 20)
  await conn.groupAdd(m.chat, users)
}
handler.help = ['add', '+'].map(v => v + ' nomor,nomor')
handler.tags = ['admin']
handler.command = /^(add|\+)$/i
handler.owner = false
handler.mods = false
handler.premium = false
handler.group = true
handler.private = false

handler.admin = true
handler.botAdmin = true

handler.fail = null
handler.limit = true

module.exports = handler
```

dari code **add.js** ngga ada teks if **(['admin'].includes(** , teks itu ada di file mana? di main.js jg ngga ada uhmm

**Comment by Nurutomo** [comment]
Di `main.js`

**Comment by ariffb25** [comment]
![image](https://user-images.githubusercontent.com/76026450/106694131-8579f300-660a-11eb-8608-7dadf107737c.png)

yang ini kan ya ada di line 120, oke ku coba dulu, terimakasih @Nurutomo
