### ISSUE TITLE
Command #stiker 

### ISSUE THREAD

**Issue by janganlahkau** [Nurutomo/wabot-aq#211]
Klo kita ketik #stiker pake text malah muncul pesan error
Misal #stiker wkwkw lanhsung emror awoawkk

**Comment by z3r0-d4y-3xplo1t** [comment]
Dah biasa

**Comment by Nurutomo** [comment]
> Klo kita ketik #stiker pake text malah muncul pesan error
> Misal #stiker wkwkw lanhsung emror awoawkk

itu buat stiker lewat url
