### ISSUE TITLE
HELP MASIH AE BANG:( Media upload failed on all hosts. 

### ISSUE THREAD

**Issue by kythepublic** [Nurutomo/wabot-aq#212]
![gambar](https://user-images.githubusercontent.com/59775277/116215582-03651a80-a772-11eb-8606-c19b439131a9.png)

Udah di install ulang juga tetep sama aja, gmna ya? apa cuman gw doang yg kek gini?

**Comment by z3r0-d4y-3xplo1t** [comment]
Emang masih banyak yang error bro

**Comment by Nurutomo** [comment]
ttp lagi error
