### ISSUE TITLE
Jadi bot eror

### ISSUE THREAD

**Issue by jauhari21** [Nurutomo/wabot-aq#215]
Padahal kemaren bisa, sekarang jadi eror, oh iya semenjak gua ganti handler yg baru dari narutomo jadi eror 
![Screenshot_2021-05-01-08-55-14-80](https://user-images.githubusercontent.com/81492529/116767556-19692880-aa5b-11eb-98a0-6d64b79bf264.jpg)

**Comment by syahrularranger** [comment]
> Padahal kemaren bisa, sekarang jadi eror
> ![Screenshot_2021-05-01-08-55-14-80](https://user-images.githubusercontent.com/81492529/116767556-19692880-aa5b-11eb-98a0-6d64b79bf264.jpg)

Pke baileys versi brp kmrin?

**Comment by ai-man-123** [comment]
Harap on bot nya :v

Pada 1 Mei 2021 12:03 PM, "syahrularranger" ***@***.***>
menulis:

**Comment by jauhari21** [comment]
> > Padahal kemaren bisa, sekarang jadi eror
> > ![Screenshot_2021-05-01-08-55-14-80](https://user-images.githubusercontent.com/81492529/116767556-19692880-aa5b-11eb-98a0-6d64b79bf264.jpg)
> 
> Pke baileys versi brp kmrin?

3.4.1 sekarang pake 3.4.1 , tadi sempet coba bot default originalnya narutomo yg belom diubah" sama aja masih eror

**Comment by jauhari21** [comment]
> > Padahal kemaren bisa, sekarang jadi eror
> > ![Screenshot_2021-05-01-08-55-14-80](https://user-images.githubusercontent.com/81492529/116767556-19692880-aa5b-11eb-98a0-6d64b79bf264.jpg)
> 
> Pke baileys versi brp kmrin?

Udah ketemu masalahnya ada dihandler.js yg diupdate narutomo yg terbaru. Gua ubah ke handler.js yg lama fitur jadibotnya kembali berfungsi.

**Comment by syahrularranger** [comment]
> > > Padahal kemaren bisa, sekarang jadi eror
> > > ![Screenshot_2021-05-01-08-55-14-80](https://user-images.githubusercontent.com/81492529/116767556-19692880-aa5b-11eb-98a0-6d64b79bf264.jpg)
> > 
> > 
> > Pke baileys versi brp kmrin?
> 
> Udah ketemu masalahnya ada dihandler.js yg diupdate @Nurutomo yg terbaru. Gua ubah ke handler.js yg lama fitur jadibotnya kembali berfungsi.

Nah iya solusi nya downgrade baileys ama sc nya..

**Comment by jauhari21** [comment]
> > > > Padahal kemaren bisa, sekarang jadi eror
> > > > ![Screenshot_2021-05-01-08-55-14-80](https://user-images.githubusercontent.com/81492529/116767556-19692880-aa5b-11eb-98a0-6d64b79bf264.jpg)
> > > 
> > > 
> > > Pke baileys versi brp kmrin?
> > 
> > 
> > Udah ketemu masalahnya ada dihandler.js yg diupdate @Nurutomo yg terbaru. Gua ubah ke handler.js yg lama fitur jadibotnya kembali berfungsi.
> 
> Nah iya solusi nya downgrade baileys ama sc nya..

Tapi ga bisa pake fitur detect :( semdih. Padahal pengen tapi bikin jadibot eror :(

**Comment by ariffb25** [comment]
yg diganti jangan handlernya aja, tapi keseluruhan :/

**Comment by jauhari21** [comment]
> yg diganti jangan handlernya aja, tapi keseluruhan :/

Udah gan, aing dah coba install ulang tanpa edit apapun tetep aja eror jadibotnya

**Comment by Nurutomo** [comment]
> > yg diganti jangan handlernya aja, tapi keseluruhan :/
> 
> Udah gan, aing dah coba install ulang tanpa edit apapun tetep aja eror jadibotnya

sampai sekarang aku masih bingung error nya dimana

**Comment by jauhari21** [comment]
> > > yg diganti jangan handlernya aja, tapi keseluruhan :/
> > 
> > 
> > Udah gan, aing dah coba install ulang tanpa edit apapun tetep aja eror jadibotnya
> 
> sampai sekarang aku masih bingung error nya dimana

Di handler gan, disitu eventnya yg baru eror. Tertulisnya sih gitu.

**Comment by z3r0-d4y-3xplo1t** [comment]
Ganti main js lama abis itu handler js lama abis itu lib simple lama baru bisa√

**Comment by syahrularranger** [comment]
Pke sc yg di pull request dri aku.. aku dah nyoba work ko.. jadi bot ga error
