### ISSUE TITLE
Tambahin  fakereplythumbnail + gambar besar

### ISSUE THREAD

**Issue by janganlahkau** [Nurutomo/wabot-aq#216]
bikin keren menunya donk..ada fakereply nya  +  jpegthumbnail + ada gambar besarnyaa..oke trs bisa ganti gambar thumbnail kecil ama gambar besar ny

**Comment by Kokoronationz** [comment]
![Screenshot_2021_0501_193908.jpg](https://user-images.githubusercontent.com/78072346/116782739-169b2180-aab5-11eb-9dfa-ce24d17b0957.jpg)

Gini?

**Comment by Kokoronationz** [comment]
```
conn.sendFile(m.chat,` foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
```

**Comment by KazukoGans** [comment]
> ```
> conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
> ```

Naruhnya dimana

**Comment by Kokoronationz** [comment]
> > ```
> > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
> > ```
> 
> Naruhnya dimana

Di menu.js, bagian
```
conn.reply(m.chat, text.trim(), m)
```

Ubah jadi

```
conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
```

**Comment by janganlahkau** [comment]
> ![Screenshot_2021_0501_194843](https://user-images.githubusercontent.com/78072346/116782967-4d256c00-aab6-11eb-8fba-af7b4ab49287.jpg)
> 
> Gini?

Iya gitu keren  bikinnin

**Comment by lilnext01** [comment]
> > > ```
> > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
> > > ```
> > 
> > 
> > Naruhnya dimana
> 
> Di menu.js, bagian
> 
> ```
> conn.reply(m.chat, text.trim(), m)
> ```
> 
> Ubah jadi
> 
> ```
> conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
> ```

conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })                                                  ^                                  ParseError: Unexpected token



Error

**Comment by janganlahkau** [comment]
Cara gk error gimana

> > > > ```
> > > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
> > > > ```
> > > 
> > > 
> > > Naruhnya dimana
> > 
> > 
> > Di menu.js, bagian
> > ```
> > conn.reply(m.chat, text.trim(), m)
> > ```
> > 
> > 
> > Ubah jadi
> > ```
> > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
> > ```
> 
> conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '[0@s.whatsapp.net](mailto:0@s.whatsapp.net)', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } }) ^ ParseError: Unexpected token
> 
> Error

**Comment by Kokoronationz** [comment]
> Cara gk error gimana
> 
> > > > > ```
> > > > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
> > > > > ```
> > > > 
> > > > 
> > > > Naruhnya dimana
> > > 
> > > 
> > > Di menu.js, bagian
> > > ```
> > > conn.reply(m.chat, text.trim(), m)
> > > ```
> > > 
> > > 
> > > Ubah jadi
> > > ```
> > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
> > > ```
> > 
> > 
> > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '[0@s.whatsapp.net](mailto:0@s.whatsapp.net)', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } }) ^ ParseError: Unexpected token
> > Error

Coba liat SC elu

**Comment by jauhari21** [comment]
> > Cara gk error gimana
> > > > > > ```
> > > > > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
> > > > > > ```
> > > > > 
> > > > > 
> > > > > Naruhnya dimana
> > > > 
> > > > 
> > > > Di menu.js, bagian
> > > > ```
> > > > conn.reply(m.chat, text.trim(), m)
> > > > ```
> > > > 
> > > > 
> > > > Ubah jadi
> > > > ```
> > > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
> > > > ```
> > > 
> > > 
> > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '[0@s.whatsapp.net](mailto:0@s.whatsapp.net)', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } }) ^ ParseError: Unexpected token
> > > Error
> 
> Coba liat SC elu

![IMG_20210504_071517](https://user-images.githubusercontent.com/81492529/116948053-89b8b980-aca8-11eb-8ade-916ac35cc97e.jpg)
Thanks gan work

**Comment by lilnext01** [comment]
![20210503_213714](https://user-images.githubusercontent.com/74841546/116949180-e049d780-ac57-11eb-8a3f-03ef13059302.jpg)
Milik saya tidak berfungsi, apa yang saya lakukan salah?

**Comment by lilnext01** [comment]
> > > Cara gk error gimana
> > > > > > > ```
> > > > > > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > Naruhnya dimana
> > > > > 
> > > > > 
> > > > > Di menu.js, bagian
> > > > > ```
> > > > > conn.reply(m.chat, text.trim(), m)
> > > > > ```
> > > > > 
> > > > > 
> > > > > Ubah jadi
> > > > > ```
> > > > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
> > > > > ```
> > > > 
> > > > 
> > > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '[0@s.whatsapp.net](mailto:0@s.whatsapp.net)', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } }) ^ ParseError: Unexpected token
> > > > Error
> > 
> > 
> > Coba liat SC elu
> 
> ![IMG_20210504_071517](https://user-images.githubusercontent.com/81492529/116948053-89b8b980-aca8-11eb-8ade-916ac35cc97e.jpg)
> Thanks gan work

Dapatkah Anda mengirimkan gambar kode Anda kepada saya sehingga saya dapat melihat bagaimana itu?

**Comment by jauhari21** [comment]
> > > > Cara gk error gimana
> > > > > > > > ```
> > > > > > > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
> > > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > > Naruhnya dimana
> > > > > > 
> > > > > > 
> > > > > > Di menu.js, bagian
> > > > > > ```
> > > > > > conn.reply(m.chat, text.trim(), m)
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > Ubah jadi
> > > > > > ```
> > > > > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
> > > > > > ```
> > > > > 
> > > > > 
> > > > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '[0@s.whatsapp.net](mailto:0@s.whatsapp.net)', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } }) ^ ParseError: Unexpected token
> > > > > Error
> > > 
> > > 
> > > Coba liat SC elu
> > 
> > 
> > ![IMG_20210504_071517](https://user-images.githubusercontent.com/81492529/116948053-89b8b980-aca8-11eb-8ade-916ac35cc97e.jpg)
> > Thanks gan work
> 
> Dapatkah Anda mengirimkan gambar kode Anda kepada saya sehingga saya dapat melihat bagaimana itu?

Halo gan, upload fotomu di file src, lalu ubah nama fotonya sesuai keinginan, setelah itu masuk ke menu, masukkan script yang dibagikan di atas, ubah kata "fotomu" menjadi nama file agan yang ada pada folder src.

**Comment by lilnext01** [comment]
> > > > > Cara gk error gimana
> > > > > > > > > ```
> > > > > > > > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
> > > > > > > > > ```
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Naruhnya dimana
> > > > > > > 
> > > > > > > 
> > > > > > > Di menu.js, bagian
> > > > > > > ```
> > > > > > > conn.reply(m.chat, text.trim(), m)
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > > Ubah jadi
> > > > > > > ```
> > > > > > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '[0@s.whatsapp.net](mailto:0@s.whatsapp.net)', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } }) ^ ParseError: Unexpected token
> > > > > > Error
> > > > 
> > > > 
> > > > Coba liat SC elu
> > > 
> > > 
> > > ![IMG_20210504_071517](https://user-images.githubusercontent.com/81492529/116948053-89b8b980-aca8-11eb-8ade-916ac35cc97e.jpg)
> > > Thanks gan work
> > 
> > 
> > Dapatkah Anda mengirimkan gambar kode Anda kepada saya sehingga saya dapat melihat bagaimana itu?
> 
> Halo gan, upload fotomu di file src, lalu ubah nama fotonya sesuai keinginan, setelah itu masuk ke menu, masukkan script yang dibagikan di atas, ubah kata "fotomu" menjadi nama foto agan yang ada pada folder src.

Saya sudah melakukan ini, bukan itu masalahnya :(

**Comment by jauhari21** [comment]
> > > > > > Cara gk error gimana
> > > > > > > > > > ```
> > > > > > > > > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
> > > > > > > > > > ```
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Naruhnya dimana
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Di menu.js, bagian
> > > > > > > > ```
> > > > > > > > conn.reply(m.chat, text.trim(), m)
> > > > > > > > ```
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Ubah jadi
> > > > > > > > ```
> > > > > > > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
> > > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '[0@s.whatsapp.net](mailto:0@s.whatsapp.net)', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } }) ^ ParseError: Unexpected token
> > > > > > > Error
> > > > > 
> > > > > 
> > > > > Coba liat SC elu
> > > > 
> > > > 
> > > > ![IMG_20210504_071517](https://user-images.githubusercontent.com/81492529/116948053-89b8b980-aca8-11eb-8ade-916ac35cc97e.jpg)
> > > > Thanks gan work
> > > 
> > > 
> > > Dapatkah Anda mengirimkan gambar kode Anda kepada saya sehingga saya dapat melihat bagaimana itu?
> > 
> > 
> > Halo gan, upload fotomu di file src, lalu ubah nama fotonya sesuai keinginan, setelah itu masuk ke menu, masukkan script yang dibagikan di atas, ubah kata "fotomu" menjadi nama foto agan yang ada pada folder src.
> 
> Saya sudah melakukan ini, bukan itu masalahnya :(

![Screenshot_2021-05-04-08-12-14-80](https://user-images.githubusercontent.com/81492529/116950852-83c6d680-acb0-11eb-85e5-c1a86296d063.jpg)
Kau belum mengubah kata " foto elu" dan "thumnail elu". Ubah menjadi nama foto yang sudah kamu upload di folder src

**Comment by Joseph92123** [comment]
menu.js:135
    conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '6281232322106@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } )
                               ^
ParseError: Unexpected token erorr

**Comment by Joseph92123** [comment]
ReferenceError: data is not defined
    at WAConnection.handler (E:\Data1\Josep-Bot\plugins\menu.js:135:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async WAConnection.handler (E:\Data1\Josep-Bot\handler.js:189:13)

keluar gini teruss

**Comment by Joseph92123** [comment]
> > > > > > Cara gk error gimana
> > > > > > > > > > ```
> > > > > > > > > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
> > > > > > > > > > ```
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Naruhnya dimana
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Di menu.js, bagian
> > > > > > > > ```
> > > > > > > > conn.reply(m.chat, text.trim(), m)
> > > > > > > > ```
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Ubah jadi
> > > > > > > > ```
> > > > > > > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } })
> > > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > > conn.sendFile(m.chat, foto elu, 'Foto elu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '[0@s.whatsapp.net](mailto:0@s.whatsapp.net)', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `caption elu`, "jpegThumbnail": fs.readFileSync(`./src/thumbnail elu.png`)} } }) ^ ParseError: Unexpected token
> > > > > > > Error
> > > > > 
> > > > > 
> > > > > Coba liat SC elu
> > > > 
> > > > 
> > > > ![IMG_20210504_071517](https://user-images.githubusercontent.com/81492529/116948053-89b8b980-aca8-11eb-8ade-916ac35cc97e.jpg)
> > > > Thanks gan work
> > > 
> > > 
> > > Dapatkah Anda mengirimkan gambar kode Anda kepada saya sehingga saya dapat melihat bagaimana itu?
> > 
> > 
> > Halo gan, upload fotomu di file src, lalu ubah nama fotonya sesuai keinginan, setelah itu masuk ke menu, masukkan script yang dibagikan di atas, ubah kata "fotomu" menjadi nama foto agan yang ada pada folder src.
> 
> Saya sudah melakukan ini, bukan itu masalahnya :(

saya sudah melalukan tapi masih error keluar data is not defined

**Comment by lilnext01** [comment]
![Uploading 20210503_235757.jpg…]()

**Comment by lilnext01** [comment]
Sekarang Anda menampilkan kesalahan ini

**Comment by lilnext01** [comment]
![Uploading 20210503_235757.jpg…]()

**Comment by lilnext01** [comment]
![20210503_235757](https://user-images.githubusercontent.com/74841546/116956484-c2866d80-ac6b-11eb-87d2-6f266d340b39.jpg)

**Comment by jauhari21** [comment]
![20210504_133001](https://user-images.githubusercontent.com/81492529/116967601-e3d37200-acdc-11eb-87e9-c1a8ef8c6681.png)
Yuk disimak baik", 
1. Upload foto yg mau dimunculkan di menu, uploadnya di folder src. Habis itu namain dengan format .png
2. Langsung pergi ke menu.js , tambahin let (nama foto yg udah diupload di src) = './src/(nama fotolu).png'
3. conn.sendFile(m.chat, nama fotolu, 'nama fotolu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `${conn.user.name} Verified Bot`, "jpegThumbnail": fs.readFileSync(`./src/nama fotolu.png`)} } }, m)

Note : Ubah "nama fotolu jadi nama foto yg ada di folder src yg udah lu upload.
4. Jika menu eror karena baileys harapa downgrade versi bailyes ke versi 3.4.1 di package.json.

**Comment by lilnext01** [comment]
> ![20210504_133001](https://user-images.githubusercontent.com/81492529/116967601-e3d37200-acdc-11eb-87e9-c1a8ef8c6681.png)
> Yuk disimak baik",
> 
> 1. Upload foto yg mau dimunculkan di menu, uploadnya di folder src. Habis itu namain dengan format .png
> 2. Langsung pergi ke menu.js , tambahin let (nama foto yg udah diupload di src) = './src/(nama fotolu).png' taruh diatasnya let exp,limit,level
> 3. Ubah conn.reply(m.chat, text.trim(), m)
>    Menjadi
>    conn.sendFile(m.chat, nama fotolu, 'nama fotolu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '[0@s.whatsapp.net](mailto:0@s.whatsapp.net)', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `${conn.user.name} Verified Bot`, "jpegThumbnail": fs.readFileSync(`./src/nama fotolu.png`)} } }, m)
> 
> Note : Ubah "nama fotolu" jadi nama foto yg ada di folder src yg udah lu upload.
> 
> 1. Jika menu eror karena baileys ga bisa kirim gambar harap downgrade versi bailyes ke versi 3.4.1 di package.json. habis itu install ulang ketik npm i
> 
> Udah itu aja, semoga paham dan semoga bisa ngebantu.

Terima kasih!!! Saya berhasil, terima kasih banyak !!

**Comment by KazukoGans** [comment]
![Screenshot_2021-05-04-19-30-19](https://user-images.githubusercontent.com/81819581/116997402-52c9be80-ad0f-11eb-9c42-4c228acba9d0.png)
Ini knp dh

**Comment by KazukoGans** [comment]
> ![20210504_133001](https://user-images.githubusercontent.com/81492529/116967601-e3d37200-acdc-11eb-87e9-c1a8ef8c6681.png)
> Yuk disimak baik",
> 
> 1. Upload foto yg mau dimunculkan di menu, uploadnya di folder src. Habis itu namain dengan format .png
> 2. Langsung pergi ke menu.js , tambahin let (nama foto yg udah diupload di src) = './src/(nama fotolu).png' taruh diatasnya let exp,limit,level
> 3. Ubah conn.reply(m.chat, text.trim(), m)
>    Menjadi
>    conn.sendFile(m.chat, nama fotolu, 'nama fotolu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '[0@s.whatsapp.net](mailto:0@s.whatsapp.net)', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `${conn.user.name} Verified Bot`, "jpegThumbnail": fs.readFileSync(`./src/nama fotolu.png`)} } }, m)
> 
> Note : Ubah "nama fotolu" jadi nama foto yg ada di folder src yg udah lu upload.
> 
> 1. Jika menu eror karena baileys ga bisa kirim gambar harap downgrade versi bailyes ke versi 3.4.1 di package.json. habis itu install ulang ketik npm i
> 
> Udah itu aja, semoga paham dan semoga bisa ngebantu.

RROR [2021-05-04 13:37:07.412 +0000] (15322): Unexpected identifier
    /data/data/com.termux/files/home/wabot-aq/plugins/menu.js:133
        conn.sendFile(m.chat, kazuko, 'kazuko.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": Verified Bot, "jpegThumbnail": fs.readFileSync(./src/logo.png)} } }, m)

**Comment by Ftwrr** [comment]
> ![Screenshot_2021_0501_194843](https://user-images.githubusercontent.com/78072346/116782967-4d256c00-aab6-11eb-8fba-af7b4ab49287.jpg)
> 
> Gini?

caranya biar tanpa kirim foto gimana?

**Comment by KazukoGans** [comment]
> > ![20210504_133001](https://user-images.githubusercontent.com/81492529/116967601-e3d37200-acdc-11eb-87e9-c1a8ef8c6681.png)
> > Yuk disimak baik",
> > 
> > 1. Upload foto yg mau dimunculkan di menu, uploadnya di folder src. Habis itu namain dengan format .png
> > 2. Langsung pergi ke menu.js , tambahin let (nama foto yg udah diupload di src) = './src/(nama fotolu).png' taruh diatasnya let exp,limit,level
> > 3. Ubah conn.reply(m.chat, text.trim(), m)
> >    Menjadi
> >    conn.sendFile(m.chat, nama fotolu, 'nama fotolu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '[0@s.whatsapp.net](mailto:0@s.whatsapp.net)', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `${conn.user.name} Verified Bot`, "jpegThumbnail": fs.readFileSync(`./src/nama fotolu.png`)} } }, m)
> > 
> > Note : Ubah "nama fotolu" jadi nama foto yg ada di folder src yg udah lu upload.
> > 
> > 1. Jika menu eror karena baileys ga bisa kirim gambar harap downgrade versi bailyes ke versi 3.4.1 di package.json. habis itu install ulang ketik npm i
> > 
> > Udah itu aja, semoga paham dan semoga bisa ngebantu.
> 
> RROR [2021-05-04 13:37:07.412 +0000] (15322): Unexpected identifier
> /data/data/com.termux/files/home/wabot-aq/plugins/menu.js:133
> conn.sendFile(m.chat, kazuko, 'kazuko.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '[0@s.whatsapp.net](mailto:0@s.whatsapp.net)', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": Verified Bot, "jpegThumbnail": fs.readFileSync(./src/logo.png)} } }, m)

ini knp

**Comment by bilal-08** [comment]
> > ![20210504_133001](https://user-images.githubusercontent.com/81492529/116967601-e3d37200-acdc-11eb-87e9-c1a8ef8c6681.png)
> > Come on, listen carefully ",
> > 
> > 1. Upload the photo that you want to appear on the menu, upload it in the src folder. After that, the name is in .png format
> > 2. Immediately go to menu.js, add let (the name of the photo that has been uploaded to src) = './src/ (your photo's name) .png' put it above let exp, limit, level
> > 3. Change conn.reply (m.chat, text.trim (), m) 
> >    to 
> >    conn.sendFile (m.chat, fotolu name, 'fotolu.jpg name', text.trim (), {key: {remoteJid: 'status @broadcast ', participant:' [0@s.whatsapp.net](mailto:0@s.whatsapp.net) ', fromMe: false}, message: {"imageMessage": {"mimetype": "image / jpeg", "caption `${conn.user.name} Verified Bot`":, "jpegThumbnail": fs. readFileSync ( `./src/nama fotolu.png`)}}}, m)
> > 
> > Note: Change "your photo name" to the name of the photo in the src folder that you uploaded.
> > 
> > 1. If the menu is an error because Baileys can't send images, please downgrade the bailyes version to version 3.4.1 in package.json. after that reinstall type npm i
> > 
> > That's all, I hope you understand and hopefully you can help.
> 
> Thank you!!! I did it, thank you very much !!

halo bisakah kamu membagikan kodenya? Saya bingung, tolong

**Comment by botstylee** [comment]
Kok menu gw gak nongol ya padahal sesuai yg di yg di kasih tau gw ikutin gak nongol nongol padahal semua fiture bisa tapi masalahnya menunya doang yg gak keluar

**Comment by jauhari21** [comment]
> Kok menu gw gak nongol ya padahal sesuai yg di yg di kasih tau gw ikutin gak nongol nongol padahal semua fiture bisa tapi masalahnya menunya doang yg gak keluar

Ada yg salah tuh

**Comment by botstylee** [comment]
> > Kok menu gw gak nongol ya padahal sesuai yg di yg di kasih tau gw ikutin gak nongol nongol padahal semua fiture bisa tapi masalahnya menunya doang yg gak keluar
> 
> Ada yg salah tuh

Salah di mana ya

**Comment by prioprast** [comment]
> ![20210504_133001](https://user-images.githubusercontent.com/81492529/116967601-e3d37200-acdc-11eb-87e9-c1a8ef8c6681.png)
> Yuk disimak baik",
> 
> 1. Upload foto yg mau dimunculkan di menu, uploadnya di folder src. Habis itu namain dengan format .png
> 2. Langsung pergi ke menu.js , tambahin let (nama foto yg udah diupload di src) = './src/(nama fotolu).png' taruh diatasnya let exp,limit,level
> 3. Ubah conn.reply(m.chat, text.trim(), m)
>    Menjadi
>    conn.sendFile(m.chat, nama fotolu, 'nama fotolu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '[0@s.whatsapp.net](mailto:0@s.whatsapp.net)', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption": `${conn.user.name} Verified Bot`, "jpegThumbnail": fs.readFileSync(`./src/nama fotolu.png`)} } }, m)
> 
> Note : Ubah "nama fotolu" jadi nama foto yg ada di folder src yg udah lu upload.
> 
> 1. Jika menu eror karena baileys ga bisa kirim gambar harap downgrade versi bailyes ke versi 3.4.1 di package.json. habis itu install ulang ketik npm i
> 
> Udah itu aja, semoga paham dan semoga bisa ngebantu.

conn.sendFile(m.chat, nama fotolu, 'nama fotolu.jpg', text.trim(), { key: { remoteJid: 'status@broadcast', participant: '0@s.whatsapp.net', fromMe: false }, message: { "imageMessage": { "mimetype": "image/jpeg", "caption":  'Verified Bot', "jpegThumbnail": fs.readFileSync('./src/nama fotolu.png')} } }, m)


Di bagian isi caption tidak ada tanda ( ' ) oleh karena itu terjadi kesalahan yang membuat anda bingung 😕
