### ISSUE TITLE
Cara nambahin tag di menu

### ISSUE THREAD

**Issue by jauhari21** [Nurutomo/wabot-aq#217]
Cara nambahin tag di menu gimana ya? Dah dicoba tetep aja ga muncul tagnya pas ketik .menu

**Comment by janganlahkau** [comment]
Contextinfo: mentionedJid

**Comment by jauhari21** [comment]
> Contextinfo: mentionedJid

Dibagian mana tuh gan?

**Comment by ariffb25** [comment]
ngetag user yang ngetik .menu gitu maksudnya?

**Comment by ariffb25** [comment]
Lihat baris ke 88 di folder plugins/menu.js
https://github.com/Nurutomo/wabot-aq/blob/7069b91bf06eb60124f93dfbb6f182de98c5312f/plugins/menu.js#L88
ubah menjadi seperti code dibawah ini
```js
│ Hai, @${m.sender.split`@`[0]}!
```

Lihat baris ke 134 di folder plugins/menu.js
kemudian ubah juga
https://github.com/Nurutomo/wabot-aq/blob/7069b91bf06eb60124f93dfbb6f182de98c5312f/plugins/menu.js#L134
jadi gini
```js
conn.reply(m.chat, text.trim(), m, { contextInfo: { mentionedJid: [m.sender] } })
```

Semoga membantu, terimakasih.

**Comment by jauhari21** [comment]
> Lihat baris ke 88 di folder plugins/menu.js
> https://github.com/Nurutomo/wabot-aq/blob/7069b91bf06eb60124f93dfbb6f182de98c5312f/plugins/menu.js#L88
> 
> 
> ubah menjadi seperti code dibawah ini
> ```js
> │ Hai, @${m.sender.split`@`[0]}!
> ```
> 
> Lihat baris ke 134 di folder plugins/menu.js
> kemudian ubah juga
> https://github.com/Nurutomo/wabot-aq/blob/7069b91bf06eb60124f93dfbb6f182de98c5312f/plugins/menu.js#L134
> 
> 
> jadi gini
> ```js
> conn.reply(m.chat, text.trim(), m, { contextInfo: { mentionedJid: [m.sender] } })
> ```
> 
> Semoga membantu, terimakasih.

Bukan gan, nambahin tag kek misalnya command game isinya apa aja gitu, nambahin daftar list command maksudnya hehe

**Comment by Kokoronationz** [comment]
![Screenshot_2021_0504_064510](https://user-images.githubusercontent.com/78072346/116946444-5116e100-aca4-11eb-90d2-b35585a0a6f7.jpg)
Ini mungkin yg dimaksud

**Comment by jauhari21** [comment]
> ![Screenshot_2021_0504_064510](https://user-images.githubusercontent.com/78072346/116946444-5116e100-aca4-11eb-90d2-b35585a0a6f7.jpg)
> Ini mungkin yg dimaksud

Iyap benar sekali thanks
