### ISSUE TITLE
Ukuran Thumbnail 

### ISSUE THREAD

**Issue by Hayasak** [Nurutomo/wabot-aq#218]
Cara Biar Ukuran Panjang & Lebar Thumbnail Nya Sesuai Sama Gambar Yg Di Kirim Gimana?

**Comment by z3r0-d4y-3xplo1t** [comment]
itu udah sesua ama ytnya emang thumnail ytnya kecil kecil

**Comment by Hayasak** [comment]
> itu udah sesua ama ytnya emang thumnail ytnya kecil kecil

Thumbnail Gambar WhatsApp
![IMG_20210503_071331](https://user-images.githubusercontent.com/81486764/116832515-40506780-abdf-11eb-9bf3-13524bba1815.jpg)

**Comment by ariffb25** [comment]
bukannya emng begitu ya?

**Comment by Nurutomo** [comment]
di option nya dikasih
`width` sama `height`

**Comment by Nurutomo** [comment]
baileys emg belum nambahin pendeteksi ukuran foto

**Comment by Nobuyaki** [comment]
> di option nya dikasih
> `width` sama `height`

oke bang
