### ISSUE TITLE
Fitur welcome m is not defined

### ISSUE THREAD

**Issue by Kokoronationz** [Nurutomo/wabot-aq#222]
Muncul error ketika ada yg join grup Pesan ga muncul, untuk yg left grup masih bisa

**Comment by jauhari21** [comment]
> Muncul error ketika ada yg join grup Pesan ga muncul, untuk yg left grup masih bisa

Ya senasib nih, @Nurutomo fitur welcome doang ga bisa , yg lain bisa

**Comment by Afdhan** [comment]
> Muncul error ketika ada yg join grup Pesan ga muncul, untuk yg left grup masih bisa
async participantsUpdate({ jid, participants, action }) {
    let chat = global.DATABASE._data.chats[jid]
    let text = ''
    switch (action) {
      case 'add':
      case 'remove':
        if (chat.welcome) {
          for (let user of participants) {
            let pp = './src/avatar_contact.png'
            try {
              pp = await this.getProfilePicture(user)
            } catch (e) {
            } finally {
              text = (action === 'add' ? (chat.sWelcome || this.welcome || conn.welcome || 'Welcome, @user!').replace('@subject', this.getName(jid)) :
                (chat.sBye || this.bye || conn.bye || 'Bye, @user!')).replace('@user', '@' + user.split('@')[0])
              this.sendFile(jid, pp, 'pp.jpg', text, null, false, {
                contextInfo: {
                  mentionedJid: [user]
                }
              })
            }
          }
        }


Ubah this.getName(m.key.remoteJid) jadi this.getName(jid)

**Comment by Afdhan** [comment]
> Muncul error ketika ada yg join grup Pesan ga muncul, untuk yg left grup masih bisa

Ganti `this.getName(m.key.remoteJid)` jadi `this.getName(jid)` 

:V

**Comment by jauhari21** [comment]
> > Muncul error ketika ada yg join grup Pesan ga muncul, untuk yg left grup masih bisa
> 
> Ganti `this.getName(m.key.remoteJid)` jadi `this.getName(jid)`
> 
> :V

Serius nih work ga?

**Comment by jauhari21** [comment]
> > Muncul error ketika ada yg join grup Pesan ga muncul, untuk yg left grup masih bisa
> 
> Ganti `this.getName(m.key.remoteJid)` jadi `this.getName(jid)`
> 
> :V

Anjay work gan, thanks

**Comment by Kokoronationz** [comment]
> > Muncul error ketika ada yg join grup Pesan ga muncul, untuk yg left grup masih bisa
> 
> Ganti `this.getName(m.key.remoteJid)` jadi `this.getName(jid)`
> 
> :V

Arigathanks

**Comment by Afdhan** [comment]
<3

**Comment by Nurutomo** [comment]
lupa ganti wkwkwk
