### ISSUE TITLE
Tambahin auto responder tanpa bikin banyak file .js 

### ISSUE THREAD

**Issue by janganlahkau** [Nurutomo/wabot-aq#225]
Misal kita ketik assalamualaikum tanpa prefix
Lalu bot jawab walaikumsalam  tapi di satu .js aja tanpa perlu bikin bnyk file .js nya cuk capek nambahin satu2

**Comment by FadliDarmawan** [comment]
let handler = m => m.reply('Waalaikumsalam)

handler.customPrefix = /Assalammualaikum/i
handler.command = new RegExp

module.exports = handler

Kalau ga mau bikin file.js susah juga sih
Btw tu case nya

**Comment by KazukoGans** [comment]
> let handler = m => m.reply('Waalaikumsalam)
> 
> handler.customPrefix = /Assalammualaikum/i
> handler.command = new RegExp
> 
> module.exports = handler
> 
> Kalau ga mau bikin file.js susah juga sih
> Btw tu case nya

Naruh dimana

**Comment by janganlahkau** [comment]
Cape anjir nambah file .js mulu asu emang

**Comment by Nurutomo** [comment]
> Cape anjir nambah file .js mulu asu emang

daripada error 1, error semua ;v
