### ISSUE TITLE
Jadibot.js 

### ISSUE THREAD

**Issue by Andika856** [Nurutomo/wabot-aq#229]
Jadibot.js error anjim 

![Screenshot_2021-05-04-08-29-15-60_6012fa4d4ddec268fc5c7112cbb265e7](https://user-images.githubusercontent.com/78887981/116952130-19b03080-acb4-11eb-94ba-e87a5ad7c752.jpg)

Gw tadi tanya sama yg pandai termux, katanya gada "function listener"

**Comment by syahrularranger** [comment]
Ambil sc nya di pull request
