### ISSUE TITLE
Bisa tambahin kayak auto respon tanpa pakai prefix gitu gak 

### ISSUE THREAD

**Issue by Joseph92123** [Nurutomo/wabot-aq#230]
jadi kayak kasih selamat pagi bot nya bales pagi jugaa ... gitu

**Comment by Joseph92123** [comment]
moga moga ada yang jawabb

**Comment by FadliDarmawan** [comment]
Bisa

**Comment by Nobuyaki** [comment]
> moga moga ada yang jawabb

let handler = m => m
m.reply('Pagi Juga')

handler.customPrefix = /Pagi/i
handler.command = new RegExp

module.exports = handler

**Comment by FadliDarmawan** [comment]
let handler = m => m.reply('selamat pagi juga')

handler.customPrefix = /Selamat Pagi|pagi|Pagi/i
handler.command = new RegExp

module.exports = handler

Punya nya @RC047 
Maaf baru pemula di github

**Comment by ariffb25** [comment]
```js
let handler = async (m) => m.reply('ngapain ngetag doi-nya nisa?! (｀Д´)')
handler.customPrefix = /^(@6283128734012)$/i
handler.command = new RegExp
module.exports = handler
```

**Comment by Joseph92123** [comment]
akhirnyaa
makasihh yaa

**Comment by KazukoGans** [comment]
gk work
