### ISSUE TITLE
Bisa tambahin fitur infobmkg, cuaca sama covid indo gak?

### ISSUE THREAD

**Issue by Joseph92123** [Nurutomo/wabot-aq#231]
gw butuh soalnya ....

**Comment by janganlahkau** [comment]
Gampang chat aja gw 085837136524

**Comment by ariffb25** [comment]
tambahin sendiri juga bisa kok, kan udah bnyk yang bisa dijadiin contoh :/

**Comment by Joseph92123** [comment]
cara

> tambahin sendiri juga bisa kok, kan udah bnyk yang bisa dijadiin contoh :/

caranya gmn???

**Comment by Nobuyaki** [comment]
> cara
> 
> > tambahin sendiri juga bisa kok, kan udah bnyk yang bisa dijadiin contoh :/
> 
> caranya gmn???

`let fetch = require('node-fetch')
let handler = async(m, { conn, text, usedPrefix }) => {
  if (!text) throw 'Masukan Nama Kota'
  let res = await fetch(`https://docs-jojo.herokuapp.com/api/cuaca?q=${text}`)
  let json = await res.json()
  if (json.status == 200) m.reply(`*「 INFORMASI CUACA 」*\n\n➸ Kota : ${json.result.tempat}\n➸ Cuaca : ${json.result.cuaca}\n➸ Desk : ${json.result.desk}\n➸ Suhu : ${json.result.suhu}\n➸ Kelembapan : ${json.result.kelembapan}\n➸ Udara : ${json.result.udara}\n➸ Angin : ${json.result.angin}`)
  else throw 'Gagal Mengambil Informasi Cuaca'
}
handler.help = ['cuaca <nama kota>']
handler.tags = ['internet']
handler.command = /^(cuaca)$/i

handler.fail = null

module.exports = handler
 `
Contohnya Tinggal Yg Lain Buat Sendiri aja
