### ISSUE TITLE
Cara biar ada kayak reply status nya itu gmn ...

### ISSUE THREAD

**Issue by Joseph92123** [Nurutomo/wabot-aq#233]
Moga ADA YANG jawab

**Comment by z3r0-d4y-3xplo1t** [comment]
Hmm emang mau buat

**Comment by z3r0-d4y-3xplo1t** [comment]
Chat whatsappkuh wa.me/16163190066

**Comment by FadliDarmawan** [comment]
conn.fakeReply(m.chat, info, '0@s.whatsapp.net', '*Teks Mu*', 'status@broadcast')

Tuh

**Comment by jauhari21** [comment]
> Moga ADA YANG jawab

Cek #216 udah gua jawab disitu
