### ISSUE TITLE
Sistem Larangan Berdasarkan Nomor

### ISSUE THREAD

**Issue by lilnext01** [Nurutomo/wabot-aq#234]

**Comment by lilnext01** [comment]
![20210504_085759](https://user-images.githubusercontent.com/74841546/117000151-03f03a80-acb7-11eb-89bf-caa34ec43842.jpg)
Bagaimana cara membuat sistem ini? Cekal orang yang bergabung dengan Grup, jika tidak memiliki DDD sesuai dengan yang mereka minta, mereka langsung di banned

**Comment by galau88** [comment]
if (num.includes('62')) return
bule = `${num.split('@')[0]}`
console.log(color('[KICK]', 'red'), color('Received a foreign participant',
'yellow'))
teks = `*Sorry bro this group only +62!*`
Shizuka.sendMessage(mdata.id, teks, MessageType.text)
Shizuka.groupRemove(anu.jid, [num])
}

Pada tanggal Sel, 4 Mei 2021 19.00, lilnext01 ***@***.***>
menulis:

**Comment by lilnext01** [comment]
> —
Dimana saya bisa menyimpan? di Handler.js?

**Comment by lilnext01** [comment]
![20210504_124802](https://user-images.githubusercontent.com/74841546/117031485-02366f00-acd7-11eb-8429-bc71f9c15491.jpg)
Error, [num] is not defined

**Comment by lilnext01** [comment]
(node:31174) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined                              at WAConnection.participantsUpdate [as onParticipantsUpdate] (/storage/emulated/0/bot/unsaidv4/handler.js:277:14)               at WAConnection.emit (events.js:315:20)                         at WAConnection.emit (/storage/emulated/0/bot/unsaidv4/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:629:41)

**Comment by jauhari21** [comment]
> (node:31174) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined at WAConnection.participantsUpdate [as onParticipantsUpdate] (/storage/emulated/0/bot/unsaidv4/handler.js:277:14) at WAConnection.emit (events.js:315:20) at WAConnection.emit (/storage/emulated/0/bot/unsaidv4/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:629:41)

Gua saranin sih mending jangan pake fitur itu, gua udah kapok pake fitur auto kick,add, promote. Dibanned wa 3x. Cape ganti nomor. Kalau masih mau make ya silahkan .

**Comment by lilnext01** [comment]
Saya sudah memiliki fitur ini. Saya ingin yang ini, karena sangat berguna bagi saya, saya tidak ingin orang dari negara lain bergabung dengan grup saya

**Comment by z3r0-d4y-3xplo1t** [comment]
jangan pakai fitur itu ntar kebaned wa kamu

**Comment by jauhari21** [comment]
> jangan pakai fitur itu ntar kebaned wa kamu

Ngeyel gan dia mah dibilangin, biarin ajalah wkwkwk. Biar ngerasain juga dia dibanned sama WA

**Comment by lilnext01** [comment]
> > jangan pakai fitur itu ntar kebaned wa kamu
> 
> Ngeyel gan dia mah dibilangin, biarin ajalah wkwkwk. Biar ngerasain juga dia dibanned sama WA

Tidak, saya tidak marah karena saya diblokir, saya sangat menyukai fungsi ini, sangat berguna bagi saya, dan grup saya, saya orang Brasil, di sini, angkanya dimulai dengan +55, dan itu terjadi beberapa kali yang digunakan orang Brasil lainnya sebuah nomor palsu misalnya, gunakan nomor dari amerika serikat "+1", dan lakukan itu untuk bergabung dengan grup dan berhenti, lho? Saya ingin menghindari ini, dan fungsi itu akan menjadi sempurna

**Comment by lilnext01** [comment]
Tolong bantu aku

**Comment by Nurutomo** [comment]
replace num with participant jid like 62XXXXXXXXXXX@s.whatsapp.net

**Comment by lilnext01** [comment]
> replace num with participant jid like [62XXXXXXXXXXX@s.whatsapp.net](mailto:62XXXXXXXXXXX@s.whatsapp.net)

Di mana saya bisa mengubah Handler.js?

**Comment by lilnext01** [comment]
> replace num with participant jid like [62XXXXXXXXXXX@s.whatsapp.net](mailto:62XXXXXXXXXXX@s.whatsapp.net)

![20210507_092507](https://user-images.githubusercontent.com/74841546/117449269-292eb400-af16-11eb-9148-95fe14e95f23.jpg)
@Nurutomo Di mana saya bisa mengubah Handler.js?
