### ISSUE TITLE
smule,twitter,snackvideo error

### ISSUE THREAD

**Issue by anshuljai** [Nurutomo/wabot-aq#235]
now solve other bugs twitter and smule and snackvideo

**Comment by anshuljai** [comment]
@Nurutomo

**Comment by Nurutomo** [comment]
> when i use it..throws error
> 
> TypeError: Cannot read property 'split' of undefined
> at WAConnection.handler (/data/data/com.termux/files/home/darkbot/plugins/inspectlink.js:16:42)
> at processTicksAndRejections (internal/process/task_queues.js:93:5)
> at async WAConnection.handler (/data/data/com.termux/files/home/darkbot/handler.js:189:13)

screenshot the command you trying to run

**Comment by anshuljai** [comment]
![IMG_20210507_073129](https://user-imag@Nurutomo s.githubusercontent.com/24720160/117387300-465b8680-af06-11eb-9447-1e6538f5cf3d.jpg)
@

**Comment by anshuljai** [comment]
@Nurutomo 



![IMG_20210507_073129](https://user-images.githubusercontent.com/24720160/117387338-596e5680-af06-11eb-8f05-ff99bcba002d.jpg)

**Comment by anshuljai** [comment]
and also plugins twitter,smule,snackvideo,tiktok has syntax error

**Comment by anshuljai** [comment]
![Screenshot_2021-05-07-07-33-45-695_com termux](https://user-images.githubusercontent.com/24720160/117387466-963a4d80-af06-11eb-8fa9-983bdbdc8a54.jpg)
check this also please

**Comment by anshuljai** [comment]
@Nurutomo @MFarelS

**Comment by FadliDarmawan** [comment]
Kan "Fitur belum jadi"

**Comment by Nurutomo** [comment]
the feature is not worked on
