### ISSUE TITLE
Ada yang tau cara bales command pake audio vn?

### ISSUE THREAD

**Issue by jauhari21** [Nurutomo/wabot-aq#236]
![IMG_20210505_174333](https://user-images.githubusercontent.com/81492529/117129975-997bef00-adc9-11eb-9a5b-a99ffc7fef23.jpg)
Kek gini contohnya, siapa tau ada yang tau . Bagi scriptnya dung

**Comment by syahrularranger** [comment]
> ![IMG_20210505_174333](https://user-images.githubusercontent.com/81492529/117129975-997bef00-adc9-11eb-9a5b-a99ffc7fef23.jpg)
> Kek gini contohnya, siapa tau ada yang tau . Bagi scriptnya dung

Harus punya audio nya dulu .opus
Kalo aku pake itu.. dari mp3 di cv ke opus di web comverter

**Comment by Afdhan** [comment]
> ![IMG_20210505_174333](https://user-images.githubusercontent.com/81492529/117129975-997bef00-adc9-11eb-9a5b-a99ffc7fef23.jpg)
> Kek gini contohnya, siapa tau ada yang tau . Bagi scriptnya dung

`let util = require('util')
let path = require('path')

let handler = async (m, { conn, args }) => {
  let vn ='src/SALAM.opus'
  conn.sendFile(m.chat, vn, 'Pake_Salam.opus','salam', m)
}
handler.customPrefix = /(p(unten|ermisi)?|halo|hai)/i
handler.command = new RegExp
module.exports = handler`

**Comment by jauhari21** [comment]
> > ![IMG_20210505_174333](https://user-images.githubusercontent.com/81492529/117129975-997bef00-adc9-11eb-9a5b-a99ffc7fef23.jpg)
> > Kek gini contohnya, siapa tau ada yang tau . Bagi scriptnya dung
> 
> Harus punya audio nya dulu .opus
> Kalo aku pake itu.. dari mp3 di cv ke opus di web comverter

Bagi scriptnya gan?

**Comment by jauhari21** [comment]
> > ![IMG_20210505_174333](https://user-images.githubusercontent.com/81492529/117129975-997bef00-adc9-11eb-9a5b-a99ffc7fef23.jpg)
> > Kek gini contohnya, siapa tau ada yang tau . Bagi scriptnya dung
> 
> let util = require('util')
> let path = require('path')
> 
> let handler = async (m, { conn, args }) => {
> let vn ='src/SALAM.opus'
> conn.sendFile(m.chat, vn, 'Pake_Salam.opus','salam', m)
> }
> handler.customPrefix = /(p(unten|ermisi)?|halo|hai)/i
> handler.command = new RegExp
> module.exports = handler
> 
> Kurang lebih gini, Maaf kalau gk work :)

Oke nanti saya coba

**Comment by jauhari21** [comment]
> > ![IMG_20210505_174333](https://user-images.githubusercontent.com/81492529/117129975-997bef00-adc9-11eb-9a5b-a99ffc7fef23.jpg)
> > Kek gini contohnya, siapa tau ada yang tau . Bagi scriptnya dung
> 
> let util = require('util')
> let path = require('path')
> 
> let handler = async (m, { conn, args }) => {
> let vn ='src/SALAM.opus'
> conn.sendFile(m.chat, vn, 'Pake_Salam.opus','salam', m)
> }
> handler.customPrefix = /(p(unten|ermisi)?|halo|hai)/i
> handler.command = new RegExp
> module.exports = handler
> 
> Kurang lebih gini, Maaf kalau gk work :)

![Screenshot_2021-05-06-07-40-15-22](https://user-images.githubusercontent.com/81492529/117226214-5c9e0f80-ae3e-11eb-8ee7-4c163fb4c840.jpg)
Bukan vn jadinya gan :v, cara biar jadi VN gimana?

**Comment by Kokoronationz** [comment]
![IMG_20210506_075117.jpg](https://user-images.githubusercontent.com/78072346/117226964-016d1c80-ae40-11eb-93af-c1e173571753.jpg)

`
let util = require('util')
let path = require('path')

let handler = async (m, { conn }) => {
let vn ='src/yamete.opus'
conn.sendFile(m.chat, vn, 'yamete.opus', null, m, true)
}
handler.customPrefix = /Yamete/i
handler.command = new RegExp
module.exports = handler
`

**Comment by jauhari21** [comment]
> ![IMG_20210506_075117.jpg](https://user-images.githubusercontent.com/78072346/117226964-016d1c80-ae40-11eb-93af-c1e173571753.jpg)
> 
> `
> let util = require('util')
> let path = require('path')
> 
> let handler = async (m, { conn }) => {
> let vn ='src/yamete.opus'
> conn.sendFile(m.chat, vn, 'yamete.opus', null, m, true)
> }
> handler.customPrefix = /Yamete/i
> handler.command = new RegExp
> module.exports = handler
> `

![IMG_20210506_081427](https://user-images.githubusercontent.com/81492529/117228562-7ee65c00-ae43-11eb-937b-aee8a2b25694.jpg)
Ga bisa diplay gan

**Comment by Kokoronationz** [comment]
> > ![IMG_20210506_075117.jpg](https://user-images.githubusercontent.com/78072346/117226964-016d1c80-ae40-11eb-93af-c1e173571753.jpg)
> > 
> > `
> > let util = require('util')
> > let path = require('path')
> > 
> > let handler = async (m, { conn }) => {
> > let vn ='src/yamete.opus'
> > conn.sendFile(m.chat, vn, 'yamete.opus', null, m, true)
> > }
> > handler.customPrefix = /Yamete/i
> > handler.command = new RegExp
> > module.exports = handler
> > `
> 
> ![IMG_20210506_081427](https://user-images.githubusercontent.com/81492529/117228562-7ee65c00-ae43-11eb-937b-aee8a2b25694.jpg)
> Ga bisa diplay gan

![Screenshot_2021_0506_081925.jpg](https://user-images.githubusercontent.com/78072346/117228717-c967d880-ae43-11eb-8af8-381530c8dc3f.jpg)

Punya gw bisa tuh

**Comment by jauhari21** [comment]
> > > ![IMG_20210506_075117.jpg](https://user-images.githubusercontent.com/78072346/117226964-016d1c80-ae40-11eb-93af-c1e173571753.jpg)
> > > `
> > > let util = require('util')
> > > let path = require('path')
> > > let handler = async (m, { conn }) => {
> > > let vn ='src/yamete.opus'
> > > conn.sendFile(m.chat, vn, 'yamete.opus', null, m, true)
> > > }
> > > handler.customPrefix = /Yamete/i
> > > handler.command = new RegExp
> > > module.exports = handler
> > > `
> > 
> > 
> > ![IMG_20210506_081427](https://user-images.githubusercontent.com/81492529/117228562-7ee65c00-ae43-11eb-937b-aee8a2b25694.jpg)
> > Ga bisa diplay gan
> 
> ![Screenshot_2021_0506_081925.jpg](https://user-images.githubusercontent.com/78072346/117228717-c967d880-ae43-11eb-8af8-381530c8dc3f.jpg)
> 
> Punya gw bisa tuh

Punya gua ga bisa njir kenapa yak, dah coba copas punya lu juga sama audionya tetep aja ga bisa diplay

**Comment by Kokoronationz** [comment]
> > > > ![IMG_20210506_075117.jpg](https://user-images.githubusercontent.com/78072346/117226964-016d1c80-ae40-11eb-93af-c1e173571753.jpg)
> > > > `let util = require('util') let path = require('path') let handler = async (m, { conn }) => { let vn ='src/yamete.opus' conn.sendFile(m.chat, vn, 'yamete.opus', null, m, true) } handler.customPrefix = /Yamete/i handler.command = new RegExp module.exports = handler`
> > > 
> > > 
> > > ![IMG_20210506_081427](https://user-images.githubusercontent.com/81492529/117228562-7ee65c00-ae43-11eb-937b-aee8a2b25694.jpg)
> > > Ga bisa diplay gan
> > 
> > 
> > ![Screenshot_2021_0506_081925.jpg](https://user-images.githubusercontent.com/78072346/117228717-c967d880-ae43-11eb-8af8-381530c8dc3f.jpg)
> > Punya gw bisa tuh
> 
> Punya gua ga bisa njir kenapa yak, dah coba copas punya lu juga sama audionya tetep aja ga bisa diplay

Coba cek file audio elu

**Comment by anshuljai** [comment]
inspect error lagi.....

**Comment by syahrularranger** [comment]
> > ![IMG_20210505_174333](https://user-images.githubusercontent.com/81492529/117129975-997bef00-adc9-11eb-9a5b-a99ffc7fef23.jpg)
> > Kek gini contohnya, siapa tau ada yang tau . Bagi scriptnya dung
> 
> Harus punya audio nya dulu .opus
> Kalo aku pake itu.. dari mp3 di cv ke opus di web comverter

Kan aku dah bilang di atas :v

**Comment by syahrularranger** [comment]
> > > > ![IMG_20210506_075117.jpg](https://user-images.githubusercontent.com/78072346/117226964-016d1c80-ae40-11eb-93af-c1e173571753.jpg)
> > > > `let util = require('util') let path = require('path') let handler = async (m, { conn }) => { let vn ='src/yamete.opus' conn.sendFile(m.chat, vn, 'yamete.opus', null, m, true) } handler.customPrefix = /Yamete/i handler.command = new RegExp module.exports = handler`
> > > 
> > > 
> > > ![IMG_20210506_081427](https://user-images.githubusercontent.com/81492529/117228562-7ee65c00-ae43-11eb-937b-aee8a2b25694.jpg)
> > > Ga bisa diplay gan
> > 
> > 
> > ![Screenshot_2021_0506_081925.jpg](https://user-images.githubusercontent.com/78072346/117228717-c967d880-ae43-11eb-8af8-381530c8dc3f.jpg)
> > Punya gw bisa tuh
> 
> Punya gua ga bisa njir kenapa yak, dah coba copas punya lu juga sama audionya tetep aja ga bisa diplay

Ubah dulu ke opus.. pake cv web... Ga smua web bisa

**Comment by jauhari21** [comment]
> > > > > ![IMG_20210506_075117.jpg](https://user-images.githubusercontent.com/78072346/117226964-016d1c80-ae40-11eb-93af-c1e173571753.jpg)
> > > > > `let util = require('util') let path = require('path') let handler = async (m, { conn }) => { let vn ='src/yamete.opus' conn.sendFile(m.chat, vn, 'yamete.opus', null, m, true) } handler.customPrefix = /Yamete/i handler.command = new RegExp module.exports = handler`
> > > > 
> > > > 
> > > > ![IMG_20210506_081427](https://user-images.githubusercontent.com/81492529/117228562-7ee65c00-ae43-11eb-937b-aee8a2b25694.jpg)
> > > > Ga bisa diplay gan
> > > 
> > > 
> > > ![Screenshot_2021_0506_081925.jpg](https://user-images.githubusercontent.com/78072346/117228717-c967d880-ae43-11eb-8af8-381530c8dc3f.jpg)
> > > Punya gw bisa tuh
> > 
> > 
> > Punya gua ga bisa njir kenapa yak, dah coba copas punya lu juga sama audionya tetep aja ga bisa diplay
> 
> Ubah dulu ke opus.. pake cv web... Ga smua web bisa

Udah njir, malahan gua copy semua script dan audionya si @Kokoronationz tetep aj ga bisa diplay

**Comment by Nurutomo** [comment]
hmm
```js
conn.sendFile(m.chat, vn, 'yamete.opus', null, m, true, {
  type: 'audioMessage', // paksa tanpa convert di ffmpeg
  ptt: true // true diatas ga work, sebab dipaksa tanpa convert ;v
})
```

**Comment by jauhari21** [comment]
> hmm
> 
> ```js
> conn.sendFile(m.chat, vn, 'yamete.opus', null, m, true, {
>   type: 'audioMessage', // paksa tanpa convert di ffmpeg
>   ptt: true // true diatas ga work, sebab dipaksa tanpa convert ;v
> })
> ```

Jadi gimana? Gua pake hosting soalnya ga pake termux. Jadi karena ga ada ffmpegnya ya? Biar tanpa ffmpeg scriptnya gimana?

**Comment by jauhari21** [comment]
> > > > > ![IMG_20210506_075117.jpg](https://user-images.githubusercontent.com/78072346/117226964-016d1c80-ae40-11eb-93af-c1e173571753.jpg)
> > > > > `let util = require('util') let path = require('path') let handler = async (m, { conn }) => { let vn ='src/yamete.opus' conn.sendFile(m.chat, vn, 'yamete.opus', null, m, true) } handler.customPrefix = /Yamete/i handler.command = new RegExp module.exports = handler`
> > > > 
> > > > 
> > > > ![IMG_20210506_081427](https://user-images.githubusercontent.com/81492529/117228562-7ee65c00-ae43-11eb-937b-aee8a2b25694.jpg)
> > > > Ga bisa diplay gan
> > > 
> > > 
> > > ![Screenshot_2021_0506_081925.jpg](https://user-images.githubusercontent.com/78072346/117228717-c967d880-ae43-11eb-8af8-381530c8dc3f.jpg)
> > > Punya gw bisa tuh
> > 
> > 
> > Punya gua ga bisa njir kenapa yak, dah coba copas punya lu juga sama audionya tetep aja ga bisa diplay
> 
> Coba cek file audio elu

Oh iya lu pake termux gan?

**Comment by jauhari21** [comment]
> > > > > ![IMG_20210506_075117.jpg](https://user-images.githubusercontent.com/78072346/117226964-016d1c80-ae40-11eb-93af-c1e173571753.jpg)
> > > > > `let util = require('util') let path = require('path') let handler = async (m, { conn }) => { let vn ='src/yamete.opus' conn.sendFile(m.chat, vn, 'yamete.opus', null, m, true) } handler.customPrefix = /Yamete/i handler.command = new RegExp module.exports = handler`
> > > > 
> > > > 
> > > > ![IMG_20210506_081427](https://user-images.githubusercontent.com/81492529/117228562-7ee65c00-ae43-11eb-937b-aee8a2b25694.jpg)
> > > > Ga bisa diplay gan
> > > 
> > > 
> > > ![Screenshot_2021_0506_081925.jpg](https://user-images.githubusercontent.com/78072346/117228717-c967d880-ae43-11eb-8af8-381530c8dc3f.jpg)
> > > Punya gw bisa tuh
> > 
> > 
> > Punya gua ga bisa njir kenapa yak, dah coba copas punya lu juga sama audionya tetep aja ga bisa diplay
> 
> Coba cek file audio elu

![Screenshot_2021-05-08-21-10-47-05](https://user-images.githubusercontent.com/81492529/117542256-144f3f00-b042-11eb-895c-ec514d56f82b.jpg)

**Comment by jauhari21** [comment]
> > ![IMG_20210505_174333](https://user-images.githubusercontent.com/81492529/117129975-997bef00-adc9-11eb-9a5b-a99ffc7fef23.jpg)
> > Kek gini contohnya, siapa tau ada yang tau . Bagi scriptnya dung
> 
> let util = require('util')
> let path = require('path')
> 
> let handler = async (m, { conn, args }) => {
> let vn ='src/SALAM.opus'
> conn.sendFile(m.chat, vn, 'Pake_Salam.opus','salam', m)
> }
> handler.customPrefix = /(p(unten|ermisi)?|halo|hai)/i
> handler.command = new RegExp
> module.exports = handler
> 
> Kurang lebih gini, Maaf kalau gk work :)

Klo audionya ambil dari github jadi kek gimna skriptnya gan? https://github.com/AlvioAdjiJanuar/SuaraCewek
