### ISSUE TITLE
Cara ngatur limit batasan

### ISSUE THREAD

**Issue by jauhari21** [Nurutomo/wabot-aq#239]
Kalo cara ngatur limit biar ada batasan terus kereset tiap harinya misalnya sehari dikasih 30 limit batasannya , nanti jam 12 malem kereset jadi 30 limit lagi :v.

**Comment by Nurutomo** [comment]
[node-cron](https://www.npmjs.com/package/node-cron) ;v

**Comment by jauhari21** [comment]
> [node-cron](https://www.npmjs.com/package/node-cron) ;v

Gimana cara makenya? :V
