### ISSUE TITLE
added triggered plugin for stickers

### ISSUE THREAD

**Issue by anshuljai** [Nurutomo/wabot-aq#240]
const uploadImage = require('../lib/uploadImage') 

const { sticker } = require('../lib/sticker')
const { MessageType } = require('@adiwajshing/baileys')

let handler = async (m, { conn, text }) => {
 try {
  let q = m.quoted ? m.quoted : m
  let mime = (q.msg || q).mimetype || ''
  if (!mime) throw 'Tidak ada foto'
  if (!/image\/(jpe?g|png)/.test(mime)) throw `Mime ${mime} tidak support`
  let img = await q.download()
  let url = await uploadImage(img)
  let trigger = `https://some-random-api.ml/canvas/triggered?avatar=${url}`
  let stiker = await sticker(null, trigger, 'Triggered', '©Anshul)
  conn.sendMessage(m.chat, stiker, MessageType.sticker, {
    quoted: m
  })
 } catch (e) {
   m.reply('Conversion Failed')
  }
}
handler.help = ['trigger']
handler.tags = ['sticker']
handler.command = /^trigger$/i
handler.owner = false
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null

module.exports = handler

**Comment by Kokoronationz** [comment]
> const uploadImage = require('../lib/uploadImage')
> const { sticker } = require('../lib/sticker')
> const { MessageType } = require('@adiwajshing/baileys')
> 
> let handler = async (m, { conn, text }) => {
> try {
> let q = m.quoted ? m.quoted : m
> let mime = (q.msg || q).mimetype || ''
> if (!mime) throw 'Tidak ada foto'
> if (!/image/(jpe?g|png)/.test(mime)) throw `Mime ${mime} tidak support`
> let img = await q.download()
> let url = await uploadImage(img)
> let trigger = `https://some-random-api.ml/canvas/triggered?avatar=${url}`
> let stiker = await sticker(null, trigger, 'Triggered', '©Anshul)
> conn.sendMessage(m.chat, stiker, MessageType.sticker, {
> quoted: m
> })
> } catch (e) {
> m.reply('Conversion Failed')
> }
> }
> handler.help = ['trigger']
> handler.tags = ['sticker']
> handler.command = /^trigger$/i
> handler.owner = false
> handler.mods = false
> handler.premium = false
> handler.group = false
> handler.private = false
> 
> handler.admin = false
> handler.botAdmin = false
> 
> handler.fail = null
> 
> module.exports = handler

Error

**Comment by anshuljai** [comment]
> > const uploadImage = require('../lib/uploadImage')
> > const { sticker } = require('../lib/sticker')
> > const { MessageType } = require('@adiwajshing/baileys')
> > let handler = async (m, { conn, text }) => {
> > try {
> > let q = m.quoted ? m.quoted : m
> > let mime = (q.msg || q).mimetype || ''
> > if (!mime) throw 'Tidak ada foto'
> > if (!/image/(jpe?g|png)/.test(mime)) throw `Mime ${mime} tidak support`
> > let img = await q.download()
> > let url = await uploadImage(img)
> > let trigger = `https://some-random-api.ml/canvas/triggered?avatar=${url}`
> > let stiker = await sticker(null, trigger, 'Triggered', '©Anshul)
> > conn.sendMessage(m.chat, stiker, MessageType.sticker, {
> > quoted: m
> > })
> > } catch (e) {
> > m.reply('Conversion Failed')
> > }
> > }
> > handler.help = ['trigger']
> > handler.tags = ['sticker']
> > handler.command = /^trigger$/i
> > handler.owner = false
> > handler.mods = false
> > handler.premium = false
> > handler.group = false
> > handler.private = false
> > handler.admin = false
> > handler.botAdmin = false
> > handler.fail = null
> > module.exports = handler
> 
> Error

the higlighted lines in the above plugin should start and end by `

**Comment by Kokoronationz** [comment]
use this one

```
const uploadImage = require('../lib/uploadImage')
const { sticker } = require('../lib/sticker')
const { MessageType } = require('@adiwajshing/baileys')

let handler = async (m, { conn, text }) => {
  await m.reply('Tunggu sebentar...')
try {
  let q = m.quoted ? m.quoted : m
  let mime = (q.msg || q).mimetype || ''
  if (!mime) throw 'Tidak ada foto'
  if (!/image\/(jpe?g|png)/.test(mime)) throw `Mime ${mime} tidak support`
  let img = await q.download()
  let url = await uploadImage(img)
  let trigger = `https://some-random-api.ml/canvas/triggered?avatar=${url}`
  let stiker = await sticker(null, trigger, 'Triggered', '@Kokoronationz')
  conn.sendMessage(m.chat, stiker, MessageType.sticker, {
    quoted: m
  })
} catch (e) {
  m.reply('Conversion Failed')
  }
}


handler.help = ['trigger (caption|reply media)']
handler.tags = ['sticker']
handler.command = /^(trigger(ed)?)$/i
handler.limit = true
handler.group = false
handler.register = true
module.exports = handler
```

**Comment by KazukoGans** [comment]
> use this one
> 
> ```
> const uploadImage = require('../lib/uploadImage')
> const { sticker } = require('../lib/sticker')
> const { MessageType } = require('@adiwajshing/baileys')
> 
> let handler = async (m, { conn, text }) => {
>   await m.reply('Tunggu sebentar...')
> try {
>   let q = m.quoted ? m.quoted : m
>   let mime = (q.msg || q).mimetype || ''
>   if (!mime) throw 'Tidak ada foto'
>   if (!/image\/(jpe?g|png)/.test(mime)) throw `Mime ${mime} tidak support`
>   let img = await q.download()
>   let url = await uploadImage(img)
>   let trigger = `https://some-random-api.ml/canvas/triggered?avatar=${url}`
>   let stiker = await sticker(null, trigger, 'Triggered', '@Kokoronationz')
>   conn.sendMessage(m.chat, stiker, MessageType.sticker, {
>     quoted: m
>   })
> } catch (e) {
>   m.reply('Conversion Failed')
>   }
> }
> 
> 
> handler.help = ['trigger (caption|reply media)']
> handler.tags = ['sticker']
> handler.command = /^(trigger(ed)?)$/i
> handler.limit = true
> handler.group = false
> handler.register = true
> module.exports = handler
> ```

failed
