### ISSUE TITLE
Node . --self

### ISSUE THREAD

**Issue by Kokoronationz** [Nurutomo/wabot-aq#242]
Cara biar owner (selain nomor bot) bisa Pake saat #disable public atau node . --self

**Comment by anshuljai** [comment]
mod?????????

**Comment by jauhari21** [comment]
> Cara biar owner (selain nomor bot) bisa Pake saat #disable public atau node . --self

Tambahin nomor di config.js tambahin di owner atau moderator

**Comment by syurki** [comment]
Cara menggunakan bot node self nya gimana ya?? 
Dan juga session name Yg mana?

**Comment by Miaweers** [comment]
> Cara menggunakan bot node self nya gimana ya??
> Dan juga session name Yg mana?

node index.js --self

**Comment by Nurutomo** [comment]
> Cara biar owner (selain nomor bot) bisa Pake saat #disable public atau node . --self

self itu diri sendiri, bukan nomor lain
