### ISSUE TITLE
welcome feature error....

### ISSUE THREAD

**Issue by anshuljai** [Nurutomo/wabot-aq#245]
not printing welcome on new member

@Nurutomo 

![Screenshot_2021-05-09-09-54-59-511_com termux](https://user-images.githubusercontent.com/24720160/117560604-d2a7ae00-b0ac-11eb-8d17-57b74e37a509.jpg)

**Comment by anshuljai** [comment]
leave is working.....add  welcome is not working

**Comment by jauhari21** [comment]
> not printing welcome on new member
> 
> @Nurutomo
> 
> ![Screenshot_2021-05-09-09-54-59-511_com termux](https://user-images.githubusercontent.com/24720160/117560604-d2a7ae00-b0ac-11eb-8d17-57b74e37a509.jpg)

Cek https://github.com/Nurutomo/wabot-aq/issues/222#issuecomment-832171738

**Comment by anshuljai** [comment]
> > not printing welcome on new member
> > @Nurutomo
> > ![Screenshot_2021-05-09-09-54-59-511_com termux](https://user-images.githubusercontent.com/24720160/117560604-d2a7ae00-b0ac-11eb-8d17-57b74e37a509.jpg)
> 
> Cek ->> [#222 (comment)](https://github.com/Nurutomo/wabot-aq/issues/222#issuecomment-832171738)

@jauhari21 line 281 of handler.js?
