### ISSUE TITLE
Harta tahta, fb ig fitur nya error semua ..., mager nulis juga

### ISSUE THREAD

**Issue by Joseph92123** [Nurutomo/wabot-aq#246]
Tolongggg

**Comment by anshuljai** [comment]
screenshot of error?

**Comment by Joseph92123** [comment]
bentarr

**Comment by Joseph92123** [comment]
keluar kayak 'error' is not defined gituu ...

**Comment by anshuljai** [comment]
wait i will create a pull request of harta tahta.....it is working

**Comment by anshuljai** [comment]
check pull requests @Joseph92123

**Comment by Joseph92123** [comment]
oke

**Comment by Joseph92123** [comment]
keluar ffmpeg spawn not found

**Comment by YuukiDes** [comment]
> wait i will create a pull request of harta tahta.....it is working

website xteam down

**Comment by FadliDarmawan** [comment]
Api server down

**Comment by Nurutomo** [comment]
> keluar ffmpeg spawn not found

install ffmpeg dulu ...
