### ISSUE TITLE
Perintah untuk melihat daftar yang paling aktif di grup ...

### ISSUE THREAD

**Issue by lilnext01** [Nurutomo/wabot-aq#257]
Contoh: Anda menjalankan perintah, dan ini menampilkan Daftar 10 Teratas dari anggota grup yang paling aktif, daftar ini dapat dihitung dengan jumlah pesan yang dikirim oleh setiap anggota

@Nurutomo & Team

**Comment by Nurutomo** [comment]
hm

**Comment by ariffb25** [comment]
https://github.com/Nurutomo/wabot-aq/commit/acb7543d512ec97f0bbd2d3c92f1b727eac160be
