### ISSUE TITLE
To IMG error Posisi run di heroku

### ISSUE THREAD

**Issue by bagusdwip** [Nurutomo/wabot-aq#260]
UnhandledPromiseRejectionWarning: Error: Could not find MIME for Buffer <null>
at Jimp.parseBitmap (/app/node_modules/@jimp/core/dist/utils/image-bitmap.js:187:15)
at Jimp.parseBitmap (/app/node_modules/@jimp/core/dist/index.js:431:32)
at /app/node_modules/@jimp/core/dist/index.js:373:15
at FSReqCallback.readFileAfterClose [as oncomplete]

Yang tau komen lah:(

**Comment by Lord-Gaming** [comment]
> UnhandledPromiseRejectionWarning: Error: Could not find MIME for Buffer
> at Jimp.parseBitmap (/app/node_modules/@jimp/core/dist/utils/image-bitmap.js:187:15)
> at Jimp.parseBitmap (/app/node_modules/@jimp/core/dist/index.js:431:32)
> at /app/node_modules/@jimp/core/dist/index.js:373:15
> at FSReqCallback.readFileAfterClose [as oncomplete]
> 
> Yang tau komen lah:(

kayaknya karena api down ngab

**Comment by Nurutomo** [comment]
itu soalnya imagemagick gaada
