### ISSUE TITLE
Cara nambahin keterangan premium di profile.js

### ISSUE THREAD

**Issue by jauhari21** [Nurutomo/wabot-aq#263]
Ada yg tau cara nambahin premium = Yes atau No gitu di profile atau menu

**Comment by Nobuyaki** [comment]
> Ada yg tau cara nambahin premium = Yes atau No gitu di profile atau menu

pakek
${××××× ? 'yes' : 'no'}
`×××××` di isi `global.DATABASE.data.users[m.sender].premium`

**Comment by anshuljai** [comment]
> > Ada yg tau cara nambahin premium = Yes atau No gitu di profile atau menu
> 
> pakek
> ${××××× ? 'yes' : 'no'}
> `×××××` di isi `global.DATABASE.data.users[m.sender].premium`

bro give full code 😞

**Comment by Nurutomo** [comment]
> > > > > Ada yg tau cara nambahin premium = Yes atau No gitu di profile atau menu
> > > > 
> > > > 
> > > > pakek
> > > > ${××××× ? 'yes' : 'no'}
> > > > `×××××` di isi `global.DATABASE.data.users[m.sender].premium`
> > > 
> > > 
> > > Tetep aja gan tulisannya tidak, padahal nomor saya udah ada di premium
> > 
> > 
> > addprems yg asli dari ini kan m.chat jadi yg di tambahin premium chat bukan users
> 
> Jadi gini?
> global.DATABASE._data.chats[m.chat].premium

yoi

**Comment by Afdhan** [comment]
> > > > > > > Ada yg tau cara nambahin premium = Yes atau No gitu di profile atau menu
> > > > > > 
> > > > > > 
> > > > > > pakek
> > > > > > ${××××× ? 'yes' : 'no'}
> > > > > > `×××××` di isi `global.DATABASE.data.users[m.sender].premium`
> > > > > 
> > > > > 
> > > > > Tetep aja gan tulisannya tidak, padahal nomor saya udah ada di premium
> > > > 
> > > > 
> > > > addprems yg asli dari ini kan m.chat jadi yg di tambahin premium chat bukan users
> > > 
> > > 
> > > Jadi gini?
> > > global.DATABASE._data.chats[m.chat].premium
> > 
> > 
> > yoi
> 
> ![Screenshot_2021-05-12-03-56-47-52](https://user-images.githubusercontent.com/81492529/117883984-4d9fdd00-b2d6-11eb-9aaf-e03f03133457.jpg)
> 
> Kalo Dari config ga kedetect kah?
> Atau scriptku yg salah ?
> 
> ${global.DATABASE._data.chats[m.chat].premium ? 'yes' : 'no'}

Kalau dari config.js bikin aja 

`let premium = global.prems.map(v => v.replace(/[^0-9]/g, '') + '@s.whatsapp.net').includes(m.sender)`
`${premium ? 'YES':'NO'}`

Atau 
`let handler = async (m, { conn, isPrems }) => {`
`${isPrems ? 'YES':'NO'}`
`}`

**Comment by jauhari21** [comment]
> > > > > > > > Ada yg tau cara nambahin premium = Yes atau No gitu di profile atau menu
> > > > > > > 
> > > > > > > 
> > > > > > > pakek
> > > > > > > ${××××× ? 'yes' : 'no'}
> > > > > > > `×××××` di isi `global.DATABASE.data.users[m.sender].premium`
> > > > > > 
> > > > > > 
> > > > > > Tetep aja gan tulisannya tidak, padahal nomor saya udah ada di premium
> > > > > 
> > > > > 
> > > > > addprems yg asli dari ini kan m.chat jadi yg di tambahin premium chat bukan users
> > > > 
> > > > 
> > > > Jadi gini?
> > > > global.DATABASE._data.chats[m.chat].premium
> > > 
> > > 
> > > yoi
> > 
> > 
> > ![Screenshot_2021-05-12-03-56-47-52](https://user-images.githubusercontent.com/81492529/117883984-4d9fdd00-b2d6-11eb-9aaf-e03f03133457.jpg)
> > Kalo Dari config ga kedetect kah?
> > Atau scriptku yg salah ?
> > ${global.DATABASE._data.chats[m.chat].premium ? 'yes' : 'no'}
> 
> Kalau dari config.js bikin aja
> 
> ```js
> let premium = global.prems.map(v => v.replace(/[^0-9]/g, '') + '@s.whatsapp.net').includes(m.sender)
> ${premium ? 'YES':'NO'}
> ```
> 
> Atau
> 
> ```js
> let handler = async (m, { conn, isPrems }) => {
> ${isPrems ? 'YES':'NO'}
> ```

Oke gan thanks, bisa hehe

**Comment by anshuljai** [comment]
> > > > > > > > > Ada yg tau cara nambahin premium = Yes atau No gitu di profile atau menu
> > > > > > > > 
> > > > > > > > 
> > > > > > > > pakek
> > > > > > > > ${××××× ? 'yes' : 'no'}
> > > > > > > > `×××××` di isi `global.DATABASE.data.users[m.sender].premium`
> > > > > > > 
> > > > > > > 
> > > > > > > Tetep aja gan tulisannya tidak, padahal nomor saya udah ada di premium
> > > > > > 
> > > > > > 
> > > > > > addprems yg asli dari ini kan m.chat jadi yg di tambahin premium chat bukan users
> > > > > 
> > > > > 
> > > > > Jadi gini?
> > > > > global.DATABASE._data.chats[m.chat].premium
> > > > 
> > > > 
> > > > yoi
> > > 
> > > 
> > > ![Screenshot_2021-05-12-03-56-47-52](https://user-images.githubusercontent.com/81492529/117883984-4d9fdd00-b2d6-11eb-9aaf-e03f03133457.jpg)
> > > Kalo Dari config ga kedetect kah?
> > > Atau scriptku yg salah ?
> > > ${global.DATABASE._data.chats[m.chat].premium ? 'yes' : 'no'}
> > 
> > 
> > Kalau dari config.js bikin aja
> > ```js
> > let premium = global.prems.map(v => v.replace(/[^0-9]/g, '') + '@s.whatsapp.net').includes(m.sender)
> > ${premium ? 'YES':'NO'}
> > ```
> > 
> > 
> >   
> >     
> >     
> > 
> >     
> >     
> > 
> >   
> > 
> > 
> > Atau
> > ```js
> > let handler = async (m, { conn, isPrems }) => {
> > ${isPrems ? 'YES':'NO'}
> > ```
> 
> Oke gan thanks, bisa hehe

bro working...send me the code

**Comment by anshuljai** [comment]
@jauhari21
