### ISSUE TITLE
heroku

### ISSUE THREAD

**Issue by ZefianAlfian** [Nurutomo/wabot-aq#27]
bang ini bisa di deploy ke heroku? soalnya aku liat ada file Procfile, setau ku itu buat heroku

**Comment by Nurutomo** [comment]
Bisa

**Comment by ZefianAlfian** [comment]
> Bisa, jangan lupa install buildpack ffmpeg sama imagemagick

bisa minta link ffmpeg sama imagemagick nya gak bang?

**Comment by ZefianAlfian** [comment]
> Bisa, jangan lupa install buildpack ffmpeg sama imagemagick

plis bang gimanaaaaaaaaaaa:(((

**Comment by ZefianAlfian** [comment]
> Bisa, jangan lupa install buildpack ffmpeg sama imagemagick

udah bisa bang ku close ya

**Comment by ariffb25** [comment]
cara install buildpacknya gmn .-.
