### ISSUE TITLE
Cara ubah otomatis angka limit ke unlimited

### ISSUE THREAD

**Issue by jauhari21** [Nurutomo/wabot-aq#270]
Bisa ga sih ubah angka limit user premium gitu ke unlimited secara otomatis pake script, terus kalo dah habis masa premiumnya limitnya kembali normal lagi. mohon dijawab .

**Comment by Nurutomo** [comment]
itu sistem database

**Comment by JereGanzz** [comment]
> Bisa ga sih ubah angka limit user premium gitu ke unlimited secara otomatis pake script, terus kalo dah habis masa premiumnya limitnya kembali normal lagi. mohon dijawab .

handler.js setting limitnya lalu save,dan kalo udh paylimit nya ke user premium
