### ISSUE TITLE
Sistem poin untuk pemenang di TicTacToe.js

### ISSUE THREAD

**Issue by lilnext01** [Nurutomo/wabot-aq#277]
Sistem Tic Tac Toe luar biasa! Saya punya saran untuk meningkatkan, jika memungkinkan, tambahkan sistem taruhan dengan XP, jadi itu akan jauh lebih menyenangkan! Contoh 1: pemain 1 bertaruh 5000XP Pemain 2 bertaruh 5000XP "Jika pertandingan berakhir dengan Vitória, pemenang menerima 10.000 pengalaman, jika seri, tidak ada yang terjadi. Contoh 2: Permainan akan terlihat seperti itu, tetapi dengan hadiah untuk pemenangnya, Contoh: Pemenang akan mendapatkan XP dalam jumlah tertentu, jika seri tidak terjadi apa-apa. Terima kasih banyak jika Anda dapat menambahkan saran, terima kasih. Selamat ulang tahun!

**Comment by Nurutomo** [comment]
added
