### ISSUE TITLE
Update Antilink

### ISSUE THREAD

**Issue by FadliDarmawan** [Nurutomo/wabot-aq#280]
Jadi, untuk menghindari terbanned nya nomor bot, dan tetap memberikan efek jera ke pengirim link, maka di update lah fitur ini

Jika ada yang ngirim link, maka bot akan autotag ke admin group jika ada yang share link 

Admin yang tertag bisa di atur

Dan, ada pengecualian, bagi yang ada jata kata "izin admin, izin min, ijin admin, ijin min (dll)" maka ga akan di tindaklanjuti

Hal ini di berlakukan agar tidak semua yang ngirim terkick

*autotag di group yang bersangkutan

Sekian

**Comment by jauhari21** [comment]
> Jadi, untuk menghindari terbanned nya nomor bot, dan tetap memberikan efek jera ke pengirim link, maka di update lah fitur ini
> 
> Jika ada yang ngirim link, maka bot akan autotag ke admin group jika ada yang share link
> 
> Admin yang tertag bisa di atur
> 
> Dan, ada pengecualian, bagi yang ada jata kata "izin admin, izin min, ijin admin, ijin min (dll)" maka ga akan di tindaklanjuti
> 
> Hal ini di berlakukan agar tidak semua yang ngirim terkick
> 
> *autotag di group yang bersangkutan
> 
> Sekian

Menarik

**Comment by ariffb25** [comment]
![image](https://user-images.githubusercontent.com/76026450/118395659-bb9d2900-b675-11eb-8cec-c0f231850376.png)
kalo punya w, ngetag owner grup, tinggal tambahin sendiri aja sih :/

```js
conn.reply(m.chat, `*「 Link terdeteksi! 」*\n\nsilahkan kak @${m.chat.split("-")[0]} kalo mau kick :/`, m, { contextInfo: { mentionedJid: [m.chat.split("-")[0] + '@s.whatsapp.net'] } })
```

mungkin bisa tambahin ini
```js
if ( /izin min/.test(m.text) ) throw false
```
selamat mgodonf 🗿👍

**Comment by FadliDarmawan** [comment]
> ![image](https://user-images.githubusercontent.com/76026450/118395659-bb9d2900-b675-11eb-8cec-c0f231850376.png)
> kalo punya w, ngetag owner grup, tinggal tambahin sendiri aja sih :/
> 
> ```js
> conn.reply(m.chat, `*「 Link terdeteksi! 」*\n\nsilahkan kak @${m.chat.split("-")[0]} kalo mau kick :/`, m, { contextInfo: { mentionedJid: [m.chat.split("-")[0] + '@s.whatsapp.net'] } })
> ```
> 
> mungkin bisa tambahin ini
> ```js
> if ( /izin min/.test(m.text) ) throw false
> ```
> selamat mgodonf 🗿👍

Wah, makasih bro

**Comment by FadliDarmawan** [comment]
> ![image](https://user-images.githubusercontent.com/76026450/118395659-bb9d2900-b675-11eb-8cec-c0f231850376.png)
> kalo punya w, ngetag owner grup, tinggal tambahin sendiri aja sih :/
> 
> ```js
> conn.reply(m.chat, `*「 Link terdeteksi! 」*\n\nsilahkan kak @${m.chat.split("-")[0]} kalo mau kick :/`, m, { contextInfo: { mentionedJid: [m.chat.split("-")[0] + '@s.whatsapp.net'] } })
> ```
> 
> mungkin bisa tambahin ini
> ```js
> if ( /izin min/.test(m.text) ) throw false
> ```
> selamat mgodonf 🗿👍

Kalau tag admin case nya gimana?

**Comment by ariffb25** [comment]
mungkin bisa ambil data dari participants
```js
let handler = async (m, { conn, participants }) => { }
```
kan ada participants -nya tuh

atau
  ![image](https://user-images.githubusercontent.com/76026450/118396760-33218700-b67b-11eb-9c62-02b4e465def7.png)
```js
conn.groupMetadata(m.chat)
```
bisa di ambil daftar admin berdasarkan isAdmin

berikut fungsi yang ku buat
```js
// ini fungsinya
const ambilAdminGrup = (participants) => {
        admins = []
        for (let i of participants) {
            i.isAdmin ? admins.push(i.jid) : ''
        }
        return admins
    }

// 
const adminGrup = ambilAdminGrup(participants)
let daftar = adminGrup.map((v, i) => `${i + 1}. @${v.split('@')[0]}`).join('\n')
conn.reply(m.chat, `${daftar}`, m , { contextInfo: { mentionedJid: adminGrup } } )
```

semoga paham & membantu

**Comment by FadliDarmawan** [comment]
> mungkin bisa ambil data dari participants
> 
> ```js
> let handler = async (m, { conn, participants }) => { }
> ```
> 
> kan ada participants -nya tuh
> 
> atau
> ![image](https://user-images.githubusercontent.com/76026450/118396760-33218700-b67b-11eb-9c62-02b4e465def7.png)
> 
> ```js
> conn.groupMetadata(m.chat)
> ```
> 
> bisa di ambil daftar admin berdasarkan isAdmin
> 
> berikut fungsi yang ku buat
> 
> ```js
> // ini fungsinya
> const ambilAdminGrup = (participants) => {
>         admins = []
>         for (let i of participants) {
>             i.isAdmin ? admins.push(i.jid) : ''
>         }
>         return admins
>     }
> 
> // 
> const adminGrup = ambilAdminGrup(participants)
> let daftar = adminGrup.map((v, i) => `${i + 1}. @${v.split('@')[0]}`).join('\n')
> conn.reply(m.chat, `${daftar}`, m , { contextInfo: { mentionedJid: adminGrup } } )
> ```
> 
> semoga paham & membantu

 const ambilAdminGroup sama const adminGroup di taruh di mana?

**Comment by ariffb25** [comment]
didlm handler ? :/

**Comment by FadliDarmawan** [comment]
> didlm handler ? :/

Siap, saya coba dulu

**Comment by Nurutomo** [comment]
```js
const listAdmin = participants.filter(member => member.isAdmin).map(member => member.jid)
```

**Comment by FadliDarmawan** [comment]
> ```js
> const listAdmin = participants.filter(member => member.isAdmin).map(member => member.jid)
> ```

Uhm
