### ISSUE TITLE
Fitur Addmsg.js, getmsg.js, delmsg.js itu cara pakainya gimana pak?, Sama wm.js, itu cara pakainya gimana juga? Udah ku coba beberapa kali gak bisa²

### ISSUE THREAD

**Issue by prioprast** [Nurutomo/wabot-aq#281]
Maksudnya kurang paham dikit

**Comment by FadliDarmawan** [comment]
Addmsg, getmsg, delmsg Itu fitur database, lu bisa nyimpen chat(note), Video, Foto, Sticker. 

WM.js itu buat nyolong sticker orang, terus watermark sticker nya di rubah

Maaf kalau salah

**Comment by prioprast** [comment]
![IMG_20210517_211048](https://user-images.githubusercontent.com/74879576/118502967-63892400-b754-11eb-87e6-74ef942f6825.jpg)
Cara makenya gimana?

**Comment by prioprast** [comment]
![IMG_20210517_211554](https://user-images.githubusercontent.com/74879576/118503729-15285500-b755-11eb-8c25-2c6ee021126b.jpg)
Ini juga salah mulu, cara pakainya gimana?

**Comment by FadliDarmawan** [comment]
> ![IMG_20210517_211554](https://user-images.githubusercontent.com/74879576/118503729-15285500-b755-11eb-8c25-2c6ee021126b.jpg)
> Ini juga salah mulu, cara pakainya gimana?

Kalau WM.js pake gambar setau saya

**Comment by Kokoronationz** [comment]
![Screenshot_2021_0517_232644](https://user-images.githubusercontent.com/78072346/118523494-617c9080-b767-11eb-823f-5cff4722de0c.jpg)

Gini loh cara pakainya

**Comment by prioprast** [comment]
> ![Screenshot_2021_0517_232644](https://user-images.githubusercontent.com/78072346/118523494-617c9080-b767-11eb-823f-5cff4722de0c.jpg)
> 
> Gini loh cara pakainya

Oiya sudah bisa, Terimakasih pak

**Comment by prioprast** [comment]
> > ![IMG_20210517_211554](https://user-images.githubusercontent.com/74879576/118503729-15285500-b755-11eb-8c25-2c6ee021126b.jpg)
> > Ini juga salah mulu, cara pakainya gimana?
> 
> Kalau WM.js pake gambar setau saya

Iya betul, harus direply pesan nya, Terimakasih pak
