### ISSUE TITLE
Tambahin AnonChat

### ISSUE THREAD

**Issue by Hayasak** [Nurutomo/wabot-aq#283]
Tambahin Anonymous Chat Yg Kayak Fi Telegram Bang

**Comment by KazukoGans** [comment]
setuju :v

**Comment by FadliDarmawan** [comment]
> Tambahin Anonymous Chat Yg Kayak Fi Telegram Bang

Wait

**Comment by Nurutomo** [comment]
Udah ;v
tapi masih ada bug

**Comment by Nobuyaki** [comment]
> Udah ;v
> tapi masih ada bug

Bang tambahan hapus sesi sendiri kalo 10 menit ga nemu partner dong
