### ISSUE TITLE
Islamic Feature

### ISSUE THREAD

**Issue by FadliDarmawan** [Nurutomo/wabot-aq#285]
Seperti
#ngaji <surah|ayat>
#randomdoa (ngirim random doa doa sehari hari)
#jadwalsholat <daerah>
#kaligrafi (ngirim kaligrafi arab)
#kisahnabi (ngirim cerita kisahnabi)
#malaikat (ngirim malaikat, berserta tugas nya)
#adzan <sholat>
   Conroh: #adzan subuh (ngirim audio adzan subuh)

Autoadzan (ngirim audio adzan sesuai dengan jam sholat)

Dll.

Fitur ini (semua) bisa di disable oleh owner bot mengingat ada yang nonmulsim

Sekian

[Tergantung apinya sih]

**Comment by Nurutomo** [comment]
aku yang bingung itu ambil api siapa? dan dari mana?

**Comment by FadliDarmawan** [comment]
> aku yang bingung itu ambil api siapa? dan dari mana?

Nah, aku juga 

Pake module🤣, eh ntar ga support termux nye

Kalau yang kek random doa paling bisa pake case buat sendiri+ngisi sendiri

**Comment by Nurutomo** [comment]
Emg butuh module apa?
