### ISSUE TITLE
Minta Tolong Tambahin Clearall Massage dong

### ISSUE THREAD

**Issue by herdygreen** [Nurutomo/wabot-aq#291]
Minta Tolong Tambahin Clearall Massage dong
biar inbox chat di nomor bot ga numpuk

kalau udah ada ini fix ini Case Terbaik

**Comment by Nobuyaki** [comment]
[clear.js](https://github.com/Nurutomo/wabot-aq/blob/master/plugins/clear.js)

**Comment by Nurutomo** [comment]
mirip kek [clear.js](https://github.com/Nurutomo/wabot-aq/blob/master/plugins/clear.js), tapi chats nya gini
```js
let chats = conn.chats.all().map(chat => chat.jid)
```

**Comment by jauhari21** [comment]
> mirip kek [clear.js](https://github.com/Nurutomo/wabot-aq/blob/master/plugins/clear.js), tapi chats nya gini
> 
> ```js
> let chats = conn.chats.all().map(chat => chat.jid)
> ```

![Screenshot_2021-05-21-00-55-34-40](https://user-images.githubusercontent.com/81492529/119026417-59268e80-b9cf-11eb-96ec-acf0c0e9cd79.jpg)
Thanks work!

**Comment by herdygreen** [comment]
Minta tolong Full Code nya dong,,
masih belum bisa

**Comment by jauhari21** [comment]
> Minta tolong Full Code nya dong,,
> masih belum bisa

  let handler = async (m, { conn, command, args }) => {
  let chats = conn.chats.all().map(chat => chat.jid)
  let isDelete = /^(clearall|deleteall)/i.test(command)
  for (let id of chats) {
    if (isDelete) await conn.modifyChat(id, 'delete').catch(console.log)
    await conn.modifyChat(id, 'mute', -Math.floor(new Date / 1e3) * 1e3 - 1e3).catch(console.log)
  }
  conn.reply(m.chat, chats.length + ' chat telah dib' + (isDelete ? 'ersihkan' : 'isukan selamanya'), m)
}
handler.help = ['deleteallchat', 'deleteallchat group', 'muteallchat', 'muteallchat group']
handler.tags = ['owner']
handler.command = /^(clearall|deleteall|muteall)chat$/i
handler.owner = true
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null

module.exports = handler

**Comment by ariffb25** [comment]
https://github.com/Nurutomo/wabot-aq/blob/master/plugins/clear.js dah canggih:v
