### ISSUE TITLE
Add Kurs

### ISSUE THREAD

**Issue by FadliDarmawan** [Nurutomo/wabot-aq#292]
Kurs mata uang berserta grafis nya dalam beberapa bulan terakhir

**Kurs**
Conroh= #kurs Dollar|Rupiah
Nanti print (1 dollar sama dengan 14.XXX rupiah [beserta di kasih grafis nya selama beberapa bulan terakhir])
#kurs mata uang tujuan|mata uang awal

**#konfersi**
Contoh: #konfersi Dollar|14.000|rupiah
#konversi mata uang tujuan|nominal|mata uang awal

Tambahin juga #saham kalau ada
Tambahin juga kripto kalau ada

**Comment by Nurutomo** [comment]
Hmm
