### ISSUE TITLE
help

### ISSUE THREAD

**Issue by amiruldev20** [Nurutomo/wabot-aq#30]
fitur reset bot eror
.debounce

result di termux
pesan: Mereset bot:v                              RESET                                             
                                                  /data/data/com.termux/files/usr/bin/node /storage/           FFFA-111C/bot3/main.js adev            
                                                  undefined:1                                                                                                                                                                                             SyntaxError: Unexpected end of JSON input             at JSON.parse (<anonymous>)                       at Database.load (/storage/FFFA-111C/bot3/lib/database.js:21:61)                                    at new Database (/storage/FFFA-111C/bot3/lib/database.js:7:14)                                      at Object.<anonymous> (/storage/FFFA-111C/bot3/main.js:20:19)                                       at Module._compile (internal/modules/cjs/loader.js:1063:30)                                         at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)                           at Module.load (internal/modules/cjs/loader.js:928:32)                                              at Function.Module._load (internal/modules/cjs/loader.js:769:14)                                    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)                 at internal/main/run_main_module.js:17:47

dan kucek file _adev kosong ga ada apa"nya

**Comment by Nurutomo** [comment]
Database nya ngesave pas bot mati...
jadi Database nya error

**Comment by amiruldev20** [comment]
botnya on um, cuman habis ngerespon "mereset bot :v" itu kucek terminalnya abis ngeload blablabla main.js adev xxx
itu trus eror gitu
kucek _adev kosong

**Comment by amiruldev20** [comment]
aku kan sessionnya 
node . adev
nah pas udh ngereset dan ngeload  adev.data.json
nah file adev_ nya kosong isinya
ga mau ngisi
{
  "users": {},
  "groups": {},
  "chats": {}
}

**Comment by amiruldev20** [comment]
sama gimana cara supaya comand ini bsa
(bot) doang, ini kuketik (bot) ga respon, ketik (bot?) ngerespon

let handler = async (m, { conn, text }) => {
conn.fakeReply(m.chat, `Bot aktif`, '0@s.whatsapp.net', 
`🤖 _*RENZ BOT 2021*_ 🤖`)
}
handler.help = ['bot','renz']

handler.customPrefix = /(\?$)/
handler.owner = false
handler.command = /^(bot|renz|\?)$/i
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null

module.exports = handler

**Comment by Nurutomo** [comment]
tanda ' lupa

**Comment by daenghunter** [comment]
wkwkkww

**Comment by Nurutomo** [comment]
customPrefix = new RegExp
