### ISSUE TITLE
Web nuru /canvas 404

### ISSUE THREAD

**Issue by ShzRGB** [Nurutomo/wabot-aq#300]
Web nuru canvas 404, ini ga seharusnya gini kan?

{"error":"Page you are looking for is not found","hint":"/","status":404}

**Comment by Nurutomo** [comment]
https://nurutomo.herokuapp.com/api/canvas bukan?

**Comment by ShzRGB** [comment]
> https://nurutomo.herokuapp.com/api/canvas bukan?

Ho'oh :v

**Comment by ariffb25** [comment]
kan methodnya post ?
