### ISSUE TITLE
Anti spam

### ISSUE THREAD

**Issue by jauhari21** [Nurutomo/wabot-aq#301]
![Screenshot_2021-05-21-18-22-58-06](https://user-images.githubusercontent.com/81492529/119129910-bf5bf180-ba61-11eb-9a52-4543d702e83d.jpg)
Ada yg tau script anti spam? Meresahkan sekali yg pake auto spam bikin bot ngelag

**Comment by ariffb25** [comment]
```js
if (!chat.isBanned && !users.banned && !m.fromMe && !isOwner && !isPrems) {
        users.spam += 1
        var spam = users.spam
        if (spam >= 3) setTimeout(() => { users.spam = 0 }, 5000)
        if (m.isGroup && !isAdmin && !chat.isBanned && !users.banned && !isOwner && !isPrems && spam == 7) {
          return conn.reply(m.chat, `*「 Over Spam! 」*

Grup & User dibanned! Bot tidak akan merespon dichat ini.

Silahkan ketik *#unban*`, m).then(async () => {
            chat.isBanned = true
            users.banned = true
            // conn.blockUser(m.sender, "add")
            if (isBotAdmin) await conn.groupSettingChange(m.chat, GroupSettingChange.messageSend, true)
            users.spam = 0
          })
        } else if (!m.isGroup && !users.banned && !chat.isBanned && !isOwner && !isPrems && spam == 7) {
          return conn.reply(m.chat, `*「 Over Spam! 」*

Kamu dibanned! Bot tidak akan merespon di chat ini.

Masuk ke-grup & minta ke admin
jika kamu ingin mengunakan bot kembali
https://chat.whatsapp.com/x`, m).then(async () => {
            // conn.blockUser(m.sender, "add")
            users.banned = true
            // users.block = true
            // chat.isBanned = true
            users.spam = 0
          })

        }
        if (spam == 5) return conn.reply(m.chat, `*「 Spam Terdeteksi! 」*\n\nTolong @${m.sender.split('@')[0]} untuk tidak spam (atau bot tidak akan merespon dichat ini), cooldown 5 detik.`, m, {
          contextInfo: {
            mentionedJid: [m.sender]
          }
        })
      }
```

**Comment by jauhari21** [comment]
> ```js
> if (!chat.isBanned && !users.banned && !m.fromMe && !isOwner && !isPrems) {
>         users.spam += 1
>         var spam = users.spam
>         if (spam >= 3) setTimeout(() => { users.spam = 0 }, 5000)
>         if (m.isGroup && !isAdmin && !chat.isBanned && !users.banned && !isOwner && !isPrems && spam == 7) {
>           return conn.reply(m.chat, `*「 Over Spam! 」*
> 
> Grup & User dibanned! Bot tidak akan merespon dichat ini.
> 
> Silahkan ketik *#unban*`, m).then(async () => {
>             chat.isBanned = true
>             users.banned = true
>             // conn.blockUser(m.sender, "add")
>             if (isBotAdmin) await conn.groupSettingChange(m.chat, GroupSettingChange.messageSend, true)
>             users.spam = 0
>           })
>         } else if (!m.isGroup && !users.banned && !chat.isBanned && !isOwner && !isPrems && spam == 7) {
>           return conn.reply(m.chat, `*「 Over Spam! 」*
> 
> Kamu dibanned! Bot tidak akan merespon di chat ini.
> 
> Masuk ke-grup & minta ke admin
> jika kamu ingin mengunakan bot kembali
> https://chat.whatsapp.com/x`, m).then(async () => {
>             // conn.blockUser(m.sender, "add")
>             users.banned = true
>             // users.block = true
>             // chat.isBanned = true
>             users.spam = 0
>           })
> 
>         }
>         if (spam == 5) return conn.reply(m.chat, `*「 Spam Terdeteksi! 」*\n\nTolong @${m.sender.split('@')[0]} untuk tidak spam (atau bot tidak akan merespon dichat ini), cooldown 5 detik.`, m, {
>           contextInfo: {
>             mentionedJid: [m.sender]
>           }
>         })
>       }
> ```

Taruh dimna nih gan? Plugins? Handler?

**Comment by lilnext01** [comment]
...

**Comment by anshuljai** [comment]
is it work?
