### ISSUE TITLE
Ada cara supaya broadcastgroup bisa ada hidetagnya?

### ISSUE THREAD

**Issue by jauhari21** [Nurutomo/wabot-aq#304]
Ada yg tau harus nambahin apa di broadcastgroup?

**Comment by ariffb25** [comment]
1. panggil participants
```js
let handler = async (m, { conn, text, participants, isOwner }) => {
```

2. ambil isinya
```js
let users = participants.map(u => u.jid)
```
3. taroh deh di options
```js
conn.reply(id, `*「 Stikerin Broadcast 」*\n\n${text}`, null, { contextInfo: { mentionedJid: users } })
```

**Comment by FadliDarmawan** [comment]
> 1. panggil participants
> ```js
> let handler = async (m, { conn, text, participants, isOwner }) => {
> ```
> 
> 2. ambil isinya
> ```js
> let users = participants.map(u => u.jid)
> ```
> 3. taroh deh di options
> ```js
> conn.reply(id, `*「 Stikerin Broadcast 」*\n\n${text}`, null, { contextInfo: { mentionedJid: users } })
> ```

Ganti 「Stickerin Broadcast」dengan nama bot anda :v

**Comment by jauhari21** [comment]
> 1. panggil participants
> 
> ```js
> let handler = async (m, { conn, text, participants, isOwner }) => {
> ```
> 
> 1. ambil isinya
> 
> ```js
> let users = participants.map(u => u.jid)
> ```
> 
> 1. taroh deh di options
> 
> ```js
> conn.reply(id, `*「 Stikerin Broadcast 」*\n\n${text}`, null, { contextInfo: { mentionedJid: users } })
> ```

Bentar nomor 3 ditaruh option? Di sebelah mana?

**Comment by ariffb25** [comment]
{ options }
