### ISSUE TITLE
Fix simi bang

### ISSUE THREAD

**Issue by z3r0-d4y-3xplo1t** [Nurutomo/wabot-aq#306]
![Screenshot_2021-05-24-07-26-50-36](https://user-images.githubusercontent.com/68469601/119282983-c5222480-bc65-11eb-898f-c49f38eb7e88.jpg)

**Comment by FadliDarmawan** [comment]
Itu dari api nya kek nya

Ga tau juga sih :v

**Comment by z3r0-d4y-3xplo1t** [comment]
> Itu dari api nya kek nya
> 
> Ga tau juga sih :v

Ok mks
