### ISSUE TITLE
SHARING OFFICIAL GRP!!!!!!

### ISSUE THREAD

**Issue by anshuljai** [Nurutomo/wabot-aq#312]
Nurutumo Official Group

`Spam`=Direct Kick

https://chat.whatsapp.com/F115Oaq76lqCPp19svWnCa

**Comment by FadliDarmawan** [comment]
> Nurutumo Official Group
> 
> `Spam`=Direct Kick
> 
> https://chat.whatsapp.com/F115Oaq76lqCPp19svWnCa

Buset :v
