### ISSUE TITLE
Update menu.js

### ISSUE THREAD

**Issue by FadliDarmawan** [Nurutomo/wabot-aq#313]
Tambahin fitur atau apa aja yang di update di versi itu 

Contoh:

Versi: 2.0.1
Penambahan fitur:
1. Tictactoe
2. Anon chat
3. Update add.js

Tanggal rilis update: 40 Mei 3039
Tanggal update: 41 Mei 3039

Sekian :v

**Comment by Nurutomo** [comment]
Itu changelog :v

**Comment by FadliDarmawan** [comment]
> Itu changelog :v

:v
