### ISSUE TITLE
How do i Add image in menu/help command?

### ISSUE THREAD

**Issue by bilal-08** [Nurutomo/wabot-aq#318]
Hey there im having a little trouble with adding Img to help/menu Command, could you pls tell me or can you describe it here?

**Comment by ShzRGB** [comment]
> Hey there im having a little trouble with adding Img to help/menu Command, could you pls tell me or can you describe it here?

Try Check Here Maybe this is what you need?
https://github.com/Nurutomo/wabot-aq/issues/216#issuecomment-831714999

**Comment by bilal-08** [comment]
Well i cleared upto 2 step and im still confused On 3rd step,
Where do i should put that?

**Comment by ShzRGB** [comment]
> Nah saya menyelesaikan hingga 2 langkah dan saya masih bingung Pada langkah ke-3,
> Di mana saya harus meletakkan itu?

In the Plugins menu Line 150

**Comment by bilal-08** [comment]
![Screenshot (3353)](https://user-images.githubusercontent.com/77657831/119869009-64cd0480-bf3d-11eb-964a-9ca91ac8ecee.png)




![Screenshot (3352)_LI](https://user-images.githubusercontent.com/77657831/119869480-e9b81e00-bf3d-11eb-9e33-51c1e173c23a.jpg)


it's throwing error,the code is good too why this is happening BC of baileys version? if it is then can you show me where to change that version in package.json file

**Comment by bilal-08** [comment]
can you show me code 👀

**Comment by bilal-08** [comment]
![image](https://user-images.githubusercontent.com/77657831/119971050-1ca9f280-bfce-11eb-8bbc-6862e849ba2a.png)
 after adding your code the error is the same ;-;

**Comment by bilal-08** [comment]
After sometime playing around I copied your code and erased  `"jpegThumbnail": fs.readFileSync(./src/Gambar.png)`
and the code worked but The problem is that thumbnail in reply isnt showing well 
This is what i Looking for , thank you for the help🤝

**Comment by bilal-08** [comment]
so Here's the solution and i was able to get result
so you have to make a variable and put the Location of the of the file there like this : 
 let oreki = './src/oreki.jpg'
conn.sendFile(m.chat, motivasi, 'motivasi.png', text.trim(), {
 key: {
 remoteJid: 'status@broadcast',
 participant: '[0@s.whatsapp.net](mailto:0@s.whatsapp.net)',
 fromMe: false
 },
 message: {
 "imageMessage": { "mimetype": "image/jpeg",
 "caption": `${conn.user.name} Verified Bot`,
"jpegThumbnail": fs.readFileSync('./src/Gambar.png')
}
 }
}, m, { contextInfo: { mentionedJid: [m.sender] } })
 } catch (e) {
