### ISSUE TITLE
Buat Leveling

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#323]
leveling yang menggunakan discord-canvas

**Comment by Nurutomo** [comment]
termux gasupport canvas

**Comment by Nobuyaki** [comment]
> termux gasupport canvas

Kalo Canvacord Support Gak Bang di termux?

**Comment by Ftwrr** [comment]
> termux gasupport canvas

gpp,
bisa buatin ga yang pake Canvacord? 🥺
