### ISSUE TITLE
Sticker Command

### ISSUE THREAD

**Issue by arh-space** [Nurutomo/wabot-aq#327]
Mau nanya, cara batasin limit video yang dikirim untuk di jadiin sticker gimana ya? maksud nya kayak maksimal 10 detik lebih dari itu ga di proses, terus apakah sticker video bug? soalnya kalau kirim video ga gerak sama wm nya gamuncul, terima kasih yang mau jawab :)

**Comment by Nurutomo** [comment]
> Mau nanya, cara batasin limit video yang dikirim untuk di jadiin sticker gimana ya? maksud nya kayak maksimal 10 detik lebih dari itu ga di proses, terus apakah sticker video bug? soalnya kalau kirim video ga gerak sama wm nya gamuncul, terima kasih yang mau jawab :)

RESTful api kena suspend

**Comment by Nurutomo** [comment]
> Mau nanya, cara batasin limit video yang dikirim untuk di jadiin sticker gimana ya? maksud nya kayak maksimal 10 detik lebih dari itu ga di proses, terus apakah sticker video bug? soalnya kalau kirim video ga gerak sama wm nya gamuncul, terima kasih yang mau jawab :)

```js
if (m.msg.seconds > 10) throw 'Maksimal 10 detik'
```

**Comment by arh-space** [comment]
> > Mau nanya, cara batasin limit video yang dikirim untuk di jadiin sticker gimana ya? maksud nya kayak maksimal 10 detik lebih dari itu ga di proses, terus apakah sticker video bug? soalnya kalau kirim video ga gerak sama wm nya gamuncul, terima kasih yang mau jawab :)
> 
> ```js
> if (m.msg.seconds > 10) throw 'Maksimal 10 detik'
> ```

taruh di line mana ya ?

**Comment by Afdhan** [comment]
> > Mau nanya, cara batasin limit video yang dikirim untuk di jadiin sticker gimana ya? maksud nya kayak maksimal 10 detik lebih dari itu ga di proses, terus apakah sticker video bug? soalnya kalau kirim video ga gerak sama wm nya gamuncul, terima kasih yang mau jawab :)
> 
> ```js
> if (m.msg.seconds > 10) throw 'Maksimal 10 detik'
> ```

Kalau batesin size atau ukuran file gimana bang? Misalnya bot ngirim file dari api,, tapi file nya terlalu besar, bot cuman ngirim link download... 

Ini biasanya di fitur ytmp4  :(

**Comment by Nurutomo** [comment]
kalo `node-fetch`

let res = await fetch()
if (res.headers.get('content-length') > 30 * 1000 * 1000) throw 'Ukuran file melebihi 30MB'

**Comment by dyono0405** [comment]
if (m.msg.seconds > 10) throw 'Maksimal 10 detik'



Code ini ga work....
Aau bisa kasih tau taruh nya dimana
Sebelum nya terimakasih

**Comment by ariffb25** [comment]
https://github.com/Nurutomo/wabot-aq/commit/4c3b3c6331d7c78e1e10ea283f217938da4a972a
