### ISSUE TITLE
Simi simi untuk grup

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#330]
simi yang langsung merespon ketika ada orang yang mengirimkan pesan di grup

**Comment by KazukoGans** [comment]
> simi yang langsung merespon ketika ada orang yang mengirimkan pesan di grup

Botny bakal spam?

**Comment by Ftwrr** [comment]
> > simi yang langsung merespon ketika ada orang yang mengirimkan pesan di grup
> 
> Botny bakal spam

iyaa gpp

**Comment by ariffb25** [comment]
aku ada, bakal spam jadi ga disarankan sih, gaenak juga kalo rest api nya di spam ._.

**Comment by Ftwrr** [comment]
> gaenak juga kalo rest api nya di spam ._

minta :v

**Comment by ariffb25** [comment]
1. nambah field di chats (gatau bahasanya)
```js
if (!'simi' in chat) chat.simi = false

//dibawahnya juga, sesuaikan aja dengan gambar dibawah

simi: false
```
![image](https://user-images.githubusercontent.com/76026450/120317985-76c9f100-c309-11eb-97ce-68052c5c9477.png)

2. buat file baru difolder plugins, bebas _simi.js
```js
let fetch = require('node-fetch')
let handler = m => m

handler.before = async (m) => {
    let chat = global.DATABASE._data.chats[m.chat]
    if (chat.simi && !chat.isBanned) {
        let res = await fetch(global.API('vinz', '/api/simi', { text: m.text }, 'apikey')) //tinggal sesuaikan dengan rest api yang kamu pake
        let json = await res.json()
        if (json.status == true) {
            if (json.result == 'Aku tidak mengerti apa yang kamu katakan.Tolong ajari aku.') await m.reply('*Simi:* Follow! https://www.instagram.com/stikerinbot/')
            else await m.reply(`*Simi:* ${json.result}`)
        } else return m.reply(`*Simi:* Error!\n\nketik *#off simi*`)
        return !0
    }
    return true
}
module.exports = handler
```

3. atur juga di enable.js
```js
 case 'simi':
      if (!m.isPrems) {
        global.dfail('premium', m, conn)
        throw false
      }
      chat.simi = isEnable
      break
```

selebihnya tinggal kamu sesuaikan, semoga membantu

**Comment by Ftwrr** [comment]
> 1. nambah field di chats (gatau bahasanya)
> 
> ```js
> if (!'simi' in chat) chat.simi = false
> 
> //dibawahnya juga, sesuaikan aja dengan gambar dibawah
> 
> simi: false
> ```
> 
> ![image](https://user-images.githubusercontent.com/76026450/120317985-76c9f100-c309-11eb-97ce-68052c5c9477.png)
> 
> 1. buat file baru difolder plugins, bebas _simi.js
> 
> ```js
> let fetch = require('node-fetch')
> let handler = m => m
> 
> handler.before = async (m) => {
>     let chat = global.DATABASE._data.chats[m.chat]
>     if (chat.simi && !chat.isBanned) {
>         let res = await fetch(global.API('vinz', '/api/simi', { text: m.text }, 'apikey')) //tinggal sesuaikan dengan rest api yang kamu pake
>         let json = await res.json()
>         if (json.status == true) {
>             if (json.result == 'Aku tidak mengerti apa yang kamu katakan.Tolong ajari aku.') await m.reply('*Simi:* Follow! https://www.instagram.com/stikerinbot/')
>             else await m.reply(`*Simi:* ${json.result}`)
>         } else return m.reply(`*Simi:* Error!\n\nketik *#off simi*`)
>         return !0
>     }
>     return true
> }
> module.exports = handler
> ```
> 
> 1. atur juga di enable.js
> 
> ```js
>  case 'simi':
>       if (!m.isPrems) {
>         global.dfail('premium', m, conn)
>         throw false
>       }
>       chat.simi = isEnable
>       break
> ```
> 
> selebihnya tinggal kamu sesuaikan, semoga membantu

makasih😭

**Comment by jauhari21** [comment]
> sama-sama 👊😎

Kalo di private fitur siminya khusus buat di private chat aja munculnya gimana?

**Comment by ariffb25** [comment]
> > sama-sama 👊😎
> 
> Kalo di private fitur siminya khusus buat di private chat aja munculnya gimana?

sama aja bisa grup bisa private, selama user ngetik **.on simi**

**Comment by jauhari21** [comment]
> > > sama-sama 👊😎
> > 
> > 
> > Kalo di private fitur siminya khusus buat di private chat aja munculnya gimana?
> 
> sama aja bisa grup bisa private, selama user ngetik **.on simi**

Pengennya auto on di private doang hehe

**Comment by jauhari21** [comment]
> 1. nambah field di chats (gatau bahasanya)
> 
> ```js
> if (!'simi' in chat) chat.simi = false
> 
> //dibawahnya juga, sesuaikan aja dengan gambar dibawah
> 
> simi: false
> ```
> 
> ![image](https://user-images.githubusercontent.com/76026450/120317985-76c9f100-c309-11eb-97ce-68052c5c9477.png)
> 
> 1. buat file baru difolder plugins, bebas _simi.js
> 
> ```js
> let fetch = require('node-fetch')
> let handler = m => m
> 
> handler.before = async (m) => {
>     let chat = global.DATABASE._data.chats[m.chat]
>     if (chat.simi && !chat.isBanned) {
>         let res = await fetch(global.API('vinz', '/api/simi', { text: m.text }, 'apikey')) //tinggal sesuaikan dengan rest api yang kamu pake
>         let json = await res.json()
>         if (json.status == true) {
>             if (json.result == 'Aku tidak mengerti apa yang kamu katakan.Tolong ajari aku.') await m.reply('*Simi:* Follow! https://www.instagram.com/stikerinbot/')
>             else await m.reply(`*Simi:* ${json.result}`)
>         } else return m.reply(`*Simi:* Error!\n\nketik *#off simi*`)
>         return !0
>     }
>     return true
> }
> module.exports = handler
> ```
> 
> 1. atur juga di enable.js
> 
> ```js
>  case 'simi':
>       if (!m.isPrems) {
>         global.dfail('premium', m, conn)
>         throw false
>       }
>       chat.simi = isEnable
>       break
> ```
> 
> selebihnya tinggal kamu sesuaikan, semoga membantu

https://fdciabdul.tech/api/ayla/?pesan='

Kalo pake api diatas ditambahin apa habis = ?

**Comment by ariffb25** [comment]
> > > > sama-sama 👊😎
> > > 
> > > 
> > > Kalo di private fitur siminya khusus buat di private chat aja munculnya gimana?
> > 
> > 
> > sama aja bisa grup bisa private, selama user ngetik **.on simi**
> 
> Pengennya auto on di private doang hehe

pas di enable.js tambahin validasi nya, supaya hanya bisa di aktifkan di chat pribadi aja

kalo bingung
```js
if (m.isGroup) {
global.dfail('private', m, conn)
throw false
}
```

**Comment by fdciabdul** [comment]
> > 1. nambah field di chats (gatau bahasanya)
> > 
> > ```js
> > if (!'simi' in chat) chat.simi = false
> > 
> > //dibawahnya juga, sesuaikan aja dengan gambar dibawah
> > 
> > simi: false
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/76026450/120317985-76c9f100-c309-11eb-97ce-68052c5c9477.png)
> > 
> > 1. buat file baru difolder plugins, bebas _simi.js
> > 
> > ```js
> > let fetch = require('node-fetch')
> > let handler = m => m
> > 
> > handler.before = async (m) => {
> >     let chat = global.DATABASE._data.chats[m.chat]
> >     if (chat.simi && !chat.isBanned) {
> >         let res = await fetch(global.API('vinz', '/api/simi', { text: m.text }, 'apikey')) //tinggal sesuaikan dengan rest api yang kamu pake
> >         let json = await res.json()
> >         if (json.status == true) {
> >             if (json.result == 'Aku tidak mengerti apa yang kamu katakan.Tolong ajari aku.') await m.reply('*Simi:* Follow! https://www.instagram.com/stikerinbot/')
> >             else await m.reply(`*Simi:* ${json.result}`)
> >         } else return m.reply(`*Simi:* Error!\n\nketik *#off simi*`)
> >         return !0
> >     }
> >     return true
> > }
> > module.exports = handler
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. atur juga di enable.js
> > 
> > ```js
> >  case 'simi':
> >       if (!m.isPrems) {
> >         global.dfail('premium', m, conn)
> >         throw false
> >       }
> >       chat.simi = isEnable
> >       break
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > selebihnya tinggal kamu sesuaikan, semoga membantu
> 
> https://fdciabdul.tech/api/ayla/?pesan='
> 
> Kalo pake api diatas ditambahin apa habis = ?

tinggal tambahin pertanyaan nya doang
