### ISSUE TITLE
Anti troli

### ISSUE THREAD

**Issue by FadliDarmawan** [Nurutomo/wabot-aq#336]
Bikin antitroli selain clearchat tapi juga ngasih kontak yang ngasih bug secara pm ke admin. Biar bisa ketauan siapa yang ngirim...

Hehe..
Sekian

**Comment by ariffb25** [comment]
mungkin tinggal tambahin gini
```js
this.reply('6283128734012@s.whatsapp.net', `Pelaku pengirim bug troli @${m.sender.split`@`[0]}`, null, { contextInfo: { mentionedJid: [m.sender] } })
```

**Comment by FadliDarmawan** [comment]
> mungkin tinggal tambahin gini
> ```js
> this.reply('6283128734012@s.whatsapp.net', `Pelaku pengirim bug troli @${m.sender.split`@`[0]}`, null, { contextInfo: { mentionedJid: [m.sender] } })
> ```

Di tambahin di bagian mana nya?

**Comment by ariffb25** [comment]
bawahnya await this.modifyChat()

**Comment by FadliDarmawan** [comment]
> bawahnya await this.modifyChat() , intinya didalam if

Makasih🙏

**Comment by ariffb25** [comment]
sama-sama

**Comment by FadliDarmawan** [comment]
> mungkin tinggal tambahin gini
> ```js
> this.reply('6283128734012@s.whatsapp.net', `Pelaku pengirim bug troli @${m.sender.split`@`[0]}`, null, { contextInfo: { mentionedJid: [m.sender] } })
> ```

This reply('62XXXXXXXX') itu fake reply?

**Comment by ariffb25** [comment]
bukan, 
```js
conn.fakeReply
```
ini baru fake reply

**Comment by FadliDarmawan** [comment]
> bukan,
> 
> ```js
> conn.fakeReply
> ```
> 
> ini baru fake reply

Lalu itu apa?

**Comment by Nurutomo** [comment]
Klo fakereply pake m.reply bisa kok

```js
m.reply('lapor! dia ngebug troli', '0@s.whasapp.net')
```

**Comment by ariffb25** [comment]
> Klo fakereply pake m.reply bisa kok
> 
> ```js
> m.reply('lapor! dia ngebug troli', '0@s.whasapp.net')
> ```

njir iya, baru liat simple.js :v

**Comment by Nobuyaki** [comment]
> Bikin antitroli selain clearchat tapi juga ngasih kontak yang ngasih bug secara pm ke admin. Biar bisa ketauan siapa yang ngirim...
> 
> Hehe..
> Sekian

troli bug apan sih bang?

**Comment by FadliDarmawan** [comment]
> > Bikin antitroli selain clearchat tapi juga ngasih kontak yang ngasih bug secara pm ke admin. Biar bisa ketauan siapa yang ngirim...
> > 
> > Hehe..
> > Sekian
> 
> troli bug apaan sih bang? 

https://github.com/adiwajshing/Baileys/issues/419 bug troli 99999

**Comment by ariffb25** [comment]
udah bisa blm? jangan lupa close :/

**Comment by FadliDarmawan** [comment]
> udah bisa blm? jangan lupa close :/

Siap, udah cuma ga ada yang ngirim troli
