### ISSUE TITLE
Cara biar batas Max limit 100 misalnya

### ISSUE THREAD

**Issue by jauhari21** [Nurutomo/wabot-aq#337]
Ada yg tau caranya ?

**Comment by HyroKidsSmp** [comment]
let handler = m => m

handler.before = function (m) {
	let users = global.db.data.users[m.sender]
	let maxlimit = 100 //Max Limitnya//
	if (users.limit > maxlimit) 
	users.limit = maxlimit
	return true
	}
module.exports = handler

**Comment by HyroKidsSmp** [comment]
> Ada yg tau caranya ?

Gitu gk?
