### ISSUE TITLE
Heroku: sticker

### ISSUE THREAD

**Issue by ariffb25** [Nurutomo/wabot-aq#34]
![image](https://user-images.githubusercontent.com/76026450/106377313-d69da300-63ce-11eb-945c-609f60809a8f.png)
buildpack yang ku pasang
### sticker
```
2021-01-31T06:25:01.024909+00:00 app[worker.1]: Error: ENOENT: no such file or directory, unlink '/app/tmp/1612074300852.png'
2021-01-31T06:25:01.024917+00:00 app[worker.1]:     at Object.unlinkSync (fs.js:1136:3)
2021-01-31T06:25:01.024918+00:00 app[worker.1]:     at ChildProcess.<anonymous> (/app/plugins/sticker.js:64:18)
2021-01-31T06:25:01.024919+00:00 app[worker.1]:     at ChildProcess.emit (events.js:314:20)
2021-01-31T06:25:01.024919+00:00 app[worker.1]:     at maybeClose (internal/child_process.js:1022:16)
2021-01-31T06:25:01.024919+00:00 app[worker.1]:     at Socket.<anonymous> (internal/child_process.js:444:11)
2021-01-31T06:25:01.024920+00:00 app[worker.1]:     at Socket.emit (events.js:314:20)
2021-01-31T06:25:01.024920+00:00 app[worker.1]:     at Pipe.<anonymous> (net.js:675:12) {
2021-01-31T06:25:01.024921+00:00 app[worker.1]:   errno: -2,
2021-01-31T06:25:01.024921+00:00 app[worker.1]:   syscall: 'unlink',
2021-01-31T06:25:01.024922+00:00 app[worker.1]:   code: 'ENOENT',
2021-01-31T06:25:01.024922+00:00 app[worker.1]:   path: '/app/tmp/1612074300852.png'
2021-01-31T06:25:01.024923+00:00 app[worker.1]: } uncaughtException
```
sedangkan toimg bisa

**Comment by ariffb25** [comment]
![image](https://user-images.githubusercontent.com/76026450/106405384-9854c200-6468-11eb-931c-bad052c9a772.png)

### .toimg
```
2021-02-01T01:33:54.456468+00:00 app[worker.1]: (node:40) UnhandledPromiseRejectionWarning: Error: Could not find MIME for Buffer <null>
2021-02-01T01:33:54.456470+00:00 app[worker.1]:     at Jimp.parseBitmap (/app/node_modules/@jimp/core/dist/utils/image-bitmap.js:187:15)
2021-02-01T01:33:54.456473+00:00 app[worker.1]:     at Jimp.parseBitmap (/app/node_modules/@jimp/core/dist/index.js:431:32)
2021-02-01T01:33:54.456473+00:00 app[worker.1]:     at new Jimp (/app/node_modules/@jimp/core/dist/index.js:384:13)
2021-02-01T01:33:54.456473+00:00 app[worker.1]:     at _construct (/app/node_modules/@babel/runtime/helpers/construct.js:19:21)
2021-02-01T01:33:54.456474+00:00 app[worker.1]:     at /app/node_modules/@jimp/core/dist/index.js:926:32
2021-02-01T01:33:54.456475+00:00 app[worker.1]:     at new Promise (<anonymous>)
2021-02-01T01:33:54.456475+00:00 app[worker.1]:     at Function.Jimp.read (/app/node_modules/@jimp/core/dist/index.js:925:10)
2021-02-01T01:33:54.456476+00:00 app[worker.1]:     at Object.compressImage (/app/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:260:39)
2021-02-01T01:33:54.456476+00:00 app[worker.1]:     at Object.generateThumbnail (/app/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:297:36)
2021-02-01T01:33:54.456479+00:00 app[worker.1]:     at WAConnection.prepareMessageMedia (/app/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:131:23)
2021-02-01T01:33:54.456529+00:00 app[worker.1]: (node:40) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)
```
:'

**Comment by Nurutomo** [comment]
> ![image](https://user-images.githubusercontent.com/76026450/106377313-d69da300-63ce-11eb-945c-609f60809a8f.png)
> buildpack yang ku pasang
> 
> ### sticker
> ```
> 2021-01-31T06:25:01.024909+00:00 app[worker.1]: Error: ENOENT: no such file or directory, unlink '/app/tmp/1612074300852.png'
> 2021-01-31T06:25:01.024917+00:00 app[worker.1]:     at Object.unlinkSync (fs.js:1136:3)
> 2021-01-31T06:25:01.024918+00:00 app[worker.1]:     at ChildProcess.<anonymous> (/app/plugins/sticker.js:64:18)
> 2021-01-31T06:25:01.024919+00:00 app[worker.1]:     at ChildProcess.emit (events.js:314:20)
> 2021-01-31T06:25:01.024919+00:00 app[worker.1]:     at maybeClose (internal/child_process.js:1022:16)
> 2021-01-31T06:25:01.024919+00:00 app[worker.1]:     at Socket.<anonymous> (internal/child_process.js:444:11)
> 2021-01-31T06:25:01.024920+00:00 app[worker.1]:     at Socket.emit (events.js:314:20)
> 2021-01-31T06:25:01.024920+00:00 app[worker.1]:     at Pipe.<anonymous> (net.js:675:12) {
> 2021-01-31T06:25:01.024921+00:00 app[worker.1]:   errno: -2,
> 2021-01-31T06:25:01.024921+00:00 app[worker.1]:   syscall: 'unlink',
> 2021-01-31T06:25:01.024922+00:00 app[worker.1]:   code: 'ENOENT',
> 2021-01-31T06:25:01.024922+00:00 app[worker.1]:   path: '/app/tmp/1612074300852.png'
> 2021-01-31T06:25:01.024923+00:00 app[worker.1]: } uncaughtException
> ```
> 
> sedangkan toimg bisa

Aku pun sama begitu...

**Comment by arl03** [comment]
> ![image](https://user-images.githubusercontent.com/76026450/106377313-d69da300-63ce-11eb-945c-609f60809a8f.png)
> buildpack yang ku pasang
> 
> ### sticker
> ```
> 2021-01-31T06:25:01.024909+00:00 app[worker.1]: Error: ENOENT: no such file or directory, unlink '/app/tmp/1612074300852.png'
> 2021-01-31T06:25:01.024917+00:00 app[worker.1]:     at Object.unlinkSync (fs.js:1136:3)
> 2021-01-31T06:25:01.024918+00:00 app[worker.1]:     at ChildProcess.<anonymous> (/app/plugins/sticker.js:64:18)
> 2021-01-31T06:25:01.024919+00:00 app[worker.1]:     at ChildProcess.emit (events.js:314:20)
> 2021-01-31T06:25:01.024919+00:00 app[worker.1]:     at maybeClose (internal/child_process.js:1022:16)
> 2021-01-31T06:25:01.024919+00:00 app[worker.1]:     at Socket.<anonymous> (internal/child_process.js:444:11)
> 2021-01-31T06:25:01.024920+00:00 app[worker.1]:     at Socket.emit (events.js:314:20)
> 2021-01-31T06:25:01.024920+00:00 app[worker.1]:     at Pipe.<anonymous> (net.js:675:12) {
> 2021-01-31T06:25:01.024921+00:00 app[worker.1]:   errno: -2,
> 2021-01-31T06:25:01.024921+00:00 app[worker.1]:   syscall: 'unlink',
> 2021-01-31T06:25:01.024922+00:00 app[worker.1]:   code: 'ENOENT',
> 2021-01-31T06:25:01.024922+00:00 app[worker.1]:   path: '/app/tmp/1612074300852.png'
> 2021-01-31T06:25:01.024923+00:00 app[worker.1]: } uncaughtException
> ```
> 
> sedangkan toimg bisa

```js

function toSticker(buffer, ext) {
  let tmp = path.join(__dirname, '../tmp' + (new Date * 1) + '.' + ext)
  let out = tmp.replace(new RegExp(ext + '$'), 'webp')
  return new Promise((resolve, reject) => {
  fs.writeFileSync(tmp, buffer)
  spawn('ffmpeg',[
    '-y',
    '-i', tmp,
    `-vcodec`,`libwebp`,
    `-vf`,`scale='min(320,iw)':min'(320,ih)':force_original_aspect_ratio=decrease,fps=15, pad=320:320:-1:-1:color=white@0.0, split [a][b]; [a] palettegen=reserve_transparent=on:transparency_color=ffffff [p]; [b][p] paletteuse`,
    '-f', 'webp',
    out])
    .on('error', reject)
    .on('error', () => fs.unlinkSync(tmp))
    .on('exit',() => {
      resolve(fs.readFileSync(out))
      fs.unlinkSync(tmp)
      if (fs.existsSync(out)) fs.unlinkSync(out)
    })
  })
  
}
```

Coba pake itu

**Comment by ariffb25** [comment]
> > ![image](https://user-images.githubusercontent.com/76026450/106377313-d69da300-63ce-11eb-945c-609f60809a8f.png)
> > buildpack yang ku pasang
> > ### sticker
> > ```
> > 2021-01-31T06:25:01.024909+00:00 app[worker.1]: Error: ENOENT: no such file or directory, unlink '/app/tmp/1612074300852.png'
> > 2021-01-31T06:25:01.024917+00:00 app[worker.1]:     at Object.unlinkSync (fs.js:1136:3)
> > 2021-01-31T06:25:01.024918+00:00 app[worker.1]:     at ChildProcess.<anonymous> (/app/plugins/sticker.js:64:18)
> > 2021-01-31T06:25:01.024919+00:00 app[worker.1]:     at ChildProcess.emit (events.js:314:20)
> > 2021-01-31T06:25:01.024919+00:00 app[worker.1]:     at maybeClose (internal/child_process.js:1022:16)
> > 2021-01-31T06:25:01.024919+00:00 app[worker.1]:     at Socket.<anonymous> (internal/child_process.js:444:11)
> > 2021-01-31T06:25:01.024920+00:00 app[worker.1]:     at Socket.emit (events.js:314:20)
> > 2021-01-31T06:25:01.024920+00:00 app[worker.1]:     at Pipe.<anonymous> (net.js:675:12) {
> > 2021-01-31T06:25:01.024921+00:00 app[worker.1]:   errno: -2,
> > 2021-01-31T06:25:01.024921+00:00 app[worker.1]:   syscall: 'unlink',
> > 2021-01-31T06:25:01.024922+00:00 app[worker.1]:   code: 'ENOENT',
> > 2021-01-31T06:25:01.024922+00:00 app[worker.1]:   path: '/app/tmp/1612074300852.png'
> > 2021-01-31T06:25:01.024923+00:00 app[worker.1]: } uncaughtException
> > ```
> > 
> > 
> > sedangkan toimg bisa
> 
> ```js
> function toSticker(buffer, ext) {
>   let tmp = path.join(__dirname, '../tmp' + (new Date * 1) + '.' + ext)
>   let out = tmp.replace(new RegExp(ext + '$'), 'webp')
>   return new Promise((resolve, reject) => {
>   fs.writeFileSync(tmp, buffer)
>   spawn('ffmpeg',[
>     '-y',
>     '-i', tmp,
>     `-vcodec`,`libwebp`,
>     `-vf`,`scale='min(320,iw)':min'(320,ih)':force_original_aspect_ratio=decrease,fps=15, pad=320:320:-1:-1:color=white@0.0, split [a][b]; [a] palettegen=reserve_transparent=on:transparency_color=ffffff [p]; [b][p] paletteuse`,
>     '-f', 'webp',
>     out])
>     .on('error', reject)
>     .on('error', () => fs.unlinkSync(tmp))
>     .on('exit',() => {
>       resolve(fs.readFileSync(out))
>       fs.unlinkSync(tmp)
>       if (fs.existsSync(out)) fs.unlinkSync(out)
>     })
>   })
>   
> }
> ```
> 
> Coba pake itu

toSticker nya gantiin fungsi sticker2 ya?
![image](https://user-images.githubusercontent.com/76026450/107107195-1d254e80-6862-11eb-8f6f-65755113eae3.png)

**Comment by arl03** [comment]
> > > ![image](https://user-images.githubusercontent.com/76026450/106377313-d69da300-63ce-11eb-945c-609f60809a8f.png)
> > > buildpack yang ku pasang
> > > ### sticker
> > > ```
> > > 2021-01-31T06:25:01.024909+00:00 app[worker.1]: Error: ENOENT: no such file or directory, unlink '/app/tmp/1612074300852.png'
> > > 2021-01-31T06:25:01.024917+00:00 app[worker.1]:     at Object.unlinkSync (fs.js:1136:3)
> > > 2021-01-31T06:25:01.024918+00:00 app[worker.1]:     at ChildProcess.<anonymous> (/app/plugins/sticker.js:64:18)
> > > 2021-01-31T06:25:01.024919+00:00 app[worker.1]:     at ChildProcess.emit (events.js:314:20)
> > > 2021-01-31T06:25:01.024919+00:00 app[worker.1]:     at maybeClose (internal/child_process.js:1022:16)
> > > 2021-01-31T06:25:01.024919+00:00 app[worker.1]:     at Socket.<anonymous> (internal/child_process.js:444:11)
> > > 2021-01-31T06:25:01.024920+00:00 app[worker.1]:     at Socket.emit (events.js:314:20)
> > > 2021-01-31T06:25:01.024920+00:00 app[worker.1]:     at Pipe.<anonymous> (net.js:675:12) {
> > > 2021-01-31T06:25:01.024921+00:00 app[worker.1]:   errno: -2,
> > > 2021-01-31T06:25:01.024921+00:00 app[worker.1]:   syscall: 'unlink',
> > > 2021-01-31T06:25:01.024922+00:00 app[worker.1]:   code: 'ENOENT',
> > > 2021-01-31T06:25:01.024922+00:00 app[worker.1]:   path: '/app/tmp/1612074300852.png'
> > > 2021-01-31T06:25:01.024923+00:00 app[worker.1]: } uncaughtException
> > > ```
> > > 
> > > 
> > > sedangkan toimg bisa
> > 
> > 
> > ```js
> > function toSticker(buffer, ext) {
> >   let tmp = path.join(__dirname, '../tmp' + (new Date * 1) + '.' + ext)
> >   let out = tmp.replace(new RegExp(ext + '$'), 'webp')
> >   return new Promise((resolve, reject) => {
> >   fs.writeFileSync(tmp, buffer)
> >   spawn('ffmpeg',[
> >     '-y',
> >     '-i', tmp,
> >     `-vcodec`,`libwebp`,
> >     `-vf`,`scale='min(320,iw)':min'(320,ih)':force_original_aspect_ratio=decrease,fps=15, pad=320:320:-1:-1:color=white@0.0, split [a][b]; [a] palettegen=reserve_transparent=on:transparency_color=ffffff [p]; [b][p] paletteuse`,
> >     '-f', 'webp',
> >     out])
> >     .on('error', reject)
> >     .on('error', () => fs.unlinkSync(tmp))
> >     .on('exit',() => {
> >       resolve(fs.readFileSync(out))
> >       fs.unlinkSync(tmp)
> >       if (fs.existsSync(out)) fs.unlinkSync(out)
> >     })
> >   })
> >   
> > }
> > ```
> > 
> > 
> > Coba pake itu
> 
> toSticker nya gantiin fungsi sticker2 ya?
> ![image](https://user-images.githubusercontent.com/76026450/107107195-1d254e80-6862-11eb-8f6f-65755113eae3.png)

Iya, ext nya jgn lupa

**Comment by ariffb25** [comment]
@arl03  
![image](https://user-images.githubusercontent.com/76026450/107107458-a4bf8d00-6863-11eb-8887-07646b399a4f.png)
begini udah?

**Comment by ariffb25** [comment]
@arl03 
```
2021-02-06T03:47:16.340024+00:00 app[worker.1]: TypeError: Cannot read property 'id' of undefined
2021-02-06T03:47:16.340025+00:00 app[worker.1]:     at WAConnection.updateMediaMessage (/app/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:279:69)
2021-02-06T03:47:16.340026+00:00 app[worker.1]:     at /app/node_modules/@adiwajshing/baileys/lib/WAConnection/Mutex.js:20:53
2021-02-06T03:47:16.340026+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-02-06T03:47:16.340026+00:00 app[worker.1]:     at async WAConnection.downloadM (/app/lib/simple.js:175:54)
2021-02-06T03:47:16.340027+00:00 app[worker.1]:     at async handler (/app/plugins/sticker.js:14:17)
2021-02-06T03:47:16.340027+00:00 app[worker.1]:     at async WAConnection.conn.handler (/app/main.js:210:11)
```
```
const fetch = require('node-fetch')
const fs = require('fs')
const path = require('path')
const { spawn } = require('child_process')
const FormData = require('form-data')
const { MessageType } = require('@adiwajshing/baileys')

let handler = async (m, { conn, args }) => {
  let stiker = false
  try {
    // const { ext } = await fromBuffer(buffer)
    let q = m.quoted ? { message: { [m.quoted.mtype]: m.quoted } } : m
    if (/image/.test((m.quoted ? m.quoted : m.msg).mimetype || '')) {
      let img = await conn.downloadM(q)
      if (!img) throw img
      stiker = await toSticker(img, ext)
    } else if (args[0]) stiker = await toSticker(false, args[0])
  } finally {
    if (stiker) conn.sendMessage(m.chat, stiker, MessageType.sticker, {
      quoted: m
    })
  }
}
handler.help = ['stiker (caption|reply media)', 'stiker <url>']
handler.tags = ['sticker']
handler.command = /^stic?ker$/i
handler.owner = false
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false
// handler.heroku = true

handler.admin = false
handler.botAdmin = false

handler.fail = null

module.exports = handler

// let tmp = path.join(__dirname, '../app/tmp')
// function sticker2(img, url) {
//   return new Promise(async (resolve, reject) => {
//     try {
//       if (url) {
//         let res = await fetch(url)
//         img = await res.buffer()
//       }
//       let inp = path.join(tmp, +new Date + '.jpeg')
//       let png = path.join(tmp, +new Date + '.png')
//       let out = path.join(tmp, +new Date + '.webp')
//       fs.writeFileSync(inp, img)
//       spawn('ffmpeg', [
//         '-y',
//         '-i', inp,
//         '-vf', 'scale=512:512:flags=lanczos:force_original_aspect_ratio=decrease,format=rgba,pad=512:512:(ow-iw)/2:(oh-ih)/2:color=#00000000,setsar=1',
//         png
//       ])
//         .on('error', reject)
//         .on('close', () => {
//           fs.unlinkSync(inp)
//           spawn('convert', [png, out])
//             .on('error', reject)
//             .on('close', () => {
//               fs.unlinkSync(png)
//               resolve(fs.readFileSync(out))
//               fs.unlinkSync(out)
//             })
//         })
//     } catch (e) {
//       reject(e)
//     }
//   })
// }

async function canvas(code, type = 'png', quality = 0.92) {
  let res = await fetch('https://nurutomo.herokuapp.com/api/canvas?' + queryURL({
    type,
    quality
  }), {
    method: 'POST',
    headers: {
      'Content-Type': 'text/plain',
      'Content-Length': code.length
    },
    body: code
  })
  let image = await res.buffer()
  return image
}

function queryURL(queries) {
  return Object.entries(queries).map(([key, value]) => key + (value ? '=' + encodeURIComponent(value) : '')).join('&')
}

let { fromBuffer } = require('file-type')
async function sticker(img, url) {
  url = url ? url : await uploadImage(img)
  let {
    mime
  } = url ? { mime: 'image/jpeg' } : await fromBuffer(img)
  let sc = `let im = await loadImg('data:${mime};base64,'+(await window.loadToDataURI('${url}')))
c.width = c.height = 512
let max = Math.max(im.width, im.height)
let w = 512 * im.width / max
let h = 512 * im.height / max
ctx.drawImage(im, 256 - w / 2, 256 - h / 2, w, h)
`
  return await canvas(sc, 'webp')
}

function uploadImage(buffer) {
  return new Promise(async (resolve, reject) => {
    try {
      const {
        ext
      } = await fromBuffer(buffer)
      let form = new FormData()
      form.append('file', buffer, 'tmp.' + ext)
      let res = await fetch('https://telegra.ph/upload', {
        method: 'POST',
        body: form
      })
      let img = await res.json()
      if (img.error) reject(img.error)
      else resolve('https://telegra.ph' + img[0].src)
    } catch (e) {
      reject(e)
    }
  })
}

function toSticker(buffer, ext) {
  let tmp = path.join(__dirname, '../tmp' + (new Date * 1) + '.' + ext)
  let out = tmp.replace(new RegExp(ext + '$'), 'webp')
  return new Promise((resolve, reject) => {
    fs.writeFileSync(tmp, buffer)
    spawn('ffmpeg', [
      '-y',
      '-i', tmp,
      `-vcodec`, `libwebp`,
      `-vf`, `scale='min(320,iw)':min'(320,ih)':force_original_aspect_ratio=decrease,fps=15, pad=320:320:-1:-1:color=white@0.0, split [a][b]; [a] palettegen=reserve_transparent=on:transparency_color=ffffff [p]; [b][p] paletteuse`,
      '-f', 'webp',
      out])
      .on('error', reject)
      .on('error', () => fs.unlinkSync(tmp))
      .on('exit', () => {
        resolve(fs.readFileSync(out))
        fs.unlinkSync(tmp)
        if (fs.existsSync(out)) fs.unlinkSync(out)
      })
  })

}
```

**Comment by ariffb25** [comment]
### silahkan copy
```
const fetch = require('node-fetch')
const fs = require('fs')
const path = require('path')
const { spawn } = require('child_process')
const FormData = require('form-data')
const { MessageType } = require('@adiwajshing/baileys')

let handler = async (m, { conn, args }) => {
  let stiker = false
  try {
    let q = m.quoted ? { message: { [m.quoted.mtype]: m.quoted } } : m
    if (/image/.test((m.quoted ? m.quoted : m.msg).mimetype || '')) {
      let img = await conn.downloadM(q)
      if (!img) throw img
      stiker = await toSticker(img)
    } else if (args[0]) stiker = await toSticker(false, args[0])
  } finally {
    if (stiker) conn.sendMessage(m.chat, stiker, MessageType.sticker, {
      quoted: m
    })
  }
}
handler.help = ['stiker (caption|reply media)', 'stiker <url>']
handler.tags = ['sticker']
handler.command = /^(st|stic?ker)$/i
handler.owner = false
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null
handler.limit = true

module.exports = handler

async function canvas(code, type = 'png', quality = 0.92) {
  let res = await fetch('https://nurutomo.herokuapp.com/api/canvas?' + queryURL({
    type,
    quality
  }), {
    method: 'POST',
    headers: {
      'Content-Type': 'text/plain',
      'Content-Length': code.length
    },
    body: code
  })
  let image = await res.buffer()
  return image
}

function queryURL(queries) {
  return Object.entries(queries).map(([key, value]) => key + (value ? '=' + encodeURIComponent(value) : '')).join('&')
}

let { fromBuffer } = require('file-type')
async function sticker(img, url) {
  url = url ? url : await uploadImage(img)
  let {
    mime
  } = url ? { mime: 'image/jpeg' } : await fromBuffer(img)
  let sc = `let im = await loadImg('data:${mime};base64,'+(await window.loadToDataURI('${url}')))
c.width = c.height = 512
let max = Math.max(im.width, im.height)
let w = 512 * im.width / max
let h = 512 * im.height / max
ctx.drawImage(im, 256 - w / 2, 256 - h / 2, w, h)
`
  return await canvas(sc, 'webp')
}

function uploadImage(buffer) {
  return new Promise(async (resolve, reject) => {
    try {
      const {
        ext
      } = await fromBuffer(buffer)
      let form = new FormData()
      form.append('file', buffer, 'tmp.' + ext)
      let res = await fetch('https://telegra.ph/upload', {
        method: 'POST',
        body: form
      })
      let img = await res.json()
      if (img.error) reject(img.error)
      else resolve('https://telegra.ph' + img[0].src)
    } catch (e) {
      reject(e)
    }
  })
}

function toSticker(buffer, ext) {
  let tmp = path.join(__dirname, '../tmp' + (new Date * 1) + '.' + ext)
  let out = tmp.replace(new RegExp(ext + '$'), 'webp')
  return new Promise((resolve, reject) => {
    fs.writeFileSync(tmp, buffer)
    spawn('ffmpeg', [
      '-y',
      '-i', tmp,
      `-vcodec`, `libwebp`,
      `-vf`, `scale='min(320,iw)':min'(320,ih)':force_original_aspect_ratio=decrease,fps=15, pad=320:320:-1:-1:color=white@0.0, split [a][b]; [a] palettegen=reserve_transparent=on:transparency_color=ffffff [p]; [b][p] paletteuse`,
      '-f', 'webp',
      out])
      .on('error', reject)
      .on('error', () => fs.unlinkSync(tmp))
      .on('exit', () => {
        resolve(fs.readFileSync(out))
        fs.unlinkSync(tmp)
        if (fs.existsSync(out)) fs.unlinkSync(out)
      })
  })

}
```
