### ISSUE TITLE
what command I use to answer math game?

### ISSUE THREAD

**Issue by Kyweev** [Nurutomo/wabot-aq#341]
hi, sorry for this issue if it bothers you
but i wanna know how to answer the math game

**Comment by prioprast** [comment]
> hai, maaf untuk masalah ini jika mengganggu Anda,
> tetapi saya ingin tahu bagaimana menjawab permainan matematika

you can adjust according to the mode from the easiest to the most difficult

for example: #math noob
or #math extreme
