### ISSUE TITLE
Tagall

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#343]
tagall?

**Comment by Afdhan** [comment]
Kan gk susah bikin tagall, sama aja kya hidetag :/

**Comment by Ftwrr** [comment]
> Kan gk susah bikin tagall, sama aja kya hidetag :/

gw maunya tagall bukan hidetag:)

**Comment by Afdhan** [comment]
> > Kan gk susah bikin tagall, sama aja kya hidetag :/
> 
> gw maunya tagall bukan hidetag:)

Buat ngambil participant di grup tiru aja kya di hidetag, 
```js
let users = participant.map(u => u.jid)
let pepek = "TAGALL\n"
for (let user of users) {
    pepek += `@${user.split("@")[0]}\n`
}
conn.reply(m.chat, pepek, m, { contextInfo: { mentionedJid: users }})
```
