### ISSUE TITLE
buat antidelete status

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#351]
daripada console log `INFO [2021-06-03 11:50:45.977 +0000] (2780): deleting message: 7703803B3DB1CAE5FB15F15C8AB50A7A in chat: status@broadcast` nya ga guna mending dibikin antidelete  status@broadcast
kalo misalkan ada orang yang ngehapus status itu langsung dikirim ke nomor kita

**Comment by Nurutomo** [comment]
pdhl antidelete nya detek status :|

tinggal diaktifin

**Comment by Ftwrr** [comment]
> pdhl antidelete nya detek status :|
> 
> tinggal diaktifin

bentar gw coba, tapi kalo ga bisa, bantuin gw yahh :(

**Comment by Ftwrr** [comment]
> > pdhl antidelete nya detek status :|
> > tinggal diaktifin
> 
> bentar gw coba, tapi kalo ga bisa, bantuin gw yahh :(

gatau jirr bingung banget
