### ISSUE TITLE
node-wrbpmux

### ISSUE THREAD

**Issue by jauhari21** [Nurutomo/wabot-aq#353]
![Screenshot_2021-06-04-03-34-12-23](https://user-images.githubusercontent.com/81492529/120708738-28257e00-c4e6-11eb-9626-7a3ebc7dd8d8.jpg)
Pas update malah gini, ada yg tahu?

**Comment by Nurutomo** [comment]
`npm i node-webpmux`

kalo mau aktifin fiturnya, nggk aku list di `package.json` sebab kasian yang nodejs dibawah v14 (kek v11,12) gabisa

**Comment by jauhari21** [comment]
> `npm i node-webpmux`
> 
> kalo mau aktifin fiturnya, nggk aku list di `package.json` sebab kasian yang nodejs dibawah v14 (kek v11,12) gabisa

Oh harus nodejs v14, pantesan aja ga bisa , gua pake nodejs12 oke" thanks info
