### ISSUE TITLE
Cara mengirimkan pdf melalui link gimana?

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#355]
¯\_(ツ)_/¯

**Comment by ariffb25** [comment]
contoh
```js
> const { MessageType, Mimetype } = require('@adiwajshing/baileys')
conn.sendMessage(m.chat, { url: 'https://core.ac.uk/download/327165680.pdf'}, MessageType.document, { mimetype: Mimetype.pdf, filename: `ini.pdf` })
```
kalo pake sendFile? hmm coba aja sendiri

**Comment by Ftwrr** [comment]
> contoh
> 
> ```js
> > const { MessageType, Mimetype } = require('@adiwajshing/baileys')
> conn.sendMessage(m.chat, { url: 'https://core.ac.uk/download/327165680.pdf'}, MessageType.document, { mimetype: Mimetype.pdf, filename: `ini.pdf` })
> ```
> 
> kalo pake sendFile? hmm coba aja sendiri

`if (json.result.pdf_file) conn.sendMessage(m.chat, json.result.pdf_file, MessageType.document, { mimetype: Mimetype.pdf, filename: `nhentai.pdf` })`

BaileysError: Unexpected status in 'action': Bad Request(400)


gimana bang :(

**Comment by ariffb25** [comment]
```js
conn.sendMessage(m.chat, {url:json.result.pdf_file}, MessageType.document, { mimetype: Mimetype.pdf, filename: `nhentai.pdf` })
```
