### ISSUE TITLE
sticker conversion failed

### ISSUE THREAD

**Issue by Rianfirnanda** [Nurutomo/wabot-aq#357]
![Screenshot (191)](https://user-images.githubusercontent.com/69239761/120740066-aef54d80-c51c-11eb-8714-bbc29b0e86cd.png)

**Comment by anshuljai** [comment]
when it fails  use prefixs

ex.:- #s

**Comment by FadliDarmawan** [comment]
> ![Screenshot (191)](https://user-images.githubusercontent.com/69239761/120740066-aef54d80-c51c-11eb-8714-bbc29b0e86cd.png)
> 

Reply the image

Url nya belom kebaca jadinya ga bisa
-nurutomo

**Comment by Nurutomo** [comment]
jadi direply aja img nya
