### ISSUE TITLE
Cant Read Property .... Undefined

### ISSUE THREAD

**Issue by AnymPedia** [Nurutomo/wabot-aq#358]
![image](https://user-images.githubusercontent.com/68510045/120792739-2a2c2300-c560-11eb-916f-102376bf7fe3.png)
![image](https://user-images.githubusercontent.com/68510045/120792774-3617e500-c560-11eb-80ed-9db53475b0f9.png)
Ada yang tau bagaimana?

**Comment by anshuljai** [comment]
just restart your bot :v.....it happens to me too....just restart and fine

**Comment by Nurutomo** [comment]
> just restart your bot :v.....it happens to me too....just restart and fine

yeah
