### ISSUE TITLE
custom vn tidak bisa kekirim, di pribadi bisa tetapi di wa target tidak ada

### ISSUE THREAD

**Issue by novusjendral** [Nurutomo/wabot-aq#360]
let handler = async (m, { conn }) => {
let vn ='src/suaracewek/IyaSayang.ogg'
conn.sendFile(m.chat, vn,'iyasayang.ogg',null,m,true, {
 type: 'audioMessage', //paksa tanpa convert
 ptt: true // true diatas ga work sebab dipaksain tanpa convert
})
}
handler.customPrefix = /^(tes)$/i
handler.command = new RegExp
handler.owner = false
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null
handler.exp = 100

module.exports = handler

**Comment by Ftwrr** [comment]
tambahin titik

`let vn ='.src/suaracewek/IyaSayang.ogg'`

kalau masih ga bisa, convert jadi mp3 dulu

**Comment by novusjendral** [comment]
solved ternyata hrus convert ke mp3
