### ISSUE TITLE
Tambahkan "jika" di AntiSpam, sehingga bot tidak menghukum dirinya sendiri terhadap spam. silahkan terima kasih.

### ISSUE THREAD

**Issue by lilnext01** [Nurutomo/wabot-aq#362]
![20210604_171428](https://user-images.githubusercontent.com/74841546/120857979-7ecba000-c558-11eb-9b6a-6c5bf14c5147.jpg)
Dia menghukum dirinya sendiri. Saya menambahkan fitur tambahan di AntiSpam, untuk menghapus pengguna dari grup, jika dia melakukan spam, namun, ketika saya melakukan perintah "Siarkan" Bot otomatis menghukum dirinya sendiri, dan meninggalkan beberapa grup, terima kasih jika saya dapat membantu.

**Comment by Nurutomo** [comment]
if (m.fromMe) return !0

**Comment by Afdhan** [comment]
```js
if (m.fromMe || m.isBaileys) return !0
```
:v
