### ISSUE TITLE
Cara fix nya gmn tolong- D:

### ISSUE THREAD

**Issue by Andika856** [Nurutomo/wabot-aq#363]
![Screenshot_2021-06-05-11-39-01-65](https://user-images.githubusercontent.com/78887981/120880162-bab34380-c5f2-11eb-82a1-a0e696d186d2.jpg)
Disconnect dan reconnect mulu padahal sinyal bagus

**Comment by Andika856** [comment]
![Screenshot_2021-06-05-11-41-11-98](https://user-images.githubusercontent.com/78887981/120880199-f9e19480-c5f2-11eb-8477-0fb79c4f1fce.jpg)
Mungkin bisa membantu apa error' nya

**Comment by ShzRGB** [comment]
Apk WhatsApp nya ngclose itu kayaknya gamau connect

**Comment by Kokoronationz** [comment]
> ![Screenshot_2021-06-05-11-41-11-98](https://user-images.githubusercontent.com/78887981/120880199-f9e19480-c5f2-11eb-8477-0fb79c4f1fce.jpg)
> Mungkin bisa membantu apa error' nya

npm i node-webpmux

**Comment by Nurutomo** [comment]
> > ![Screenshot_2021-06-05-11-41-11-98](https://user-images.githubusercontent.com/78887981/120880199-f9e19480-c5f2-11eb-8477-0fb79c4f1fce.jpg)
> > Mungkin bisa membantu apa error' nya
> 
> npm i node-webpmux

nggk aku tambahin ke package.json sebab itu fitur opsional, nggk terlalu penting

jadi bisa pake `$ npm i node-webpmux`

**Comment by Nurutomo** [comment]
> ![Screenshot_2021-06-05-11-39-01-65](https://user-images.githubusercontent.com/78887981/120880162-bab34380-c5f2-11eb-82a1-a0e696d186d2.jpg)
> Disconnect dan reconnect mulu padahal sinyal bagus

aku juga sering gitu, kadang normal lagi

**Comment by jauhari21** [comment]
> ![Screenshot_2021-06-05-11-39-01-65](https://user-images.githubusercontent.com/78887981/120880162-bab34380-c5f2-11eb-82a1-a0e696d186d2.jpg)
> Disconnect dan reconnect mulu padahal sinyal bagus

Gua aja masih pake webp hehe, pake node webpmux suka eror malez

**Comment by FadliDarmawan** [comment]
> ![Screenshot_2021-06-05-11-41-11-98](https://user-images.githubusercontent.com/78887981/120880199-f9e19480-c5f2-11eb-8477-0fb79c4f1fce.jpg)
> Mungkin bisa membantu apa error' nya

Woakwoka handker

**Comment by jauhari21** [comment]
> > ![Screenshot_2021-06-05-11-41-11-98](https://user-images.githubusercontent.com/78887981/120880199-f9e19480-c5f2-11eb-8477-0fb79c4f1fce.jpg)
> > Mungkin bisa membantu apa error' nya
> 
> Woakwoka handker

Typo, udah di fix
