### ISSUE TITLE
[ERROR] Leaderboard 

### ISSUE THREAD

**Issue by lilnext01** [Nurutomo/wabot-aq#366]
![20210605_171128](https://user-images.githubusercontent.com/74841546/120904195-5196f480-c621-11eb-9935-0fa061ab4829.jpg)

**Comment by Nurutomo** [comment]
Why is it called ranking.js? Did you modify or just rename?

**Comment by lilnext01** [comment]
> Why is it called ranking.js? Did you modify or just rename?

It's just renamed
