### ISSUE TITLE
similarity

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#367]
terapin similarity ke dalam tebak gambar seperti yang ada di family 100

**Comment by Kokoronationz** [comment]
> terapin similarity ke dalam tebak gambar seperti yang ada di family 100

Tebakgambar itu mudah

Ada hint nya pula, similarity ga perlu

**Comment by Nurutomo** [comment]
> > terapin similarity ke dalam tebak gambar seperti yang ada di family 100
> 
> Tebakgambar itu mudah
> 
> Ada hint nya pula, similarity ga perlu

2in
