### ISSUE TITLE
Fitur sim simi eror

### ISSUE THREAD

**Issue by elssword** [Nurutomo/wabot-aq#37]
Bang pas pake fitur simsimi apikeynya invalid gimana cara betulin nya

**Comment by ariffb25** [comment]
soalnya ilegal jadi mati
https://tobz-api.herokuapp.com/api , ada di Other API

**Comment by Urbaee** [comment]
> Bang pas pake fitur simsimi apikeynya invalid gimana cara betulin nya

https://github.com/Urbaee/whatsapp-bot2

**Comment by Nurutomo** [comment]
Itu apikey simi nya habis
