### ISSUE TITLE
thumbnail

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#370]
caranya ngirim foto tapi kaya ada thumbnail nya gitu
awalnya gitu tapi ngeblur abis di download gambarnya jadi gambar lain
yaaa gitu lah lu tau kan apa yang gw maksud

**Comment by Afdhan** [comment]
**Login**

Ini pertanyaan gw di grup tadi:)

**Comment by Kokoronationz** [comment]
> caranya ngirim foto tapi kaya ada thumbnail nya gitu
> awalnya gitu tapi ngeblur abis di download gambarnya jadi gambar lain
> yaaa gitu lah lu tau kan apa yang gw maksud

Kurang lebih kek gini

```
conn.sendFile(m.chat, image, 'image.jpg', 'caption', m, { thumbnail: fs.readFileSync('./src/photo.jpg')}
```

**Comment by Ftwrr** [comment]
> > caranya ngirim foto tapi kaya ada thumbnail nya gitu
> > awalnya gitu tapi ngeblur abis di download gambarnya jadi gambar lain
> > yaaa gitu lah lu tau kan apa yang gw maksud
> 
> Kurang lebih kek gini
> 
> ```
> conn.sendFile(m.chat, image, 'image.jpg', 'caption', m, { thumbnail: fs.readFileSync('./src/photo.jpg')}
> ```

makasih, tapi ga work

**Comment by anshuljai** [comment]
> > > caranya ngirim foto tapi kaya ada thumbnail nya gitu
> > > awalnya gitu tapi ngeblur abis di download gambarnya jadi gambar lain
> > > yaaa gitu lah lu tau kan apa yang gw maksud
> > 
> > 
> > Kurang lebih kek gini
> > ```
> > conn.sendFile(m.chat, image, 'image.jpg', 'caption', m, { thumbnail: fs.readFileSync('./src/photo.jpg')}
> > ```
> 
> makasih, tapi ga work

conn.sendFile(m.chat,img,'','*© pppp*',m,false,{ thumbnail : fs.readFileSync('./src/avatar_contact.png')} )

**Comment by Ftwrr** [comment]
> > > > caranya ngirim foto tapi kaya ada thumbnail nya gitu
> > > > awalnya gitu tapi ngeblur abis di download gambarnya jadi gambar lain
> > > > yaaa gitu lah lu tau kan apa yang gw maksud
> > > 
> > > 
> > > Kurang lebih kek gini
> > > ```
> > > conn.sendFile(m.chat, image, 'image.jpg', 'caption', m, { thumbnail: fs.readFileSync('./src/photo.jpg')}
> > > ```
> > 
> > 
> > makasih, tapi ga work
> > first declare
> > let fs = require('fs')
> 
> then
> 
> conn.sendFile(m.chat,img,'','_© pppp_',m,false,{ thumbnail : fs.readFileSync('./src/avatar_contact.png')} )

thengs
