### ISSUE TITLE
[Feature] A twitter twit downloader

### ISSUE THREAD

**Issue by Mayonnaise53** [Nurutomo/wabot-aq#371]
when someone Twit something Then bot will upload whole Twitter Post with caption To where the Twitter feature is enabled and  same goes for Status automatical status broadcast from Twitts 

features 2nd : meme generator using dank memer api or other apis

feature 3rd : add Urban dictionary

**Comment by Nurutomo** [comment]
can you help me for the api link?

**Comment by Nurutomo** [comment]
- [ ] Twitter API?? you need twitter apikey :\
- [x] Meme
- [ ] Urban Dictionary

**Comment by bilal-08** [comment]
> * [ ]  Twitter API?? you need twitter apikey :\
> * [x]  Meme
> * [ ]  Urban Dictionary

https://towardsdatascience.com/downloading-data-from-twitter-using-the-rest-api-24becf413875?gi=fa20fe50db09
a article on Twitter api
(Twitter official api is paid:( )
and
https://rapidapi.com/community/api/urban-dictionary

urban dictionary api


will this work?

**Comment by Nurutomo** [comment]
> > * [ ]   Twitter API?? you need twitter apikey :\
> > * [x]   Meme
> > * [ ]   Urban Dictionary
> 
> https://towardsdatascience.com/downloading-data-from-twitter-using-the-rest-api-24becf413875?gi=fa20fe50db09
> a article on Twitter api
> (Twitter official api is paid:( )
> and
> https://rapidapi.com/community/api/urban-dictionary
> 
> urban dictionary api
> 
> will this work?

can you show me an example how to create the request? like https://rest.api/v2/something?query=first&second=third
