### ISSUE TITLE
[ASK] How to make separate Command 

### ISSUE THREAD

**Issue by bilal-08** [Nurutomo/wabot-aq#372]
How do i make separate Exp,date, islamic date and time command For seeing stats?

And just a request How About starting a place for discussion?

**Comment by ariffb25** [comment]
1. create a new file in the plugins folder, for the name it's up to you, here I give the name exp.js
```js
let handler = async (m) => {
    let who
    if (m.isGroup) who = m.mentionedJid[0] ? m.mentionedJid[0] : m.sender
    else who = m.sender
    m.reply(`${global.DATABASE.data.users[who].exp} EXP`)
}
handler.help = ['exp [@user]']
handler.tags = ['xp']
handler.command = /^(e?xp)$/i
module.exports = handler
```

the rest u can make it yourself ._.
