### ISSUE TITLE
[Fix needed] Kicked out by other antilink bot 🙂

### ISSUE THREAD

**Issue by Mayonnaise53** [Nurutomo/wabot-aq#373]
Kicked out by another bot :/
I want to ask if you add A command that sends Msgs to DM directly or you show me here :)

**Comment by FadliDarmawan** [comment]
> Kicked out by another bot :/
> I want to ask if you add A command that sends Msgs to DM directly or you show me here :)

Act the bot number into an admin

**Comment by Nurutomo** [comment]
> Kicked out by another bot :/
> I want to ask if you add A command that sends Msgs to DM directly or you show me here :)
```js
m.reply('your message', m.sender) // it will dm the sender
```

**Comment by Mayonnaise53** [comment]
Yosh got it thanks

**Comment by Mayonnaise53** [comment]
> > Kicked out by another bot :/
> > I want to ask if you add A command that sends Msgs to DM directly or you show me here :)
> 
> Act the bot number into an admin

Well it's work in some cases but not all admins wants to make bot admin

**Comment by FadliDarmawan** [comment]
> > > Kicked out by another bot :/
> > > I want to ask if you add A command that sends Msgs to DM directly or you show me here :)
> > 
> > Act the bot number into an admin
> 
> Well it's work in some cases but not all admins wants to make bot admin

:v
