### ISSUE TITLE
telegra.ph alternative

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#376]
telegra.ph anjing stress babi
failed, reason: connect ETIMEDOUT

tambahin media upload lainnya selain telegra.ph

**Comment by FadliDarmawan** [comment]
> telegra.ph anjing stress babi
> failed, reason: connect ETIMEDOUT
> 
> tambahin media upload lainnya selain telegra.ph

:v

**Comment by Afdhan** [comment]
> telegra.ph anjing stress babi
> failed, reason: connect ETIMEDOUT
> 
> tambahin media upload lainnya selain telegra.ph

Pakailah imgbb buat cadangan :)

**Comment by Nurutomo** [comment]
> > telegra.ph anjing stress babi
> > failed, reason: connect ETIMEDOUT
> > tambahin media upload lainnya selain telegra.ph
> 
> Pakailah imgbb buat cadangan :)

free?

**Comment by ariffb25** [comment]
free
