### ISSUE TITLE
ERROR: maker was not found

### ISSUE THREAD

**Issue by FadliDarmawan** [Nurutomo/wabot-aq#378]
Error yang kayaknya semua temuin di fitur yang pake upload gambar
_the error was founded at the feature who upload the image_

Contoh: #wallpaperanime, bukannya upload gambar malah error maker was not found
_example: #wallpaperanime, the feature should uploade some image but in this case the feature make an error maker was not found_

Sorry for my bad english

**Comment by anshuljai** [comment]
it doesnt upload image....it send image to whatsapp through api......and you can add fake thumbnail to remove this error

**Comment by Nurutomo** [comment]
add this option when sending image/video, it will hide your thumbnail..but it still works
```js
{
 thumbnail: Buffer.alloc(0)
}
 ```

**Comment by FadliDarmawan** [comment]
> add this option when sending image/video, it will hide your thumbnail..but it still works
> 
> ```js
> {
>  thumbnail: Buffer.alloc(0)
> }
> ```

Where?

**Comment by Nurutomo** [comment]
> > add this option when sending image/video, it will hide your thumbnail..but it still works
> > ```js
> > {
> >  thumbnail: Buffer.alloc(0)
> > }
> > ```
> 
> Where?

options
