### ISSUE TITLE
Set Welcome

### ISSUE THREAD

**Issue by ariffb25** [Nurutomo/wabot-aq#38]
![image](https://user-images.githubusercontent.com/76026450/106694342-ebff1100-660a-11eb-8e00-5d22ccb523bd.png)

dari line 276 itu kan **pp** isinya foto profil nya user, tetapi ketika user yang baru masuk tidak memiliki foto profil dan hanya mengirim file kosong. pgnnya sih ada gambar default gitu di direktori, cuma ngga tau gmn blm belajar dasar js apalagi oop nya hehe '-'

**Comment by Nurutomo** [comment]
Sebenarnya gitu, tapi gatau kenapa kok foto profilnya (dari lokal) nggk terkirim

**Comment by ariffb25** [comment]
thanks udah fix ❤️
