### ISSUE TITLE
[NEW GAME] 

### ISSUE THREAD

**Issue by lilnext01** [Nurutomo/wabot-aq#383]
Mod game baru yang sederhana dan keren, cara kerjanya seperti ini: Setidaknya ada 2 pemain atau lebih, ketika perintah dijalankan, Bot akan menggambar 'Acak' dengan semua huruf AZ & huruf yang digambar, peserta akan memiliki waktu untuk menyebutkan nama dengan huruf itu, dan di itu, Bot juga akan mengatakan Objek mana yang akan dikatakan. Saya akan memberikan contoh yang lebih baik:

Bot memberikan opsi pilihan 'Objek' untuk undian. contoh benda; (Hewan, Nama kota, negara, tim sepak bola, dll...) Misalkan saya memilih 'Hewan', maka Bot akan menggambar huruf, dan huruf yang digambar, peserta harus menyebutkan nama hewan dengan inisial huruf yang digambar. 
Contoh 2: 
Objek yang dipilih [Hewan] 
surat yang ditarik: F 
pemain1; semut 
pemain2; Gajah (Tapi gajah tidak dimulai dengan F), jadi, kesalahan... 
Anda dapat melakukannya dengan cara yang lebih sederhana jika Anda sempurna. 
Terima kasih!

**Comment by Nurutomo** [comment]
> Mod game baru yang sederhana dan keren, cara kerjanya seperti ini: Setidaknya ada 2 pemain atau lebih, ketika perintah dijalankan, Bot akan menggambar 'Acak' dengan semua huruf AZ & huruf yang digambar, peserta akan memiliki waktu untuk menyebutkan nama dengan huruf itu, dan di itu, Bot juga akan mengatakan Objek mana yang akan dikatakan. Saya akan memberikan contoh yang lebih baik:
> 
> Bot memberikan opsi pilihan 'Objek' untuk undian. contoh benda; (Hewan, Nama kota, negara, tim sepak bola, dll...) Misalkan saya memilih 'Hewan', maka Bot akan menggambar huruf, dan huruf yang digambar, peserta harus menyebutkan nama hewan dengan inisial huruf yang digambar.
> Contoh 2:
> Objek yang dipilih [Hewan]
> surat yang ditarik: F
> pemain1; semut
> pemain2; Gajah (Tapi gajah tidak dimulai dengan F), jadi, kesalahan...
> Anda dapat melakukannya dengan cara yang lebih sederhana jika Anda sempurna.
> Terima kasih!

https://gartic.io like?

**Comment by lilnext01** [comment]
> > Mod game baru yang sederhana dan keren, cara kerjanya seperti ini: Setidaknya ada 2 pemain atau lebih, ketika perintah dijalankan, Bot akan menggambar 'Acak' dengan semua huruf AZ & huruf yang digambar, peserta akan memiliki waktu untuk menyebutkan nama dengan huruf itu, dan di itu, Bot juga akan mengatakan Objek mana yang akan dikatakan. Saya akan memberikan contoh yang lebih baik:
> > Bot memberikan opsi pilihan 'Objek' untuk undian. contoh benda; (Hewan, Nama kota, negara, tim sepak bola, dll...) Misalkan saya memilih 'Hewan', maka Bot akan menggambar huruf, dan huruf yang digambar, peserta harus menyebutkan nama hewan dengan inisial huruf yang digambar.
> > Contoh 2:
> > Objek yang dipilih [Hewan]
> > surat yang ditarik: F
> > pemain1; semut
> > pemain2; Gajah (Tapi gajah tidak dimulai dengan F), jadi, kesalahan...
> > Anda dapat melakukannya dengan cara yang lebih sederhana jika Anda sempurna.
> > Terima kasih!
> 
> https://gartic.io like?

ya :v

**Comment by FadliDarmawan** [comment]
> > Mod game baru yang sederhana dan keren, cara kerjanya seperti ini: Setidaknya ada 2 pemain atau lebih, ketika perintah dijalankan, Bot akan menggambar 'Acak' dengan semua huruf AZ & huruf yang digambar, peserta akan memiliki waktu untuk menyebutkan nama dengan huruf itu, dan di itu, Bot juga akan mengatakan Objek mana yang akan dikatakan. Saya akan memberikan contoh yang lebih baik:
> > 
> > Bot memberikan opsi pilihan 'Objek' untuk undian. contoh benda; (Hewan, Nama kota, negara, tim sepak bola, dll...) Misalkan saya memilih 'Hewan', maka Bot akan menggambar huruf, dan huruf yang digambar, peserta harus menyebutkan nama hewan dengan inisial huruf yang digambar.
> > Contoh 2:
> > Objek yang dipilih [Hewan]
> > surat yang ditarik: F
> > pemain1; semut
> > pemain2; Gajah (Tapi gajah tidak dimulai dengan F), jadi, kesalahan...
> > Anda dapat melakukannya dengan cara yang lebih sederhana jika Anda sempurna.
> > Terima kasih!
> 
> https://gartic.io like?

Buat lh bang
