### ISSUE TITLE
Help, Bagaimana Cara Menambahkan Fitur Tagall

### ISSUE THREAD

**Issue by yourtypicalbae** [Nurutomo/wabot-aq#385]
Permisi gan ane newbie, cara buat nambahin fitur tagall + pengumuman nya gimana ya ? Terimakasjh

**Comment by Ftwrr** [comment]
let { MessageType } = require('@adiwajshing/baileys')

let handler = async (m, { conn, text, participants }) => {
  let users = participants.map(u => u.jid)
  conn.reply(m.chat, users.map(v => '@' + v.replace(/@.+/, '')).join``, m, {
    contextInfo: { mentionedJid: users }
})
  
}
handler.customPrefix = /(@)/
handler.command = /^everyone$/i
handler.owner = true
handler.mods = false
handler.premium = false
handler.group = true
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null

module.exports = handler


gw sih gitu

**Comment by FadliDarmawan** [comment]
> let { MessageType } = require('@adiwajshing/baileys')
> 
> let handler = async (m, { conn, text, participants }) => {
> let users = participants.map(u => u.jid)
> conn.reply(m.chat, users.map(v => '@' + v.replace(/@.+/, '')).join``, m, {
> contextInfo: { mentionedJid: users }
> })
> 
> }
> handler.customPrefix = /(@)/
> handler.command = /^everyone$/i
> handler.owner = true
> handler.mods = false
> handler.premium = false
> handler.group = true
> handler.private = false
> 
> handler.admin = false
> handler.botAdmin = false
> 
> handler.fail = null
> 
> module.exports = handler
> 
> gw sih gitu

Bjir kayak discord

**Comment by yourtypicalbae** [comment]
Nambahinnya gimana gan ?

**Comment by KazukoGans** [comment]
> Nambahinnya gimana gan ?

Chat W --> https://wa.me/62895333380095

**Comment by Ftwrr** [comment]
> Nambahinnya gimana gan ?

bikin file tagall.js baru di folder plugin, terus tinggal paste ke dalam tagall.js yang dibikin tadi

**Comment by FadliDarmawan** [comment]
> Nambahinnya gimana gan ?

Bikin file nya
Terus ntar
cd /sdcrad
cp -r <nama file lu>.js ~
cd ~
cp -r <nama file lu>.js wabot-aq
cd wabot-aq
cp -r <nama file lu>.js plugins

**Comment by FadliDarmawan** [comment]
> > Nambahinnya gimana gan ?
> 
> Chat W --> https://wa.me/62895333380095

Siap :v

**Comment by KazukoGans** [comment]
> > > Nambahinnya gimana gan ?
> > 
> > 
> > Chat W --> https://wa.me/62895333380095
> 
> Siap :v

:v
