### ISSUE TITLE
Fitur #attp gk work

### ISSUE THREAD

**Issue by Miaweers** [Nurutomo/wabot-aq#39]

**Comment by ariffb25** [comment]
pesan errornya apa?
punyaku masih tetep bisa dipake

**Comment by Miaweers** [comment]
> pesan errornya apa?
> punyaku masih tetep bisa dipake

(node:16528) UnhandledPromiseRejectionWarning: Error: Unsupported MIME type: image/webp                         at Jimp.throwError (/data/data/com.termux/files/home/bot/node_modules/@jimp/utils/dist/index.js:33:13)      at Jimp.parseBitmap (/data/data/com.termux/files/home/bot/node_modules/@jimp/core/dist/utils/image-bitmap.js:198:32)                                              at Jimp.parseBitmap (/data/data/com.termux/files/home/bot/node_modules/@jimp/core/dist/index.js:431:32)     at new Jimp (/data/data/com.termux/files/home/bot/node_modules/@jimp/core/dist/index.js:384:13)             at _construct (/data/data/com.termux/files/home/bot/node_modules/@babel/runtime/helpers/construct.js:19:21)                                                       at /data/data/com.termux/files/home/bot/node_modules/@jimp/core/dist/index.js:926:32                        at new Promise (<anonymous>)                          at Function.Jimp.read (/data/data/com.termux/files/home/bot/node_modules/@jimp/core/dist/index.js:925:10)                                                         at Object.compressImage (/data/data/com.termux/files/home/bot/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:260:39)                                 at Object.generateThumbnail (/data/data/com.termux/files/home/bot/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:297:36)                             at WAConnection.prepareMessageMedia (/data/data/com.termux/files/home/bot/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:131:23)            at runMicrotasks (<anonymous>)                        at processTicksAndRejections (internal/process/task_queues.js:93:5)                                         at async WAConnection.prepareMessageContent (/data/data/com.termux/files/home/bot/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:81:21)     at async WAConnection.prepareMessage (/data/data/com.termux/files/home/bot/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:30:25)            at async WAConnection.sendMessage (/data/data/com.termux/files/home/bot/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:24:27)               at async WAConnection.sendFile (/data/data/com.termux/files/home/bot/lib/simple.js:50:20)               (node:16528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)

**Comment by ariffb25** [comment]
```
$ pkg install ffmpeg -y
$ pkg install imagemagick -y
```
itu udh diinstal?

```
const fetch = require('node-fetch')
const FormData = require('form-data')
const { MessageType } = require('@adiwajshing/baileys')

let handler = async (m, { conn, text }) => {
  if (text) conn.sendFile(m.chat, global.API('xteam', '/attp', { file: '', text }), 'attp.webp', '', m, false, { asSticker: true })
  else throw 'Uhm...Teksnya mana?\ncontoh: *.attp astrobot*'
}
handler.help = ['attp <teks>']
handler.tags = ['sticker']
handler.command = /^attp$/i
handler.owner = false
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null
handler.limit = true

module.exports = handler
```

**Comment by Miaweers** [comment]
> ```
> $ pkg install ffmpeg -y
> $ pkg install imagemagick -y
> ```
> 
> itu udh diinstal?
> 
> ```
> const fetch = require('node-fetch')
> const FormData = require('form-data')
> const { MessageType } = require('@adiwajshing/baileys')
> 
> let handler = async (m, { conn, text }) => {
>   if (text) conn.sendFile(m.chat, global.API('xteam', '/attp', { file: '', text }), 'attp.webp', '', m, false, { asSticker: true })
>   else throw 'Uhm...Teksnya mana?\ncontoh: *.attp astrobot*'
> }
> handler.help = ['attp <teks>']
> handler.tags = ['sticker']
> handler.command = /^attp$/i
> handler.owner = false
> handler.mods = false
> handler.premium = false
> handler.group = false
> handler.private = false
> 
> handler.admin = false
> handler.botAdmin = false
> 
> handler.fail = null
> handler.limit = true
> 
> module.exports = handler
> ```

Udah
