### ISSUE TITLE
Command pake sticker

### ISSUE THREAD

**Issue by FadliDarmawan** [Nurutomo/wabot-aq#395]
![Screenshot_20210611-212054_WhatsApp.jpg](https://user-images.githubusercontent.com/79369935/121701336-fd957f80-cafa-11eb-8bcc-f010f151a2bb.jpg)

Bisa command pake sticker kayak gitu

Yang w saranin:
Menu
Delete
Tutup
Buka
.q (reply)
Profile
Sticker

Sekian :v

**Comment by anshuljai** [comment]
yes....just make a case of its sha256 enc @Nurutomo need assistance of yours 😂

**Comment by ariffb25** [comment]
```js
if ( m.quoted.url == 'https://mmg.whatsapp.net/d/f/AvQTuVHng_IbX0fpX_0J_bjmXMOue2ZVEofKtIFNRZez.enc' ) throw true
else throw false
```
nyoba samain url :v 
true

**Comment by Nobuyaki** [comment]
> ```js
> if ( m.quoted.url == 'https://mmg.whatsapp.net/d/f/AvQTuVHng_IbX0fpX_0J_bjmXMOue2ZVEofKtIFNRZez.enc' ) throw true
> else throw false
> ```
> 
> nyoba samain url :v
> true

Bang cara biar gak di reply dulu gimana?

**Comment by anshuljai** [comment]
> ```js
> if ( m.quoted.url == 'https://mmg.whatsapp.net/d/f/AvQTuVHng_IbX0fpX_0J_bjmXMOue2ZVEofKtIFNRZez.enc' ) throw true
> else throw false
> ```
> 
> nyoba samain url :v
> true

wrong url can be changed....


it is to be matched with sha256 hex code because it remains same irrespective of wm fiturs

**Comment by jauhari21** [comment]
> ![Screenshot_20210611-212054_WhatsApp.jpg](https://user-images.githubusercontent.com/79369935/121701336-fd957f80-cafa-11eb-8bcc-f010f151a2bb.jpg)
> 
> Bisa command pake sticker kayak gitu
> 
> Yang w saranin:
> Menu
> Delete
> Tutup
> Buka
> .q (reply)
> Profile
> Sticker
> 
> Sekian :v

Tumtor bagi sc

**Comment by Nurutomo** [comment]
Done!

**Comment by Nurutomo** [comment]
# Usage
## Example Sticker/Image/Video
![image](https://user-images.githubusercontent.com/18616827/121813258-87795000-cc95-11eb-92b5-e3ef55a958c3.png)
![image](https://user-images.githubusercontent.com/18616827/121813267-919b4e80-cc95-11eb-9fba-f01fb59907a4.png)

## Set Command
![image](https://user-images.githubusercontent.com/18616827/121813286-a2e45b00-cc95-11eb-8775-dedb06c627d5.png)

## Delete
![image](https://user-images.githubusercontent.com/18616827/121813308-b1cb0d80-cc95-11eb-99e0-dba6080ea1f9.png)

## List
![image](https://user-images.githubusercontent.com/18616827/121813492-6ebd6a00-cc96-11eb-9e31-4d6ad425c575.png)

**Comment by FadliDarmawan** [comment]
> Done!

Thx nur
