### ISSUE TITLE
Refferal

### ISSUE THREAD

**Issue by Users1233** [Nurutomo/wabot-aq#398]
Bisa buatin ga fitur refferal jadi kalo ada pengguna baru terus kalo masukkin refferall orang yang punya refferal dapet tambahan XP

**Comment by Nurutomo** [comment]
Interesting

**Comment by FadliDarmawan** [comment]
> Bisa buatin ga fitur refferal jadi kalo ada pengguna baru terus kalo masukkin refferall orang yang punya refferal dapet tambahan XP 

Tiktok moment

**Comment by Users1233** [comment]
@Nurutomo Bisa ga??

**Comment by Nurutomo** [comment]
ketik `#ref`
