### ISSUE TITLE
tomp3 ?

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#399]

**Comment by lilnext01** [comment]
let { Presence, Mimetype } = require('@adiwajshing/baileys')
let ffmpeg = require('fluent-ffmpeg');
let fetch = require('node-fetch');
let ftype = require('file-type');
let fs = require('fs');
let { exec } = require('child_process');

let handler = async (m, { conn, text, args, usedPrefix, command }) => {

    m.reply('Convertendo, aguarde...')
   await conn.updatePresence(m.chat, Presence.composing)
	  let type = Object.keys(m.message)[0]
	  const content = JSON.stringify(m.message)
      let isMedia = (type === 'videoMessage')
      let isQuotedVideo = type === 'extendedTextMessage' && content.includes('videoMessage')
      if (!m.quoted) return conn.reply(m.chat, 'Responda à um vídeo!', m)
	  if (!isQuotedVideo) return m.reply('Apenas para Vídeo!')
	  let encmedia = JSON.parse(JSON.stringify(m).replace('quotedM', 'm')).message.extendedTextMessage.contextInfo
	     let media = await conn.downloadAndSaveMediaMessage(encmedia)
	     let exportar = ('.mp3')
		     exec(`ffmpeg -i ${media} ${exportar}`, (err) => {
					fs.unlinkSync(media)
					let buffer = fs.readFileSync(ran)
					conn.sendFile(m.chat, buffer, { mimetype: 'audio/mp3', quoted: m })
                    fs.unlinkSync(exportar)
                    })
      m.reply('Pronto!')
}
handler.help = ['mp3 _<responda à um vídeo>_']
handler.tags = ['audio']
handler.command = /^tomp3|mp3$/i
handler.fail = null
handler.exp = 0
handler.limit = true

module.exports = handler

**Comment by Ftwrr** [comment]
```const fs = require('fs')
const { exec } = require('child_process')

let handler = async (m, { conn, usedPrefix, command }) => {
    try {
        let q = m.quoted ? { message: { [m.quoted.mtype]: m.quoted } } : m
        let mime = ((m.quoted ? m.quoted : m.msg).mimetype || '')
        if (/video/.test(mime)) {
            let media = await conn.downloadAndSaveMediaMessage(q)
            let ran = getRandom('.mp3')
            exec(`ffmpeg -i ${media} ${ran}`, (err, stderr, stdout) => {
                fs.unlinkSync(media)
                if (err) throw `_*Error!*_`
                let buff = fs.readFileSync(ran)
                conn.sendFile(m.chat, buff, ran, null, m, null)
                fs.unlinkSync(ran)
            })
        } else throw `Balas video yang ingin diubah dengan caption *${usedPrefix + command}*`
    } catch (e) {
        throw e
    }
}
handler.help = ['tomp3']
handler.tags = ['audio']
handler.command = /^(tomp3)$/i
module.exports = handler


const getRandom = (ext) => {
    return `${Math.floor(Math.random() * 10000)}${ext}`
}
```

**Comment by Lord-Gaming** [comment]
> ```
> const { exec } = require('child_process')
> 
> let handler = async (m, { conn, usedPrefix, command }) => {
>     try {
>         let q = m.quoted ? { message: { [m.quoted.mtype]: m.quoted } } : m
>         let mime = ((m.quoted ? m.quoted : m.msg).mimetype || '')
>         if (/video/.test(mime)) {
>             let media = await conn.downloadAndSaveMediaMessage(q)
>             let ran = getRandom('.mp3')
>             exec(`ffmpeg -i ${media} ${ran}`, (err, stderr, stdout) => {
>                 fs.unlinkSync(media)
>                 if (err) throw `_*Error!*_`
>                 let buff = fs.readFileSync(ran)
>                 conn.sendFile(m.chat, buff, ran, null, m, null)
>                 fs.unlinkSync(ran)
>             })
>         } else throw `Balas video yang ingin diubah dengan caption *${usedPrefix + command}*`
>     } catch (e) {
>         throw e
>     }
> }
> handler.help = ['tomp3']
> handler.tags = ['audio']
> handler.command = /^(tomp3)$/i
> module.exports = handler
> 
> 
> const getRandom = (ext) => {
>     return `${Math.floor(Math.random() * 10000)}${ext}`
> }
> ```
ReferenceError: fs is not defined
    at c:\wabot-aq\plugins\tomp3.js:11:17
    at ChildProcess.exithandler (child_process.js:299:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) uncaughtException

bruh

**Comment by Ftwrr** [comment]
> > ```
> > const { exec } = require('child_process')
> > 
> > let handler = async (m, { conn, usedPrefix, command }) => {
> >     try {
> >         let q = m.quoted ? { message: { [m.quoted.mtype]: m.quoted } } : m
> >         let mime = ((m.quoted ? m.quoted : m.msg).mimetype || '')
> >         if (/video/.test(mime)) {
> >             let media = await conn.downloadAndSaveMediaMessage(q)
> >             let ran = getRandom('.mp3')
> >             exec(`ffmpeg -i ${media} ${ran}`, (err, stderr, stdout) => {
> >                 fs.unlinkSync(media)
> >                 if (err) throw `_*Error!*_`
> >                 let buff = fs.readFileSync(ran)
> >                 conn.sendFile(m.chat, buff, ran, null, m, null)
> >                 fs.unlinkSync(ran)
> >             })
> >         } else throw `Balas video yang ingin diubah dengan caption *${usedPrefix + command}*`
> >     } catch (e) {
> >         throw e
> >     }
> > }
> > handler.help = ['tomp3']
> > handler.tags = ['audio']
> > handler.command = /^(tomp3)$/i
> > module.exports = handler
> > 
> > 
> > const getRandom = (ext) => {
> >     return `${Math.floor(Math.random() * 10000)}${ext}`
> > }
> > ```
> 
> ReferenceError: fs is not defined
> at c:\wabot-aq\plugins\tomp3.js:11:17
> at ChildProcess.exithandler (child_process.js:299:7)
> at ChildProcess.emit (events.js:315:20)
> at maybeClose (internal/child_process.js:1048:16)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) uncaughtException
> 
> bruh

tambahin sendiri lah, lu kan udah gede
