### ISSUE TITLE
cooldown/delay command

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#402]

**Comment by ShzRGB** [comment]
Kalo dikasih delay nanti di hujat bot lemot, bot ngeleg, bot kentang 🙁

**Comment by Ftwrr** [comment]
> Kalo dikasih delay nanti di hujat bot lemot, bot ngeleg, bot kentang 🙁

yahh tinggal `m.reply('cooldown 5 sec')` kaya gitu biar mereka tau kalo lagi cooldown

**Comment by Nurutomo** [comment]
> > Kalo dikasih delay nanti di hujat bot lemot, bot ngeleg, bot kentang 🙁
> 
> yahh tinggal `m.reply('cooldown 5 sec')` kaya gitu biar mereka tau kalo lagi cooldown

tapi nanti spam :\

**Comment by Ftwrr** [comment]
> > > Kalo dikasih delay nanti di hujat bot lemot, bot ngeleg, bot kentang 🙁
> > 
> > 
> > yahh tinggal `m.reply('cooldown 5 sec')` kaya gitu biar mereka tau kalo lagi cooldown
> 
> tapi nanti spam :\

aghhh serba salah yaudalah ><
