### ISSUE TITLE
Cara nambahin fitur pp couple gimana?

### ISSUE THREAD

**Issue by YuukiDes** [Nurutomo/wabot-aq#403]
Gimana ya? Gue ga paham kalo send 2 gambar

**Comment by Ftwrr** [comment]
conn.sendFile(m.chat, json.url, 'gambar1', '',m)
conn.sendFile(m.chat, json.url, 'gambar2', '',m)

:v

**Comment by YuukiDes** [comment]
> conn.sendFile(m.chat, json.url, 'gambar1', '',m)
> conn.sendFile(m.chat, json.url, 'gambar2', '',m)
> 
> :v

Full sc dong, w ga work :v

**Comment by Ftwrr** [comment]
> > conn.sendFile(m.chat, json.url, 'gambar1', '',m)
> > conn.sendFile(m.chat, json.url, 'gambar2', '',m)
> > :v
> 
> Full sc dong, w ga work :v

emang cuman itu jirr jadiin dua aja kan ngirim 2 gambar, tergantung api yang lo pake 
gw gapunya sc pp couple
