### ISSUE TITLE
cara ngambil foto profil orang yang kita reply?

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#405]

**Comment by anshuljai** [comment]
let pic = (await conn.getFile(await conn.getProfilePicture(m.sender))).data.toString('base64')

**Comment by anshuljai** [comment]
remove base64 if you dont want it to add in fake reply

**Comment by Ftwrr** [comment]
> let pic = (await conn.getFile(await conn.getProfilePicture(m.sender))).data.toString('base64')

ga work, gw masih ga ngerti

**Comment by Nurutomo** [comment]
> let pic = (await conn.getFile(await conn.getProfilePicture(m.sender))).data.toString('base64')

```js
let pp = await conn.getFile(
  await conn.getProfilePicture(m.quoted.sender) // Dapetin sender yang di reply
  .catch(() => './src/avatar_contact.png') // Kalo gaada profil, pake gambar default
).then(res => res.data) // Buffernya disini
```

**Comment by Ftwrr** [comment]
> > let pic = (await conn.getFile(await conn.getProfilePicture(m.sender))).data.toString('base64')
> 
> ```js
> let pp = await conn.getFile(
>   await conn.getProfilePicture(m.quoted.sender) // Dapetin sender yang di reply
>   .catch(() => './src/avatar_contact.png') // Kalo gaada profil, pake gambar default
> ).then(res => res.data) // Buffernya disini
> ```

cara gabungin ``m.quoted.sender`` nya ke dalam ``let who = m.mentionedJid && m.mentionedJid[0] ? m.mentionedJid[0] : m.fromMe ? conn.user.jid : m.sender`` gimana?

**Comment by Nurutomo** [comment]
```js
let who = m.quoted ? m.quoted.sender : m.mentionedJid && m.mentionedJid[0] ? m.mentionedJid[0] : m.fromMe ? conn.user.jid : m.sender
```

**Comment by ilhamimut** [comment]
> > let pic = (await conn.getFile(await conn.getProfilePicture(m.sender))).data.toString('base64')
> 
> ```js
> let pp = await conn.getFile(
>   await conn.getProfilePicture(m.quoted.sender) // Dapetin sender yang di reply
>   .catch(() => './src/avatar_contact.png') // Kalo gaada profil, pake gambar default
> ).then(res => res.data) // Buffernya disini
> ```


> > let pic = (await conn.getFile(await conn.getProfilePicture(m.sender))).data.toString('base64')
> 
> ```js
> let pp = await conn.getFile(
>   await conn.getProfilePicture(m.quoted.sender) // Dapetin sender yang di reply
>   .catch(() => './src/avatar_contact.png') // Kalo gaada profil, pake gambar default
> ).then(res => res.data) // Buffernya disini
> ```

taruhnya di file mana?
