### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Lord-Gaming** [Nurutomo/wabot-aq#407]
pas gw npm start keluar kek gini 
connect attempt 1 failed: Error: close, retrying...

**Comment by kythepublic** [comment]
Same

**Comment by prioprast** [comment]
Aku juga seperti itu, saya kira ada update pada termux nya, ternyata memang error dari sananya:(

**Comment by SanzGantengz** [comment]
Gw dah bisa ko

**Comment by Lord-Gaming** [comment]
> Gw dah bisa ko

gw kok gk bisa ya?

**Comment by kythepublic** [comment]
Masih sama ae

**Comment by kythepublic** [comment]
Masih error. ini entah gw nya yg salah entah dari sana nya

**Comment by YuukiDes** [comment]
Versi ganti ke [2, 2119, 6] kalo masi bingung chat w di wa.me/994407339135

**Comment by SanzGantengz** [comment]
> Versi ganti ke [2, 2119, 6] kalo masi bingung chat w di wa.me/994407339135

Iya 
Editnya di main.js
conn.version = [2, 2119, 6]
Kalau gw Di bawah global.conn

**Comment by SanzGantengz** [comment]
main.js 
Line 38

**Comment by SanzGantengz** [comment]
Gw di situ bisa

**Comment by Ftwrr** [comment]
npm i update


gitu doang :v
