### ISSUE TITLE
Qr limit for cmd jadibot

### ISSUE THREAD

**Issue by hardiantojek93** [Nurutomo/wabot-aq#408]
Supaya ga spam qr di jadibot gimana yah kak
Soalnya udah Ku kasih settimeout tetap spam

**Comment by jauhari21** [comment]
> Supaya ga spam qr di jadibot gimana yah kak
> Soalnya udah Ku kasih settimeout tetap spam

Jadiin khusus premium aja, tambahin handler.premium = true

**Comment by jauhari21** [comment]
Kalo mau dikasih limit tambahin handler.limit = true

**Comment by Nurutomo** [comment]
> Supaya ga spam qr di jadibot gimana yah kak
> Soalnya udah Ku kasih settimeout tetap spam

aneh, padahal udah ku setTimeout 60 detik (3 QR)

**Comment by hardiantojek93** [comment]
> > Supaya ga spam qr di jadibot gimana yah kak
> > Soalnya udah Ku kasih settimeout tetap spam
> 
> aneh, padahal udah ku setTimeout 60 detik (3 QR)

Iya bang soal cuma ngejeda aka gitu tapi NGK ngehentiin

**Comment by Nurutomo** [comment]
tapi kan udh ku conn.close()

**Comment by hardiantojek93** [comment]
Ok ok lah
