### ISSUE TITLE
Error : close ketika menghubungkan ke whatsapp web, mau scan qr diminta scan qr lagi, ini bug dari baileys ya?

### ISSUE THREAD

**Issue by rthelolchex** [Nurutomo/wabot-aq#409]

**Comment by Ftwrr** [comment]
https://github.com/adiwajshing/Baileys/issues/526

npm i update

**Comment by ngadimin51** [comment]
> 
> 
> [adiwajshing/Baileys#526](https://github.com/adiwajshing/Baileys/issues/526)
> 
> npm i update

jika masih gagal update file 0.Base.js
this.version=[2,2119,6];

https://github.com/adiwajshing/Baileys/issues/526#issuecomment-861990409

**Comment by Wahyubot123** [comment]
nambahin this vesion itu dimana ngab? di index.js bukan?

**Comment by Ftwrr** [comment]
src/WAConnection/0.Base.ts

**Comment by rthelolchex** [comment]
Tq ya ngab, udah kefix xD
