### ISSUE TITLE
 Stiker Tidak bisa di simpan

### ISSUE THREAD

**Issue by dyono0405** [Nurutomo/wabot-aq#411]
Mohon untuk di case sticker.. saat convert di seting menjadi 512x152 dan maksimal durasi 5 detik..

Soalnya kalau lebih dari itu walau stiker berhasil dibuat
Namun tidak bisa di simpan/difavoritkan

Makasih sebelumnya Atas bantuan abang..

**Comment by Nurutomo** [comment]
stiker tidak mengalami kompresi atau pemotongan ukuran otomatis, jadi stiker yang melebihi 1MB tidak akan bisa dilihat di hp, di web.whatsapp.com masih bisa

**Comment by dyono0405** [comment]
Minta Tolong di Upgrade gan biar biasa setidaknya nya durasinya Stiker jd ga lebih dari 6 detik..
Makasih

**Comment by Nurutomo** [comment]
itu bukan masalah durasi. tapi kompresi
