### ISSUE TITLE
pls fix baileys eror!

### ISSUE THREAD

**Issue by Wahyubot123** [Nurutomo/wabot-aq#415]
tolong di fix ya ngab nuru, soalnya pengguna setia wabot-aq :(

**Comment by Ftwrr** [comment]
npm update

**Comment by Wahyubot123** [comment]
setelah itu sudah bisa fix baileys eror ya?

**Comment by Ftwrr** [comment]
iya

**Comment by prioprast** [comment]
Tumntor ngab, kok gue gbisa² hehe'-'

**Comment by Ftwrr** [comment]
https://github.com/adiwajshing/Baileys/issues/526

**Comment by prioprast** [comment]
![Screenshot_2021-06-18-21-23-18-798_com termux](https://user-images.githubusercontent.com/74879576/122576559-00085400-d07c-11eb-96c1-0b1984dd14ba.jpg)

Terpaksa aku download ulang termuxnya Ama file botnya:

$termux-setup-storage
$pkg update && pkg upgrade
$pkg install ffmpeg
$pkg install imagemagick
$pkg install git
$pkg install nodejs
$clear
$cd /sdcard
$mv namafile elu $HOME
$cd
$cd namafile elu
$npm i update
$bash install.sh

Run
$npm start

Done.... hehe kira² tadi gue begitu bisa sih bang:v

**Comment by Ftwrr** [comment]
padahal mah gw tinggal update doang bisa jir :v

**Comment by Nurutomo** [comment]
> padahal mah gw tinggal update doang bisa jir :v

lalu rescan

**Comment by Wahyubot123** [comment]
Bang update fitur tagall & anti badword dong

Pada tanggal Min, 20 Jun 2021 00:33 Nurutomo ***@***.***
menulis:
