### ISSUE TITLE
[NEW] Feature buyxp

### ISSUE THREAD

**Issue by lilnext01** [Nurutomo/wabot-aq#417]
Bagaimana cara membeli Limit XP, limit sama dengan 350 XP, kan? jadi jika saya melakukan .buyxp, itu akan memberi saya 350 XP. 
> contoh: 
>>> .buyxp 
-1 limit 
+350 exp
>>> .buyxp 2x 
-2 limit 
+700 exp

**Comment by anshuljai** [comment]
just make a reverse plugin.of buylimit.js

**Comment by FadliDarmawan** [comment]
> just make a reverse plugin.of buylimit.js

Hello anshul
