### ISSUE TITLE
AutoRegister?

### ISSUE THREAD

**Issue by Andika856** [Nurutomo/wabot-aq#419]
Ini perintah nya utk owner, jadi gini, kan kalo gw reset(uhh gw pernah pas error tinggal hapus trus pake yg baru trus balik ke awal lagi :v) gitu nanti exp+limit+level mereka ilang, gw balikin deh sendiri, tapi ga nyuruh2 mereka register, mungkin cara kerjanya kek gini :

#autoregister @tag nama.umur

Ya kek gitu

Pls di add 🙏

**Comment by Kokoronationz** [comment]
Pake #Sudo aja

**Comment by FadliDarmawan** [comment]
> Ini perintah nya utk owner, jadi gini, kan kalo gw reset(uhh gw pernah pas error tinggal hapus trus pake yg baru trus balik ke awal lagi :v) gitu nanti exp+limit+level mereka ilang, gw balikin deh sendiri, tapi ga nyuruh2 mereka register, mungkin cara kerjanya kek gini :
> 
> #autoregister @tag nama.umur
> 
> Ya kek gitu
> 
> Pls di add 🙏 

Copy database.json ke memo internal buat cadangan kek cadangan chat wa :v

**Comment by anshuljai** [comment]
> Ini perintah nya utk owner, jadi gini, kan kalo gw reset(uhh gw pernah pas error tinggal hapus trus pake yg baru trus balik ke awal lagi :v) gitu nanti exp+limit+level mereka ilang, gw balikin deh sendiri, tapi ga nyuruh2 mereka register, mungkin cara kerjanya kek gini :
> 
> #autoregister @tag nama.umur
> 
> Ya kek gitu
> 
> Pls di add 🙏
use it in eval ( you can make it a plugin too for owner only)
>global.DATABASE._data.users['+62nomor@s.whatsapp.net'].register = true

**Comment by Nurutomo** [comment]
> Pake #Sudo aja

`#sudo @tag #register nama.umur`
