### ISSUE TITLE
Cara ganti nomer owner

### ISSUE THREAD

**Issue by dikaa09** [Nurutomo/wabot-aq#42]
Bang ini cara ganti nomer owner gimana????
Tolong di jawab ya makasih

**Comment by ariffb25** [comment]
di file **[main.js](https://github.com/Nurutomo/wabot-aq/blob/master/main.js)** baris ke 17 / [lihat disini](https://github.com/Nurutomo/wabot-aq/blob/f55f701af9722c322fd49fb50e0111c8ab9bf603/main.js#L17)

![image](https://user-images.githubusercontent.com/76026450/107176038-e6d20580-6a00-11eb-825d-2cd5e74777bc.png)
tinggal ganti aja nomor kamu/tambah nomor juga bisa 👍

**Comment by achmadromi** [comment]
> di file **[main.js](https://github.com/Nurutomo/wabot-aq/blob/master/main.js)** baris ke 17 / [lihat disini](https://github.com/Nurutomo/wabot-aq/blob/f55f701af9722c322fd49fb50e0111c8ab9bf603/main.js#L17)
> 
> ![gambar](https://user-images.githubusercontent.com/76026450/107176038-e6d20580-6a00-11eb-825d-2cd5e74777bc.png)
> tinggal ganti aja nomor kamu / tambah nomor juga bisa 👍

boleh ni?

**Comment by ariffb25** [comment]
> > di file **[main.js](https://github.com/Nurutomo/wabot-aq/blob/master/main.js)** baris ke 17 / [lihat disini](https://github.com/Nurutomo/wabot-aq/blob/f55f701af9722c322fd49fb50e0111c8ab9bf603/main.js#L17)
> > ![gambar](https://user-images.githubusercontent.com/76026450/107176038-e6d20580-6a00-11eb-825d-2cd5e74777bc.png)
> > tinggal ganti aja nomor kamu / tambah nomor juga bisa 👍
> 
> boleh ni?

boleh lah, asal jgn apus githubnya nurotomo👍
