### ISSUE TITLE
New Feature: Ngutang

### ISSUE THREAD

**Issue by FadliDarmawan** [Nurutomo/wabot-aq#420]
Kalau limit habis selain buy memakai EXP bisa juga ngutang ke users lain

Utang nya jangan lupa di bayar ya :v

Ada juga bank central bisa ngutang ke bank itu dengan bunga, bunga nya masuk ke owner

Utang yang di sini itu Limit atau apapun yang kalian namakan di handler.js

#YNTKTS

**Comment by Nurutomo** [comment]
:v

manual aja lah, kan ada #87 (#paylimit) dan #pay xp

**Comment by FadliDarmawan** [comment]
> :v
> 
> manual aja lah, kan ada #87 (#paylimit) dan #pay xp

Ngisi pull request ke 420 :v
