### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Lord-Gaming** [Nurutomo/wabot-aq#437]
![image](https://user-images.githubusercontent.com/82928780/122675420-8ac78b00-d203-11eb-80dd-cdd58f54d9e3.png)
Ini kenapa bege 🗿

**Comment by botstylee** [comment]
> ![image](https://user-images.githubusercontent.com/82928780/122675420-8ac78b00-d203-11eb-80dd-cdd58f54d9e3.png)
> Ini kenapa bege 🗿

Apus file npm-cache terus kalo udh di apus baru bisa tapi update ulang
