### ISSUE TITLE
[Feature] How do I add ncode downloader

### ISSUE THREAD

**Issue by bilal-08** [Nurutomo/wabot-aq#439]
I know From before you are opposing from this Idea and what i want is , can you pls Show me the code here 
I'll remove Islamic Codes from there too after Adding ncode downloader :)
(ik you might don't like to add ncode and Islamic Things to be together that's why im asking here)

**Comment by Ftwrr** [comment]
maksud kamu nhentai?

``conn.sendMessage(m.chat, {url:json.result.pdf_file}, MessageType.document, { mimetype: Mimetype.pdf, filename: `nhentai.pdf` })``

**Comment by bilal-08** [comment]
> do you mean nhentai?
> 
> `` conn.sendMessage(m.chat, {url:json.result.pdf_file}, MessageType.document, { mimetype: Mimetype.pdf, filename: `nhentai.pdf` }) ``

nah bagaimana itu bisa mengambil kodenya?

**Comment by Ftwrr** [comment]
> > do you mean nhentai?
> > `` conn.sendMessage(m.chat, {url:json.result.pdf_file}, MessageType.document, { mimetype: Mimetype.pdf, filename: `nhentai.pdf` }) ``
> 
> nah bagaimana itu bisa mengambil kodenya?

tergantung dari api yang kamu gunakan :/

**Comment by bilal-08** [comment]
> > > do you mean nhentai?
> > > `` conn.sendMessage(m.chat, {url:json.result.pdf_file}, MessageType.document, { mimetype: Mimetype.pdf, filename: `nhentai.pdf` }) ``
> > 
> > 
> > well how can it fetch the code?
> 
> depending on the fire you use :/

@Ftwrr oi How do i contact you?
