### ISSUE TITLE
kick orang yang kita reply

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#447]

**Comment by ariffb25** [comment]
```js
await conn.groupRemove(m.chat, [m.quoted.sender])
```

**Comment by Nobuyaki** [comment]
> ```js
> await conn.groupRemove(m.chat, [m.quoted.sender])
> ```

Bang biar bisa tag & reply gimana?

**Comment by ariffb25** [comment]
```js
let who = m.mentionedJid[0] ? m.mentionedJid[0] : m.qouted ? m.quoted.sender : ''
await conn.groupRemove(m.chat, [who])
```
 hanya bisa 1 tag atau reply pesan org yg mau dikick

**Comment by jauhari21** [comment]
Full scnya?

**Comment by ilhamimut** [comment]
> Full scnya?

let handler = async (m, { conn }) => {
  await conn.groupRemove(m.chat, [m.quoted.sender]) // untuk reply orang yang ingin di kick
  // code di bawah hanya bisa 1 tag dan reply (pastikan baris comment dihapus)
  // let who = m.mentionedJid[0] ? m.mentionedJid[0] : m.qouted ? m.quoted.sender : ''
  // await conn.groupRemove(m.chat, [who])
}
handler.help = ['kick']
handler.tags = ['fitur kick']
handler.command = /^(kick2)$/i

handler.owner = true

module.exports = handler

**Comment by ilhamimut** [comment]
// update: bisa reply maupun mention orang yang ingin dikick :v

let handler = async (m, { conn }) => {
  let who = m.mentionedJid[0] ? m.mentionedJid[0] : m.qouted ? m.quoted.sender : ''
  await conn.groupRemove(m.chat, [who || m.quoted.sender])
}
handler.help = []
handler.tags = []
handler.command = /^(kick)$/i

handler.owner = false

module.exports = handler
