### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Wahyudianshar** [Nurutomo/wabot-aq#449]
Bang tolong tambahin fitur lirik, bug gc/troli dong
Buat hanguskn grup yg meresahkan seperti grup bokep dll

**Comment by Nurutomo** [comment]
fitur lirik udah ada, klo bug gaakan ku add. nanti ada yang salah gunain di grup sekolah ;v

**Comment by FadliDarmawan** [comment]
> fitur lirik udah ada, klo bug gaakan ku add. nanti ada yang salah gunain di grup sekolah ;v

pake eval ke pc guru
