### ISSUE TITLE
Ffmpeg

### ISSUE THREAD

**Issue by Akhdan2111** [Nurutomo/wabot-aq#45]
Ffmpeg dont forget to path itu maksudnya gimana yh..?

**Comment by ariffb25** [comment]
https://youtu.be/AXNugnsSdPc 
cek videonya ada cara buat path ffmpeg

**Comment by Akhdan2111** [comment]
> https://youtu.be/AXNugnsSdPc 
> cek videonya ada cara buat path ffmpeg

Ok bg thx.. Oiya cara matikan bot nya yg seharusnya gimana yh bg..? Langsung close ajh atau gimana..? Abis itu cara hidupkan nya lagi gimana bg..?

**Comment by ariffb25** [comment]
dari wa nya langsung bisa kek nya, ketik aja
```
> conn.close
```
kalo logout/ngehapus session
```
> conn.logout
```
selebihnya ada di folder lib kalo gasalah ya

bisa juga kalo scan ulang/ganti wa, hapus aja file **session.data.json** terus npm start aja nanti muncul barcode lagi

**Comment by Akhdan2111** [comment]
> dari wa nya langsung bisa kek nya, ketik aja
> ```
> > conn.close
> ```
> kalo logout/ngehapus session
> ```
> > conn.logout
> ```
> selebihnya ada di folder lib kalo gasalah ya
> 
> bisa juga kalo scan ulang/ganti wa, hapus aja file **session.data.json** terus npm start aja nanti muncul barcode lagi

Udh bisa bg..

**Comment by Akhdan2111** [comment]
> dari wa nya langsung bisa kek nya, ketik aja
> ```
> > conn.close
> ```
> kalo logout/ngehapus session
> ```
> > conn.logout
> ```
> selebihnya ada di folder lib kalo gasalah ya
> 
> bisa juga kalo scan ulang/ganti wa, hapus aja file **session.data.json** terus npm start aja nanti muncul barcode lagi

Aku udh nonton tutor di yt abg.. Cuman pas di npm instal nya error bg.. Closed connection, reason invalid session... Gimana tuh bg..?

**Comment by ariffb25** [comment]
coba ss

**Comment by Akhdan2111** [comment]
> coba ss

![IMG_20210210_090029_resize_61.jpg](https://user-images.githubusercontent.com/78744264/107453944-97b1df00-6b7e-11eb-845f-6516f3e09b61.jpg)

**Comment by ariffb25** [comment]
![image](https://user-images.githubusercontent.com/76026450/107455225-0ee87280-6b81-11eb-9ea7-e72d1218eecf.png)
ada file itu ngga? kalo ada coba hapus dulu

**Comment by Akhdan2111** [comment]
> ![image](https://user-images.githubusercontent.com/76026450/107455225-0ee87280-6b81-11eb-9ea7-e72d1218eecf.png)
> ada file itu ngga? kalo ada coba hapus dulu

Ok gan udh bisa semua thx..
