### ISSUE TITLE
Error ketika menggunakan fitur stikergif

### ISSUE THREAD

**Issue by meegoy69** [Nurutomo/wabot-aq#451]
ERROR [2021-06-22 15:02:57.221 +0000] (11152): Error in uploading to media-iad3-1.cdn.whatsapp.net (HTTPError: Response code 415 (Unsupported Media Type)) ,
 retrying...
    class: "Baileys"

**Comment by anshuljai** [comment]
its just error from baileys...the sticker is still sent...so no issue

**Comment by Users1233** [comment]
Hmmm dipunyaku kalau kirim media terus kasih feed #sticker ga bisa tapi kalau di reply mediannya pakai #stiker bisa
knp?
