### ISSUE TITLE
Sticker error

### ISSUE THREAD

**Issue by Users1233** [Nurutomo/wabot-aq#454]
Kalo kirim gambar dikasih feed #stiker error kalo di reply ga error napa tuh?

**Comment by Nurutomo** [comment]
url media belum terkirim ke bot

**Comment by Users1233** [comment]
hmm maksudnya?

**Comment by Nurutomo** [comment]
tiap pesan masuk, beberapa media nggk ada url buat didownload :|

**Comment by Akbarsans** [comment]
kalo di gua ko error semua ya, no such file or directory

**Comment by Ftwrr** [comment]
> kalo di gua ko error semua ya, no such file or directory

hapus temp :v

**Comment by ilhamimut** [comment]
> > kalo di gua ko error semua ya, no such file or directory
> 
> hapus temp :v

Letak file temp nya dimana gan?

**Comment by Ftwrr** [comment]
> > > kalo di gua ko error semua ya, no such file or directory
> > 
> > 
> > hapus temp :v
> 
> Letak file temp nya dimana gan?

folder tmp

**Comment by ilhamimut** [comment]
> > > > kalo di gua ko error semua ya, no such file or directory
> > > 
> > > 
> > > hapus temp :v
> > 
> > 
> > Letak file temp nya dimana gan?
> 
> folder tmp

Di folder whatsapp hp?
