### ISSUE TITLE
Fitur getip

### ISSUE THREAD

**Issue by Users1233** [Nurutomo/wabot-aq#459]
Jadi kalo misalnya kita command #getipaddress @users gitu keluar IPnya yang di tag 

Contoh  #getipaddress @user 
Bot nya bales : Ip Address @user adalah 102.02.11.04 

Gitu :v

**Comment by Nurutomo** [comment]
ga mungkin bisa lah  :v

**Comment by Ftwrr** [comment]
> ga mungkin bisa lah :v

ngayal jadi hengker mungkin

**Comment by FadliDarmawan** [comment]
> Jadi kalo misalnya kita command #getipaddress @users gitu keluar IPnya yang di tag 
> 
> Contoh  #getipaddress @user 
> Bot nya bales : Ip Address @user adalah 102.02.11.04 
> 
> Gitu :v 

Buset
