### ISSUE TITLE
Getcode

### ISSUE THREAD

**Issue by Dicky1303** [Nurutomo/wabot-aq#46]
Ngab ytmp3 nya kenapa gk dalam bentuk dokumen lagi? Enak an bentuk dokumen ngab:'

Sekalian getcode juga gk bisa apa":(

**Comment by ariffb25** [comment]
kalo **getcode** kan emng buat user yang numpang **jadibot** ubah aja ada di folder plugins

**Comment by Dicky1303** [comment]
Iya ngab di gw kok eror pas user yg mau jadibot malah nampil text khusus owner

**Comment by ariffb25** [comment]
```
handler.help = ['jadibot']
handler.tags = ['jadibot']
handler.command = /^jadibot$/i
**handler.owner = false**
handler.mods = false
handler.premium = false
handler.group = false
handler.private = true

handler.admin = false
handler.botAdmin = false

handler.fail = null
handler.limit = true

module.exports = handler
```

ubah aja jadi false

**Comment by Dicky1303** [comment]
> ```
> handler.help = ['jadibot']
> handler.tags = ['jadibot']
> handler.command = /^jadibot$/i
> handler.owner = false                              // yang ini
> handler.mods = false
> handler.premium = false
> handler.group = false
> handler.private = true
> 
> handler.admin = false
> handler.botAdmin = false
> 
> handler.fail = null
> handler.limit = true
> 
> module.exports = handler
> ```
> 
> ubah aja jadi false



> ```
> handler.help = ['jadibot']
> handler.tags = ['jadibot']
> handler.command = /^jadibot$/i
> handler.owner = false                              // yang ini
> handler.mods = false
> handler.premium = false
> handler.group = false
> handler.private = true
> 
> handler.admin = false
> handler.botAdmin = false
> 
> handler.fail = null
> handler.limit = true
> 
> module.exports = handler
> ```
> 
> ubah aja jadi false

Dimana ubahnya?

**Comment by Dicky1303** [comment]
Udah gan thanks

**Comment by Miaweers** [comment]
> Kalau yg ytmp3 jadi dokumen lagi kek sebelumnya gimana?

https://github.com/Nurutomo/wabot-aq/blob/14137e167e5e096222cfca8cea49eead7d49b2b5/plugins/yta.js#L18

Ubah Jadi `.trim(), m, false, {asDocument: true})

Note: Dapet Dari Plugins yang Lama , Tapi Gk Tau Work apa kgk :v , tapi pas aku coba sih work

**Comment by Dicky1303** [comment]
> > Kalau yg ytmp3 jadi dokumen lagi kek sebelumnya gimana?
> 
> https://github.com/Nurutomo/wabot-aq/blob/14137e167e5e096222cfca8cea49eead7d49b2b5/plugins/yta.js#L18
> 
> Ubah Jadi `.trim(), m, false, { asDocument: true })
> 
> Note: Dapet Dari Plugins yang Lama , Tapi Gk Tau Work apa kgk :v , tapi pas aku coba sih work

Work gan thanks

**Comment by Dicky1303** [comment]
Makasih banyak yg udah bantu 🙏

**Comment by Dicky1303** [comment]
![Screenshot_20210209_215227](https://user-images.githubusercontent.com/56459048/107381208-34459400-6b21-11eb-957f-29c8b75f1536.jpg)

1 getcode nya gini help dong
