### ISSUE TITLE
[NEW FEATURE] patent system

### ISSUE THREAD

**Issue by lilnext01** [Nurutomo/wabot-aq#463]
Sistem paten berdasarkan level.
misalnya: 
Jika pengguna level 1 (0) dia adalah Peringkat Perunggu, dan saat dia naik level, peringkatnya meningkat, dengan demikian, Perunggu, Perunggu II, Perunggu III, dll...

**Comment by Nurutomo** [comment]
use some array :)

```js
const ranks = ['Perunggu', 'Perunggu II', 'Perunggu III']

let level = 4

ranks[Math.min(level, ranks.length - 1)] // Perunggu III
```

**Comment by lilnext01** [comment]
Pls @Nurutomo help me :v

**Comment by Nurutomo** [comment]
> > use some array :)
> > ```js
> > const ranks = ['Perunggu', 'Perunggu II', 'Perunggu III']
> > 
> > let level = 4
> > 
> > ranks[Math.min(level, ranks.length - 1)] // Perunggu III
> > ```
> 
> Di mana saya bisa menambahkan ini? maaf saya pemula :v

anywhere you want to show :v
