### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Lord-Gaming** [Nurutomo/wabot-aq#465]
Tambahin fitur search lagu mas,Ntar dikirim pake vn

**Comment by ariffb25** [comment]
kan ada ```.play <pencarian>``` kalo mau jadi voice note tinggal jadiin true
https://github.com/Nurutomo/wabot-aq/blob/fc9b78c2cd022747ab0352a2f9e5c3f9424aa830/plugins/play.js#L33
jadi
```js
`.trim(), m, true)
```
kalo diatas ga bisa jg jadi gini
```js
`.trim(), m, true, { mimetype: 'audio/mp4' })
```

**Comment by Lord-Gaming** [comment]
> kan ada `.play <pencarian>` kalo mau jadi voice note tinggal jadiin true
> https://github.com/Nurutomo/wabot-aq/blob/fc9b78c2cd022747ab0352a2f9e5c3f9424aa830/plugins/play.js#L33
> 
> 
> jadi
> ```js
> `.trim(), m, true)
> ```
> 
> kalo diatas ga bisa jg jadi gini
> 
> ```js
> `.trim(), m, true, { mimetype: 'audio/mp4' })
> ```

2 2 nya gk jadi vn,tpi gpp lah
