### ISSUE TITLE
Buatin fitur check plugin

### ISSUE THREAD

**Issue by Users1233** [Nurutomo/wabot-aq#466]
Misal #plugin menu.js lansung otomasi dijawab fitur menu sudah dipakai 10 kali 5 kali di private 5 kali di grup berhasil 8 kali gagal 2 kali gitu ...

**Comment by Nurutomo** [comment]
hmm

**Comment by ariffb25** [comment]
```js
let handler = async (m, { args, usedPrefix, command }) => {
    if (!args[0]) throw `contoh:\n${usedPrefix + command} sticker`
    let { total, success, last, lastSuccess } = global.DATABASE.data.stats[args[0] + '.js']
    m.reply(`
*Plugin ${args[0]}*

*total:* ${total}
*berhasil:* ${success}
*terakhir digunakan:* ${new Date(last)}
*terakhir berhasil:* ${new Date(lastSuccess)}
`.trim())
}
handler.help = ['plugin *stiker*']
handler.tags = ['owner']
handler.command = /^plugin$/i
module.exports = handler
```
blm ku coba, baru ngetik dinotepad aja tadi:v

**Comment by lilnext01** [comment]
> ```js
> let handler = async (m, { args, usedPrefix, command }) => {
>     if (!args[0]) throw `contoh:\n${usedPrefix + command} sticker`
>     let { total, success, last, lastSuccess } = global.DATABASE.data.stats[args[0] + '.js']
>     m.reply(`
> *Plugin ${args[0]}*
> 
> *total:* ${total}
> *berhasil:* ${success}
> *terakhir digunakan:* ${new Date(last)}
> *terakhir berhasil:* ${new Date(lastSuccess)}
> `.trim())
> }
> handler.help = ['plugin *stiker*']
> handler.tags = ['owner']
> handler.command = /^plugin$/i
> module.exports = handler
> ```
> 
> blm ku coba, baru ngetik dinotepad aja tadi:v

Apakah mungkin juga menambahkan untuk menampilkan 5 pengguna terakhir yang menggunakan perintah? atau setidaknya yang terakhir? 
contoh: 
Pengguna terakhir yang menggunakan menu plugin: 
5. @pengguna 
4. @pengguna2 
3. @pengguna3 
2. @pengguna4 
1. @pengguna5 

Terima kasih jika Anda dapat menambahkan, terima kasih!!

**Comment by pengguna** [comment]
Lads please

**Comment by Users1233** [comment]
> ```js
> let handler = async (m, { args, usedPrefix, command }) => {
>     if (!args[0]) throw `contoh:\n${usedPrefix + command} sticker`
>     let { total, success, last, lastSuccess } = global.DATABASE.data.stats[args[0] + '.js']
>     m.reply(`
> *Plugin ${args[0]}*
> 
> *total:* ${total}
> *berhasil:* ${success}
> *terakhir digunakan:* ${new Date(last)}
> *terakhir berhasil:* ${new Date(lastSuccess)}
> `.trim())
> }
> handler.help = ['plugin *stiker*']
> handler.tags = ['owner']
> handler.command = /^plugin$/i
> module.exports = handler
> ```
> 
> blm ku coba, baru ngetik dinotepad aja tadi:v

Thx nanti kucoba :v

**Comment by Nurutomo** [comment]
> > ```js
> > let handler = async (m, { args, usedPrefix, command }) => {
> >     if (!args[0]) throw `contoh:\n${usedPrefix + command} sticker`
> >     let { total, success, last, lastSuccess } = global.DATABASE.data.stats[args[0] + '.js']
> >     m.reply(`
> > *Plugin ${args[0]}*
> > 
> > *total:* ${total}
> > *berhasil:* ${success}
> > *terakhir digunakan:* ${new Date(last)}
> > *terakhir berhasil:* ${new Date(lastSuccess)}
> > `.trim())
> > }
> > handler.help = ['plugin *stiker*']
> > handler.tags = ['owner']
> > handler.command = /^plugin$/i
> > module.exports = handler
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > blm ku coba, baru ngetik dinotepad aja tadi:v
> 
> Apakah mungkin juga menambahkan untuk menampilkan 5 pengguna terakhir yang menggunakan perintah? atau setidaknya yang terakhir?
> contoh:
> Pengguna terakhir yang menggunakan menu plugin:
> 5. @pengguna
> 4. @pengguna2
> 3. @pengguna3
> 2. @pengguna4
> 
> 1. @pengguna5
> 
> Terima kasih jika Anda dapat menambahkan, terima kasih!!

it doesnt save that data :\
