### ISSUE TITLE
#update eror

### ISSUE THREAD

**Issue by Nobuyaki** [Nurutomo/wabot-aq#469]
Kok gini bang

![Screenshot_2021-06-24-17-43-14](https://user-images.githubusercontent.com/72033395/123249961-c029ec80-d513-11eb-9ff2-4e500791a7b2.png)

**Comment by anshuljai** [comment]
use this

>#update --autostash

**Comment by Nobuyaki** [comment]
> use this
> 
> > #update --autostash

![Screenshot_2021-06-25-06-10-42](https://user-images.githubusercontent.com/72033395/123343520-1f234c00-d57c-11eb-9a83-4d04c89d7b4a.png)

**Comment by ariffb25** [comment]
fork

**Comment by Nobuyaki** [comment]
> fork

Harus fork repo dulu kah bang?

**Comment by anshuljai** [comment]
> > fork
> 
> Harus fork repo dulu kah bang?

no clone in termux
