### ISSUE TITLE
Cara Gunain ApiKey TebakGambar

### ISSUE THREAD

**Issue by Miaweers** [Nurutomo/wabot-aq#47]
{
    "code": 200,
    "status": true,
    "bantuan": "S_d_ng s_ns_",
    "jawaban": "Sedang sensi",
    "url": "https://api.xteam.xyz/downtebakgambar?id=1144.png"
}

**Comment by ariffb25** [comment]
jejak, mungkin bakal dibuat sih keknya

**Comment by Miaweers** [comment]
:v
