### ISSUE TITLE
Auto block

### ISSUE THREAD

**Issue by Lord-Gaming** [Nurutomo/wabot-aq#471]
Buatin auto blok kalo di telp/vc

**Comment by Ftwrr** [comment]
udah ada :v

**Comment by Users1233** [comment]
di punya gw kok ga bisa :v

**Comment by Lord-Gaming** [comment]
> udah ada :v

Letakny dimn bg?
Gw cari kok ga ada

**Comment by jauhari21** [comment]
> > udah ada :v
> 
> Letakny dimn bg?
> Gw cari kok ga ada

Handler
Main

**Comment by jauhari21** [comment]
> > udah ada :v
> 
> Letakny dimn bg?
> Gw cari kok ga ada

https://github.com/Nurutomo/wabot-aq/commit/fa70ef5915f6decaceec13610a756466867db100

**Comment by Lord-Gaming** [comment]
Oke thx
