### ISSUE TITLE
npm update in heroku

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#474]
gimana caranya npm update setelah npm install saat deploy di heroku

**Comment by anshuljai** [comment]
no need of update...heroku automatic install from npm cache 🙂

**Comment by Ftwrr** [comment]
just tell me where it is

**Comment by bilal-08** [comment]
> how to npm update after npm install when deploying on heroku

+ More options on Config vars
like
> changeable apikey
> prefix 
> name of the bot
> Mods of the bot

**Comment by Ftwrr** [comment]
> > how to npm update after npm install when deploying on heroku
> 
> * More options on Config vars
>   like
> 
> > changeable apikey
> > prefix
> > name of the bot
> > Mods of the bot

buatlah issues tersendiri untuk itu

**Comment by bilal-08** [comment]
> > > how to npm update after npm install when deploying on heroku
> > 
> > 
> > 
> > * More options on Config vars
> >   like
> > 
> > > changeable apikey
> > > prefix
> > > name of the bot
> > > Mods of the bot
> 
> make a separate issue for it

Okie dokie

**Comment by ariffb25** [comment]
di wa :v
```$ npm update```
