### ISSUE TITLE
Cara auto out jika member grup kurang dari 100 

### ISSUE THREAD

**Issue by jauhari21** [Nurutomo/wabot-aq#477]

**Comment by ariffb25** [comment]
```js
if (m.isGroup) {
        if (participants.length <= 100) { m.reply(`minimal 100 anggota, ${this.user.name} akan keluar dari grup`).then(() => this.groupLeave(m.chat)) }
      }
```

**Comment by Nurutomo** [comment]
> ```js
> if (m.isGroup) {
>         if (participants.length <= 100) { m.reply(`minimal 100 anggota, ${this.user.name} akan keluar dari grup`).then(() => this.groupLeave(m.chat)) }
>       }
> ```

if (groupSekolah) leave()

**Comment by jauhari21** [comment]
Itu ditaro dimana?

**Comment by ariffb25** [comment]
handler.js

**Comment by jauhari21** [comment]
> handler.js

Taruh di line ke berapa ya? Punyaku jadi eror kalo taro ngasal hehe

**Comment by ariffb25** [comment]
> > handler.js
> 
> Taruh di line ke berapa ya? Punyaku jadi eror kalo taro ngasal hehe

dibawah baris ini
https://github.com/Nurutomo/wabot-aq/blob/ab7af813b0e073870d79fd406144cf073c71268f/handler.js#L310

**Comment by jauhari21** [comment]
> > > handler.js
> > 
> > 
> > Taruh di line ke berapa ya? Punyaku jadi eror kalo taro ngasal hehe
> 
> dibawah baris ini, biar ga berantakan aja sih
> https://github.com/Nurutomo/wabot-aq/blob/ab7af813b0e073870d79fd406144cf073c71268f/handler.js#L310

![Screenshot_2021-06-29-14-18-09-27](https://user-images.githubusercontent.com/81492529/123754692-5cbe0700-d8e5-11eb-9e66-8ebd1946b851.jpg)

**Comment by jauhari21** [comment]
Eror lagi

**Comment by ariffb25** [comment]
itu karena variabel participants ga kepanggil karena pake let
ubah aja ```let``` jadi ```var```
(pembahasan mengenai statement berikut https://stackoverflow.com/questions/762011/whats-the-difference-between-using-let-and-var)
https://github.com/Nurutomo/wabot-aq/blob/90eaccc063939ab492a25c05b338b83fd871fd06/handler.js#L111

**Comment by jauhari21** [comment]
> itu karena variabel participants ga kepanggil karena pake let
> ubah aja `let` jadi `var`
> (pembahasan mengenai statement berikut https://stackoverflow.com/questions/762011/whats-the-difference-between-using-let-and-var)
> https://github.com/Nurutomo/wabot-aq/blob/90eaccc063939ab492a25c05b338b83fd871fd06/handler.js#L111

Oke terima kasih
