### ISSUE TITLE
profile error

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#478]
TypeError: Cannot destructure property 'name' of 'global.DATABASE.data.users[who]' as it is undefined.

**Comment by ariffb25** [comment]
usernya ngga ada di database.json / blm pake bot

**Comment by anshuljai** [comment]
just add in profile.js


>handler.register = true

**Comment by Nurutomo** [comment]
> just add in profile.js
> 
> > handler.register = true

:v

if (!(who in global.DATABASE.data.users)) throw 'User belum terdaftar dalam database!'
