### ISSUE TITLE
mengubah resolusi video ytv?

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#487]

**Comment by Nurutomo** [comment]
see y2mate.js

**Comment by ariffb25** [comment]
Opsi:
https://github.com/Nurutomo/wabot-aq/blob/ab7af813b0e073870d79fd406144cf073c71268f/lib/y2mate.js#L17-L25

Atur di:
https://github.com/Nurutomo/wabot-aq/blob/ab7af813b0e073870d79fd406144cf073c71268f/lib/y2mate.js#L90
