### ISSUE TITLE
Numpang tanya Kenapa Ada Deploy apa fungsinya makasih..

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#496]
Mohon di jawab Makasih 🙏

**Comment by ariffb25** [comment]
buat run di heroku ngab
![image](https://user-images.githubusercontent.com/76026450/123776650-b03a5000-d8f9-11eb-94e4-a1fbe6eac107.png)

**Comment by Nobuyaki** [comment]
> buat run di heroku ngab
> ![image](https://user-images.githubusercontent.com/76026450/123776650-b03a5000-d8f9-11eb-94e4-a1fbe6eac107.png)

Bang kalo mau ngedit file di heroku bisa gak?

**Comment by ariffb25** [comment]
@Nobuyaki bisa kyknya, tapi ribet, mending ngedit di code editor, trs push.
soalnya kan heroku suka reset kalo slug sizenya lewat dari 500MB/uptimenya udh 22 jam keatas

**Comment by Nobuyaki** [comment]
> @Nobuyaki bisa kyknya, tapi ribet, mending ngedit di code editor, trs push.
> soalnya kan heroku suka reset kalo slug sizenya lewat dari 500MB/uptimenya udh 22 jam keatas

Push ke repo github?

**Comment by ariffb25** [comment]
> > @Nobuyaki bisa kyknya, tapi ribet, mending ngedit di code editor, trs push.
> > soalnya kan heroku suka reset kalo slug sizenya lewat dari 500MB/uptimenya udh 22 jam keatas
> 
> Push ke repo github?

iya

**Comment by ariffb25** [comment]
> Cara mengunakan nya giamana?

https://www.youtube.com/watch?v=5aNbcQy0C0o&t=100s

**Comment by Bintangp02** [comment]
Trimakasih informasinya,, 
Apakah hanya bisa Dilakukan di leptop saya..?

**Comment by ariffb25** [comment]
typo? atau gmn? termux bisa, pc bisa

**Comment by Bintangp02** [comment]
Giamana agar kita menjadi owner bot file apa yang kita ubah??

**Comment by ariffb25** [comment]
maksud owner itu sendiri gmn? kan kalo ngerun, km la ownernya

```config.js``` tambah ownernya disini
```plugins/creator.js``` ganti command ```.owner``` nya disini

seengganya paham js dulu kalo bisa

**Comment by Bintangp02** [comment]
Cara menambah fitur gimana?? Dan Bagaimana cara mengubah Menu Bot??
Trimakasih..
