### ISSUE TITLE
Saya telah mendaftar api https://api.xteam.xyz/ Tapi verivikasi Nya belum terkirim di email saya

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#499]
Saya telah mendaftar api https://api.xteam.xyz/ Tapi verivikasi Nya belum terkirim di email saya..

**Comment by anshuljai** [comment]
contact xteam owner -_

**Comment by Bintangp02** [comment]
Di mana saya bisa mendapatkan kontak nya answer with details please me.
