### ISSUE TITLE
calc error

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#501]
TypeError: Cannot use 'in' operator to search for '56456546546-45645634643@g.us' in undefined

**Comment by Ftwrr** [comment]
lihat tidak ada yang peduli

**Comment by Ftwrr** [comment]
aghhh

**Comment by ariffb25** [comment]
https://github.com/Nurutomo/wabot-aq/commit/cb9742f9b8e74cfef0fc88d82c8cb29702d104a4
