### ISSUE TITLE
[HOW TO] add feature lewat whatsapp

### ISSUE THREAD

**Issue by FadliDarmawan** [Nurutomo/wabot-aq#502]
Tinggal kayak eval upload fitur lewat bot, males harus lewat terminal

**Comment by anshuljai** [comment]
use fs to write file through eval

**Comment by ariffb25** [comment]
```js
> let fs = require('fs')
let code = `let fetch = require('node-fetch')

let handler = async (m, { conn }) => {
 //
}
handler.help = ['']
handler.tags = ['']

handler.command = /^example$/i

module.exports = handler`

fs.writeFileSync('./plugins/example.js', code, function(err) {
if(err) return m.reply(`eror`)
else return m.reply('berhasil')
})
```

**Comment by FadliDarmawan** [comment]
> ```js
> > let fs = require('fs')
> let code = `let fetch = require('node-fetch')
> 
> let handler = async (m, { conn }) => {
>  //
> }
> handler.help = ['']
> handler.tags = ['']
> 
> handler.command = /^example$/i
> 
> module.exports = handler`
> 
> fs.writeFileSync('./plugins/example.js', code, function(err) {
> if(err) return m.reply(`eror`)
> else return m.reply('berhasil')
> })
> ```

Thx rif
