### ISSUE TITLE
(help)Wanna add space between in Commands

### ISSUE THREAD

**Issue by bilal-08** [Nurutomo/wabot-aq#505]
like `tebakgambar` is there 
i want to make it ``` tebak gambar```

**Comment by BochilGaming** [comment]
Change ```handler.command``` in file tebakgambar.js to
```handler.command = /^tebak ?gambar/i```

**Comment by bilal-08** [comment]
that's it ?!
Thnx

**Comment by ariffb25** [comment]
use 
```js
handler.customPrefix = /^.*tebak gambar$/i
```
coz ```handler.command``` can't add space T_T

**Comment by bilal-08** [comment]
> use
> 
> ```js
> handlers . customPrefix  =  / ^ . * guess the image $ / i
> ```
> 
> coz `handler.command` can't add space T_T

custom prefix......ehh so It will work with mulitple prefix?

**Comment by ariffb25** [comment]
> > use
> > ```js
> > handlers . customPrefix  =  / ^ . * guess the image $ / i
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > coz `handler.command` can't add space T_T
> 
> custom prefix......ehh so It will work with mulitple prefix?

![image](https://user-images.githubusercontent.com/76026450/124120127-95a0dc00-da9d-11eb-9e5a-797a9ccaf1b7.png)
test it yourself https://regexr.com/
