### ISSUE TITLE
Update app.json

### ISSUE THREAD

**Issue by bilal-08** [Nurutomo/wabot-aq#506]
Hey Can you able to add
changeable apikey
prefix
name of the bot
Mods/owner of the bot

following details to .env file?

if so then , add this to app.json so we can change the values later

```js
    "env": {
      "PREFIX": {
        "description": "Prefix of your bot"
      },
      "OWNER": {
        "description": "Add your number"
        "required": false
      },
    },
    "buildpacks": [
      {
        "url": "heroku/nodejs"
      },
      {
        "url": "https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git"
      },
  
      {
        "url": "https://github.com/steeple-org/heroku-buildpack-imagemagick.git"
      },
      {
        "url": "heroku/nodejs"
      }
    ]
  } ```

_ https://github.com/Nurutomo/wabot-aq/issues/476#issuecomment-871338843_

**Comment by bilal-08** [comment]
STFU

code Copy developer @TOXIC-DEVIL

**Comment by TOXIC-DEVIL** [comment]
> STFU
> 
> code Copy developer @TOXIC-DEVIL

Get Lost Fucker, I didn't do anything to you or your friends. If I am a Code Copier Then Just Check Your Profiles and respiratory, Did you done any project? All are forks and other ropo cloned 🤭🤫 And Also When I re-edited asena bot You stolen my codes then  calling me a code copier 😤 You stolen my codes and made those on your ropo and after some days you just deleted that ropo when I told 🥶🤧 Then Calling me such nonsense name fucker, world fucker 😣🥶

**Comment by bilal-08** [comment]
> > STFU
> > code Copy developer @TOXIC-DEVIL
> 
> Get Lost Fucker, I didn't do anything to you or your friends. If I am a Code Copier Then Just Check Your Profiles and respiratory, Did you done any project? All are forks and other ropo cloned 🤭🤫 And Also When I re-edited asena bot You stolen my codes then calling me a code copier 😤 You stolen my codes and made those on your ropo and after some days you just deleted that ropo when I told 🥶🤧 Then Calling me such nonsense name fucker, world fucker 😣🥶

First of all what did i Copied huh? do you have any proof?
You made whatsapp asena public 
and didnt forked
here 's your deleted Repo i admit that i use it but you copied it and don't even Mention the Original dev
https://github.com/TOXIC-DEVIL/WhatsAsenaPublic#What-Is-WhatsAsenaPublic



And Yh im not a copy dev , im still a student learning things and its my choice whether to maintain my Github profile or not

and are you a minor? huh?

**Comment by TOXIC-DEVIL** [comment]
> > > STFU
> > > code Copy developer @TOXIC-DEVIL
> > 
> > 
> > Get Lost Fucker, I didn't do anything to you or your friends. If I am a Code Copier Then Just Check Your Profiles and respiratory, Did you done any project? All are forks and other ropo cloned 🤭🤫 And Also When I re-edited asena bot You stolen my codes then calling me a code copier 😤 You stolen my codes and made those on your ropo and after some days you just deleted that ropo when I told 🥶🤧 Then Calling me such nonsense name fucker, world fucker 😣🥶
> 
> First of all what did i Copied huh? do you have any proof?
> You made whatsapp asena public
> and didnt forked
> here 's your deleted Repo i admit that i use it but you copied it and don't even Mention the Original dev
> https://github.com/TOXIC-DEVIL/WhatsAsenaPublic#What-Is-WhatsAsenaPublic
> 
> And Yh im not a copy dev , im still a student learning things and its my choice whether to maintain my Github profile or not
> 
> and are you a minor? huh?

No, I don't have any proof but You know that 😯🥶 lier. Yes, I have given credits to Phaticusthiccy!! He only developed it and author is Yusuf Usta I know I have already given credits to Phaticusthiccy ✅️ I don't have Dev's Github Id Or Anything so I didn't mention him 🥵🥶. Me too, its my choice to maintain, copy or clone not Yours? You only first started this issue 🤧 Changing Those Subjects 🥶

**Comment by ariffb25** [comment]
https://github.com/Nurutomo/wabot-aq/pull/510

dan Issue bukan tempat gelut 🤔

**Comment by BochilGaming** [comment]
> #510
> 
> dan Issue bukan tempat gelut

Wkwkwkkw

**Comment by bilal-08** [comment]
> > > > STFU
> > > > code Copy developer @TOXIC-DEVIL
> > > 
> > > 
> > > Get Lost Fucker, I didn't do anything to you or your friends. If I am a Code Copier Then Just Check Your Profiles and respiratory, Did you done any project? All are forks and other ropo cloned 🤭🤫 And Also When I re-edited asena bot You stolen my codes then calling me a code copier 😤 You stolen my codes and made those on your ropo and after some days you just deleted that ropo when I told 🥶🤧 Then Calling me such nonsense name fucker, world fucker 😣🥶
> > 
> > 
> > First of all what did i Copied huh? do you have any proof?
> > You made whatsapp asena public
> > and didnt forked
> > here 's your deleted Repo i admit that i use it but you copied it and don't even Mention the Original dev
> > https://github.com/TOXIC-DEVIL/WhatsAsenaPublic#What-Is-WhatsAsenaPublic
> > And Yh im not a copy dev , im still a student learning things and its my choice whether to maintain my Github profile or not
> > and are you a minor? huh?
> 
> No, I don't have any proof but You know that 😯🥶 lier. Yes, I have given credits to Phaticusthiccy!! He only developed it and author is Yusuf Usta I know I have already given credits to Phaticusthiccy ✅️ I don't have Dev's Github Id Or Anything so I didn't mention him 🥵🥶. Me too, its my choice to maintain, copy or clone not Yours? You only first started this issue 🤧 Changing Those Subjects 🥶 Also You have starred that ropo, If You think I was wrong then why you use my ropo? 🤧 Why You Starred? 🥴🥶🙄🤥

Coz Your repo popped up first and there is no mentioning to Phaticusthiccy so id knew arnd that time Ehhhhh this getting bigger 


chill out

**Comment by bilal-08** [comment]
> #510
> 
> and Issue is not a place to struggle 🤔

Well i personally want to delete this Issue lol

**Comment by TOXIC-DEVIL** [comment]
> > > > > STFU
> > > > > code Copy developer @TOXIC-DEVIL
> > > > 
> > > > 
> > > > Get Lost Fucker, I didn't do anything to you or your friends. If I am a Code Copier Then Just Check Your Profiles and respiratory, Did you done any project? All are forks and other ropo cloned 🤭🤫 And Also When I re-edited asena bot You stolen my codes then calling me a code copier 😤 You stolen my codes and made those on your ropo and after some days you just deleted that ropo when I told 🥶🤧 Then Calling me such nonsense name fucker, world fucker 😣🥶
> > > 
> > > 
> > > First of all what did i Copied huh? do you have any proof?
> > > You made whatsapp asena public
> > > and didnt forked
> > > here 's your deleted Repo i admit that i use it but you copied it and don't even Mention the Original dev
> > > https://github.com/TOXIC-DEVIL/WhatsAsenaPublic#What-Is-WhatsAsenaPublic
> > > And Yh im not a copy dev , im still a student learning things and its my choice whether to maintain my Github profile or not
> > > and are you a minor? huh?
> > 
> > 
> > No, I don't have any proof but You know that 😯🥶 lier. Yes, I have given credits to Phaticusthiccy!! He only developed it and author is Yusuf Usta I know I have already given credits to Phaticusthiccy ✅️ I don't have Dev's Github Id Or Anything so I didn't mention him 🥵🥶. Me too, its my choice to maintain, copy or clone not Yours? You only first started this issue 🤧 Changing Those Subjects 🥶 Also You have starred that ropo, If You think I was wrong then why you use my ropo? 🤧 Why You Starred? 🥴🥶🙄🤥
> 
> Coz Your repo popped up first and there is no mentioning to Phaticusthiccy so id knew arnd that time Ehhhhh this getting bigger
> 
> chill out

No there, I have tagged Thiccy their! 🙄

**Comment by bilal-08** [comment]
> > > > > > STFU
> > > > > > code Copy developer @TOXIC-DEVIL
> > > > > 
> > > > > 
> > > > > Get Lost Fucker, I didn't do anything to you or your friends. If I am a Code Copier Then Just Check Your Profiles and respiratory, Did you done any project? All are forks and other ropo cloned 🤭🤫 And Also When I re-edited asena bot You stolen my codes then calling me a code copier 😤 You stolen my codes and made those on your ropo and after some days you just deleted that ropo when I told 🥶🤧 Then Calling me such nonsense name fucker, world fucker 😣🥶
> > > > 
> > > > 
> > > > First of all what did i Copied huh? do you have any proof?
> > > > You made whatsapp asena public
> > > > and didnt forked
> > > > here 's your deleted Repo i admit that i use it but you copied it and don't even Mention the Original dev
> > > > https://github.com/TOXIC-DEVIL/WhatsAsenaPublic#What-Is-WhatsAsenaPublic
> > > > And Yh im not a copy dev , im still a student learning things and its my choice whether to maintain my Github profile or not
> > > > and are you a minor? huh?
> > > 
> > > 
> > > No, I don't have any proof but You know that 😯🥶 lier. Yes, I have given credits to Phaticusthiccy!! He only developed it and author is Yusuf Usta I know I have already given credits to Phaticusthiccy ✅️ I don't have Dev's Github Id Or Anything so I didn't mention him 🥵🥶. Me too, its my choice to maintain, copy or clone not Yours? You only first started this issue 🤧 Changing Those Subjects 🥶 Also You have starred that ropo, If You think I was wrong then why you use my ropo? 🤧 Why You Starred? 🥴🥶🙄🤥
> > 
> > 
> > Coz Your repo popped up first and there is no mentioning to Phaticusthiccy so id knew arnd that time Ehhhhh this getting bigger
> > chill out
> 
> No there, I have tagged Thiccy their! 🙄

oh okay
my bad
sorry
okay

**Comment by TOXIC-DEVIL** [comment]
> > > > > > > STFU
> > > > > > > code Copy developer @TOXIC-DEVIL
> > > > > > 
> > > > > > 
> > > > > > Get Lost Fucker, I didn't do anything to you or your friends. If I am a Code Copier Then Just Check Your Profiles and respiratory, Did you done any project? All are forks and other ropo cloned 🤭🤫 And Also When I re-edited asena bot You stolen my codes then calling me a code copier 😤 You stolen my codes and made those on your ropo and after some days you just deleted that ropo when I told 🥶🤧 Then Calling me such nonsense name fucker, world fucker 😣🥶
> > > > > 
> > > > > 
> > > > > First of all what did i Copied huh? do you have any proof?
> > > > > You made whatsapp asena public
> > > > > and didnt forked
> > > > > here 's your deleted Repo i admit that i use it but you copied it and don't even Mention the Original dev
> > > > > https://github.com/TOXIC-DEVIL/WhatsAsenaPublic#What-Is-WhatsAsenaPublic
> > > > > And Yh im not a copy dev , im still a student learning things and its my choice whether to maintain my Github profile or not
> > > > > and are you a minor? huh?
> > > > 
> > > > 
> > > > No, I don't have any proof but You know that 😯🥶 lier. Yes, I have given credits to Phaticusthiccy!! He only developed it and author is Yusuf Usta I know I have already given credits to Phaticusthiccy ✅️ I don't have Dev's Github Id Or Anything so I didn't mention him 🥵🥶. Me too, its my choice to maintain, copy or clone not Yours? You only first started this issue 🤧 Changing Those Subjects 🥶 Also You have starred that ropo, If You think I was wrong then why you use my ropo? 🤧 Why You Starred? 🥴🥶🙄🤥
> > > 
> > > 
> > > Coz Your repo popped up first and there is no mentioning to Phaticusthiccy so id knew arnd that time Ehhhhh this getting bigger
> > > chill out
> > 
> > 
> > No there, I have tagged Thiccy their! 🙄
> 
> oh okay
> my bad
> sorry
> okay

🙂

**Comment by TOXIC-DEVIL** [comment]
> > > > > > > STFU
> > > > > > > code Copy developer @TOXIC-DEVIL
> > > > > > 
> > > > > > 
> > > > > > Get Lost Fucker, I didn't do anything to you or your friends. If I am a Code Copier Then Just Check Your Profiles and respiratory, Did you done any project? All are forks and other ropo cloned 🤭🤫 And Also When I re-edited asena bot You stolen my codes then calling me a code copier 😤 You stolen my codes and made those on your ropo and after some days you just deleted that ropo when I told 🥶🤧 Then Calling me such nonsense name fucker, world fucker 😣🥶
> > > > > 
> > > > > 
> > > > > First of all what did i Copied huh? do you have any proof?
> > > > > You made whatsapp asena public
> > > > > and didnt forked
> > > > > here 's your deleted Repo i admit that i use it but you copied it and don't even Mention the Original dev
> > > > > https://github.com/TOXIC-DEVIL/WhatsAsenaPublic#What-Is-WhatsAsenaPublic
> > > > > And Yh im not a copy dev , im still a student learning things and its my choice whether to maintain my Github profile or not
> > > > > and are you a minor? huh?
> > > > 
> > > > 
> > > > No, I don't have any proof but You know that 😯🥶 lier. Yes, I have given credits to Phaticusthiccy!! He only developed it and author is Yusuf Usta I know I have already given credits to Phaticusthiccy ✅️ I don't have Dev's Github Id Or Anything so I didn't mention him 🥵🥶. Me too, its my choice to maintain, copy or clone not Yours? You only first started this issue 🤧 Changing Those Subjects 🥶 Also You have starred that ropo, If You think I was wrong then why you use my ropo? 🤧 Why You Starred? 🥴🥶🙄🤥
> > > 
> > > 
> > > Coz Your repo popped up first and there is no mentioning to Phaticusthiccy so id knew arnd that time Ehhhhh this getting bigger
> > > chill out
> > 
> > 
> > No there, I have tagged Thiccy their! 🙄
> 
> oh okay
> my bad
> sorry
> okay

Kindly Close this issue 🙂

**Comment by Bintangp02** [comment]
>:)
