### ISSUE TITLE
Cara mengubah Menu , Saya Mau Menambahkan Menu Di Bot Cara mengedit nya giamana??

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#507]
Saya ingin menambah Fitur,Tetapi Gimana Cara Mengubah tampilan Menu Bot??

**Comment by Ftwrr** [comment]
menu.js

**Comment by Bintangp02** [comment]
saya tidak dapat mengubah nya di situ saya mau taruh di premium..

**Comment by BochilGaming** [comment]
> saya tidak dapat mengubah nya di situ saya mau taruh di premium..

Maksutnya?

**Comment by Bintangp02** [comment]
> > saya tidak dapat mengubah nya di situ saya mau taruh di premium..
> 
> Maksutnya?

Saya ingin menambahkan menu di premium bagai mana cara menambah nya??

**Comment by jauhari21** [comment]
> > > saya tidak dapat mengubah nya di situ saya mau taruh di premium..
> > 
> > 
> > Maksutnya?
> 
> Saya ingin menambahkan menu di premium bagai mana cara menambah nya??

Ngelag otak gua

**Comment by FadliDarmawan** [comment]
> > > saya tidak dapat mengubah nya di situ saya mau taruh di premium..
> > 
> > Maksutnya?
> 
> Saya ingin menambahkan menu di premium bagai mana cara menambah nya??

Kalau nambahin menu premium
Bikin aja text biasa

let fetch = require('node-fetch')
let handler = async(m, { conn }) => {
    let menuprem = `
    Taruh menu di sini
    `.trim()
    conn.reply(m.chat, menuprem, m)

handler command = /^(menuprem)$/i

Tambahin handler sesuai kebutuhan....
