### ISSUE TITLE
Expired Join group

### ISSUE THREAD

**Issue by Users1233** [Nurutomo/wabot-aq#511]
Tambahin fitur expired misal ada yang mau add bot ke group 3 hari doang jadi #trial 3 jadi ketika udh 3 hari left group gitu kalau mau lebih dari 3 hari harus nyewa gitu

**Comment by Bintangp02** [comment]
> Tambahin fitur expired misal ada yang mau add bot ke group 3 hari doang jadi #trial 3 jadi ketika udh 3 hari left group gitu kalau mau lebih dari 3 hari harus nyewa gitu

>>>>>>>>>> Up
