### ISSUE TITLE
#ban #unban error

### ISSUE THREAD

**Issue by Users1233** [Nurutomo/wabot-aq#512]
fitur #ban #unban error

**Comment by BochilGaming** [comment]
> fitur #ban #unban error

Bisa lebih detail errornya?

**Comment by Users1233** [comment]
banned not definden @BochilGaming 

> > fitur #ban #unban error
> 
> Bisa lebih detail errornya?

**Comment by BochilGaming** [comment]
> banned not definden @BochilGaming
> 
> > > fitur #ban #unban error
> > 
> > 
> > Bisa lebih detail errornya?

You have screnshoot?

**Comment by ariffb25** [comment]
it's coz the user isn't registered
