### ISSUE TITLE
[how to] matiin anti troli

### ISSUE THREAD

**Issue by FadliDarmawan** [Nurutomo/wabot-aq#515]
Ya gw tau agak resiko

Tapi banyak jir bot bot fek reply ke katalog (troli) ga ngasih token jadi kedetek bug troli
Dan karena kedetek jadi ilang chat nya

Masalah nya clearchat nya sama stared message nya juga

**Comment by Ftwrr** [comment]
hapus _antitroli.js :v

**Comment by BochilGaming** [comment]
> hapus _antitroli.js :v

wkwkwk

**Comment by BochilGaming** [comment]
> > hapus _antitroli.js :v
> 
> wkwkwk.
 kasih aja 
```handler.disable = true```

**Comment by FadliDarmawan** [comment]
> > > hapus _antitroli.js :v
> > 
> > wkwkwk.
>  kasih aja 
> ```handler.disable = true```

Nice ingfo
