### ISSUE TITLE
Ini kenapa ?

### ISSUE THREAD

**Issue by Xnuvers007** [Nurutomo/wabot-aq#517]
![image](https://user-images.githubusercontent.com/62522733/124340864-6fd11f80-dbe2-11eb-8486-aee73080e770.png)

Ini Kenapa ? semenjak ditambahin lowdb jadi seperi ini

**Comment by BochilGaming** [comment]
> ![image](https://user-images.githubusercontent.com/62522733/124340864-6fd11f80-dbe2-11eb-8486-aee73080e770.png)
> 
> Ini Kenapa ? semenjak ditambahin lowdb jadi seperi ini

npm install

**Comment by Gchan1319** [comment]
> ![image](https://user-images.githubusercontent.com/62522733/124340864-6fd11f80-dbe2-11eb-8486-aee73080e770.png)
> 
> Ini Kenapa ? semenjak ditambahin lowdb jadi seperi ini

Npm install <nama module yang error>
