### ISSUE TITLE
List messages

### ISSUE THREAD

**Issue by FadliDarmawan** [Nurutomo/wabot-aq#522]
![20210704_142315.jpg](https://user-images.githubusercontent.com/79369935/124376933-7ee3ca80-dcd3-11eb-8297-324640feed1f.jpg)

Cara bikin menu/feature kayak gitu yang work dan bisa di pake

Ada yang tau?

**Comment by BochilGaming** [comment]
> ![20210704_142315.jpg](https://user-images.githubusercontent.com/79369935/124376933-7ee3ca80-dcd3-11eb-8297-324640feed1f.jpg)
> 
> Cara bikin menu/feature kayak gitu yang work dan bisa di pake
> 
> Ada yang tau?

emang whatsapp support itu?

**Comment by BochilGaming** [comment]
> > ![20210704_142315.jpg](https://user-images.githubusercontent.com/79369935/124376933-7ee3ca80-dcd3-11eb-8297-324640feed1f.jpg)
> > Cara bikin menu/feature kayak gitu yang work dan bisa di pake
> > Ada yang tau?
> 
> emang whatsapp support itu?, kalau pilih kayak 1, 2 bisa, tapi kalau kek gitu gk bisa keknya :v

**Comment by FadliDarmawan** [comment]
> > ![20210704_142315.jpg](https://user-images.githubusercontent.com/79369935/124376933-7ee3ca80-dcd3-11eb-8297-324640feed1f.jpg)
> > 
> > Cara bikin menu/feature kayak gitu yang work dan bisa di pake
> > 
> > Ada yang tau?
> 
> emang whatsapp support itu?, kalau pilih kayak 1, 2 atau teks itu mungkin. tapi entah kalau kayak gitu :v

>emang whatsapp support
Entah lah tadi bisa gw pencet pencet sama mainin

**Comment by BochilGaming** [comment]
> > > ![20210704_142315.jpg](https://user-images.githubusercontent.com/79369935/124376933-7ee3ca80-dcd3-11eb-8297-324640feed1f.jpg)
> > > Cara bikin menu/feature kayak gitu yang work dan bisa di pake
> > > Ada yang tau?
> > 
> > 
> > emang whatsapp support itu?, kalau pilih kayak 1, 2 atau teks itu mungkin. tapi entah kalau kayak gitu :v
> 
> > emang whatsapp support
> 
> Entah lah tadi bisa gw pencet pencet sama mainin

minta nomer nya :v

**Comment by Nobuyaki** [comment]
[list](https://github.com/adiwajshing/Baileys/pull/574#issue-683833590)

**Comment by lilnext01** [comment]
> [list](https://github.com/adiwajshing/Baileys/pull/574#issue-683833590)

How do you add?

**Comment by FadliDarmawan** [comment]
> [list](https://github.com/adiwajshing/Baileys/pull/574#issue-683833590) 

    ![Screenshot_20210708-211505_WhatsApp.jpg](https://user-images.githubusercontent.com/79369935/124937466-9dc6c180-e031-11eb-8e6f-daadc0b81c62.jpg)
??

**Comment by Nobuyaki** [comment]
> > [list](https://github.com/adiwajshing/Baileys/pull/574#issue-683833590)
> 
> ![Screenshot_20210708-211505_WhatsApp.jpg](https://user-images.githubusercontent.com/79369935/124937466-9dc6c180-e031-11eb-8e6f-daadc0b81c62.jpg)

Coba update baileys nya dulu

**Comment by FadliDarmawan** [comment]
> > [list](https://github.com/adiwajshing/Baileys/pull/574#issue-683833590) 
> 
>     ![Screenshot_20210708-211505_WhatsApp.jpg](https://user-images.githubusercontent.com/79369935/124937466-9dc6c180-e031-11eb-8e6f-daadc0b81c62.jpg)
> 
> ??

    Cara update baileys di wabot?

**Comment by FadliDarmawan** [comment]
> > > [list](https://github.com/adiwajshing/Baileys/pull/574#issue-683833590) 
> > 
> >     ![Screenshot_20210708-211505_WhatsApp.jpg](https://user-images.githubusercontent.com/79369935/124937466-9dc6c180-e031-11eb-8e6f-daadc0b81c62.jpg)
> > 
> > ??
> 
 Cara update baileys di wabot?
