### ISSUE TITLE
Database.json hilang 

### ISSUE THREAD

**Issue by FadliDarmawan** [Nurutomo/wabot-aq#526]
Database.json tiba tiba hilang, jadi EXP, Limit, Level user ilang :\

Entah di gw doang atau ada yang gitu juga...
(Pake Termux)

**Comment by jauhari21** [comment]
> Database.json tiba tiba hilang, jadi EXP, Limit, Level user ilang :\
> 
> Entah di gw doang atau ada yang gitu juga...
> (Pake Termux)

Wkwkwk gua juga tadi, untung ada backupan kemaren

**Comment by FadliDarmawan** [comment]
> > Database.json tiba tiba hilang, jadi EXP, Limit, Level user ilang :\
> > 
> > Entah di gw doang atau ada yang gitu juga...
> > (Pake Termux)
> 
> Wkwkwk gua juga tadi, untung ada backupan kemaren. Oh iya gua pake hosting bukan termux

Iy sih bisa di backup, cuma kadang sok males

**Comment by BochilGaming** [comment]
pas matiin botnya kalau udh ada tulisan 'Saving database...', nanti aman. (aku sih begitu)
