### ISSUE TITLE
Akun langsung di banned saat banyak user yang make anonymous chat

### ISSUE THREAD

**Issue by Rianfirnanda** [Nurutomo/wabot-aq#527]
Maaf OOT, Kenapa ya akun langsung di banned sama whatsapp saat user banyak yang make anonymous chat. Itu kira kira kenapa ya?
![Screenshot_20210705-185735](https://user-images.githubusercontent.com/69239761/124472505-69040180-ddc8-11eb-8fe9-774b48a5deed.png)

**Comment by jauhari21** [comment]
> Maaf OOT, Kenapa ya akun langsung di banned sama whatsapp saat user banyak yang make anonymous chat. Itu kira kira kenapa ya?
> ![Screenshot_20210705-185735](https://user-images.githubusercontent.com/69239761/124472505-69040180-ddc8-11eb-8fe9-774b48a5deed.png)

Bjir baru tau gua, setau gua kalo keseringan pake fiTur kick,add,promote, demote, yg dikick

**Comment by Rianfirnanda** [comment]
> > Maaf OOT, Kenapa ya akun langsung di banned sama whatsapp saat user banyak yang make anonymous chat. Itu kira kira kenapa ya?
> > ![Screenshot_20210705-185735](https://user-images.githubusercontent.com/69239761/124472505-69040180-ddc8-11eb-8fe9-774b48a5deed.png)
> 
> Bjir baru tau gua, setau gua kalo keseringan pake fiTur kick,add,promote, demote, yg dibanned

Entahlah bro gw juga gatau, udah 2 kali akun gw di banned karena yang make anonymous chat ratusan orang.dan juga gw pake rdp server singapura.

**Comment by syahrularranger** [comment]
> > > Maaf OOT, Kenapa ya akun langsung di banned sama whatsapp saat user banyak yang make anonymous chat. Itu kira kira kenapa ya?
> > > ![Screenshot_20210705-185735](https://user-images.githubusercontent.com/69239761/124472505-69040180-ddc8-11eb-8fe9-774b48a5deed.png)
> > 
> > 
> > Bjir baru tau gua, setau gua kalo keseringan pake fiTur kick,add,promote, demote, yg dibanned
> 
> Entahlah bro gw juga gatau, udah 2 kali akun gw di banned karena yang make anonymous chat ratusan orang.dan juga gw pake rdp server singapura.

Pakai Wa ori apa mod?

**Comment by ariffb25** [comment]
emang wkwk, coba pakein delay (jadi gaenak diuser nya juga sih karena ada jeda)

**Comment by BochilGaming** [comment]
gara gara spam banyak orang, dan orang yang kamu spam gk save nomor botnya. maybe?

**Comment by Rianfirnanda** [comment]
> gara gara spam banyak orang, dan orang yang kamu spam gk save nomor botnya. maybe?

Engga bro, gw ga pernah make broadcast/spam user

**Comment by BochilGaming** [comment]
> > gara gara spam banyak orang, dan orang yang kamu spam gk save nomor botnya. maybe?
> 
> Engga bro, gw ga pernah make broadcast/spam user

itu anonymus kalau banyak yang makek kan otomatis botmu spam

**Comment by syahrularranger** [comment]
> emang wkwk, coba pakein delay (jadi gaenak diuser nya juga sih karena ada jeda)

Pake setTimeuut yakan :v

**Comment by BochilGaming** [comment]
> > emang wkwk, coba pakein delay (jadi gaenak diuser nya juga sih karena ada jeda)
> 
> Pake setTimeuut yakan :v

 setTimeuut is not a function :v. wkwkkw

**Comment by ariffb25** [comment]
```js
const delay = time => new Promise(res => setTimeout(res, time))
```
.-.

**Comment by BochilGaming** [comment]
> Maaf OOT, Kenapa ya akun langsung di banned sama whatsapp saat user banyak yang make anonymous chat. Itu kira kira kenapa ya?
> ![Screenshot_20210705-185735](https://user-images.githubusercontent.com/69239761/124472505-69040180-ddc8-11eb-8fe9-774b48a5deed.png)

Klick dukungan aja terus isi teks nya contoh "Tolong unbanned nomor whatsapp saya (nomormu)", terus kasih foto itu ( foto kebanned ). klick kirim, klick "Ini tidak membantu saya". tunggu beberapa menit, nanti muncul popup, terus pilih email, dan kirim.
langkah terakhir tunggu balasan dari pihak whatsappnya

**Comment by Rianfirnanda** [comment]
> > Maaf OOT, Kenapa ya akun langsung di banned sama whatsapp saat user banyak yang make anonymous chat. Itu kira kira kenapa ya?
> > ![Screenshot_20210705-185735](https://user-images.githubusercontent.com/69239761/124472505-69040180-ddc8-11eb-8fe9-774b48a5deed.png)
> 
> Klick dukungan aja terus isi teks nya contoh "Tolong unbanned nomor whatsapp saya (nomormu)", terus kasih foto itu ( foto kebanned ). klick kirim, klick "Ini tidak membantu saya". tunggu beberapa menit, nanti muncul popup, terus pilih email, dan kirim.
> langkah terakhir tunggu balasan dari pihak whatsappnya

Udah sering gw kaya gini mah wkwk,pas di unban eh ga lama ke ban lagi hadeh..padahal pake wa business bukan gb wa/wa mod
