### ISSUE TITLE
[BUG] Closed connection...

### ISSUE THREAD

**Issue by lilnext01** [Nurutomo/wabot-aq#539]
![20210707_162704](https://user-images.githubusercontent.com/74841546/124817522-4e549880-df40-11eb-989f-b2a1f0e58f32.jpg)

How is it possible to fix this? Before it was not like this (My internet is not the problem)

**Comment by FadliDarmawan** [comment]
> ![20210707_162704](https://user-images.githubusercontent.com/74841546/124817522-4e549880-df40-11eb-989f-b2a1f0e58f32.jpg)
> 
> How is it possible to fix this? Before it was not like this (My internet is not the problem) 

no incoming chat, so it's like that

**Comment by anshuljai** [comment]
> ![20210707_162704](https://user-images.githubusercontent.com/74841546/124817522-4e549880-df40-11eb-989f-b2a1f0e58f32.jpg)
> 
> How is it possible to fix this? Before it was not like this (My internet is not the problem)

if there still a problem....rescan the bot number
