### ISSUE TITLE
Bikin auto reply tanpa prefix

### ISSUE THREAD

**Issue by Akbarsans** [Nurutomo/wabot-aq#54]
Bang request bikin auto reply tanpa prefix dong, ane nyoba utak atik malah yang kekirim ga habis habis, ga berenti berenti wkwk

**Comment by Nurutomo** [comment]
Autoreply gmn? Fakereply?

**Comment by ariffb25** [comment]
handler.customPrefix = /^(command nya sayang)$/i
handler.command = /(?:)/i

**Comment by Nurutomo** [comment]
```js
handler.customPrefix = /assalamualaikum/i
handler.command = new RegExp
````
