### ISSUE TITLE
apikay

### ISSUE THREAD

**Issue by github838** [Nurutomo/wabot-aq#541]
i dont get the apikay from x-team why????

**Comment by ariffb25** [comment]
https://api.xteam.xyz/register

**Comment by kaiyo6** [comment]
> https://api.xteam.xyz/register 

I registered but I don't get anything in the email

**Comment by bilal-08** [comment]
> > https://api.xteam.xyz/register
> 
> I registered but I don't get anything in the email

check spam folder

**Comment by github838** [comment]
Ok i get the APIKEY but look![image](https://user-images.githubusercontent.com/78624931/125182366-2aca7000-e216-11eb-90e3-fb906f888a92.jpeg)

**Comment by github838** [comment]
And this🙂💔💔![image](https://user-images.githubusercontent.com/78624931/125182376-3b7ae600-e216-11eb-937e-0400fba08000.jpeg)

I don't know what's the problem 
I pit the APIKEY in config.js
