### ISSUE TITLE
Bg tukar grouplist.js biar owner aja bisa liat, takut ketahuan grup keluarga :v

### ISSUE THREAD

**Issue by Adhwa9981** [Nurutomo/wabot-aq#544]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MrMeegoy** [comment]
`handler.owner = true`

**Comment by ariffb25** [comment]
ubah sendiri, udah dikasih tau sama @mrmeegoy
