### ISSUE TITLE
Heroku Bug

### ISSUE THREAD

**Issue by DevN2** [Nurutomo/wabot-aq#548]
kenapa waktu deploy ke heroku hanya muncul tampilan loading yang mutar saja? dan dipencet hanya keluar angka "12". tidak keluar QR code nya

**Comment by Anshuljai** [comment]
if you want qrcode


> http://yourappname/views

visit this page for qr

**Comment by DevN2** [comment]
> if you want qrcode
> 
> > http://yourappname/views
> 
> visit this page for qr

yes,it resolved, but when I scanned, it said "unable to scan the qr code, make sure you are on WhatsApp web and try again"

**Comment by Anshuljai** [comment]
> > if you want qrcode
> > > http://yourappname/views
> > 
> > 
> > visit this page for qr
> 
> yes,it resolved, but when I scanned, it said "unable to scan the qr code, make sure you are on WhatsApp web and try again"

if the problem is still there...first scan qr through termux then copy session file and upload it to github and rest you know what to be done

**Comment by DevN2** [comment]
> > > if you want qrcode
> > > > http://yourappname/views
> > > 
> > > 
> > > visit this page for qr
> > 
> > 
> > yes,it resolved, but when I scanned, it said "unable to scan the qr code, make sure you are on WhatsApp web and try again"
> 
> if the problem is still there...first scan qr through termux then copy session file and upload it to github and rest you know what to be done

where can i find the session file? is this the only way?

**Comment by Anshuljai** [comment]
> > > > if you want qrcode
> > > > > http://yourappname/views
> > > > 
> > > > 
> > > > visit this page for qr
> > > 
> > > 
> > > yes,it resolved, but when I scanned, it said "unable to scan the qr code, make sure you are on WhatsApp web and try again"
> > 
> > 
> > if the problem is still there...first scan qr through termux then copy session file and upload it to github and rest you know what to be done
> 
> where can i find the session file? is this the only way?

if you cant scan thorugh heroku url then thats the only way....and you can copy session from termux root folder and then upload it to your repi

**Comment by DevN2** [comment]
> > where can i find the session file? is this the only way?
> 
> if you cant scan thorugh heroku url then thats the only way....and you can copy session from termux root folder and then upload it to your repo

but the one on https://yourappname/views is just an ordinary QR image, not a QR from WhatsApp web, I've repeated several times and the QR code is the same

**Comment by Anshuljai** [comment]
> > > if you want qrcode
> > > > http://yourappname/views
> > > 
> > > 
> > > visit this page for qr
> > 
> > 
> > yes,it resolved, but when I scanned, it said "unable to scan the qr code, make sure
> if the problem is still there...first scan qr through termux then copy session file from termux and upload it to github and rest you know what to be done

follow this

**Comment by DevN2** [comment]
> > if the problem is still there...first scan qr through termux then copy session file from termux and upload it to github and rest you know what to be done
> 
> follow this

copy that. thanks for the suggestion
