### ISSUE TITLE
tambahkan status user yang menyebutkan kalau dia user biasa/premium

### ISSUE THREAD

**Issue by Rianfirnanda** [Nurutomo/wabot-aq#550]
<h3>
<p> xp : _*%totalexp*_  </p>
<p> limit  : *_%limit_* </p>
<p> Status user : %status </p>
</h3>

**Comment by ariffb25** [comment]
bikin bang ntar aku merge 😎👍

**Comment by Rianfirnanda** [comment]
> bikin bang ntar aku merge 😎👍

Bjir
