### ISSUE TITLE
Unsupport Mime

### ISSUE THREAD

**Issue by hardiantojek93** [Nurutomo/wabot-aq#555]
![Screenshot_2021-07-10-14-03-39-599_com microsoft rdc android](https://user-images.githubusercontent.com/71861395/125153672-032cc680-e188-11eb-8587-d496d4d196f8.jpg)

Sebenernya Ketika Saya MeReply Pesan media Dari Bot console Error Itu yg muncul tetapi jika saya MeReply media dri temen saya dan pesan saya status true(work)

**Comment by hardiantojek93** [comment]
Apakah ini dari baileys atau code saya sebelumnya code saya work sebelum upgrade baileys
Sy menggunakan baileys latest versi dri github lansung
Kalo ini dari baileys saya akan issues disana

**Comment by ariffb25** [comment]
log nya bukan wabot-aq :/

**Comment by hardiantojek93** [comment]
> log nya bukan wabot-aq :/

bukan sc bot wabot-aq :/ soalnya saya rakit sesuai kemauan saya dan Script ini menggunakan simple.js modif dru nurutomo/wabot-aq

**Comment by BochilGaming** [comment]
> ![Screenshot_2021-07-10-14-03-39-599_com microsoft rdc android](https://user-images.githubusercontent.com/71861395/125153672-032cc680-e188-11eb-8587-d496d4d196f8.jpg)
> 
> Sebenernya Ketika Saya MeReply Pesan media Dari Bot console Error Itu yg muncul tetapi jika saya MeReply media dri temen saya dan pesan saya status true(work)

restat botnya ( matikan dan hidupkan ), itu akan membuat bot anda bekerja seperti semula

**Comment by hardiantojek93** [comment]
> > ![Screenshot_2021-07-10-14-03-39-599_com microsoft rdc android](https://user-images.githubusercontent.com/71861395/125153672-032cc680-e188-11eb-8587-d496d4d196f8.jpg)
> > Sebenernya Ketika Saya MeReply Pesan media Dari Bot console Error Itu yg muncul tetapi jika saya MeReply media dri temen saya dan pesan saya status true(work)
> 
> restat botnya ( matikan dan hidupkan ), itu akan membuat bot anda bekerja seperti semula

saya bahkan sudah restart beberapa pulu kali tetap sama tetapi saya coba mendevploy nya ke heroku console log error tetap ada. bedanya send media berhasil tetapi console log tetap sama
