### ISSUE TITLE
Please Help 😟

### ISSUE THREAD

**Issue by TOXIC-DEVIL** [Nurutomo/wabot-aq#559]
Any One Please Tell How to deploy wabot -aq on heroku 🙂

**Comment by Anshuljai** [comment]
where are you stuck???

**Comment by TOXIC-DEVIL** [comment]
> where are you stuck???

Procfile and balance

**Comment by Anshuljai** [comment]
you mean dyno hours???

**Comment by TOXIC-DEVIL** [comment]
> you mean dyno hours??? and use uptimerobot.com for pinging heroku dyno

May Be, I'm just starting I have only set up procfile for heroku 😔 Balance I don't know so Please Help

**Comment by Anshuljai** [comment]
first connect github then deploy then add buildpack

https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest

https://github.com/DuckyTeam/heroku-buildpack-imagemagick

then turn on dyno

**Comment by TOXIC-DEVIL** [comment]
> first connect github then deploy then add buildpack
> 
> https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest
> 
> https://github.com/DuckyTeam/heroku-buildpack-imagemagick
> 
> then turn on dyno

😳😳 let me Contact you? Can you give your Instagram id (name). I will msg you

**Comment by TOXIC-DEVIL** [comment]
> first connect github then deploy then add buildpack
> 
> https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest
> 
> https://github.com/DuckyTeam/heroku-buildpack-imagemagick
> 
> then turn on dyno

How do I scan qr?

**Comment by Ftwrr** [comment]
> > first connect github then deploy then add buildpack
> > https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest
> > https://github.com/DuckyTeam/heroku-buildpack-imagemagick
> > then turn on dyno
> 
> How do I scan qr?


session.data.json

**Comment by Anshuljai** [comment]
thats enough info

**Comment by TOXIC-DEVIL** [comment]
> > > first connect github then deploy then add buildpack
> > > https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest
> > > https://github.com/DuckyTeam/heroku-buildpack-imagemagick
> > > then turn on dyno
> > 
> > 
> > How do I scan qr?
> 
> session.data.json

How can I set up session.data.json 😟

**Comment by TOXIC-DEVIL** [comment]
> thats enough info

😟😒

**Comment by Ftwrr** [comment]
> > > > first connect github then deploy then add buildpack
> > > > https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest
> > > > https://github.com/DuckyTeam/heroku-buildpack-imagemagick
> > > > then turn on dyno
> > > 
> > > 
> > > How do I scan qr?
> > 
> > 
> > session.data.json
> 
> How can I set up session.data.json 😟

just copy

**Comment by TOXIC-DEVIL** [comment]
> > > > > first connect github then deploy then add buildpack
> > > > > https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest
> > > > > https://github.com/DuckyTeam/heroku-buildpack-imagemagick
> > > > > then turn on dyno
> > > > 
> > > > 
> > > > How do I scan qr?
> > > 
> > > 
> > > session.data.json
> > 
> > 
> > How can I set up session.data.json 😟
> 
> just copy

What I want to copy :P
