### ISSUE TITLE
[Feature request] Sticker tag

### ISSUE THREAD

**Issue by Mayonnaise53** [Nurutomo/wabot-aq#562]
a feature that adds user jid into sticker like
i Use #stickertag @mention [tag a sticker]
And that sticker will add user jid whenever someone use that Sticker it would ping the user

**Comment by Anshuljai** [comment]
> conn.sendMessage(m.chat, stiker, MessageType.sticker, {
              contextInfo: { 
                     mentionedJid: user
               }
          })



in this user should be you want to mention
