### ISSUE TITLE
stickerwm

### ISSUE THREAD

**Issue by github838** [Nurutomo/wabot-aq#563]
I wnat stickerwm the wm.js just for take sticker when i use it in imgae come error ![image](https://user-images.githubusercontent.com/78624931/125182497-1d61b580-e217-11eb-8a55-d8e86dff9dc6.jpeg)
i wnat image to sticker and packname|author 
like #stickerwm me|🕊

**Comment by FadliDarmawan** [comment]
> I wnat stickerwm the wm.js just for take sticker when i use it in imgae come error ![image](https://user-images.githubusercontent.com/78624931/125182497-1d61b580-e217-11eb-8a55-d8e86dff9dc6.jpeg)
> i wnat image to sticker and packname|author 
> like #stickerwm me|🕊

Try: reply the photo, and then #stickerwm

Uhm... honestly i dont know the problem

**Comment by ariffb25** [comment]
https://github.com/Nurutomo/wabot-aq/blob/3359c69d9cf5d405e41057c4576809dc733b2082/plugins/wm.js#L9

only sticker :/

**Comment by github838** [comment]
Works but without packname|author > > I wnat stickerwm the wm.js just for take sticker when i use it in imgae come error ![image](https://user-images.githubusercontent.com/78624931/125182497-1d61b580-e217-11eb-8a55-d8e86dff9dc6.jpeg)
> > i wnat image to sticker and packname|author 
> > like #stickerwm me|🕊
> 
> Try: reply the photo, and then #stickerwm
> 
> Uhm... honestly i dont know the problem

**Comment by github838** [comment]
> https://github.com/Nurutomo/wabot-aq/blob/3359c69d9cf5d405e41057c4576809dc733b2082/plugins/wm.js#L9
> 
> 
> 
> only sticker :/

I know I said i wnat to images

**Comment by Anshuljai** [comment]
> > https://github.com/Nurutomo/wabot-aq/blob/3359c69d9cf5d405e41057c4576809dc733b2082/plugins/wm.js#L9
> > 
> > only sticker :/
> 
> I know I said i wnat to images

use sticker.js then use wm :v

**Comment by github838** [comment]
> > > https://github.com/Nurutomo/wabot-aq/blob/3359c69d9cf5d405e41057c4576809dc733b2082/plugins/wm.js#L9
> 
> > > 
> 
> > > only sticker :/
> 
> > 
> 
> > I know I said i wnat to images
> 
> 
> 
> use sticker.js then use wm :v 

It's complicated
I can't get stickerwm 🙂🙂🙂
