### ISSUE TITLE
no command

### ISSUE THREAD

**Issue by Users1233** [Nurutomo/wabot-aq#564]
Jadi kalau user gunain bot tapi command yang dipake ga ada di bot bot nya bliang Mohon maaf fitur tidak ada di bot

**Comment by lilnext01** [comment]
let` handler = (m, { usedPrefix, command }) => {
let name = conn.getName(m.sender)
 m.reply(`
Desculpe *${name}*,
O comando *'${m.text}'*
Não está listado no *${usedPrefix}menu*
`.trim())
}
handler.command = new RegExp

module.exports = handler

**Comment by Users1233** [comment]
> let` handler = (m, { usedPrefix, command }) => { let name = conn.getName(m.sender) m.reply(`
> Desculpe _${name}_,
> O comando _'${m.text}'_
> Não está listado no _${usedPrefix}menu_
> `.trim())
> }
> handler.command = new RegExp
> 
> module.exports = handler

Malah ngespam semua command ga bisa dipake :v

**Comment by lilnext01** [comment]
> Malah ngespam semua command ga bisa dipake :v

Use customprefix 
*handler.customPrefix = /example|example2/*
