### ISSUE TITLE
CARA GANTI ISI !help

### ISSUE THREAD

**Issue by Geruays** [Nurutomo/wabot-aq#567]
Cara Gantinya Gimana Bwang

**Comment by Nobuyaki** [comment]
> Cara Gantinya Gimana Bwang
#setmenu

**Comment by Ftwrr** [comment]
menu.js

**Comment by Geruays** [comment]
> > Cara Gantinya Gimana Bwang
> 
> #setmenu

Than

**Comment by FadliDarmawan** [comment]
>>> Cara Gantinya Gimana Bwang
>> menu.js
> than?
Diedit sesuka hati
