### ISSUE TITLE
Bagaimana cara nya mengaktifkan enable welcome lewat owner

### ISSUE THREAD

**Issue by prioprastyo** [Nurutomo/wabot-aq#573]
![IMG_20210712_215353](https://user-images.githubusercontent.com/74877180/125309107-ad107c80-e35b-11eb-95b2-ffa82f3b1d38.jpg)
Gimana ngaturnya ngab?, Dibagian mana?

**Comment by ariffb25** [comment]
```enable.js```

**Comment by FadliDarmawan** [comment]
> ![IMG_20210712_215353](https://user-images.githubusercontent.com/74877180/125309107-ad107c80-e35b-11eb-95b2-ffa82f3b1d38.jpg)
> Gimana ngaturnya ngab?, Dibagian mana?

> `enable.js`

handler.admin = false ?

**Comment by ilhamimut** [comment]
> > ![IMG_20210712_215353](https://user-images.githubusercontent.com/74877180/125309107-ad107c80-e35b-11eb-95b2-ffa82f3b1d38.jpg)
> > Gimana ngaturnya ngab?, Dibagian mana?
> 
> > `enable.js`
> 
> handler.admin = false ?

Betul, dicoba dulu
