### ISSUE TITLE
[NEW FEATURE] Brainly image suport

### ISSUE THREAD

**Issue by lilnext01** [Nurutomo/wabot-aq#574]
kita sudah memiliki Brainly, kan? tetapi fitur ini hanya berguna dalam pesan teks. Dimungkinkan juga untuk menambahkan sumber daya di brainly dengan gambar, seperti yang ada di Aplikasi? 
contoh: seseorang mengirim gambar dengan pertanyaan, dan dalam keterangan .brainly Saya pikir, ada fitur itu. tunggu, di mana dia mengidentifikasi anime dengan gambar, jadi saya juga berpikir apakah mungkin untuk melakukannya di brainly... 
Terima kasih!

**Comment by ariffb25** [comment]
brainly buat pelajaran, sedangkan pencarian anime berdasarkan gambar bisa menggunakan ```.wait```

**Comment by FadliDarmawan** [comment]
> kita sudah memiliki Brainly, kan? tetapi fitur ini hanya berguna dalam pesan teks. Dimungkinkan juga untuk menambahkan sumber daya di brainly dengan gambar, seperti yang ada di Aplikasi?
> contoh: seseorang mengirim gambar dengan pertanyaan, dan dalam keterangan .brainly Saya pikir, ada fitur itu. tunggu, di mana dia mengidentifikasi anime dengan gambar, jadi saya juga berpikir apakah mungkin untuk melakukannya di brainly...
> Terima kasih!

google lens api? hmm
