### ISSUE TITLE
Cara Agar Pesan Dari Whatsapp Tidak Tampil Di termux??

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#575]
Delivery: saya sangat terbatas ruang penyimpanan apakah ada yang bisa membantu saya??

**Comment by Nobuyaki** [comment]
> Delivery: saya sangat terbatas ruang penyimpanan apakah ada yang bisa membantu saya??

Hapus console.log nya [Print.js](https://github.com/Nurutomo/wabot-aq/blob/master/lib/print.js)

**Comment by Bintangp02** [comment]
> > Delivery: saya sangat terbatas ruang penyimpanan apakah ada yang bisa membantu saya??
> 
> Hapus console.log nya [Print.js](https://github.com/Nurutomo/wabot-aq/blob/master/lib/print.js)

Makasih saya akan coba itu nanti

**Comment by Bintangp02** [comment]
> > Delivery: saya sangat terbatas ruang penyimpanan apakah ada yang bisa membantu saya??
> 
> Hapus console.log nya [Print.js](https://github.com/Nurutomo/wabot-aq/blob/master/lib/print.js)

problem: Apakah anda mengetahui letak cache bot ??

**Comment by Users1233** [comment]
> > > Delivery: saya sangat terbatas ruang penyimpanan apakah ada yang bisa membantu saya??
> > 
> > 
> > Hapus console.log nya [Print.js](https://github.com/Nurutomo/wabot-aq/blob/master/lib/print.js)
> 
> problem: Apakah anda mengetahui letak cache bot ??

kalo gw sih hapusnya `Win +R terus isi %temp% terus hapus semua file yang ada kalo keluar error klik skip ... gitu doang sih :v`

**Comment by Users1233** [comment]
- [ ]

**Comment by Users1233** [comment]
- [ ] hmmm

**Comment by Bintangp02** [comment]
> > > > Delivery: saya sangat terbatas ruang penyimpanan apakah ada yang bisa membantu saya??
> > > 
> > > 
> > > Hapus console.log nya [Print.js](https://github.com/Nurutomo/wabot-aq/blob/master/lib/print.js)
> > 
> > 
> > problem: Apakah anda mengetahui letak cache bot ??
> 
> kalo gw sih hapusnya `Win +R terus isi %temp% terus hapus semua file yang ada kalo keluar error klik skip ... gitu doang sih :v`

Bagaimana cara yang bisa saya lakukan saya pemula..
