### ISSUE TITLE
ig.js

### ISSUE THREAD

**Issue by github838** [Nurutomo/wabot-aq#581]
![image](https://user-images.githubusercontent.com/78624931/125774008-7b298ecc-108a-48d9-847c-be992060c0af.jpeg)
🙂🙂🙂🙂

**Comment by Bintangp02** [comment]
🤔

**Comment by github838** [comment]
> > ![image](https://user-images.githubusercontent.com/78624931/125774008-7b298ecc-108a-48d9-847c-be992060c0af.jpeg)
> 
> > 🙂🙂🙂🙂
> 
> 
> 
> 
> 
> >Saya Juga Sama:)

Jadi apa solusinya /:

**Comment by FadliDarmawan** [comment]
> ![image](https://user-images.githubusercontent.com/78624931/125774008-7b298ecc-108a-48d9-847c-be992060c0af.jpeg)
> 🙂🙂🙂🙂

Dari api nya kek nya
