### ISSUE TITLE
cara agar stiker pikachu menjadi img/gambar?

### ISSUE THREAD

**Issue by ilhamimut** [Nurutomo/wabot-aq#582]
assalamualaikum.

mau tanya nih cara agar sticker di pikachu.js bisa langsung ke bentuk img/gambar (bukan sticker) gimana ya?

file : plugins\pikachu.js

**Comment by syahrularranger** [comment]
Wa'aalaikum salam

Ubah bagian

`conn.sendMessage(m.chat, stiker, MessageType.sticker, {
    quoted: m
  })`

Menjadi

`conn.sendFile(m.chat, json.link, 'img.jpg', '', m)`

**Comment by ilhamimut** [comment]
> Wa'aalaikum salam
> 
> Ubah bagian
> 
> ```js
> conn.sendMessage(m.chat, stiker, MessageType.sticker, {
>     quoted: m
>   })
> ```
> 
> Menjadi
> 
> ```js
> conn.sendFile(m.chat, json.link, 'img.jpg', '', m)
> ```

terimakasih, work 100% 👍
