### ISSUE TITLE
Qr code error

### ISSUE THREAD

**Issue by fazilvk786** [Nurutomo/wabot-aq#584]
In heroku not getting proper qr code.

**Comment by syahrularranger** [comment]
You can scan QR code first in terminal cmd or termux.. then you will got a filename 'session.data.json'

Copy file/upload a file to heroku/github

**Comment by fazilvk786** [comment]
> You can scan QR code first in terminal cmd or termux.. then you will got a filename 'session.data.json'
> 
> Copy file/upload a file to heroku/github

How  please explain
