### ISSUE TITLE
fitur telpon bot = auto block

### ISSUE THREAD

**Issue by NugrahaMP** [Nurutomo/wabot-aq#585]
bang, cara hapus fitur telpon auto block gimana? soalnya takut klo misalnya ada keluarga yg nelpon abistu diblock sm bot nya, bisa" dimarahin. itu aja sih, semoga dibales

**Comment by syahrularranger** [comment]
@ariffb25 keknya musti ditambahin ke opts dan enable juga

**Comment by ariffb25** [comment]
> bang, cara hapus fitur telpon auto block gimana? soalnya takut klo misalnya ada keluarga yg nelpon abistu diblock sm bot nya, bisa" dimarahin. itu aja sih, semoga dibales

https://github.com/ariffb25/stikerinbot :v

**Comment by syahrularranger** [comment]
> > bang, cara hapus fitur telpon auto block gimana? soalnya takut klo misalnya ada keluarga yg nelpon abistu diblock sm bot nya, bisa" dimarahin. itu aja sih, semoga dibales
> 
> https://github.com/ariffb25/stikerinbot :v tinggal ketik .off anticall

Bjir ada ya trnyata

**Comment by NugrahaMP** [comment]
> > bang, cara hapus fitur telpon auto block gimana? soalnya takut klo misalnya ada keluarga yg nelpon abistu diblock sm bot nya, bisa" dimarahin. itu aja sih, semoga dibales
> 
> https://github.com/ariffb25/stikerinbot :v tinggal ketik .off anticall
brrti gw tinggal pake itu, dan pas udh selesai install segala macem, gw ketik .off anticall ya bang?
