### ISSUE TITLE
help: #tovn tidak bisa di play

### ISSUE THREAD

**Issue by ilhamimut** [Nurutomo/wabot-aq#590]
assalamualaikum.

ketika saya mereply/quote file audio, hasil vn-nya tidak bisa diplay, mohon solusinya untuk memperbaikinya

file name : plugins/toptt.js

original sc :

const { toPTT } = require('../lib/converter')
const { MessageType } = require('@adiwajshing/baileys')

let handler = async (m, { conn, usedPrefix, command }) => {
  let q = m.quoted ? m.quoted : m
  let mime = (m.quoted ? m.quoted : m.msg).mimetype || ''
  if (!/video|audio/.test(mime)) throw `Balas audio yang ingin diubah ke voice note dengan caption *${usedPrefix + command}*`
  let media = await q.download()
  let audio = await toPTT(media, 'mp4')
  conn.sendMessage(m.chat, audio, MessageType.audio, {
    quoted: m,
    ptt: true
  })
}
handler.help = ['tovn']
handler.tags = ['audio']

handler.command = /^to(vn|(ptt)?)$/i

module.exports = handler

**Comment by Ftwrr** [comment]
coba pake ini
```
conn.sendFile(m.chat, vn, 'yamete.opus', null, m, true, {
  type: 'audioMessage', // paksa tanpa convert di ffmpeg
  ptt: true // true diatas ga work, sebab dipaksa tanpa convert ;v
})
```

**Comment by ilhamimut** [comment]
> coba pake ini
> 
> ```
> conn.sendFile(m.chat, audio, 'yfsdfdsfs.mp3', null, m, true, {
>   type: 'audioMessage', // paksa tanpa convert di ffmpeg
>   ptt: true // true diatas ga work, sebab dipaksa tanpa convert ;v
> })
> ```

terimakasih gan, work it 👍
