### ISSUE TITLE
#delcmd ga fungsi

### ISSUE THREAD

**Issue by FadliDarmawan** [Nurutomo/wabot-aq#591]
Pas #delcmd sticker ga bisa
+
Cara hapus semua cmd sticker

**Comment by BochilGaming** [comment]
> Pas #delcmd sticker ga bisa
> +
> Cara hapus semua cmd sticker

ketik di whatsapp ```=> delete global.db.data.sticker```

**Comment by FadliDarmawan** [comment]
> > Pas #delcmd sticker ga bisa
> > +
> > Cara hapus semua cmd sticker
> 
> ketik di whatsapp ```=> delete global.db.data.sticker```

![20210719_145043.jpg](https://user-images.githubusercontent.com/79369935/126123665-294d4a4f-eaa7-4653-ae11-1e7ee48dfc55.jpg) kayak gini?

**Comment by BochilGaming** [comment]
> > > Pas #delcmd sticker ga bisa
> > > +
> > > Cara hapus semua cmd sticker
> > 
> > 
> > ketik di whatsapp `=> delete global.db.data.sticker`
> 
> ![20210719_145043.jpg](https://user-images.githubusercontent.com/79369935/126123665-294d4a4f-eaa7-4653-ae11-1e7ee48dfc55.jpg) kayak gini?

Kamu belum pakek sc nuru yang terbaru, coba ketik ini di whatsapp
```=> delete global.DATABASE._data.sticker```
