### ISSUE TITLE
send gambar dari file local/pc

### ISSUE THREAD

**Issue by ilhamimut** [Nurutomo/wabot-aq#592]
assalamualaikum.

bagaimana ya cara send gambar dari file local?
misalkan letak filenya di folder d:\datagambar\gambar1.jpg

menggunakan perintah #sendimglocal1

**Comment by FebbAdityaN** [comment]
const fs = require('fs')

conn.sendMessage(m.chat, fs.readFileSync("./pathnya"), "imageMessage")

**Comment by ariffb25** [comment]
```js
let fs = require('fs')

await conn.sendFile(m.chat, fs.readFileSync('./src/image.png'), 'ini caption', m, 0, { thumbnail: Buffer.alloc(0) })
```

**Comment by ilhamimut** [comment]
> ```js
> let fs = require('fs')
> 
> await conn.sendFile(m.chat, fs.readFileSync('./src/image.png'), 'ini caption', m, 0, { thumbnail: Buffer.alloc(0) })
> ```

jika alamat file localnya di jadikan pickrandom bisa gak bang?
kayak di bucin.js

**Comment by ilhamimut** [comment]
thanks gan, work 👍
