### ISSUE TITLE
setbotpp tidak bisa digunakan

### ISSUE THREAD

**Issue by ilhamimut** [Nurutomo/wabot-aq#605]
assalamualaikum

untuk fitur setbotpp.js tolong diperbaiki lagi ya, karena fitur tersebut tidak berfungsi

terimakasih

**Comment by Ftwrr** [comment]
error nya mana?

**Comment by ilhamimut** [comment]
> error nya mana?

Gak bisa ubah foto profil bot, consolenya juga gk nampilin error
