### ISSUE TITLE
Username & password github? 

### ISSUE THREAD

**Issue by Kyluesky** [Nurutomo/wabot-aq#606]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Username & password github?

**Comment by Kyluesky** [comment]
Username & password github?

**Comment by rescenic** [comment]
git clone repo ini jangan pake ssh, tapi https.
