### ISSUE TITLE
Tomp3 is occurring error

### ISSUE THREAD

**Issue by fazilvk786** [Nurutomo/wabot-aq#612]
Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs: [
    '-y',
    '-i',
    '/workspace/tmp/1626848929119.mp4',
    '-vn',
    '-ac',
    '2',
    '-b:a',
    '128k',
    '-ar',
    '44100',
    '-f',
    'mp3',
    '/workspace/tmp/1626848929119.mp4.mp3'
  ]
}

**Comment by BochilGaming** [comment]
> Error: spawn ffmpeg ENOENT
> at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
> at onErrorNT (node:internal/child_process:480:16)
> at processTicksAndRejections (node:internal/process/task_queues:83:21) {
> errno: -2,
> code: 'ENOENT',
> syscall: 'spawn ffmpeg',
> path: 'ffmpeg',
> spawnargs: [
> '-y',
> '-i',
> '/workspace/tmp/1626848929119.mp4',
> '-vn',
> '-ac',
> '2',
> '-b:a',
> '128k',
> '-ar',
> '44100',
> '-f',
> 'mp3',
> '/workspace/tmp/1626848929119.mp4.mp3'
> ]
> }

pkg install ffmpeg -y atau apt install ffmpeg

**Comment by fazilvk786** [comment]
> > Error: spawn ffmpeg ENOENT
> > at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
> > at onErrorNT (node:internal/child_process:480:16)
> > at processTicksAndRejections (node:internal/process/task_queues:83:21) {
> > errno: -2,
> > code: 'ENOENT',
> > syscall: 'spawn ffmpeg',
> > path: 'ffmpeg',
> > spawnargs: [
> > '-y',
> > '-i',
> > '/workspace/tmp/1626848929119.mp4',
> > '-vn',
> > '-ac',
> > '2',
> > '-b:a',
> > '128k',
> > '-ar',
> > '44100',
> > '-f',
> > 'mp3',
> > '/workspace/tmp/1626848929119.mp4.mp3'
> > ]
> > }
> 
> pkg install ffmpeg -y atau apt install ffmpeg -y

Not working
