### ISSUE TITLE
Help ❗️

### ISSUE THREAD

**Issue by TOXIC-DEVIL** [Nurutomo/wabot-aq#613]
How can I get session.data.json :-

{
	"clientID": "?!",
	"serverToken": "?!",
	"clientToken": "?!",
	"encKey": "?!",
	"macKey": "?!"
}

**Comment by syahrularranger** [comment]
Scan new QR Code.. then  you will get a file

**Comment by TOXIC-DEVIL** [comment]
> Scan new QR Code.. then you will get a file

Yes, I scan(ed) but I didn't get anything :/

**Comment by TOXIC-DEVIL** [comment]
Let me try once again wait.

**Comment by TOXIC-DEVIL** [comment]
No, Its only showing :-

[ false, false, false, false, false, false ]
WARN [2021-07-21 13:47:00.542 +0000] (22172): Please install ffmpeg for sending videos (pkg install ffmpeg)
    class: "Baileys"
WARN [2021-07-21 13:47:00.545 +0000] (22172): Stickers may not work without imagemagick if libwebp on ffmpeg doesnt isntalled (pkg install imagemagick)
    class: "Baileys"
INFO [2021-07-21 13:47:00.546 +0000] (22172): Quick Test Done
    class: "Baileys"
INFO [2021-07-21 13:47:01.797 +0000] (22172): connected to WhatsApp Web server, authenticating via takeover
    class: "Baileys"

**Comment by ilhamimut** [comment]
> No, Its only showing :-
> 
> [ false, false, false, false, false, false ]
> WARN [2021-07-21 13:47:00.542 +0000] (22172): Please install ffmpeg for sending videos (pkg install ffmpeg)
> class: "Baileys"
> WARN [2021-07-21 13:47:00.545 +0000] (22172): Stickers may not work without imagemagick if libwebp on ffmpeg doesnt isntalled (pkg install imagemagick)
> class: "Baileys"
> INFO [2021-07-21 13:47:00.546 +0000] (22172): Quick Test Done
> class: "Baileys"
> INFO [2021-07-21 13:47:01.797 +0000] (22172): connected to WhatsApp Web server, authenticating via takeover
> class: "Baileys"

Install ffmpeg, imagemagick dan pasang path env udah?
Dan habis itu coba keluar bailyes di whatsapp dan file senssion data.json dihapus

**Comment by TOXIC-DEVIL** [comment]
> > No, Its only showing :-
> > [ false, false, false, false, false, false ]
> > WARN [2021-07-21 13:47:00.542 +0000] (22172): Please install ffmpeg for sending videos (pkg install ffmpeg)
> > class: "Baileys"
> > WARN [2021-07-21 13:47:00.545 +0000] (22172): Stickers may not work without imagemagick if libwebp on ffmpeg doesnt isntalled (pkg install imagemagick)
> > class: "Baileys"
> > INFO [2021-07-21 13:47:00.546 +0000] (22172): Quick Test Done
> > class: "Baileys"
> > INFO [2021-07-21 13:47:01.797 +0000] (22172): connected to WhatsApp Web server, authenticating via takeover
> > class: "Baileys"
> 
> Have you installed ffmpeg, imagemagick and installed the env path?
> And after that, try to exit bailyes on whatsapp and the senssion data.json file is deleted

No, I am just trying to get session.data.json :|

**Comment by TOXIC-DEVIL** [comment]
> > No, Its only showing :-
> > [ false, false, false, false, false, false ]
> > WARN [2021-07-21 13:47:00.542 +0000] (22172): Please install ffmpeg for sending videos (pkg install ffmpeg)
> > class: "Baileys"
> > WARN [2021-07-21 13:47:00.545 +0000] (22172): Stickers may not work without imagemagick if libwebp on ffmpeg doesnt isntalled (pkg install imagemagick)
> > class: "Baileys"
> > INFO [2021-07-21 13:47:00.546 +0000] (22172): Quick Test Done
> > class: "Baileys"
> > INFO [2021-07-21 13:47:01.797 +0000] (22172): connected to WhatsApp Web server, authenticating via takeover
> > class: "Baileys"
> 
> Have you installed ffmpeg, imagemagick and installed the env path?
> And after that, try to exit bailyes on whatsapp and the senssion data.json file is deleted

ENV path? You mean to change whole handler to env process.

**Comment by ilhamimut** [comment]
> > > No, Its only showing :-
> > > [ false, false, false, false, false, false ]
> > > WARN [2021-07-21 13:47:00.542 +0000] (22172): Please install ffmpeg for sending videos (pkg install ffmpeg)
> > > class: "Baileys"
> > > WARN [2021-07-21 13:47:00.545 +0000] (22172): Stickers may not work without imagemagick if libwebp on ffmpeg doesnt isntalled (pkg install imagemagick)
> > > class: "Baileys"
> > > INFO [2021-07-21 13:47:00.546 +0000] (22172): Quick Test Done
> > > class: "Baileys"
> > > INFO [2021-07-21 13:47:01.797 +0000] (22172): connected to WhatsApp Web server, authenticating via takeover
> > > class: "Baileys"
> > 
> > 
> > Have you installed ffmpeg, imagemagick and installed the env path?
> > And after that, try to exit bailyes on whatsapp and the senssion data.json file is deleted
> 
> ENV path? You mean to change whole handler to env process.

it depends, if you use windows os have to add environment path after install ffmpeg and imagemagick

**Comment by TOXIC-DEVIL** [comment]
> > > > No, Its only showing :-
> > > > [ false, false, false, false, false, false ]
> > > > WARN [2021-07-21 13:47:00.542 +0000] (22172): Please install ffmpeg for sending videos (pkg install ffmpeg)
> > > > class: "Baileys"
> > > > WARN [2021-07-21 13:47:00.545 +0000] (22172): Stickers may not work without imagemagick if libwebp on ffmpeg doesnt isntalled (pkg install imagemagick)
> > > > class: "Baileys"
> > > > INFO [2021-07-21 13:47:00.546 +0000] (22172): Quick Test Done
> > > > class: "Baileys"
> > > > INFO [2021-07-21 13:47:01.797 +0000] (22172): connected to WhatsApp Web server, authenticating via takeover
> > > > class: "Baileys"
> > > 
> > > 
> > > Have you installed ffmpeg, imagemagick and installed the env path?
> > > And after that, try to exit bailyes on whatsapp and the senssion data.json file is deleted
> > 
> > 
> > ENV path? You mean to change whole handler to env process.
> 
> it depends, if you use windows os have to add environment path after install ffmpeg and imagemagick

Phone?! :(

**Comment by syahrularranger** [comment]
> > > > > No, Its only showing :-
> > > > > [ false, false, false, false, false, false ]
> > > > > WARN [2021-07-21 13:47:00.542 +0000] (22172): Please install ffmpeg for sending videos (pkg install ffmpeg)
> > > > > class: "Baileys"
> > > > > WARN [2021-07-21 13:47:00.545 +0000] (22172): Stickers may not work without imagemagick if libwebp on ffmpeg doesnt isntalled (pkg install imagemagick)
> > > > > class: "Baileys"
> > > > > INFO [2021-07-21 13:47:00.546 +0000] (22172): Quick Test Done
> > > > > class: "Baileys"
> > > > > INFO [2021-07-21 13:47:01.797 +0000] (22172): connected to WhatsApp Web server, authenticating via takeover
> > > > > class: "Baileys"
> > > > 
> > > > 
> > > > Have you installed ffmpeg, imagemagick and installed the env path?
> > > > And after that, try to exit bailyes on whatsapp and the senssion data.json file is deleted
> > > 
> > > 
> > > ENV path? You mean to change whole handler to env process.
> > 
> > 
> > it depends, if you use windows os have to add environment path after install ffmpeg and imagemagick
> 
> Phone?! :(

After scanning, dont close the terminal.. wait for minutes .. until receive a some message.. 
It is happen maybe you closing terminal before receive message..

**Comment by TOXIC-DEVIL** [comment]
> > > > > > No, Its only showing :-
> > > > > > [ false, false, false, false, false, false ]
> > > > > > WARN [2021-07-21 13:47:00.542 +0000] (22172): Please install ffmpeg for sending videos (pkg install ffmpeg)
> > > > > > class: "Baileys"
> > > > > > WARN [2021-07-21 13:47:00.545 +0000] (22172): Stickers may not work without imagemagick if libwebp on ffmpeg doesnt isntalled (pkg install imagemagick)
> > > > > > class: "Baileys"
> > > > > > INFO [2021-07-21 13:47:00.546 +0000] (22172): Quick Test Done
> > > > > > class: "Baileys"
> > > > > > INFO [2021-07-21 13:47:01.797 +0000] (22172): connected to WhatsApp Web server, authenticating via takeover
> > > > > > class: "Baileys"
> > > > > 
> > > > > 
> > > > > Have you installed ffmpeg, imagemagick and installed the env path?
> > > > > And after that, try to exit bailyes on whatsapp and the senssion data.json file is deleted
> > > > 
> > > > 
> > > > ENV path? You mean to change whole handler to env process.
> > > 
> > > 
> > > it depends, if you use windows os have to add environment path after install ffmpeg and imagemagick
> > 
> > 
> > Phone?! :(
> 
> After scanning, dont close the terminal.. wait for minutes .. until receive a some message..
> It is happen maybe you closing terminal before receive message..

Okay :) Let me check 💕

**Comment by TOXIC-DEVIL** [comment]
INFO [2021-07-22 11:04:10.565 +0000] (29236): closed connection, reason invalid_session
    class: "Baileys"
ERROR [2021-07-22 11:04:10.567 +0000] (BaileysError/29236): Unexpected error in login
    BaileysError: Unexpected error in login
        at WAConnection.authenticate (/data/data/com.termux/files/home/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/1.Validation.js:97:19)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at async WebSocket.<anonymous> (/data/data/com.termux/files/home/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:107:40)
INFO [2021-07-22 11:04:15.568 +0000] (29236): loading authentication credentials from session.data.json

--------------------

**Comment by TOXIC-DEVIL** [comment]
INFO [2021-07-22 12:32:01.896 +0000] (18844): connected to WhatsApp Web server, authenticating via takeover                                               class: "Baileys"                              INFO [2021-07-22 12:32:23.843 +0000] (18844): resolving login challenge                                 class: "Baileys"                              > INFO [2021-07-22 12:32:29.630 +0000] (18844): received 3 chats                                        class: "Baileys"                              INFO [2021-07-22 12:32:29.679 +0000] (18844): received 163 contacts                                     class: "Baileys"                              INFO [2021-07-22 12:32:39.112 +0000] (18844): checking phone connection...                              class: "Baileys"

-------
I didn't got any credentials than this 😔
