### ISSUE TITLE
Menambah kan fitur Gambar dan replay pada menu

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#618]

**Comment by NurFy** [comment]
gimanaa tuh mas , bisa dikasih pencerahan?

**Comment by ilhamimut** [comment]
> gimanaa tuh mas , bisa dikasih pencerahan?

maksudnya mungkin di #menu bot ditambahkan gambar/reply kek logo botnya sendiri :v

**Comment by NurFy** [comment]
Maybe You Mean This? #216
