### ISSUE TITLE
Apakah anda dapat menambahkan grub tutup dengan waktu?

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#621]
Apakah anda dapat menambahkan buka atau tutup grub dengan waktu??
Dan Fitur Mematikan Bot Dengan Command ke whatsapp Bot??(karna kontrol jarak jauh)
Tambakan juga fitur Bug yang langsung terhubung ke issue github??

Ini hanya saran, jika kalian boleh reply chat ini dan tuliskan kodingan saya akan membuat nya di bot saya sendiri..

Trimakasih Nurutomo Team..

**Comment by ilhamimut** [comment]
> Apakah anda dapat menambahkan buka atau tutup grub dengan waktu??
> Dan Fitur Mematikan Bot Dengan Command ke whatsapp Bot??(karna kontrol jarak jauh)
> Tambakan juga fitur Bug yang langsung terhubung ke issue github??
> 
> Ini hanya saran, jika kalian boleh reply chat ini dan tuliskan kodingan saya akan membuat nya di bot saya sendiri..
> 
> Trimakasih Nurutomo Team..

bantu up

**Comment by syahrularranger** [comment]
> Apakah anda dapat menambahkan buka atau tutup grub dengan waktu??
> Dan Fitur Mematikan Bot Dengan Command ke whatsapp Bot??(karna kontrol jarak jauh)
> Tambakan juga fitur Bug yang langsung terhubung ke issue github??
> 
> Ini hanya saran, jika kalian boleh reply chat ini dan tuliskan kodingan saya akan membuat nya di bot saya sendiri..
> 
> Trimakasih Nurutomo Team..

Membantu menjawab terkait mematikan bot di WhatsApp chat

Kamu bisa mengubah file `stopjadibot.js` di plugin

Ubah bagian:
```js
if (global.conn.user.jid == conn.user.jid) conn.reply(m.chat, 'Kenapa nggk langsung ke terminalnya?', m)
  else {
    await conn.reply(m.chat, 'Goodbye bot :\')', m)
    conn.close()
  }
```
Menjadi:
```js
    await conn.reply(m.chat, 'Goodbye bot :\')', m)
    conn.close()
```

**Comment by Bintangp02** [comment]
> > Apakah anda dapat menambahkan buka atau tutup grub dengan waktu??
> > Dan Fitur Mematikan Bot Dengan Command ke whatsapp Bot??(karna kontrol jarak jauh)
> > Tambakan juga fitur Bug yang langsung terhubung ke issue github??
> > Ini hanya saran, jika kalian boleh reply chat ini dan tuliskan kodingan saya akan membuat nya di bot saya sendiri..
> > Trimakasih Nurutomo Team..
> 
> Membantu menjawab terkait mematikan bot di WhatsApp chat
> 
> Kamu bisa mengubah file `stopjadibot.js` di plugin
> 
> Ubah bagian:
> 
> ```js
> if (global.conn.user.jid == conn.user.jid) conn.reply(m.chat, 'Kenapa nggk langsung ke terminalnya?', m)
>   else {
>     await conn.reply(m.chat, 'Goodbye bot :\')', m)
>     conn.close()
>   }
> ```
> 
> Menjadi:
> 
> ```js
>     await conn.reply(m.chat, 'Goodbye bot :\')', m)
>     conn.close()
> ```

Apakah anda baisa membuatkan buka / tutup grub dengan waktu di tentukan

**Comment by Ftwrr** [comment]
@ariffb25
