### ISSUE TITLE
Kok ad MP3 file di wabot-aq?

### ISSUE THREAD

**Issue by Andika856** [Nurutomo/wabot-aq#622]
Gw lagi mau lakuin sesuatu tiba2 pas w ls gw ketemu banyak banget MP3 di wabot-aq, apa gunanya si?

**Comment by Andika856** [comment]
![Screenshot_2021-07-22-18-57-10-88](https://user-images.githubusercontent.com/78887981/126635436-6462c567-7d68-49aa-8205-0560dc94ab78.jpg)
Pas w play kan suara nya redacted banget telinga w sakit

**Comment by ilhamimut** [comment]
> ![Screenshot_2021-07-22-18-57-10-88](https://user-images.githubusercontent.com/78887981/126635436-6462c567-7d68-49aa-8205-0560dc94ab78.jpg)
> Pas w play kan suara nya redacted banget telinga w sakit

bawaan sistem keknya tu :v

**Comment by syahrularranger** [comment]
Klo mnurutku itu tmp sampah dari plugins tomp3/toaudio

**Comment by ilhamimut** [comment]
> Klo mnurutku itu tmp sampah dari plugins tomp3/toaudio

Bisa dibersihkan gak?

**Comment by BochilGaming** [comment]
> > Klo mnurutku itu tmp sampah dari plugins tomp3/toaudio
> 
> Bisa dibersihkan gak?

hapus aja bwang, gk penting itu
