### ISSUE TITLE
Menu grup

### ISSUE THREAD

**Issue by Lord-Patrick** [Nurutomo/wabot-aq#623]
Abis restart bot,menu grup kek antilink,welcome dll. ke reset jadi harus enable 1 1,Cara supaya menu grup gk ke reset kl bot di restart gmn ya?

**Comment by BochilGaming** [comment]
> Abis restart bot,menu grup kek antilink,welcome dll. ke reset jadi harus enable 1 1,Cara supaya menu grup gk ke reset kl bot di restart gmn ya?

gk ke restat kok, mungkin aja databasenya ke reset/rusak

**Comment by FadliDarmawan** [comment]
> > Abis restart bot,menu grup kek antilink,welcome dll. ke reset jadi harus enable 1 1,Cara supaya menu grup gk ke reset kl bot di restart gmn ya?
> 
> gk ke restat kok, mungkin aja databasenya ke reset/rusak

#526 :v
