### ISSUE TITLE
[ Doubt ] ?!

### ISSUE THREAD

**Issue by TOXIC-DEVIL** [Nurutomo/wabot-aq#632]
Apakah **kode ini right?!**

    conn.open()

Untuk **Turn on** the bot.
------------
Apakah **kode ini right?!**

    conn.close()

Untuk **Turn off** the bot.
------------
I **don't know** Indonesian well, So **Please Be corporate.** 😂 I'm just studying Indonesian 🙂💕
----------
Really I mean :-
----------
Is the **code is right?!**

    conn.open()

To **Turn on** the bot.
-------
Is the **code is right?!**

    conn.close()

To **Turn off** the bot.
-------

**Comment by fazilvk786** [comment]
> Apakah **kode ini right?!**
> 
> ```
> conn.open()
> ```
> 
> ## Untuk **Turn on** the bot.
> Apakah **kode ini right?!**
> 
> ```
> conn.close()
> ```
> 
> ## Untuk **Turn off** the bot.
> ## I **don't know** Indonesian well, So **Please Be corporate.** 😂 I'm just studying 🙂💕
> ## Really I mean :-
> Is the **code is right?!**
> 
> ```
> conn.open()
> ```
> 
> ## To **Turn on** the bot.
> Is the **code is right?!**
> 
> ```
> conn.close()
> ```
> 
> ## To **Turn off** the bot.

നീ മലയാളി ആണോ ?

**Comment by TOXIC-DEVIL** [comment]
> > Apakah **kode ini right?!**
> > ```
> > conn.open()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Untuk **Turn on** the bot.
> > Apakah **kode ini right?!**
> > ```
> > conn.close()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Untuk **Turn off** the bot.
> > ## I **don't know** Indonesian well, So **Please Be corporate.** 😂 I'm just studying 🙂💕
> > ## Really I mean :-
> > Is the **code is right?!**
> > ```
> > conn.open()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## To **Turn on** the bot.
> > Is the **code is right?!**
> > ```
> > conn.close()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## To **Turn off** the bot.
> 
> നീ മലയാളി ആണോ ?

Ahda 😂
