### ISSUE TITLE
Cara Tidak undefined Di Fitur Role?

### ISSUE THREAD

**Issue by Chifuy** [Nurutomo/wabot-aq#636]
![IMG_20210725_091818](https://user-images.githubusercontent.com/86765212/126885494-36fca776-0301-4b26-947f-f87096b33003.jpg)
Ini Gimana Min Biar Engga undefined?

**Comment by jauhari21** [comment]
> ![IMG_20210725_091818](https://user-images.githubusercontent.com/86765212/126885494-36fca776-0301-4b26-947f-f87096b33003.jpg)
> Ini Gimana Min Biar Engga undefined?

Ada yg salah tuh

**Comment by RC047** [comment]
ya fix sendirilah

**Comment by Chifuy** [comment]
> > ![IMG_20210725_091818](https://user-images.githubusercontent.com/86765212/126885494-36fca776-0301-4b26-947f-f87096b33003.jpg)
> > Ini Gimana Min Biar Engga undefined?
> 
> Ada yg salah tuh

Salah di mana nya yah, aku bingung

**Comment by Ftwrr** [comment]
> > > ![IMG_20210725_091818](https://user-images.githubusercontent.com/86765212/126885494-36fca776-0301-4b26-947f-f87096b33003.jpg)
> > > Ini Gimana Min Biar Engga undefined?
> > 
> > 
> > Ada yg salah tuh
> 
> Salah di mana nya yah, aku bingung

coba liat profile.js nya

**Comment by Ftwrr** [comment]
> ya fix sendirilah

good answer

**Comment by Chifuy** [comment]
> > > > ![IMG_20210725_091818](https://user-images.githubusercontent.com/86765212/126885494-36fca776-0301-4b26-947f-f87096b33003.jpg)
> > > > Ini Gimana Min Biar Engga undefined?
> > > 
> > > 
> > > Ada yg salah tuh
> > 
> > 
> > Salah di mana nya yah, aku bingung
> 
> coba liat profile.js nya


> > > > ![IMG_20210725_091818](https://user-images.githubusercontent.com/86765212/126885494-36fca776-0301-4b26-947f-f87096b33003.jpg)
> > > > Ini Gimana Min Biar Engga undefined?
> > > 
> > > 
> > > Ada yg salah tuh
> > 
> > 
> > Salah di mana nya yah, aku bingung
> 
> coba liat profile.js nya

profile.js nya masih ORI dari SC nya :v

**Comment by Chifuy** [comment]
> > > > ![IMG_20210725_091818](https://user-images.githubusercontent.com/86765212/126885494-36fca776-0301-4b26-947f-f87096b33003.jpg)
> > > > Ini Gimana Min Biar Engga undefined?
> > > 
> > > 
> > > Ada yg salah tuh
> > 
> > 
> > Salah di mana nya yah, aku bingung
> 
> coba liat profile.js nya

profile.js nya masih ORI dari SC yang sekarang min

**Comment by jauhari21** [comment]
> > ya fix sendirilah
> 
> good answer

Awoawokaowkakwkka

**Comment by jauhari21** [comment]
> > > > > ![IMG_20210725_091818](https://user-images.githubusercontent.com/86765212/126885494-36fca776-0301-4b26-947f-f87096b33003.jpg)
> > > > > Ini Gimana Min Biar Engga undefined?
> > > > 
> > > > 
> > > > Ada yg salah tuh
> > > 
> > > 
> > > Salah di mana nya yah, aku bingung
> > 
> > 
> > coba liat profile.js nya
> 
> profile.js nya masih ORI dari SC yang sekarang min

Dah tambahin di handler? Sama _role.js juga?

**Comment by syahrularranger** [comment]
> > > > > ![IMG_20210725_091818](https://user-images.githubusercontent.com/86765212/126885494-36fca776-0301-4b26-947f-f87096b33003.jpg)
> > > > > Ini Gimana Min Biar Engga undefined?
> > > > 
> > > > 
> > > > Ada yg salah tuh
> > > 
> > > 
> > > Salah di mana nya yah, aku bingung
> > 
> > 
> > coba liat profile.js nya
> 
> profile.js nya masih ORI dari SC yang sekarang min

Di handler harus di update,

**Comment by Chifuy** [comment]
> > > > > > ![IMG_20210725_091818](https://user-images.githubusercontent.com/86765212/126885494-36fca776-0301-4b26-947f-f87096b33003.jpg)
> > > > > > Ini Gimana Min Biar Engga undefined?
> > > > > 
> > > > > 
> > > > > Ada yg salah tuh
> > > > 
> > > > 
> > > > Salah di mana nya yah, aku bingung
> > > 
> > > 
> > > coba liat profile.js nya
> > 
> > 
> > profile.js nya masih ORI dari SC yang sekarang min
> 
> Di handler harus di update,

Udah Tapi Kok Malah Jadi Beginner Semua Mau Itu Level 60 Atau 30

**Comment by syahrularranger** [comment]
> > > > > > > ![IMG_20210725_091818](https://user-images.githubusercontent.com/86765212/126885494-36fca776-0301-4b26-947f-f87096b33003.jpg)
> > > > > > > Ini Gimana Min Biar Engga undefined?
> > > > > > 
> > > > > > 
> > > > > > Ada yg salah tuh
> > > > > 
> > > > > 
> > > > > Salah di mana nya yah, aku bingung
> > > > 
> > > > 
> > > > coba liat profile.js nya
> > > 
> > > 
> > > profile.js nya masih ORI dari SC yang sekarang min
> > 
> > 
> > Di handler harus di update,
> 
> Udah Tapi Kok Malah Jadi Beginner Semua Mau Itu Level 60 Atau 30

Jangan lupa tambahin Update _role.js
