### ISSUE TITLE
Menu Change

### ISSUE THREAD

**Issue by Netsh1** [Nurutomo/wabot-aq#64]
#menu kalo mau di edit apa nama filenya?

**Comment by Miaweers** [comment]
menu.js

**Comment by Nurutomo** [comment]
> #menu kalo mau di edit apa nama filenya?

me

> menu.js

Di folder plugins

**Comment by Netsh1** [comment]
Edit yang mana? Haya ada headernya saja untuk menambahkan menu baru harus edit yang mana?

**Comment by ariffb25** [comment]
> Edit yang mana? Haya ada headernya saja untuk menambahkan menu baru harus edit yang mana?

otomatis ngambil namanya dari handler.tags , harus sesuai juga sama variabel tags yang ada di menu.js

**Comment by Netsh1** [comment]
> > Edit yang mana? Haya ada headernya saja untuk menambahkan menu baru harus edit yang mana?
> 
> otomatis ngambil namanya dari handler.tags , harus sesuai juga sama variabel tags yang ada di menu.js

Wah Ribet Yah 😅

**Comment by ariffb25** [comment]
> > > Edit yang mana? Haya ada headernya saja untuk menambahkan menu baru harus edit yang mana?
> > 
> > 
> > otomatis ngambil namanya dari handler.tags , harus sesuai juga sama variabel tags yang ada di menu.js
> 
> Wah Ribet Yah 😅

ngga ribet malah keliatan lebih simpel 🙂

**Comment by Netsh1** [comment]
> > > > Edit yang mana? Haya ada headernya saja untuk menambahkan menu baru harus edit yang mana?
> > > 
> > > 
> > > otomatis ngambil namanya dari handler.tags , harus sesuai juga sama variabel tags yang ada di menu.js
> > 
> > 
> > Wah Ribet Yah 😅
> 
> ngga ribet malah keliatan lebih simpel 🙂

Wah? Bisa kirim screenshot gak :(  mau add #math soalnya fitur itu belum di tambahin di menu

**Comment by Nurutomo** [comment]
Baru nyadar kalo belum ada di menu:v

**Comment by Netsh1** [comment]
> Baru nyadar kalo belum ada di menu:v
🤣 Gimana bg nambahinnya kalo bot lain saya ngerti ini rada ribet

**Comment by Netsh1** [comment]
Ketemu akhirnya XD simple ternyata

**Comment by usoajwj** [comment]
> Ketemu akhirnya XD simple ternyata

dimana
