### ISSUE TITLE
How to deconnect whatsapp web

### ISSUE THREAD

**Issue by Pinindu-Tharushan** [Nurutomo/wabot-aq#640]
**How to deconnect whatsapp web**

**Comment by NurFy** [comment]
I dont understand

**Comment by Pinindu-Tharushan** [comment]
How to move bot to other whatsapp account

**Comment by NurFy** [comment]
> How to move bot to other whatsapp account

Remove The Session
```
rm session.data.json
```

**Comment by TOXIC-DEVIL** [comment]
> > How to move bot to other whatsapp account
> 
> Remove The Session
> 
> ```
> rm session.data.json
> ```

Can You Give your Instagram id let me contact you? 💬

**Comment by Pinindu-Tharushan** [comment]
Thanx all 🥰
