### ISSUE TITLE
Bang fitur textpro gak work/blank file

### ISSUE THREAD

**Issue by Ghost19-ui** [Nurutomo/wabot-aq#65]
Bang fitur textpro gak work/blank file

**Comment by ariffb25** [comment]
udah beli apikeynya?

**Comment by Ghost19-ui** [comment]
> udah beli apikeynya?

Belum bang tapi work kah kalau udah beli apikeynya?

**Comment by ariffb25** [comment]
> > udah beli apikeynya?
> 
> Belum bang tapi work kah kalau udah beli apikeynya?

![Screenshot_2021-02-19-17-26-01-734_com android chrome](https://user-images.githubusercontent.com/76026450/108492310-93e92f80-72d7-11eb-9944-7c5704774a12.jpg)
work kalo udah beli
