### ISSUE TITLE
Cara fix

### ISSUE THREAD

**Issue by bayganzz** [Nurutomo/wabot-aq#657]
Kok pas mau node . Error? Bantuin dong aku baru pemula

**Comment by NurFy** [comment]
error nya gimana :V

**Comment by bayganzz** [comment]
![2021_07_29_17 08 17](https://user-images.githubusercontent.com/87753667/127473757-a7936de2-427e-4e4c-a81d-2f05448e1d04.jpg)
Kaya gitu

**Comment by NurFy** [comment]
`npm install` udh?

**Comment by Bk-SaD** [comment]
Cuando ejecuto el comando "node ." para iniciar, me sale esto ![20210804_030804](https://user-images.githubusercontent.com/82702287/128137449-e007d4a8-1c08-4d14-b923-e016fa4fc429.jpg)

**Comment by Bk-SaD** [comment]
![Uploading 20210804_030821.jpg…]()

**Comment by Bk-SaD** [comment]
![20210804_030821](https://user-images.githubusercontent.com/82702287/128138325-ff2eea59-2028-4909-94d4-a97f7b1cb3e1.jpg)

**Comment by Bk-SaD** [comment]
Ya ejecute npm install y sale error
