### ISSUE TITLE
Node server.js

### ISSUE THREAD

**Issue by FadliDarmawan** [Nurutomo/wabot-aq#660]
![Screenshot_20210729-070420_Termux.jpg](https://user-images.githubusercontent.com/79369935/127412283-0b93c449-6572-43bb-b31c-41ed9b78dec5.jpg)
Help me pls

**Comment by lilnext01** [comment]
$ rm -r node-modules
$ npm install
$ npm start

**Comment by FadliDarmawan** [comment]
> $ rm -r node-modules
> $ npm install
> $ npm start

![Screenshot_20210729-074955_Termux.jpg](https://user-images.githubusercontent.com/79369935/127414632-8ff88ada-afc3-4d56-b3bc-146eec75da00.jpg)
