### ISSUE TITLE
bot auto keluar jika tidak admin

### ISSUE THREAD

**Issue by ilhamimut** [Nurutomo/wabot-aq#663]
assalamuaikum.

jadi gini kan ada orang yang undang bot ke grup, jika botnya tidak dijadiin admin selama 1 menit maka botnya akan otomatis keluar dari grup tersebut.
bagi tau dong caranya :/

**Comment by ariffb25** [comment]
```js
if (m.isGroup && !isBotAdmin) this.groupLeave(m.chat)
```

**Comment by FadliDarmawan** [comment]
> wa'alaikumussalam, bisa dibuat file baru atau letakan dalam handler.js
> ```js
> if (m.isGroup && !isBotAdmin) this.groupLeave(m.chat)
> ```

Kalau ngasih delay nya gimana bang?

(Ya masuk perlu waktu biar jadi admin)

**Comment by Ftwrr** [comment]
> > wa'alaikumussalam, bisa dibuat file baru atau letakan dalam handler.js
> > ```js
> > if (m.isGroup && !isBotAdmin) this.groupLeave(m.chat)
> > ```
> 
> Kalau ngasih delay nya gimana bang?
> 
> (Ya masuk perlu waktu biar jadi admin)

hmmm

**Comment by ilhamimut** [comment]
> > wa'alaikumussalam, bisa dibuat file baru atau letakan dalam handler.js
> > ```js
> > if (m.isGroup && !isBotAdmin) this.groupLeave(m.chat)
> > ```
> 
> Kalau ngasih delay nya gimana bang?
> 
> (Ya masuk perlu waktu biar jadi admin)

Bantu up
