### ISSUE TITLE
Git clone ga berfungsi..?

### ISSUE THREAD

**Issue by Andika856** [Nurutomo/wabot-aq#664]
![Screenshot_2021-07-30-08-34-17-79](https://user-images.githubusercontent.com/78887981/127586612-3f219988-f732-4ae5-8fcc-84dfd25821c0.jpg)

Cara fix gmn y?

Maaf kalo saya sering ganggu nge bug report kalo itu mengganggu

**Comment by oneechan123** [comment]
Ntahlah

**Comment by rescenic** [comment]
Coba install DNSCrypt. Pastikan internet aman.
