### ISSUE TITLE
fake reply

### ISSUE THREAD

**Issue by M1zxn** [Nurutomo/wabot-aq#668]
tambahin fake reply dong di !hidetag :)
(edit: fakereply yang ada verifiednya)

**Comment by FadliDarmawan** [comment]
> tambahin fake reply dong di !hidetag :)
> (edit: fakereply yang ada verifiednya)

Bisa di tambahkan sendiri

Saya ada sih mentahan fake reply
Berikut:

```conn.sendFile(m.chat, 'https://telegra.ph/file/bfd07cc2eb289ed12010d.jpg', 'a.jpg', `Testing`.trim(), {
            key: {
                remoteJid: '0@s.whatsapp.net',
                fromMe: false,
            }, message: {
                imageMessage: {
                    jpegThumbnail: require('fs').readFileSync('./src/loli1.png')
                }
            }
        })```

Note: `jpegThumbnail` sesuaikan sendiri, karena saya pake daru src

**Comment by FadliDarmawan** [comment]
> > tambahin fake reply dong di !hidetag :)
> > (edit: fakereply yang ada verifiednya)
> 
> Bisa di tambahkan sendiri
> 
> Saya ada sih mentahan fake reply
> Berikut:
> 
>conn.sendFile(m.chat, 'https://telegra.ph/file/bfd07cc2eb289ed12010d.jpg', 'a.jpg', `Testing`.trim(), {
>             key: {
>                 remoteJid: '0@s.whatsapp.net',
>                 fromMe: false,
>             }, message: {
>                 imageMessage: {
>                     jpegThumbnail: require('fs').readFileSync('./src/loli1.png')
>                 }
>             }
>         })
> 
> Note: `jpegThumbnail` sesuaikan sendiri, karena saya pake daru src

**Comment by M1zxn** [comment]
> > tambahin fake reply dong di !hidetag :)
> > (edit: fakereply yang ada verifiednya)
> 
> Bisa di tambahkan sendiri
> 
> Saya ada sih mentahan fake reply
> Berikut:
> 
> conn.sendFile(m.chat, 'https://telegra.ph/file/bfd07cc2eb289ed12010d.jpg', 'a.jpg', `Testing`.trim(), {
> key: {
> remoteJid: '[0@s.whatsapp.net](mailto:0@s.whatsapp.net)',
> fromMe: false,
> }, message: {
> imageMessage: {
> jpegThumbnail: require('fs').readFileSync('./src/loli1.png')
> }
> }
> })
> 
> Note: `jpegThumbnail` sesuaikan sendiri, karena saya pake daru src

ini taro dimana bang?

**Comment by FadliDarmawan** [comment]
> > > tambahin fake reply dong di !hidetag :)
> > > (edit: fakereply yang ada verifiednya)
> > 
> > Bisa di tambahkan sendiri
> > 
> > Saya ada sih mentahan fake reply
> > Berikut:
> > 
> > conn.sendFile(m.chat, 'https://telegra.ph/file/bfd07cc2eb289ed12010d.jpg', 'a.jpg', `Testing`.trim(), {
> > key: {
> > remoteJid: '[0@s.whatsapp.net](mailto:0@s.whatsapp.net)',
> > fromMe: false,
> > }, message: {
> > imageMessage: {
> > jpegThumbnail: require('fs').readFileSync('./src/loli1.png')
> > }
> > }
> > })
> > 
> > Note: `jpegThumbnail` sesuaikan sendiri, karena saya pake daru src
> 
> ini taro dimana bang?
> (edit: di line berapa?)

![Screenshot_20210731-170717_WhatsApp.jpg](https://user-images.githubusercontent.com/79369935/127736540-ba73cbb7-2b56-433c-9578-2bae6e37b56b.jpg)
