### ISSUE TITLE
Saya ingin opsi gif atau video untuk stiker, ini adalah opsi yang sangat bagus

### ISSUE THREAD

**Issue by peraltakw** [Nurutomo/wabot-aq#67]
tolong tambahkan gif ke opsi stiker. itulah satu-satunya pilihan yang tersisa baginya untuk menjadi sempurna

**Comment by ariffb25** [comment]
tinggal tambahin video aja bang

**Comment by ariffb25** [comment]
```
if (/image/.test(q.mimetype || '')) {
```
[line 7 ](https://github.com/Nurutomo/wabot-aq/blob/4c649b3026ba1fdc254f2f728fa811fca6caf766/plugins/sticker.js#L7)

diedit menjadi 
```
if (/image|video/.test(q.mimetype || '')) {
```

**Comment by Netsh1** [comment]
> ```
> if (/image/.test(q.mimetype || '')) {
> ```
> 
> [line 7 ](https://github.com/Nurutomo/wabot-aq/blob/4c649b3026ba1fdc254f2f728fa811fca6caf766/plugins/sticker.js#L7)
> 
> diedit menjadi
> 
> ```
> if (/image|video/.test(q.mimetype || '')) {
> ```

Itu di file mana ya?

**Comment by Netsh1** [comment]
Nevermind nemu di sticker.js

**Comment by peraltakw** [comment]
Saya melakukan apa yang Anda katakan, sebagian berhasil. tapi ini statis, saya ingin terlihat seperti stiker animasi

**Comment by Netsh1** [comment]
> ```
> if (/image/.test(q.mimetype || '')) {
> ```
> 
> [line 7 ](https://github.com/Nurutomo/wabot-aq/blob/4c649b3026ba1fdc254f2f728fa811fca6caf766/plugins/sticker.js#L7)
> 
> diedit menjadi
> 
> ```
> if (/image|video/.test(q.mimetype || '')) {
> ```

Work sih tapi stickernya dari gif jadi img doang gk gerak stickernya

**Comment by peraltakw** [comment]
Sayang sekali, saya ingin dia bergerak seperti bot lainnya. bot Anda adalah yang terbaik yang pernah saya gunakan. Hanya saja kerugiannya, karena di sini, di negara saya, kami banyak menggunakan opsi ini

**Comment by ariffb25** [comment]
> > ```
> > if (/image/.test(q.mimetype || '')) {
> > ```
> > 
> > 
> > [line 7 ](https://github.com/Nurutomo/wabot-aq/blob/4c649b3026ba1fdc254f2f728fa811fca6caf766/plugins/sticker.js#L7)
> > diedit menjadi
> > ```
> > if (/image|video/.test(q.mimetype || '')) {
> > ```
> 
> Work sih tapi stickernya dari gif jadi img doang gk gerak stickernya

dari gif juga work kok🤔
