### ISSUE TITLE
Tidak bisa scan barcode untuk whatsapp versi beta

### ISSUE THREAD

**Issue by Rianfirnanda** [Nurutomo/wabot-aq#672]
<h4>In WhatsApp beta version, you can still use WhatsApp on other devices even if you are offline .So, the primary device for the bot account does not need to be connected to the internet all the time. It's very useful for bots <h4>

**Comment by FadliDarmawan** [comment]
> <h4>In WhatsApp beta version, you can still use WhatsApp on other devices even if you are offline .So, the primary device for the bot account does not need to be connected to the internet all the time. It's very useful for bots <h4>

Baileys not support

(Maybe)

But multi device-account is very usefull

**Comment by Rianfirnanda** [comment]
> > #### In WhatsApp beta version, you can still use WhatsApp on other devices even if you are offline .So, the primary device for the bot account does not need to be connected to the internet all the time. It's very useful for bots ####
> 
> Baileys not support
> 
> (Maybe)
> 
> But multi device-account is very usefull

https://github.com/sigalor/whatsapp-web-multi-device-reveng

Katanya lagi di update sama dev baileys
