### ISSUE TITLE
Family100.Js

### ISSUE THREAD

**Issue by github838** [Nurutomo/wabot-aq#674]
Bagaimana cara mengubah pertanyaan dan jawaban?

![image](https://user-images.githubusercontent.com/78624931/127761101-31dd87e6-f345-4317-83ee-6817587d0ca7.jpeg)

![image](https://user-images.githubusercontent.com/78624931/127761105-14dc05f8-74ad-4f20-9be8-d9deb736d4f1.jpeg)

**Comment by ariffb25** [comment]
itu kan hasil json dari rest API nya, kalo mau bisa ngubah sendiri ya buat soal/scrape sendiri simpen ke json trs ubah deh

**Comment by github838** [comment]
Bisakah Anda menjelaskan lebih lanjut!

**Comment by github838** [comment]
> itu kan hasil json dari rest API nya, kalo mau bisa ngubah sendiri ya buat soal/scrape sendiri simpen ke json trs ubah deh

Saya ingin penjelasan rinci

**Comment by Bk-SaD** [comment]
Cómo soluciono esto cuando pongo "!family100"
![Screenshot_20210802-054740_WhatsApp](https://user-images.githubusercontent.com/82702287/127841769-98f81a9e-4ef1-40d5-aa19-f9c667b24d91.jpg)

**Comment by ItsukaaChan** [comment]
> Cómo soluciono esto cuando pongo "!family100"
> ![Screenshot_20210802-054740_WhatsApp](https://user-images.githubusercontent.com/82702287/127841769-98f81a9e-4ef1-40d5-aa19-f9c667b24d91.jpg)

buy apikey on website api.xteam.xyz :v

**Comment by ariffb25** [comment]
https://github.com/ariffb25/stikerinbot use this @Bk-SaD
