### ISSUE TITLE
esta dando erro dps que eu dou npm install, dps node index.js ele nao abre o codigo qr

### ISSUE THREAD

**Issue by anonymous690** [Nurutomo/wabot-aq#68]

**Comment by anonymous690** [comment]
o erro e 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR!
npm ERR!

**Comment by Nurutomo** [comment]
???

**Comment by ariffb25** [comment]
faça o comando abaixo no seu termux
```
> pkg update && pkg upgrade
> pkg install git -y
> pkg install nodejs -y
> pkg install ffmpeg -y
> pkg install imagemagick -y
> git clone https://github.com/Nurutomo/wabot-aq
> cd wabot-aq
> npm install
```

Run
```
> node . [<session name>] (session name is optional)
```
se isso falhar, tente bifurcar o projeto wabot-aq e repetir o comando acima

**Comment by Nurutomo** [comment]
`npm install`
then `npm run`

**Comment by anonymous690** [comment]
npm install 
node index.js

**Comment by anonymous690** [comment]
so mais uma coisa o 
.ttp ta bugando
.attp tbm ta bugando

**Comment by Saad-bn** [comment]
> so mais uma coisa o 
> .ttp ta bugando
> .attp tbm ta bugando 

Have you written "pkg install imagemagick -y" ?
