### ISSUE TITLE
#register dapet bonus limit

### ISSUE THREAD

**Issue by ilhamimut** [Nurutomo/wabot-aq#680]
assalamualaikum

kasi tau dong gimana caranya ketika user abis daftar/register dapet bonus 10 limit

**Comment by syahrularranger** [comment]
Tambahin

```js
global.db.data.users[m.sender].limit += 10
```

**Comment by ilhamimut** [comment]
> Tambahin
> 
> ```js
> global.db.data.users[m.sender].limit += 10
> ```

pasang di handler atau di register.js?

**Comment by botkus** [comment]
`const { createHash } = require('crypto')
let Reg = /\|?(.*)([.|] *?)([0-9]*)$/i
let handler = async function (m, { text, usedPrefix }) {
  let user = global.db.data.users[m.sender]
  if (user.registered === true) throw `Anda sudah terdaftar\nMau daftar ulang? ${usedPrefix}unreg <SN|SERIAL NUMBER>`
  if (!Reg.test(text)) throw `Format salah\n*${usedPrefix}daftar nama.umur*`
  let [_, name, splitter, age] = text.match(Reg)
  if (!name) throw 'Nama tidak boleh kosong (Alphanumeric)'
  if (!age) throw 'Umur tidak boleh kosong (Angka)'
  age = parseInt(age)
  if (age > 120) throw 'Umur terlalu tua 😂'
  if (age < 5) throw 'Bayi bisa ngetik sesuai format bjir ._.'
  user.name = name.trim()
  user.age = age
  user.regTime = + new Date
  user.registered = true
  let sn = createHash('md5').update(m.sender).digest('hex')
  m.reply(`
Daftar berhasil!
╭─「 Info 」
│ Nama: ${name}
│ Umur: ${age} tahun
│ SN: ${sn}
╰────
`.trim())
global.db.data.users[m.sender].limit += 10
m.reply(`Terimakasih telah mendaftar ... Anda mendapatkan bonus 10 Limit ...`)
}
handler.help = ['daftar', 'reg', 'register'].map(v => v + ' <nama>.<umur>')
handler.tags = ['exp']

handler.command = /^(daftar|reg(ister)?)$/i

module.exports = `

**Comment by ilhamimut** [comment]
> const { createHash } = require('crypto')
> let Reg = /|?(.*)([.|] _?)([0-9]_)$/i
> let handler = async function (m, { text, usedPrefix }) {
> let user = global.db.data.users[m.sender]
> if (user.registered === true) throw `Anda sudah terdaftar\nMau daftar ulang? ${usedPrefix}unreg <SN|SERIAL NUMBER>`
> if (!Reg.test(text)) throw `Format salah\n*${usedPrefix}daftar nama.umur*`
> let [_, name, splitter, age] = text.match(Reg) if (!name) throw 'Nama tidak boleh kosong (Alphanumeric)' if (!age) throw 'Umur tidak boleh kosong (Angka)' age = parseInt(age) if (age > 120) throw 'Umur terlalu tua 😂' if (age < 5) throw 'Bayi bisa ngetik sesuai format bjir ._.'
> user.name = name.trim()
> user.age = age
> user.regTime = + new Date
> user.registered = true
> let sn = createHash('md5').update(m.sender).digest('hex')
> m.reply(`Daftar berhasil! ╭─「 Info 」 │ Nama: ${name} │ Umur: ${age} tahun │ SN: ${sn} ╰────`.trim())
> global.db.data.users[m.sender].limit += 10
> m.reply(`Terimakasih telah mendaftar ... Anda mendapatkan bonus 10 Limit ...`)
> }
> handler.help = ['daftar', 'reg', 'register'].map(v => v + ' .')
> handler.tags = ['exp']
> 
> handler.command = /^(daftar|reg(ister)?)$/i
> 
> module.exports =

makasi gan udah bisa 👍
