### ISSUE TITLE
sendButton reply pesan

### ISSUE THREAD

**Issue by ilhamimut** [Nurutomo/wabot-aq#691]
Assalamualaikum.

Ada bisa ngasi tau gk gimana caranya conn.sendButton bisa mereply pesan setelah user tekan tombol lgsg mereply/ngetag user yg tekan tombol tersebut

**Comment by ariffb25** [comment]
disini mana ada sendButton :v

**Comment by Ftwrr** [comment]
salah tempat

**Comment by Bintang73** [comment]
Silahkan jika mau menambahkan sendButton, pullreq aja
