### ISSUE TITLE
Cara Bikin Button Gimana Min?

### ISSUE THREAD

**Issue by Chifuy** [Nurutomo/wabot-aq#700]
Cara Bikin Button Di levelup.js/_autolevelup.js Kayak Gimana Min?

**Comment by Ftwrr** [comment]
stikerin :v

**Comment by Chifuy** [comment]
> stikerin :v

Error Njir :/

**Comment by Ftwrr** [comment]
> > stikerin :v
> 
> Error Njir :/

bikin issues disana, kok malah bikin issues disini jirr

**Comment by Bintang73** [comment]
Pull request
