### ISSUE TITLE
scan qr

### ISSUE THREAD

**Issue by Cilbosswp** [Nurutomo/wabot-aq#701]
kenapa scan qr nya ga muncul di heroku

**Comment by ariffb25** [comment]
isi procfilenya udah diganti blm?

**Comment by mrsunss** [comment]
![Screenshot_2021-08-14-15-49-38-92](https://user-images.githubusercontent.com/47669574/129444308-98519fc2-0c06-4bd9-ba73-f193c33b4f64.jpg)

I can't scan qr code 🤔 why

**Comment by ariffb25** [comment]
@mrsunss use this
```node . --server```
- then, open it in your browser, for example name-application.herokuapp.com
- a qr code will appear, then scan


why can't scan on heroku terminal? it's coz the terminal color is reversed

or you can do a local scan first then push the session.data.json file so you don't need to do a re-scan

**Comment by TOXIC-DEVIL** [comment]
> ![Screenshot_2021-08-14-15-49-38-92](https://user-images.githubusercontent.com/47669574/129444308-98519fc2-0c06-4bd9-ba73-f193c33b4f64.jpg)
> 
> I can't scan qr code 🤔 why

Can You Tell me How to get credentials for Session.data.json?! I want to use on heroku :(

**Comment by Oreki-san** [comment]
> @mrsunss use this
> `node . --server`
> 
> * then, open it in your browser, for example name-application.herokuapp.com
> * a qr code will appear, then scan
> 
> why can't scan on heroku terminal? it's coz the terminal color is reversed
> 
> or you can do a local scan first then push the session.data.json file so you don't need to do a re-scan


there is a problem of qr when you open
Name.heroku.com/views
it outputs a small qr code :,(
