### ISSUE TITLE
[Ask] Skrg Wabot-aq Dh Gk Support Di Hp Old Kah?

### ISSUE THREAD

**Issue by WibuSesats** [Nurutomo/wabot-aq#702]
> Bg Mo Nanya Skrg Wabot-aq Dh G Support Di Hp Old Kah?
Contoh Kyk Samsung J2 Prime

**Comment by WibuSesats** [comment]
Klo Dh g Support Nasib Nasib :(

**Comment by Ftwrr** [comment]
coba aja

**Comment by TheUnknownPeople-user** [comment]
Sesuai Info Dari Pihak Termux Bahwa Android Versi 7 kebawah Gak Akan Support Lagi

> >Misal Android: 5,6, Dll

> > Bg Mo Nanya Skrg Wabot-aq Dh G Support Di Hp Old Kah?
> > Contoh Kyk Samsung J2 Prime

**Comment by Rhmn404** [comment]
makanya ganteng awokawok
