### ISSUE TITLE
[HELP] SendButton

### ISSUE THREAD

**Issue by lilnext01** [Nurutomo/wabot-aq#713]
Bagaimana cara mengirim pesan dengan tombol? dan bagaimana cara mengirim gambar dengan tombol?

**Comment by ilhamimut** [comment]
> Bagaimana cara mengirim pesan dengan tombol? dan bagaimana cara mengirim gambar dengan tombol?



coba ini:

let { MessageType } = require('@adiwajshing/baileys')
const { sticker } = require('../lib/sticker')
let fs = require('fs')

const buttons = [
  {buttonId: '.menu', buttonText: {displayText: 'MENU'}, type: 1},
  {buttonId: '.limit', buttonText: {displayText: 'LIMIT'}, type: 1},
]

const buttonMessage = {
  contentText: "Ada yang bisa dibantu? \nTekan MENU",
  footerText: 'test doang',
  buttons: buttons,
  headerType: 1
}

let handler = async (m, { conn }) => {
  conn.sendMessage(m.chat, buttonMessage, MessageType.buttonsMessage, {quoted : m} )
}

handler.customPrefix = /^bot$|halo$|/i // ketik bot atau halo (tanpa prefix)
handler.command = new RegExp

handler.owner = false
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null

module.exports = handler




simpan file dengan nama terserah.js

**Comment by BochilGaming** [comment]
> Bagaimana cara mengirim pesan dengan tombol? dan bagaimana cara mengirim gambar dengan tombol?

conn.sendButton(m.chat, 'content', 'footer', null, [['button text', 'button id']])

**Comment by yoga875** [comment]
> > Bagaimana cara mengirim pesan dengan tombol? dan bagaimana cara mengirim gambar dengan tombol?
> 
> conn.sendButton(m.chat, 'content', 'footer', null, [['button text', 'button id']])

Tulis di?

**Comment by BochilGaming** [comment]
> > > Bagaimana cara mengirim pesan dengan tombol? dan bagaimana cara mengirim gambar dengan tombol?
> > 
> > 
> > conn.sendButton(m.chat, 'content', 'footer', null, [['button text', 'button id']])
> 
> Tulis di?

Di plugins yang mau kamu add button

**Comment by yoga875** [comment]
> > > > Bagaimana cara mengirim pesan dengan tombol? dan bagaimana cara mengirim gambar dengan tombol?
> > > 
> > > 
> > > conn.sendButton(m.chat, 'content', 'footer', null, [['button text', 'button id']])
> > 
> > 
> > Tulis di?
> 
> Di plugins yang mau kamu add button

Terus pas buttomnya dipencet ko ngga ngerespon yh?

**Comment by Ftwrr** [comment]
salin aja sendbutton dari stikerinbot
