### ISSUE TITLE
Fakereply dgn gambar dan button

### ISSUE THREAD

**Issue by aryaxplofc** [Nurutomo/wabot-aq#715]
![Screenshot_2021_0813_131821](https://user-images.githubusercontent.com/79091330/129313583-77ab09de-dfa9-4beb-b574-1ee2121622bf.png)

Cara nambahin Fakereply diatas gambar k gitu gmana

**Comment by Adiixyz** [comment]
> ![Screenshot_2021_0813_131821](https://user-images.githubusercontent.com/79091330/129313583-77ab09de-dfa9-4beb-b574-1ee2121622bf.png)
> 
> Cara nambahin Fakereply diatas gambar k gitu gmana

dengan caranya gatau

**Comment by Adiixyz** [comment]
> ![Screenshot_2021_0813_131821](https://user-images.githubusercontent.com/79091330/129313583-77ab09de-dfa9-4beb-b574-1ee2121622bf.png)
> 
> Cara nambahin Fakereply diatas gambar k gitu gmana

taruh

const freply = {key:{ fromMe:false, participant: `0@s.whatsapp.net`, ...(m.chat ? { remoteJid: `status@broadcast` } : {}) }, message: {

					"productMessage": {
						"product": {
							"productImage": {
								"url": "https://mmg.whatsapp.net/d/f/Am1sSqpVypFpsQawFUFkm4HgkPRqEx8rt32niyBmL4Wa.enc",
								"mimetype": "image/jpeg",
								"fileSha256": "KbJC20DoVEdDw+8WF1EqwtPsdPUTF8/xQbhg+65P3q4=",
								"fileLength": "43344",
								"height": 1080,
								"width": 1080,
								"mediaKey": "cX+6c20dws6B++0slmMNXcCk7omK+zvheoN6087j9nl=",
								"fileEncSha256": "BGO1C/OttoScb1UxDrGlwsI9eImocg1zwbLgYKmecXs=",
								"directPath": "/v/t62.7118-24/20036572_1210576852672540_4032358369544328852_n.enc?oh=d0e477e1bf0a01bfcf328776ab50ccee&oe=6043238E",
								"mediaKeyTimestamp": "1612168223"
		},
							"productId": "3872465552870232",
							"title": `${ucapanWaktu} ${conn.getName(m.sender)}`,
							"currencyCode": "USD",
							"priceAmount1000": "99",
							"productImageCount": 1
						},
						"businessOwnerJid": "0@s.whatsapp.net"}}}

**Comment by Adiixyz** [comment]
> > ![Screenshot_2021_0813_131821](https://user-images.githubusercontent.com/79091330/129313583-77ab09de-dfa9-4beb-b574-1ee2121622bf.png)
> > Cara nambahin Fakereply diatas gambar k gitu gmana
> 
> taruh
> 
> ```js
> const freply = {key:{ fromMe:false, participant: `0@s.whatsapp.net`, ...(m.chat ? { remoteJid: `status@broadcast` } : {}) }, message: {
> 
> 					"productMessage": {
> 						"product": {
> 							"productImage": {
> 								"url": "https://mmg.whatsapp.net/d/f/Am1sSqpVypFpsQawFUFkm4HgkPRqEx8rt32niyBmL4Wa.enc",
> 								"mimetype": "image/jpeg",
> 								"fileSha256": "KbJC20DoVEdDw+8WF1EqwtPsdPUTF8/xQbhg+65P3q4=",
> 								"fileLength": "43344",
> 								"height": 1080,
> 								"width": 1080,
> 								"mediaKey": "cX+6c20dws6B++0slmMNXcCk7omK+zvheoN6087j9nl=",
> 								"fileEncSha256": "BGO1C/OttoScb1UxDrGlwsI9eImocg1zwbLgYKmecXs=",
> 								"directPath": "/v/t62.7118-24/20036572_1210576852672540_4032358369544328852_n.enc?oh=d0e477e1bf0a01bfcf328776ab50ccee&oe=6043238E",
> 								"mediaKeyTimestamp": "1612168223"
> 		},
> 							"productId": "3872465552870232",
> 							"title": `${ucapanWaktu} ${conn.getName(m.sender)}`,
> 							"currencyCode": "USD",
> 							"priceAmount1000": "99",
> 							"productImageCount": 1
> 						},
> 						"businessOwnerJid": "0@s.whatsapp.net"}}}
> ```

tros

```js
conn.sendMessage(m.chat, text.trim(), 'conversation', { sendEphemeral: true, quoted: freply, contextInfo : { mentionedJid: conn.parseMention(text) }})
```

**Comment by jauhari21** [comment]
> ![Screenshot_2021_0813_131821](https://user-images.githubusercontent.com/79091330/129313583-77ab09de-dfa9-4beb-b574-1ee2121622bf.png)
> 
> Cara nambahin Fakereply diatas gambar k gitu gmana

Di foto ga ada fakereply :v

**Comment by yoga875** [comment]
> > ![Screenshot_2021_0813_131821](https://user-images.githubusercontent.com/79091330/129313583-77ab09de-dfa9-4beb-b574-1ee2121622bf.png)
> > Cara nambahin Fakereply diatas gambar k gitu gmana
> 
> taruh
> 
> ```js
> const freply = {key:{ fromMe:false, participant: `0@s.whatsapp.net`, ...(m.chat ? { remoteJid: `status@broadcast` } : {}) }, message: {
> 
> 					"productMessage": {
> 						"product": {
> 							"productImage": {
> 								"url": "https://mmg.whatsapp.net/d/f/Am1sSqpVypFpsQawFUFkm4HgkPRqEx8rt32niyBmL4Wa.enc",
> 								"mimetype": "image/jpeg",
> 								"fileSha256": "KbJC20DoVEdDw+8WF1EqwtPsdPUTF8/xQbhg+65P3q4=",
> 								"fileLength": "43344",
> 								"height": 1080,
> 								"width": 1080,
> 								"mediaKey": "cX+6c20dws6B++0slmMNXcCk7omK+zvheoN6087j9nl=",
> 								"fileEncSha256": "BGO1C/OttoScb1UxDrGlwsI9eImocg1zwbLgYKmecXs=",
> 								"directPath": "/v/t62.7118-24/20036572_1210576852672540_4032358369544328852_n.enc?oh=d0e477e1bf0a01bfcf328776ab50ccee&oe=6043238E",
> 								"mediaKeyTimestamp": "1612168223"
> 		},
> 							"productId": "3872465552870232",
> 							"title": `${ucapanWaktu} ${conn.getName(m.sender)}`,
> 							"currencyCode": "USD",
> 							"priceAmount1000": "99",
> 							"productImageCount": 1
> 						},
> 						"businessOwnerJid": "0@s.whatsapp.net"}}}
> ```

Taruh dmn?

**Comment by Adiixyz** [comment]
> > > ![Screenshot_2021_0813_131821](https://user-images.githubusercontent.com/79091330/129313583-77ab09de-dfa9-4beb-b574-1ee2121622bf.png)
> > > Cara nambahin Fakereply diatas gambar k gitu gmana
> > 
> > 
> > taruh
> > ```js
> > const freply = {key:{ fromMe:false, participant: `0@s.whatsapp.net`, ...(m.chat ? { remoteJid: `status@broadcast` } : {}) }, message: {
> > 
> > 					"productMessage": {
> > 						"product": {
> > 							"productImage": {
> > 								"url": "https://mmg.whatsapp.net/d/f/Am1sSqpVypFpsQawFUFkm4HgkPRqEx8rt32niyBmL4Wa.enc",
> > 								"mimetype": "image/jpeg",
> > 								"fileSha256": "KbJC20DoVEdDw+8WF1EqwtPsdPUTF8/xQbhg+65P3q4=",
> > 								"fileLength": "43344",
> > 								"height": 1080,
> > 								"width": 1080,
> > 								"mediaKey": "cX+6c20dws6B++0slmMNXcCk7omK+zvheoN6087j9nl=",
> > 								"fileEncSha256": "BGO1C/OttoScb1UxDrGlwsI9eImocg1zwbLgYKmecXs=",
> > 								"directPath": "/v/t62.7118-24/20036572_1210576852672540_4032358369544328852_n.enc?oh=d0e477e1bf0a01bfcf328776ab50ccee&oe=6043238E",
> > 								"mediaKeyTimestamp": "1612168223"
> > 		},
> > 							"productId": "3872465552870232",
> > 							"title": `${ucapanWaktu} ${conn.getName(m.sender)}`,
> > 							"currencyCode": "USD",
> > 							"priceAmount1000": "99",
> > 							"productImageCount": 1
> > 						},
> > 						"businessOwnerJid": "0@s.whatsapp.net"}}}
> > ```
> 
> Taruh dmn?

serah

**Comment by yoga875** [comment]
> > > > ![Screenshot_2021_0813_131821](https://user-images.githubusercontent.com/79091330/129313583-77ab09de-dfa9-4beb-b574-1ee2121622bf.png)
> > > > Cara nambahin Fakereply diatas gambar k gitu gmana
> > > 
> > > 
> > > taruh
> > > ```js
> > > const freply = {key:{ fromMe:false, participant: `0@s.whatsapp.net`, ...(m.chat ? { remoteJid: `status@broadcast` } : {}) }, message: {
> > > 
> > > 					"productMessage": {
> > > 						"product": {
> > > 							"productImage": {
> > > 								"url": "https://mmg.whatsapp.net/d/f/Am1sSqpVypFpsQawFUFkm4HgkPRqEx8rt32niyBmL4Wa.enc",
> > > 								"mimetype": "image/jpeg",
> > > 								"fileSha256": "KbJC20DoVEdDw+8WF1EqwtPsdPUTF8/xQbhg+65P3q4=",
> > > 								"fileLength": "43344",
> > > 								"height": 1080,
> > > 								"width": 1080,
> > > 								"mediaKey": "cX+6c20dws6B++0slmMNXcCk7omK+zvheoN6087j9nl=",
> > > 								"fileEncSha256": "BGO1C/OttoScb1UxDrGlwsI9eImocg1zwbLgYKmecXs=",
> > > 								"directPath": "/v/t62.7118-24/20036572_1210576852672540_4032358369544328852_n.enc?oh=d0e477e1bf0a01bfcf328776ab50ccee&oe=6043238E",
> > > 								"mediaKeyTimestamp": "1612168223"
> > > 		},
> > > 							"productId": "3872465552870232",
> > > 							"title": `${ucapanWaktu} ${conn.getName(m.sender)}`,
> > > 							"currencyCode": "USD",
> > > 							"priceAmount1000": "99",
> > > 							"productImageCount": 1
> > > 						},
> > > 						"businessOwnerJid": "0@s.whatsapp.net"}}}
> > > ```
> > 
> > 
> > Taruh dmn?
> 
> serah

![Uploading Screenshot_20210814-224032_Termux.jpg…]()

**Comment by yoga875** [comment]
> > > > ![Screenshot_2021_0813_131821](https://user-images.githubusercontent.com/79091330/129313583-77ab09de-dfa9-4beb-b574-1ee2121622bf.png)
> > > > Cara nambahin Fakereply diatas gambar k gitu gmana
> > > 
> > > 
> > > taruh
> > > ```js
> > > const freply = {key:{ fromMe:false, participant: `0@s.whatsapp.net`, ...(m.chat ? { remoteJid: `status@broadcast` } : {}) }, message: {
> > > 
> > > 					"productMessage": {
> > > 						"product": {
> > > 							"productImage": {
> > > 								"url": "https://mmg.whatsapp.net/d/f/Am1sSqpVypFpsQawFUFkm4HgkPRqEx8rt32niyBmL4Wa.enc",
> > > 								"mimetype": "image/jpeg",
> > > 								"fileSha256": "KbJC20DoVEdDw+8WF1EqwtPsdPUTF8/xQbhg+65P3q4=",
> > > 								"fileLength": "43344",
> > > 								"height": 1080,
> > > 								"width": 1080,
> > > 								"mediaKey": "cX+6c20dws6B++0slmMNXcCk7omK+zvheoN6087j9nl=",
> > > 								"fileEncSha256": "BGO1C/OttoScb1UxDrGlwsI9eImocg1zwbLgYKmecXs=",
> > > 								"directPath": "/v/t62.7118-24/20036572_1210576852672540_4032358369544328852_n.enc?oh=d0e477e1bf0a01bfcf328776ab50ccee&oe=6043238E",
> > > 								"mediaKeyTimestamp": "1612168223"
> > > 		},
> > > 							"productId": "3872465552870232",
> > > 							"title": `${ucapanWaktu} ${conn.getName(m.sender)}`,
> > > 							"currencyCode": "USD",
> > > 							"priceAmount1000": "99",
> > > 							"productImageCount": 1
> > > 						},
> > > 						"businessOwnerJid": "0@s.whatsapp.net"}}}
> > > ```
> > 
> > 
> > Taruh dmn?
> 
> serah

INFO [2021-08-14 15:37:23.377 +0000] (28154): loading authentication credentials from session.data.json
    class: "Baileys"
ERROR [2021-08-14 15:37:23.756 +0000] (28154): m is not defined
    ReferenceError: m is not defined
        at Object.<anonymous> (/data/data/com.termux/files/home/wabot-aq/plugins/freply.js:1:74)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        at Module.load (internal/modules/cjs/loader.js:928:32)
        at Function.Module._load (internal/modules/cjs/loader.js:769:14)
        at Module.require (internal/modules/cjs/loader.js:952:19)
        at require (internal/modules/cjs/helpers.js:88:18)
        at Object.<anonymous> (/data/data/com.termux/files/home/wabot-aq/main.js:165:32)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Gmn bang? Gafahan w masih

**Comment by Ftwrr** [comment]
> > > > > ![Screenshot_2021_0813_131821](https://user-images.githubusercontent.com/79091330/129313583-77ab09de-dfa9-4beb-b574-1ee2121622bf.png)
> > > > > Cara nambahin Fakereply diatas gambar k gitu gmana
> > > > 
> > > > 
> > > > taruh
> > > > ```js
> > > > const freply = {key:{ fromMe:false, participant: `0@s.whatsapp.net`, ...(m.chat ? { remoteJid: `status@broadcast` } : {}) }, message: {
> > > > 
> > > > 					"productMessage": {
> > > > 						"product": {
> > > > 							"productImage": {
> > > > 								"url": "https://mmg.whatsapp.net/d/f/Am1sSqpVypFpsQawFUFkm4HgkPRqEx8rt32niyBmL4Wa.enc",
> > > > 								"mimetype": "image/jpeg",
> > > > 								"fileSha256": "KbJC20DoVEdDw+8WF1EqwtPsdPUTF8/xQbhg+65P3q4=",
> > > > 								"fileLength": "43344",
> > > > 								"height": 1080,
> > > > 								"width": 1080,
> > > > 								"mediaKey": "cX+6c20dws6B++0slmMNXcCk7omK+zvheoN6087j9nl=",
> > > > 								"fileEncSha256": "BGO1C/OttoScb1UxDrGlwsI9eImocg1zwbLgYKmecXs=",
> > > > 								"directPath": "/v/t62.7118-24/20036572_1210576852672540_4032358369544328852_n.enc?oh=d0e477e1bf0a01bfcf328776ab50ccee&oe=6043238E",
> > > > 								"mediaKeyTimestamp": "1612168223"
> > > > 		},
> > > > 							"productId": "3872465552870232",
> > > > 							"title": `${ucapanWaktu} ${conn.getName(m.sender)}`,
> > > > 							"currencyCode": "USD",
> > > > 							"priceAmount1000": "99",
> > > > 							"productImageCount": 1
> > > > 						},
> > > > 						"businessOwnerJid": "0@s.whatsapp.net"}}}
> > > > ```
> > > 
> > > 
> > > Taruh dmn?
> > 
> > 
> > serah
> 
> INFO [2021-08-14 15:37:23.377 +0000] (28154): loading authentication credentials from session.data.json
> class: "Baileys"
> ERROR [2021-08-14 15:37:23.756 +0000] (28154): m is not defined
> ReferenceError: m is not defined
> at Object. (/data/data/com.termux/files/home/wabot-aq/plugins/freply.js:1:74)
> at Module._compile (internal/modules/cjs/loader.js:1063:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> at Module.load (internal/modules/cjs/loader.js:928:32)
> at Function.Module._load (internal/modules/cjs/loader.js:769:14)
> at Module.require (internal/modules/cjs/loader.js:952:19)
> at require (internal/modules/cjs/helpers.js:88:18)
> at Object. (/data/data/com.termux/files/home/wabot-aq/main.js:165:32)
> at Module._compile (internal/modules/cjs/loader.js:1063:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> Gmn bang? Gafahan w masih

salin aja sendbutton dari stikerinbot

**Comment by Adiixyz** [comment]
> > > > > ![Screenshot_2021_0813_131821](https://user-images.githubusercontent.com/79091330/129313583-77ab09de-dfa9-4beb-b574-1ee2121622bf.png)
> > > > > Cara nambahin Fakereply diatas gambar k gitu gmana
> > > > 
> > > > 
> > > > taruh
> > > > ```js
> > > > const freply = {key:{ fromMe:false, participant: `0@s.whatsapp.net`, ...(m.chat ? { remoteJid: `status@broadcast` } : {}) }, message: {
> > > > 
> > > > 					"productMessage": {
> > > > 						"product": {
> > > > 							"productImage": {
> > > > 								"url": "https://mmg.whatsapp.net/d/f/Am1sSqpVypFpsQawFUFkm4HgkPRqEx8rt32niyBmL4Wa.enc",
> > > > 								"mimetype": "image/jpeg",
> > > > 								"fileSha256": "KbJC20DoVEdDw+8WF1EqwtPsdPUTF8/xQbhg+65P3q4=",
> > > > 								"fileLength": "43344",
> > > > 								"height": 1080,
> > > > 								"width": 1080,
> > > > 								"mediaKey": "cX+6c20dws6B++0slmMNXcCk7omK+zvheoN6087j9nl=",
> > > > 								"fileEncSha256": "BGO1C/OttoScb1UxDrGlwsI9eImocg1zwbLgYKmecXs=",
> > > > 								"directPath": "/v/t62.7118-24/20036572_1210576852672540_4032358369544328852_n.enc?oh=d0e477e1bf0a01bfcf328776ab50ccee&oe=6043238E",
> > > > 								"mediaKeyTimestamp": "1612168223"
> > > > 		},
> > > > 							"productId": "3872465552870232",
> > > > 							"title": `${ucapanWaktu} ${conn.getName(m.sender)}`,
> > > > 							"currencyCode": "USD",
> > > > 							"priceAmount1000": "99",
> > > > 							"productImageCount": 1
> > > > 						},
> > > > 						"businessOwnerJid": "0@s.whatsapp.net"}}}
> > > > ```
> > > 
> > > 
> > > Taruh dmn?
> > 
> > 
> > serah
> 
> INFO [2021-08-14 15:37:23.377 +0000] (28154): loading authentication credentials from session.data.json
> class: "Baileys"
> ERROR [2021-08-14 15:37:23.756 +0000] (28154): m is not defined
> ReferenceError: m is not defined
> at Object. (/data/data/com.termux/files/home/wabot-aq/plugins/freply.js:1:74)
> at Module._compile (internal/modules/cjs/loader.js:1063:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> at Module.load (internal/modules/cjs/loader.js:928:32)
> at Function.Module._load (internal/modules/cjs/loader.js:769:14)
> at Module.require (internal/modules/cjs/loader.js:952:19)
> at require (internal/modules/cjs/helpers.js:88:18)
> at Object. (/data/data/com.termux/files/home/wabot-aq/main.js:165:32)
> at Module._compile (internal/modules/cjs/loader.js:1063:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> Gmn bang? Gafahan w masih

jan buat plugin njirrrr

**Comment by Adiixyz** [comment]
> > > > > > ![Screenshot_2021_0813_131821](https://user-images.githubusercontent.com/79091330/129313583-77ab09de-dfa9-4beb-b574-1ee2121622bf.png)
> > > > > > Cara nambahin Fakereply diatas gambar k gitu gmana
> > > > > 
> > > > > 
> > > > > taruh
> > > > > ```js
> > > > > const freply = {key:{ fromMe:false, participant: `0@s.whatsapp.net`, ...(m.chat ? { remoteJid: `status@broadcast` } : {}) }, message: {
> > > > > 
> > > > > 					"productMessage": {
> > > > > 						"product": {
> > > > > 							"productImage": {
> > > > > 								"url": "https://mmg.whatsapp.net/d/f/Am1sSqpVypFpsQawFUFkm4HgkPRqEx8rt32niyBmL4Wa.enc",
> > > > > 								"mimetype": "image/jpeg",
> > > > > 								"fileSha256": "KbJC20DoVEdDw+8WF1EqwtPsdPUTF8/xQbhg+65P3q4=",
> > > > > 								"fileLength": "43344",
> > > > > 								"height": 1080,
> > > > > 								"width": 1080,
> > > > > 								"mediaKey": "cX+6c20dws6B++0slmMNXcCk7omK+zvheoN6087j9nl=",
> > > > > 								"fileEncSha256": "BGO1C/OttoScb1UxDrGlwsI9eImocg1zwbLgYKmecXs=",
> > > > > 								"directPath": "/v/t62.7118-24/20036572_1210576852672540_4032358369544328852_n.enc?oh=d0e477e1bf0a01bfcf328776ab50ccee&oe=6043238E",
> > > > > 								"mediaKeyTimestamp": "1612168223"
> > > > > 		},
> > > > > 							"productId": "3872465552870232",
> > > > > 							"title": `${ucapanWaktu} ${conn.getName(m.sender)}`,
> > > > > 							"currencyCode": "USD",
> > > > > 							"priceAmount1000": "99",
> > > > > 							"productImageCount": 1
> > > > > 						},
> > > > > 						"businessOwnerJid": "0@s.whatsapp.net"}}}
> > > > > ```
> > > > 
> > > > 
> > > > Taruh dmn?
> > > 
> > > 
> > > serah
> > 
> > 
> > INFO [2021-08-14 15:37:23.377 +0000] (28154): loading authentication credentials from session.data.json
> > class: "Baileys"
> > ERROR [2021-08-14 15:37:23.756 +0000] (28154): m is not defined
> > ReferenceError: m is not defined
> > at Object. (/data/data/com.termux/files/home/wabot-aq/plugins/freply.js:1:74)
> > at Module._compile (internal/modules/cjs/loader.js:1063:30)
> > at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> > at Module.load (internal/modules/cjs/loader.js:928:32)
> > at Function.Module._load (internal/modules/cjs/loader.js:769:14)
> > at Module.require (internal/modules/cjs/loader.js:952:19)
> > at require (internal/modules/cjs/helpers.js:88:18)
> > at Object. (/data/data/com.termux/files/home/wabot-aq/main.js:165:32)
> > at Module._compile (internal/modules/cjs/loader.js:1063:30)
> > at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> > Gmn bang? Gafahan w masih
> 
> jan buat plugin njirrrr

taruh di menu biar ada fake reply

**Comment by Adiixyz** [comment]
> > > > > > > ![Screenshot_2021_0813_131821](https://user-images.githubusercontent.com/79091330/129313583-77ab09de-dfa9-4beb-b574-1ee2121622bf.png)
> > > > > > > Cara nambahin Fakereply diatas gambar k gitu gmana
> > > > > > 
> > > > > > 
> > > > > > taruh
> > > > > > ```js
> > > > > > const freply = {key:{ fromMe:false, participant: `0@s.whatsapp.net`, ...(m.chat ? { remoteJid: `status@broadcast` } : {}) }, message: {
> > > > > > 
> > > > > > 					"productMessage": {
> > > > > > 						"product": {
> > > > > > 							"productImage": {
> > > > > > 								"url": "https://mmg.whatsapp.net/d/f/Am1sSqpVypFpsQawFUFkm4HgkPRqEx8rt32niyBmL4Wa.enc",
> > > > > > 								"mimetype": "image/jpeg",
> > > > > > 								"fileSha256": "KbJC20DoVEdDw+8WF1EqwtPsdPUTF8/xQbhg+65P3q4=",
> > > > > > 								"fileLength": "43344",
> > > > > > 								"height": 1080,
> > > > > > 								"width": 1080,
> > > > > > 								"mediaKey": "cX+6c20dws6B++0slmMNXcCk7omK+zvheoN6087j9nl=",
> > > > > > 								"fileEncSha256": "BGO1C/OttoScb1UxDrGlwsI9eImocg1zwbLgYKmecXs=",
> > > > > > 								"directPath": "/v/t62.7118-24/20036572_1210576852672540_4032358369544328852_n.enc?oh=d0e477e1bf0a01bfcf328776ab50ccee&oe=6043238E",
> > > > > > 								"mediaKeyTimestamp": "1612168223"
> > > > > > 		},
> > > > > > 							"productId": "3872465552870232",
> > > > > > 							"title": `${ucapanWaktu} ${conn.getName(m.sender)}`,
> > > > > > 							"currencyCode": "USD",
> > > > > > 							"priceAmount1000": "99",
> > > > > > 							"productImageCount": 1
> > > > > > 						},
> > > > > > 						"businessOwnerJid": "0@s.whatsapp.net"}}}
> > > > > > ```
> > > > > 
> > > > > 
> > > > > Taruh dmn?
> > > > 
> > > > 
> > > > serah
> > > 
> > > 
> > > INFO [2021-08-14 15:37:23.377 +0000] (28154): loading authentication credentials from session.data.json
> > > class: "Baileys"
> > > ERROR [2021-08-14 15:37:23.756 +0000] (28154): m is not defined
> > > ReferenceError: m is not defined
> > > at Object. (/data/data/com.termux/files/home/wabot-aq/plugins/freply.js:1:74)
> > > at Module._compile (internal/modules/cjs/loader.js:1063:30)
> > > at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> > > at Module.load (internal/modules/cjs/loader.js:928:32)
> > > at Function.Module._load (internal/modules/cjs/loader.js:769:14)
> > > at Module.require (internal/modules/cjs/loader.js:952:19)
> > > at require (internal/modules/cjs/helpers.js:88:18)
> > > at Object. (/data/data/com.termux/files/home/wabot-aq/main.js:165:32)
> > > at Module._compile (internal/modules/cjs/loader.js:1063:30)
> > > at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> > > Gmn bang? Gafahan w masih
> > 
> > 
> > jan buat plugin njirrrr
> 
> taruh di menu biar ada fake reply

nih contohnya...
[menu.js | JavaScript File](https://github.com/Adiixyz/bot-aq/blob/master/plugins/menu.js)
