### ISSUE TITLE
Tanya bang

### ISSUE THREAD

**Issue by Lilithxdef** [Nurutomo/wabot-aq#717]
Simple.js buat apa ya bng

**Comment by TheUnknownPeople-user** [comment]
Function Baileys  Misall Function sendbutton/dll ntah sih ini menurut gw

**Comment by yoga875** [comment]
> Function Baileys Misall Function sendbutton/dll ntah sih ini menurut gw

Terus cara gunain sendbuttonnya gmn bng

**Comment by TheUnknownPeople-user** [comment]
> > Function Baileys Misall Function sendbutton/dll ntah sih ini menurut gw
> 
> Terus cara gunain sendbuttonnya gmn bng

tinggal buat plugin baru terus Coba liat di github baileys di bagian no media message

**Comment by yoga875** [comment]
> > > Function Baileys Misall Function sendbutton/dll ntah sih ini menurut gw
> > 
> > 
> > Terus cara gunain sendbuttonnya gmn bng
> 
> tinggal buat plugin baru terus Coba liat di github baileys di bagian no media message

Gafaham w masih

**Comment by BochilGaming** [comment]
> > Function Baileys Misall Function sendbutton/dll ntah sih ini menurut gw
> 
> Terus cara gunain sendbuttonnya gmn bng

sendButton nya lagi ngebug, tapi di fix di pr [ini](https://github.com/Nurutomo/wabot-aq/pull/716)

Cara gunainnya kalau mau text doank 
```conn.sendButton(m.chat, 'content text',  'footer', 
null,  [['button text',  'button id'], ['button text dan button id']])```, kalau mau pakek img tinggal
```conn.sendButton(m.chat, 'content text',  'footer', 
buffer,  [['button text',  'button id'], ['button text dan button id']])```

**Comment by yoga875** [comment]
> > > Function Baileys Misall Function sendbutton/dll ntah sih ini menurut gw
> > 
> > 
> > Terus cara gunain sendbuttonnya gmn bng
> 
> sendButton nya lagi ngebug, tapi di fix di pr [ini](https://github.com/Nurutomo/wabot-aq/pull/716)
> 
> Cara gunainnya kalau mau text doank
> 
> conn.sendButton(m.chat, 'content text', 'footer',
> null, [['button text', 'button id'], ['button text dan button id']])
> , kalau mau pakek img tinggal
> 
> conn.sendButton(m.chat, 'content text', 'footer',
> buffer, [['button text', 'button id'], ['button text dan button id']])

Dipake dibagian mn bng?

**Comment by TheUnknownPeople-user** [comment]
> > > > Function Baileys Misall Function sendbutton/dll ntah sih ini menurut gw
> > > 
> > > 
> > > Terus cara gunain sendbuttonnya gmn bng
> > 
> > 
> > sendButton nya lagi ngebug, tapi di fix di pr [ini](https://github.com/Nurutomo/wabot-aq/pull/716)
> > Cara gunainnya kalau mau text doank
> > conn.sendButton(m.chat, 'content text', 'footer',
> > null, [['button text', 'button id'], ['button text dan button id']])
> > , kalau mau pakek img tinggal
> > conn.sendButton(m.chat, 'content text', 'footer',
> > buffer, [['button text', 'button id'], ['button text dan button id']])
> 
> Dipake dibagian mn bng?

buat file js baru di plugins
