### ISSUE TITLE
chatbot

### ISSUE THREAD

**Issue by Naruto010** [Nurutomo/wabot-aq#725]
Bagaimana cara membuat penjawab otomatis dengan balasan?

ex:
if (budy == 'hi') {
							response = ["hey there","hi", "bye"]
							random = response[Math.floor(Math.random() * response.length)]
							reply(random)
						}

**Comment by TheUnknownPeople-user** [comment]
pake simi aja


let handler = m => m

handler.all = async function (m) {
if (m.isBaileys) return 
if (!prefix.test(m.text) && !m.isGroup && m.text && !m.text.startsWith('>')) {
   try {
  this.updatePresence(m.chat, 'composing')
   sios = await require('axios').get('https://simsumi.herokuapp.com/api?text='+encodeURIComponent(m.text) +'&lang=id')
   m.reply( '*SIMI*: ' +sios.data.success)
   } catch {
   }
  }
  return true
}

module.exports = handler

**Comment by TheUnknownPeople-user** [comment]
> pake simi aja
> 
> let handler = m => m
> 
> handler.all = async function (m) {
> if (m.isBaileys) return
> if (!prefix.test(m.text) && !m.isGroup && m.text && !m.text.startsWith('>')) {
> try {
> this.updatePresence(m.chat, 'composing')
> sios = await require('axios').get('https://simsumi.herokuapp.com/api?text='+encodeURIComponent(m.text) +'&lang=id')
> m.reply( '_SIMI_: ' +sios.data.success)
> } catch {
> }
> }
> return true
> }
> 
> module.exports = handler

ntar lu bisa setting lagi jadi kalau misal simi mode on  si simi auto on juga

**Comment by Naruto010** [comment]
> pake simi aja
> 
> let handler = m => m
> 
> handler.all = async function (m) {
> if (m.isBaileys) return
> if (!prefix.test(m.text) && !m.isGroup && m.text && !m.text.startsWith('>')) {
> try {
> this.updatePresence(m.chat, 'composing')
> sios = await require('axios').get('https://simsumi.herokuapp.com/api?text='+encodeURIComponent(m.text) +'&lang=id')
> m.reply( '_SIMI_: ' +sios.data.success)
> } catch {
> }
> }
> return true
> }
> 
> module.exports = handler

maaf tapi bagaimana saya bisa menggunakannya

**Comment by Naruto010** [comment]
> > > pake simi aja
> > > let handler = m => m
> > > handler.all = async function (m) {
> > > if (m.isBaileys) return
> > > if (!prefix.test(m.text) && !m.isGroup && m.text && !m.text.startsWith('>')) {
> > > try {
> > > this.updatePresence(m.chat, 'composing')
> > > sios = await require('axios').get('https://simsumi.herokuapp.com/api?text='+encodeURIComponent(m.text) +'&lang=id')
> > > m.reply( '_SIMI_: ' +sios.data.success)
> > > } catch {
> > > }
> > > }
> > > return true
> > > }
> > > module.exports = handler
> > 
> > 
> > maaf tapi bagaimana saya bisa menggunakannya
> 
> buat file js baru di plugins

Ya, tetapi jawaban yang saya inginkan, di mana saya meletakkannya

if (budy == 'hi') {
response = ["hey there","hi", "bye"]
random = response[Math.floor(Math.random() * response.length)]
reply(random)
}

**Comment by TheUnknownPeople-user** [comment]
> > > > pake simi aja
> > > > let handler = m => m
> > > > handler.all = async function (m) {
> > > > if (m.isBaileys) return
> > > > if (!prefix.test(m.text) && !m.isGroup && m.text && !m.text.startsWith('>')) {
> > > > try {
> > > > this.updatePresence(m.chat, 'composing')
> > > > sios = await require('axios').get('https://simsumi.herokuapp.com/api?text='+encodeURIComponent(m.text) +'&lang=id')
> > > > m.reply( '_SIMI_: ' +sios.data.success)
> > > > } catch {
> > > > }
> > > > }
> > > > return true
> > > > }
> > > > module.exports = handler
> > > 
> > > 
> > > maaf tapi bagaimana saya bisa menggunakannya
> > 
> > 
> > buat file js baru di plugins
> 
> Ya, tetapi jawaban yang saya inginkan, di mana saya meletakkannya
> 
> if (budy == 'hi') {
> response = ["hey there","hi", "bye"]
> random = response[Math.floor(Math.random() * response.length)]
> reply(random)
> }

ouh wait

**Comment by rescenic** [comment]
ijin nyimak bang

**Comment by ariffb25** [comment]
```js
let handler = m => m

handler.all = async function (m) {
    
    if (['hi','hai'].includes(m.text)) {
        m.reply(pickRandom(['hey there','hi', 'bye']))
    }

}

module.exports = handler

function pickRandom(list) {
    return list[Math.floor(list.length * Math.random())]
  }
```

**Comment by Naruto010** [comment]
> ```js
> let handler = m => m
> 
> handler.all = async function (m) {
>     
>     if (['hi','hai'].includes(m.text)) {
>         m.reply(pickRandom(['hey there','hi', 'bye']))
>     }
> 
> }
> 
> module.exports = handler
> 
> function pickRandom(list) {
>     return list[Math.floor(list.length * Math.random())]
>   }
> ```

Terima kasih, itu berhasil
Bisakah saya juga memasukkan pesan audio dan video?

**Comment by ariffb25** [comment]
tentu, silahkan baca dokumentasi baileys -,

**Comment by TheUnknownPeople-user** [comment]
bisa kamu tinggal pickrandom audio pada folder

**Comment by Naruto010** [comment]
> bisa kamu tinggal pickrandom audio pada folder

Ya, saya akan membuat file di file src dan saya akan mengatur arah file

**Comment by yoga875** [comment]
> ```js
> let handler = m => m
> 
> handler.all = async function (m) {
>     
>     if (['hi','hai'].includes(m.text)) {
>         m.reply(pickRandom(['hey there','hi', 'bye']))
>     }
> 
> }
> 
> module.exports = handler
> 
> function pickRandom(list) {
>     return list[Math.floor(list.length * Math.random())]
>   }
> ```

Kalo balesnya audio gmn bang

**Comment by ariffb25** [comment]
@yoga875 
jika audio berasal dari lokal
```js
this.sendFile(m.chat, './src/audio.mp3', 'file.mp3', null, m, true)
```
jika audio berasal dari url
```js
this.sendFile(m.chat, 'http://piyobot.000webhostapp.com/citacita1.mp3', 'file.mp3', null, m, true)
```
