### ISSUE TITLE
Stickker

### ISSUE THREAD

**Issue by Paezak** [Nurutomo/wabot-aq#726]
Ini knp ya? pas mau bikin stiker selalu begini
![Uploading Screenshot 2021-08-16 07.37.55.png…]()

**Comment by unx21** [comment]
> Ini knp ya? pas mau bikin stiker selalu begini

hmm?

**Comment by Paezak** [comment]
belum ke upload 
![Screenshot 2021-08-16 07 37 55](https://user-images.githubusercontent.com/73917768/129503475-3c9805e7-27d3-4d8f-bcde-9f8aba0b7a98.png)

**Comment by unx21** [comment]
> belum ke upload
> ![Screenshot 2021-08-16 07 37 55](https://user-images.githubusercontent.com/73917768/129503475-3c9805e7-27d3-4d8f-bcde-9f8aba0b7a98.png)

mungkin ini membantu :")
#454

**Comment by Paezak** [comment]
masih sama 🥲

**Comment by unx21** [comment]
> masih sama 🥲

pakai yang ini coba, barangkali bisa :")
https://github.com/stikerinbot

**Comment by ariffb25** [comment]
forceGet = true

**Comment by ariffb25** [comment]
```
node_modules > @adiwajshing > baileys > lib > WAConnection > 6.MessageSend.js 
```
cari ```forceGet``` atau langsung aja ke baris 412
```js
async refreshMediaConn(forceGet = false) {
```
ubah false jadi true

**Comment by BochilGaming** [comment]
> belum ke upload
> ![Screenshot 2021-08-16 07 37 55](https://user-images.githubusercontent.com/73917768/129503475-3c9805e7-27d3-4d8f-bcde-9f8aba0b7a98.png)

pakek simple.js versi terbaru bang
