### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by elssword** [Nurutomo/wabot-aq#73]
Bang tambahin anti link dong

**Comment by ariffb25** [comment]
kek nya bisa dibuat pake customPrefix hhmmm

**Comment by Saad-bn** [comment]
Bang mau tanya cara ganti prefixnya gimana?

**Comment by ariffb25** [comment]
@Saad-bn prefixnya kan macam2

kalo mau nambah bisa disini
[https://github.com/Nurutomo/wabot-aq/blob/7258de10f77bcf0c362bfed6a78e600aecfdaa8d/main.js#L41](https://github.com/Nurutomo/wabot-aq/blob/7258de10f77bcf0c362bfed6a78e600aecfdaa8d/main.js#L41)

**Comment by Saad-bn** [comment]
> @Saad-bn prefixnya kan macam2
> 
> kalo mau nambah bisa disini
> [https://github.com/Nurutomo/wabot-aq/blob/7258de10f77bcf0c362bfed6a78e600aecfdaa8d/main.js#L41](https://github.com/Nurutomo/wabot-aq/blob/7258de10f77bcf0c362bfed6a78e600aecfdaa8d/main.js#L41)
> 
> 

@ariffb25 eh Ternyata di file main.js toh ok ok thank you :)

**Comment by ariffb25** [comment]
@Saad-bn ur welcome👍
