### ISSUE TITLE
Fake reply

### ISSUE THREAD

**Issue by ilhamimut** [Nurutomo/wabot-aq#732]
Assalamualaikum, Ada yang tau cara bikin fake reply kayak gini?

![IMG-20210817-WA0004](https://user-images.githubusercontent.com/85117653/129649037-be8a6596-380a-4e75-b4a2-2175b363ca53.jpg)

**Comment by ariffb25** [comment]
tinggal ```.q``` terus ```=> m.qouted``` contek dah
