### ISSUE TITLE
getmsg.js

### ISSUE THREAD

**Issue by Naruto010** [Nurutomo/wabot-aq#733]
how i can use it without perfix and getmsg;

let handler = async (m, { conn, command, usedPrefix, text }) => {
    let which = command.replace(/get/i, '')
    if (!text) throw `Gunakan *${usedPrefix}list${which}* untuk melihat list nya`
    let msgs = global.db.data.msgs
    if (!(text in msgs)) throw `'${text}' tidak terdaftar di list pesan`
    let _m = conn.serializeM(JSON.parse(JSON.stringify(msgs[text]), (_, v) => {
        if (
            v !== null &&
            typeof v === 'object' &&
            'type' in v &&
            v.type === 'Buffer' &&
            'data' in v &&
            Array.isArray(v.data)) {
            return Buffer.from(v.data)
        }
        return v
    }))
    // m.reply(`[debug]\n${require('util').format(_m)}`)
    await _m.copyNForward(m.chat, true)
}
handler.help = ['vn', 'msg', 'video', 'audio', 'img', 'sticker'].map(v => 'get' + v + ' <text>')
handler.tags = ['database']
handler.command = /^get(vn|msg|video|audio|img|sticker)$/

module.exports = handler

**Comment by Bintangp02** [comment]
> how i can use it without perfix and getmsg;
> 
> let handler = async (m, { conn, command, usedPrefix, text }) => {
> let which = command.replace(/get/i, '')
> if (!text) throw `Gunakan *${usedPrefix}list${which}* untuk melihat list nya`
> let msgs = global.db.data.msgs
> if (!(text in msgs)) throw `'${text}' tidak terdaftar di list pesan`
> let _m = conn.serializeM(JSON.parse(JSON.stringify(msgs[text]), (_, v) => {
> if (
> v !== null &&
> typeof v === 'object' &&
> 'type' in v &&
> v.type === 'Buffer' &&
> 'data' in v &&
> Array.isArray(v.data)) {
> return Buffer.from(v.data)
> }
> return v
> }))
> // m.reply(`[debug]\n${require('util').format(_m)}`)
> await _m.copyNForward(m.chat, true)
> }
> handler.help = ['vn', 'msg', 'video', 'audio', 'img', 'sticker'].map(v => 'get' + v + ' ')
> handler.tags = ['database']
> handler.command = /^get(vn|msg|video|audio|img|sticker)$/
> 
> module.exports = handler

Untuk apa ini dan apa fungsinya😮

**Comment by Bintang73** [comment]
> how i can use it without perfix and getmsg;
> 
> let handler = async (m, { conn, command, usedPrefix, text }) => { let which = command.replace(/get/i, '') if (!text) throw `Gunakan *${usedPrefix}list${which}* untuk melihat list nya` let msgs = global.db.data.msgs if (!(text in msgs)) throw `'${text}' tidak terdaftar di list pesan` let _m = conn.serializeM(JSON.parse(JSON.stringify(msgs[text]), (_, v) => { if ( v !== null && typeof v === 'object' && 'type' in v && v.type === 'Buffer' && 'data' in v && Array.isArray(v.data)) { return Buffer.from(v.data) } return v })) // m.reply(`[debug]\n${require('util').format(_m)}`) await _m.copyNForward(m.chat, true) } handler.help = ['vn', 'msg', 'video', 'audio', 'img', 'sticker'].map(v => 'get' + v + ' ') handler.tags = ['database'] handler.command = /^get(vn|msg|video|audio|img|sticker)$/
> 
> module.exports = handler

global.prefix = '!' or with regex
