### ISSUE TITLE
sticker no background

### ISSUE THREAD

**Issue by ilhamimut** [Nurutomo/wabot-aq#735]
assalamualaikum

kalau bisa bikinin fitur sticker no background min

**Comment by TOXIC-DEVIL** [comment]
> assalamualaikum
> 
> kalau bisa bikinin fitur sticker no background min

Tentu, saya dapat Membantu Anda dengan ini,
https://github.com/TOXIC-DEVIL/WhatsAlexa Silakan periksa ropo ini mereka menghapus perintah latar belakang, Anda dapat Menggunakan bot itu & menjadikan gambar sebagai latar belakang kemudian Anda dapat menjadikannya sebagai stiker (Dalam bahasa Indonesia ropo itu juga mendukung)

**Comment by TheUnknownPeople-user** [comment]
snobg?

**Comment by ilhamimut** [comment]
> snobg?

Iya, punya kode nya?

**Comment by hardianto-cpu** [comment]
> > snobg?
> 
> Iya, punya kode nya?
`Kamu Bisa menggunakan https://hardianto.xyz/api/removebg?url=https://i.ibb.co/7CM77tx/c180e14f43cf.jpg&apikey=hardianto Tentu nya Gratis Dan Unlimited Hit`

**Comment by Bintang73** [comment]
Pull req aja
