### ISSUE TITLE
perfix

### ISSUE THREAD

**Issue by dev0001812** [Nurutomo/wabot-aq#740]
How can I use all the commands without perfix

**Comment by unx21** [comment]
> How can I use all the commands without perfix

what the...

**Comment by dev0001812** [comment]
> > How can I use all the commands without perfix
> 
> what the...

i mean without #

**Comment by GARIOX3D** [comment]
> > > How can I use all the commands without perfix
> > 
> > 
> > what the...
> 
> i mean without #


Use Custom Prefix

handler.customPrefix = /hello/i

But not work in all Cmd

**Comment by FadliDarmawan** [comment]
> > > > How can I use all the commands without perfix
> > > 
> > > 
> > > what the...
> > 
> > 
> > i mean without #
> 
> Use Custom Prefix
> 
> handler.customPrefix = /hello/i
> 
> But not work in all Cmd

use regex?
