### ISSUE TITLE
ganti owner dimana?

### ISSUE THREAD

**Issue by Arullaja** [Nurutomo/wabot-aq#741]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HyroKidsSmp** [comment]
Owner bot config.js
Kontak owner di creator.js

**Comment by Arullaja** [comment]
creator.js dimana toh bang?

**Comment by HyroKidsSmp** [comment]
> creator.js dimana toh bang?

Di folder plugins
