### ISSUE TITLE
OVERSIZED maksudnya?

### ISSUE THREAD

**Issue by oneechan123** [Nurutomo/wabot-aq#742]
![IMG_20210826_115305](https://user-images.githubusercontent.com/73242335/130902936-acd1bf1a-26d1-417b-a46b-10a6bf29874a.jpg)
Maksudnya apa?
Btw ini pake sc stikerinbot, mau nanya di github stikerin tapi scnya udh kg suport termux

**Comment by Rizxyu** [comment]
> > ![IMG_20210826_115305](https://user-images.githubusercontent.com/73242335/130902936-acd1bf1a-26d1-417b-a46b-10a6bf29874a.jpg)
> > Maksudnya apa?
> > Btw ini pake sc stikerinbot, mau nanya di github stikerin tapi scnya udh kg suport termux
> 
> mungkin ukuran gambarnya terlalu besar :/

Yup, bner
Tapi Biasanya dokumen kayak lagu,Zip,pdf,video
Yg bisa size filenya Ampe puluhan mb
