### ISSUE TITLE
Eror Lowdb

### ISSUE THREAD

**Issue by Rizxyu** [Nurutomo/wabot-aq#744]
![Screenshot_2021-08-27-19-52-21-023_com termux](https://user-images.githubusercontent.com/88314302/131130423-ba09c93d-b116-4ea4-882b-02b8e5ea7302.png)
![Screenshot_2021-08-27-19-52-21-023_com termux](https://user-images.githubusercontent.com/88314302/131130482-fe94bc48-f918-4530-8f49-8e9276cc857e.png)
g. 22]

**Additional context**

**Comment by BochilGaming** [comment]
> Bang itu kenapa

Nodejs versi?
Npm versi?

**Comment by HyroKidsSmp** [comment]
> ![Screenshot_2021-08-27-19-52-21-023_com termux](https://user-images.githubusercontent.com/88314302/131130423-ba09c93d-b116-4ea4-882b-02b8e5ea7302.png)
> ![Screenshot_2021-08-27-19-52-21-023_com termux](https://user-images.githubusercontent.com/88314302/131130482-fe94bc48-f918-4530-8f49-8e9276cc857e.png)
> g. 22]
> 
> **Additional context**
> Add any other context about the problem here.

Coba pake lowdb di gw
