### ISSUE TITLE
cara ganti author stiker dmn

### ISSUE THREAD

**Issue by fidly12** [Nurutomo/wabot-aq#745]
dmn nya bang buat ganti author stiker biasa maupun gif makasih

**Comment by ilhamimut** [comment]
> dmn nya bang buat ganti author stiker biasa maupun gif makasih

Di config.js
Cari global.packname dan global.author

**Comment by fidly12** [comment]
![image](https://user-images.githubusercontent.com/89673097/131204941-c5797ba3-1c7e-4c13-86a0-aeda6eb96a05.png)
ttp aja gakeluar author nya

**Comment by unx21** [comment]
> ![image](https://user-images.githubusercontent.com/89673097/131204941-c5797ba3-1c7e-4c13-86a0-aeda6eb96a05.png)
> ttp aja gakeluar author nya

emang kadang ga keluar gitu kalo di ganti wm nya

**Comment by fidly12** [comment]
biar keluar gmn author stiker nya

**Comment by unx21** [comment]
> biar keluar gmn author stiker nya

entah :v

**Comment by RizkyGantengjr** [comment]
> biar keluar gmn author stiker nya

Dibagian lib sticker

**Comment by Rizxyu** [comment]
> biar keluar gmn author stiker nya

Oprek File sticker.js yg ada di lib gan
