### ISSUE TITLE
Gimana?

### ISSUE THREAD

**Issue by oneechan123** [Nurutomo/wabot-aq#746]
Cara supaya di setiap fitur pakai limit tanpa ketik "handler.limit = true" di setiap case gimana?

**Comment by Rizxyu** [comment]
Cuman bisa handler.limit aja gan
G bisa yg lain keknya

**Comment by Bintang73** [comment]
> Cara supaya di setiap fitur pakai limit tanpa ketik "handler.limit = true" di setiap case gimana?

Jadiin global
