### ISSUE TITLE
Icon fake reply

### ISSUE THREAD

**Issue by ilhamimut** [Nurutomo/wabot-aq#747]
Ada yang tau cara bikin icon fake reply kayak gini:

![IMG-20210830-WA0001](https://user-images.githubusercontent.com/85117653/131270635-3ac53083-0e74-489a-9ca7-3379ec1cc206.jpg)

**Comment by Rizxyu** [comment]
Pakek Contact array

**Comment by ilhamimut** [comment]
> Pakek Contact array

Punya contoh bentuk code nya?
