### ISSUE TITLE
Bisa gk?

### ISSUE THREAD

**Issue by oneechan123** [Nurutomo/wabot-aq#755]
Bisa gk setiap user cuma bisa masukin bot ke gc dengan jumlah tertentu

Contoh:
User 6281522815407@s.whatsapp.net cuma bisa masukin bot ke 2gc klo lebih botnya gk bakal join

Trus klo dia masukin ke gc yg sama botnya kg ngerespon

**Comment by unx21** [comment]
> Bisa gk setiap user cuma bisa masukin bot ke gc dengan jumlah tertentu
> 
> Contoh:
> User [6281522815407@s.whatsapp.net](mailto:6281522815407@s.whatsapp.net) cuma bisa masukin bot ke 2gc klo lebih botnya gk bakal join
> 
> Trus klo dia masukin ke gc yg sama botnya kg ngerespon

maksudnya gc yang sama kek gimana?

**Comment by syahrularranger** [comment]
> Bisa gk setiap user cuma bisa masukin bot ke gc dengan jumlah tertentu
> 
> Contoh:
> User [6281522815407@s.whatsapp.net](mailto:6281522815407@s.whatsapp.net) cuma bisa masukin bot ke 2gc klo lebih botnya gk bakal join
> 
> Trus klo dia masukin ke gc yg sama botnya kg ngerespon

Kasih aja database baru pas joinn


```js
// Di handler.js kasih properti baru
users.join = 0
join: 0,
//Sesuain aja

// Di join.js
let users = global.db.data.users[m.sender]
if (users.join == 2) throw `Kamu sudah join sebanyak 2 kali`
users.join += 1

```

Lalu juga

**Comment by oneechan123** [comment]
> > Bisa gk setiap user cuma bisa masukin bot ke gc dengan jumlah tertentu
> > Contoh:
> > User [6281522815407@s.whatsapp.net](mailto:6281522815407@s.whatsapp.net) cuma bisa masukin bot ke 2gc klo lebih botnya gk bakal join
> > Trus klo dia masukin ke gc yg sama botnya kg ngerespon
> 
> Kasih aja database baru pas joinn
> 
> ```js
> // Di handler.js kasih properti baru
> users.join = 0
> join: 0,
> //Sesuain aja
> 
> // Di join.js
> let users = global.db.data.users[m.sender]
> if (users.join == 2) throw `Kamu sudah join sebanyak 2 kali`
> users.join += 1
> ```

Ditaro dimana? Udh nyoba tapi kg bisa

**Comment by unx21** [comment]
> > > Bisa gk setiap user cuma bisa masukin bot ke gc dengan jumlah tertentu
> > > Contoh:
> > > User [6281522815407@s.whatsapp.net](mailto:6281522815407@s.whatsapp.net) cuma bisa masukin bot ke 2gc klo lebih botnya gk bakal join
> > > Trus klo dia masukin ke gc yg sama botnya kg ngerespon
> > 
> > 
> > Kasih aja database baru pas joinn
> > ```js
> > // Di handler.js kasih properti baru
> > users.join = 0
> > join: 0,
> > //Sesuain aja
> > 
> > // Di join.js
> > let users = global.db.data.users[m.sender]
> > if (users.join == 2) throw `Kamu sudah join sebanyak 2 kali`
> > users.join += 1
> > ```
> 
> Ditaro dimana? Udh nyoba tapi kg bisa

handler.js ama join.js
