### ISSUE TITLE
Biar kyk gini gimana?

### ISSUE THREAD

**Issue by oneechan123** [Nurutomo/wabot-aq#757]
![Screenshot_2021-09-02-06-13-06-92_7352322957d4404136654ef4adb64504](https://user-images.githubusercontent.com/73242335/131757414-a098eefd-20de-4d00-b424-612f0509c75f.jpg)
Gimana supaya kyk gini?

**Comment by TheUnknownPeople-user** [comment]
Sebelum Send Menu Kasih await m.reply('Teks Lu')

Misal: await m.reply('Mohon Tunggu Sedang Memuat Perintah')

**Comment by Adiixyz** [comment]
waduh bot gw

**Comment by TheUnknownPeople-user** [comment]
> waduh bot gw

aokaoakw Tuh Kasih Tutor Kalau Dia Gak Paham ✌🏻

**Comment by Adiixyz** [comment]
> > waduh bot gw
> 
> aokaoakw Tuh Kasih Tutor Kalau Dia Gak Paham ✌🏻

fake reply?

**Comment by TheUnknownPeople-user** [comment]
> > > waduh bot gw
> > 
> > 
> > aokaoakw Tuh Kasih Tutor Kalau Dia Gak Paham ✌🏻
> 
> fake reply?

Itu Dia Buat Issue Apa, Nah Lu Terangin Caranya Gimana Gituloh 👍🏻

**Comment by Adiixyz** [comment]
await conn.fakeReply(m.chat, `
[❗] *L O A D I N G . . .*
    *READING* _menu.js_
`, '0@s.whatsapp.net', `HALO ${conn.getName(m.sender}`, 'status@broadcast')

**Comment by ariffb25** [comment]
waduh sc gw

**Comment by Adiixyz** [comment]
> waduh sc gw

+ di recode gw:v

**Comment by FadliDarmawan** [comment]
> ```js
> conn.fakeReply(m.chat, `
> [❗] *L O A D I N G . . .*
>     *READING* _menu.js_
> `, '0@s.whatsapp.net', `HALO ${conn.getName(m.sender}`, 'status@broadcast')
> ```

buat di pakein ke global.wait nya stikerin @ariffb25 awoakwoak
btw makasih

**Comment by Adiixyz** [comment]
> > ```js
> > conn.fakeReply(m.chat, `
> > [❗] *L O A D I N G . . .*
> >     *READING* _menu.js_
> > `, '0@s.whatsapp.net', `HALO ${conn.getName(m.sender}`, 'status@broadcast')
> > ```
> 
> buat di pakein ke global.wait nya stikerin @ariffb25 awoakwoak
> btw makasih

iya sama sama:v

**Comment by frmdeveloper** [comment]
Waduh udah 26 days ago
