### ISSUE TITLE
Request: Simsimi without command/prefix

### ISSUE THREAD

**Issue by ariffb25** [Nurutomo/wabot-aq#76]
kira-kira algoritmanya gmn ya? maunya sih buat sendiri cuma masih bingung, jadi ada switch on/off nya gitu

**Comment by Nurutomo** [comment]
Nanti boros :/

**Comment by ariffb25** [comment]
uhm boros gmn?  boros request? gpp biar lagi apikeynya

**Comment by Nurutomo** [comment]
Server api nya ribet :v

**Comment by ariffb25** [comment]
tapi buat **Simsimi without command/prefix** kek gini di wabot-aq bisa? trs handler.command/customPrefix nya gmn ?

**Comment by ariffb25** [comment]
gak ngerti :v

**Comment by ariffb25** [comment]
https://github.com/Nurutomo/wabot-aq/issues/330#issuecomment-852060749
