### ISSUE TITLE
How to mention a user that used a command?

### ISSUE THREAD

**Issue by bilal-08** [Nurutomo/wabot-aq#761]
Example,

someone say : "#Slap @user1"

the bot will Reply with someone slapped user1

**Comment by Finnel465** [comment]
you know how to do that?

**Comment by Naruto010** [comment]
> you know how to do that?

how bro?

**Comment by bilal-08** [comment]
> you know how to do that?

i will try Doing it And if i succeed i will let you know

**Comment by github838** [comment]
> > you know how to do that?
> 
> 
> 
> i will try Doing it And if i succeed i will let you know 

Nothing yet?
