### ISSUE TITLE
this.parseMention is not a function on TicTacToe

### ISSUE THREAD

**Issue by Finnel465** [Nurutomo/wabot-aq#766]
I update simple.js, Tictactoe.js and _tictactoe.js and i get this.parseMention is not a function when i put !ttt

![image](https://user-images.githubusercontent.com/70238672/132643845-edb86a7f-29c1-4a76-8b00-fcad0254a1ec.png)

![image](https://user-images.githubusercontent.com/70238672/132645367-fe9c7d59-804d-46e5-b195-e85eb8294136.png)

and, i update bucin.js and works perfect!

**Comment by ariffb25** [comment]
https://github.com/Nurutomo/wabot-aq/blob/a7df1d1003401aa356341559873aa728d3df4ea6/lib/simple.js#L709-L715
check again, update ur simple.js

**Comment by Finnel465** [comment]
> https://github.com/Nurutomo/wabot-aq/blob/a7df1d1003401aa356341559873aa728d3df4ea6/lib/simple.js#L709-L715
> 
> 
> check again, update ur simple.js

Get same error:
![image](https://user-images.githubusercontent.com/70238672/132937138-fcff8566-9802-47e0-a353-ade4f81bbdce.png)

![image](https://user-images.githubusercontent.com/70238672/132937141-95a203e7-b772-42c1-9fbc-eb5b355fe112.png)

**Comment by Finnel465** [comment]
Problem resolve! thanks @ariffb25
