### ISSUE TITLE
Cara pake --db gimana??

### ISSUE THREAD

**Issue by unknowkzr** [Nurutomo/wabot-aq#767]
Kan saya jalanin bot pake heroku otomatis gabisa nge sv database ketika ada yg baru registrasi Nahh di contoh --db itu harus pake repl nahhh cara buat repl dan idupinya gimana???
bingung cara nge sv database secara cloud

**Comment by iniariaaa** [comment]
bikin databasenya bang seperti di deskripsi

**Comment by unknowkzr** [comment]
> bikin databasenya bang seperti di deskripsi

Gimana???
Yg jelas donk

**Comment by bilal-08** [comment]
> Right, I run the bot using Heroku, I can't automatically sv the database when someone has just registered. Well, in the --db example, you have to use REPL, how do you make a REPL and how do you live it???
> confused about how to sv database in the cloud

have you used Mongodb ? Try and say if it's Works
