### ISSUE TITLE
Only absolute URLs are supported on SSWEB.js

### ISSUE THREAD

**Issue by Finnel465** [Nurutomo/wabot-aq#768]
Only absolute URLs are supported when i type !ssweb all websites
Console

![image](https://user-images.githubusercontent.com/70238672/132938001-46d9682a-d7fb-4064-94b4-e466bfb708be.png)

whatsapp

![image](https://user-images.githubusercontent.com/70238672/132938010-0582b6bc-31bc-4024-bd25-02030cd6b9ce.png)

**Comment by TOXIC-DEVIL** [comment]
I have fixed it 👋 
If collaborators/owners accept my pull, it will be fixed 📌

> Only absolute URLs are supported when i type !ssweb all websites
> Console
> 
> ![image](https://user-images.githubusercontent.com/70238672/132938001-46d9682a-d7fb-4064-94b4-e466bfb708be.png)
> 
> whatsapp
> 
> ![image](https://user-images.githubusercontent.com/70238672/132938010-0582b6bc-31bc-4024-bd25-02030cd6b9ce.png)

**Comment by FadliDarmawan** [comment]
> Only absolute URLs are supported when i type !ssweb all websites
> Console
> 
> ![image](https://user-images.githubusercontent.com/70238672/132938001-46d9682a-d7fb-4064-94b4-e466bfb708be.png)
> 
> whatsapp
> 
> ![image](https://user-images.githubusercontent.com/70238672/132938010-0582b6bc-31bc-4024-bd25-02030cd6b9ce.png)

that's coz ssweb using global api, and maybe in your config.js doesnt have global api

example
global api for ssweb is sswebapi
so, await fetch(global.API('sswebapi' ect
and in your config.js doenst have sswebapi

**Comment by BochilGaming** [comment]
> > Only absolute URLs are supported when i type !ssweb all websites
> > Console
> > ![image](https://user-images.githubusercontent.com/70238672/132938001-46d9682a-d7fb-4064-94b4-e466bfb708be.png)
> > whatsapp
> > ![image](https://user-images.githubusercontent.com/70238672/132938010-0582b6bc-31bc-4024-bd25-02030cd6b9ce.png)
> 
> that's coz ssweb using global api, and maybe in your config.js doesnt have global api
> 
> example
> global api for ssweb is sswebapi
> so, await fetch(global.API('sswebapi' ect
> and in your config.js doenst have sswebapi

use http or https in url

**Comment by Finnel465** [comment]
> > > Only absolute URLs are supported when i type !ssweb all websites
> > > Console
> > > ![image](https://user-images.githubusercontent.com/70238672/132938001-46d9682a-d7fb-4064-94b4-e466bfb708be.png)
> > > whatsapp
> > > ![image](https://user-images.githubusercontent.com/70238672/132938010-0582b6bc-31bc-4024-bd25-02030cd6b9ce.png)
> > 
> > 
> > that's coz ssweb using global api, and maybe in your config.js doesnt have global api
> > example
> > global api for ssweb is sswebapi
> > so, await fetch(global.API('sswebapi' ect
> > and in your config.js doenst have sswebapi
> 
> use http or https in url

Thanks!!
