### ISSUE TITLE
Console.log Credentials after scanning 

### ISSUE THREAD

**Issue by bilal-08** [Nurutomo/wabot-aq#770]
i want to Show Loggin credentials in Console log after scanning the Qr code how do i do that?

**Comment by BochilGaming** [comment]
> i want to Show Loggin credentials in Console log after scanning the Qr code how do i do that?

you can open anda read file session.data.sjon

**Comment by bilal-08** [comment]
> > i want to Show Loggin credentials in Console log after scanning the Qr code how do i do that?
> 
> you can open anda read file session.data.sjon

-_-

if we can do that then adding it to heroku would be easier

**Comment by BochilGaming** [comment]
> > > i want to Show Loggin credentials in Console log after scanning the Qr code how do i do that?
> > 
> > 
> > you can open anda read file session.data.sjon
> 
> -_-
> 
> if we can do that then adding it to heroku would be easier

Under [this](https://github.com/Nurutomo/wabot-aq/blob/a7df1d1003401aa356341559873aa728d3df4ea6/main.js#L109) add kode ```console.log(JSON.stringify(conn.base64EncodedAuthInfo())```

**Comment by bilal-08** [comment]
> > > > i want to Show Loggin credentials in Console log after scanning the Qr code how do i do that?
> > > 
> > > 
> > > you can open anda read file session.data.sjon
> > 
> > 
> > -_-
> > if we can do that then adding it to heroku would be easier
> 
> Under [this](https://github.com/Nurutomo/wabot-aq/blob/a7df1d1003401aa356341559873aa728d3df4ea6/main.js#L109) add kode `console.log(JSON.stringify(conn.base64EncodedAuthInfo())`

okay thanks will try
