### ISSUE TITLE
Kanapa harus mengulangnya!

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#773]
Mengapa scan qr harus mengulangnya dari awal lagi dan tidak tersimpan dalam bentuk sesion?
Tolong ,please bantu saya🙏

>Trimakasih yang sudah membantu

**Comment by unx21** [comment]
> Mengapa scan qr harus mengulangnya dari awal lagi dan tidak tersimpan dalam bentuk sesion?
> Tolong ,please bantu saya🙏
> 
> > Trimakasih yang sudah membantu

untuk penggunaan via termux install mc terlebih dahulu

dalam folder bot biasa terdapat session.data dan jika tidak ditemukan, mungkin session.data tersebut dipindahkan dan belum dimasukkan kembali kedalam file bot itu,

semoga bisa membantu

**Comment by Bintangp02** [comment]
> > Mengapa scan qr harus mengulangnya dari awal lagi dan tidak tersimpan dalam bentuk sesion?
> > Tolong ,please bantu saya🙏
> > > Trimakasih yang sudah membantu
> 
> untuk penggunaan via termux install mc terlebih dahulu
> 
> dalam folder bot biasa terdapat session.data dan jika tidak ditemukan, mungkin session.data tersebut dipindahkan dan belum dimasukkan kembali kedalam file bot itu,
> 
> semoga bisa membantu

Saya sudah Meng scan Nya Kenapa Tidak Bisa menyimpannya Dan Saya merasa tidak memindahkan nya🙏
>>>>Please,tolong🙏

**Comment by unx21** [comment]
> > > Mengapa scan qr harus mengulangnya dari awal lagi dan tidak tersimpan dalam bentuk sesion?
> > > Tolong ,please bantu saya🙏
> > > > Trimakasih yang sudah membantu
> > 
> > 
> > untuk penggunaan via termux install mc terlebih dahulu
> > dalam folder bot biasa terdapat session.data dan jika tidak ditemukan, mungkin session.data tersebut dipindahkan dan belum dimasukkan kembali kedalam file bot itu,
> > semoga bisa membantu
> 
> Saya sudah Meng scan Nya Kenapa Tidak Bisa menyimpannya Dan Saya merasa tidak memindahkan nya🙏
> 
> > > > > Please,tolong🙏

![20210914_112854](https://user-images.githubusercontent.com/84166927/133190376-3a9ca226-c1b7-4d5d-beda-3792dbea5ac1.jpg)

kira" seperti itu nama session.data nya di luar file bot

**Comment by unx21** [comment]
punya whatsapp? saya akan membantu sebisa mungkin

**Comment by BochilGaming** [comment]
> Mengapa scan qr harus mengulangnya dari awal lagi dan tidak tersimpan dalam bentuk sesion?
> Tolong ,please bantu saya🙏
> 
> > Trimakasih yang sudah membantu

Setalah anda men scan qr coba tunggu beberapa saat sampai di terminal muncul pesan dari whatsapp anda

**Comment by Bintangp02** [comment]
> punya whatsapp? saya akan membantu sebisa mungkin

Boleh Ini Nomer saya & berteman lah dengan Saya 089647417373
