### ISSUE TITLE
Saya sudah MenScan QR Kenapa eror?!

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#774]
Saya sudah mennScan QR Masih Saja Eror 
Kejadian nya Waktu Saya Scan Di Termux Sudah Keluar Sesion Nya, Sesudahnya Saya Pindahkan Sesion Ke Sdcard.
Setelah nya Saya Upload di github saya Dan Saya Mendeploy repositori waboy-aq ini, setelahnya saya edit dan dll,, saya upload Sesion Json nya masih saja belum bisa di ran ke Heroku

>>Mohon Bantuannya Trimakasih🙏

**Comment by unx21** [comment]
> Saya sudah mennScan QR Masih Saja Eror
> Kejadian nya Waktu Saya Scan Di Termux Sudah Keluar Sesion Nya, Sesudahnya Saya Pindahkan Sesion Ke Sdcard.
> Setelah nya Saya Upload di github saya Dan Saya Mendeploy repositori waboy-aq ini, setelahnya saya edit dan dll,, saya upload Sesion Json nya masih saja belum bisa di ran ke Heroku
> 
> > > Mohon Bantuannya Trimakasih🙏

ketika kamu mengupload nya, apakah session.data tersebut telah di masukkan kembali kedalam file wabot-aq atau belum?

**Comment by Bintangp02** [comment]
> > Saya sudah mennScan QR Masih Saja Eror
> > Kejadian nya Waktu Saya Scan Di Termux Sudah Keluar Sesion Nya, Sesudahnya Saya Pindahkan Sesion Ke Sdcard.
> > Setelah nya Saya Upload di github saya Dan Saya Mendeploy repositori waboy-aq ini, setelahnya saya edit dan dll,, saya upload Sesion Json nya masih saja belum bisa di ran ke Heroku
> > > > Mohon Bantuannya Trimakasih🙏
> 
> ketika kamu mengupload nya, apakah session.data tersebut telah di masukkan kembali kedalam file wabot-aq atau belum?

Apakah anda bisa menjelaskan ?
