### ISSUE TITLE
Eror Pada Salah Satu Menu!

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#777]
Eror pada menu
toimg2, toimg

>>Mohon Diperbaiki🙏

**Comment by BochilGaming** [comment]
> Eror pada menu
> toimg2, toimg
> 
> > > Mohon Diperbaiki🙏

install buildpack imagemagick ama ffmpeg kalau di heroku

**Comment by Bintangp02** [comment]
> > Eror pada menu
> > toimg2, toimg
> > > > Mohon Diperbaiki🙏
> 
> install buildpack imagemagick ama ffmpeg kalau di heroku

Bagaimana cara menginstalnya apa saya perlu install di console

**Comment by Bintangp02** [comment]
> > Eror pada menu
> > toimg2, toimg
> > > > Mohon Diperbaiki🙏
> 
> install buildpack imagemagick ama ffmpeg kalau di heroku

![16317719442235254129032730709787](https://user-images.githubusercontent.com/80300921/133557827-68e13c21-6adf-440e-ac8a-1a13e31e63ce.jpg)

Udah gw install bang tapi masih aja eror

**Comment by BochilGaming** [comment]
> > > Eror pada menu
> > > toimg2, toimg
> > > > > Mohon Diperbaiki🙏
> > 
> > 
> > install buildpack imagemagick ama ffmpeg kalau di heroku
> 
> ![16317719442235254129032730709787](https://user-images.githubusercontent.com/80300921/133557827-68e13c21-6adf-440e-ac8a-1a13e31e63ce.jpg)
> 
> [Gw juga eror di heroku!+ Toimg toimg2 eror🙏](https://github.com/Nurutomo/wabot-aq/issues/778)
> 
> Udah gw install bang tapi masih aja eror

errornya gimana?

**Comment by Bintangp02** [comment]
> > > > Eror pada menu
> > > > toimg2, toimg
> > > > > > Mohon Diperbaikipray
> > > 
> > > 
> > > install buildpack imagemagick ama ffmpeg kalau di heroku
> > 
> > 
> > ![16317719442235254129032730709787](https://user-images.githubusercontent.com/80300921/133557827-68e13c21-6adf-440e-ac8a-1a13e31e63ce.jpg)
> > [Gw juga eror di heroku!+ Toimg toimg2 erorpray](https://github.com/Nurutomo/wabot-aq/issues/778)
> > Udah gw install bang tapi masih aja eror
> 
> errornya gimana?

#779 

**untuk fitur yang eror play,toimg, yang berhubungan dengan mengirim file bot eror merespon tetapi eror**

**Comment by Bintang73** [comment]
Buildpack ffmpeg mu bermasalah
