### ISSUE TITLE
Eror Ketika Run di Heroku!

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#778]
Eror Run Heroku Saya Sudah Menginstal Buildpacks kenapa untuk menu seperti converter contoh .stiker, toimg eror?

>Ada yang yang tahu, tolong bantu🙏
![16317711860796116899397450764124](https://user-images.githubusercontent.com/80300921/133556573-85c6750c-7110-48fa-a6bf-42ef9d40aa24.jpg)

![16317719442235254129032730709787](https://user-images.githubusercontent.com/80300921/133557827-68e13c21-6adf-440e-ac8a-1a13e31e63ce.jpg)

**Comment by ariffb25** [comment]
upload blom kelar jgn langsung komen

**Comment by Bintangp02** [comment]
> upload blom kelar jgn langsung komen

Udh gw edit bruh sory  gw nge stug 😮

**Comment by BochilGaming** [comment]
> Eror Run Heroku Saya Sudah Menginstal Buildpacks kenapa untuk menu seperti converter contoh .stiker, toimg eror?
> 
> > Ada yang yang tahu, tolong bantu🙏
> > ![16317711860796116899397450764124](https://user-images.githubusercontent.com/80300921/133556573-85c6750c-7110-48fa-a6bf-42ef9d40aa24.jpg)
> 
> ![16317719442235254129032730709787](https://user-images.githubusercontent.com/80300921/133557827-68e13c21-6adf-440e-ac8a-1a13e31e63ce.jpg)

full errornya?

**Comment by Bintangp02** [comment]
> > Eror Run Heroku Saya Sudah Menginstal Buildpacks kenapa untuk menu seperti converter contoh .stiker, toimg eror?
> > > Ada yang yang tahu, tolong bantupray
> > > ![16317711860796116899397450764124](https://user-images.githubusercontent.com/80300921/133556573-85c6750c-7110-48fa-a6bf-42ef9d40aa24.jpg)
> > 
> > 
> > ![16317719442235254129032730709787](https://user-images.githubusercontent.com/80300921/133557827-68e13c21-6adf-440e-ac8a-1a13e31e63ce.jpg)
> 
> full errornya?

#779

**Comment by BochilGaming** [comment]
> > > Eror Run Heroku Saya Sudah Menginstal Buildpacks kenapa untuk menu seperti converter contoh .stiker, toimg eror?
> > > > Ada yang yang tahu, tolong bantupray
> > > > ![16317711860796116899397450764124](https://user-images.githubusercontent.com/80300921/133556573-85c6750c-7110-48fa-a6bf-42ef9d40aa24.jpg)
> > > 
> > > 
> > > ![16317719442235254129032730709787](https://user-images.githubusercontent.com/80300921/133557827-68e13c21-6adf-440e-ac8a-1a13e31e63ce.jpg)
> > 
> > 
> > full errornya?
> 
> nih #779
> 
> untuk fitur yang eror play,toimg, yang berhubungan dengan mengirim file bot eror merespon tetapi eror

coba liat file config.js mu yang bagian global.prems
