### ISSUE TITLE
EROR !

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#779]
Saya run bot ini di heroku kenapa eror yak ada yang tahu?
>> [Buildpacks udah saya Tambahin](https://user-images.githubusercontent.com/80300921/133557827-68e13c21-6adf-440e-ac8a-1a13e31e63ce.jpg)

Kenapa masih saja eror?
Saran @BochilGaming Install Ffmpeg saya sudah Menginstal nya sebelum nya,

Untuk @ariffb25 saya masih menunggu anda untuk menjawabnya🙏

**Issue Saya Lainnya #777 #778**

Tolong Di Balas🙏, Saya Masih Pemula Untuk Hal ini..

Trimakasih Banyak Untuk Semua Colabtor dan Nurutomo🙏

**Comment by BochilGaming** [comment]
> Saya run bot ini di heroku kenapa eror yak ada yang tahu?
> 
> > > [Buildpacks udah saya Tambahin](https://user-images.githubusercontent.com/80300921/133557827-68e13c21-6adf-440e-ac8a-1a13e31e63ce.jpg)
> 
> Kenapa masih saja eror?
> Saran @BochilGaming Install Ffmpeg saya sudah Menginstal nya sebelum nya,
> 
> Untuk @ariffb25 saya masih menunggu anda untuk menjawabnya🙏
> 
> **Issue Saya Lainnya #777 #778**
> 
> Tolong Di Balas🙏, Saya Masih Pemula Untuk Hal ini..
> 
> Trimakasih Banyak Untuk Semua Colabtor dan Nurutomo🙏

ss error nya?

**Comment by BochilGaming** [comment]
> > Saya run bot ini di heroku kenapa eror yak ada yang tahu?
> > > > [Buildpacks udah saya Tambahin](https://user-images.githubusercontent.com/80300921/133557827-68e13c21-6adf-440e-ac8a-1a13e31e63ce.jpg)
> > 
> > 
> > Kenapa masih saja eror?
> > Saran @BochilGaming Install Ffmpeg saya sudah Menginstal nya sebelum nya,
> > Untuk @ariffb25 saya masih menunggu anda untuk menjawabnya🙏
> > **Issue Saya Lainnya #777 #778**
> > Tolong Di Balas🙏, Saya Masih Pemula Untuk Hal ini..
> > Trimakasih Banyak Untuk Semua Colabtor dan Nurutomo🙏
> 
> ss error nya? (full error)

**Comment by Bintangp02** [comment]
> > Saya run bot ini di heroku kenapa eror yak ada yang tahu?
> > > > [Buildpacks udah saya Tambahin](https://user-images.githubusercontent.com/80300921/133557827-68e13c21-6adf-440e-ac8a-1a13e31e63ce.jpg)
> > 
> > 
> > Kenapa masih saja eror?
> > Saran @BochilGaming Install Ffmpeg saya sudah Menginstal nya sebelum nya,
> > Untuk @ariffb25 saya masih menunggu anda untuk menjawabnyapray
> > **Issue Saya Lainnya #777 #778**
> > Tolong Di Balaspray, Saya Masih Pemula Untuk Hal ini..
> > Trimakasih Banyak Untuk Semua Colabtor dan Nurutomopray
> 
> ss error nya? (full error)

anda dapat melihat nya di link berikut https://drive.google.com/folderview?id=1m_9J06U9HwnQjrasuvCE3_QRpGFesW0w

**Comment by BochilGaming** [comment]
> > > Saya run bot ini di heroku kenapa eror yak ada yang tahu?
> > > > > [Buildpacks udah saya Tambahin](https://user-images.githubusercontent.com/80300921/133557827-68e13c21-6adf-440e-ac8a-1a13e31e63ce.jpg)
> > > 
> > > 
> > > Kenapa masih saja eror?
> > > Saran @BochilGaming Install Ffmpeg saya sudah Menginstal nya sebelum nya,
> > > Untuk @ariffb25 saya masih menunggu anda untuk menjawabnyapray
> > > **Issue Saya Lainnya #777 #778**
> > > Tolong Di Balaspray, Saya Masih Pemula Untuk Hal ini..
> > > Trimakasih Banyak Untuk Semua Colabtor dan Nurutomopray
> > 
> > 
> > ss error nya? (full error)
> 
> anda dapat melihat nya di link berikut https://drive.google.com/folderview?id=1m_9J06U9HwnQjrasuvCE3_QRpGFesW0w

Ada wa?

**Comment by Lord-Gaming** [comment]
Gk usah nyepam issue lah klo eror nya itu2 aja

**Comment by Bintangp02** [comment]
> > > > Saya run bot ini di heroku kenapa eror yak ada yang tahu?
> > > > > > [Buildpacks udah saya Tambahin](https://user-images.githubusercontent.com/80300921/133557827-68e13c21-6adf-440e-ac8a-1a13e31e63ce.jpg)
> > > > 
> > > > 
> > > > Kenapa masih saja eror?
> > > > Saran @BochilGaming Install Ffmpeg saya sudah Menginstal nya sebelum nya,
> > > > Untuk @ariffb25 saya masih menunggu anda untuk menjawabnyapray
> > > > **Issue Saya Lainnya #777 #778**
> > > > Tolong Di Balaspray, Saya Masih Pemula Untuk Hal ini..
> > > > Trimakasih Banyak Untuk Semua Colabtor dan Nurutomopray
> > > 
> > > 
> > > ss error nya? (full error)
> > 
> > 
> > anda dapat melihat nya di link berikut https://drive.google.com/folderview?id=1m_9J06U9HwnQjrasuvCE3_QRpGFesW0w
> 
> Ada wa?

089647417373

**Comment by Bintangp02** [comment]
![Screenshot_20210917_192611](https://user-images.githubusercontent.com/80300921/133782776-754f1954-4631-494e-a513-04a0294008ef.jpg)

Saya temui eror pada tiktok!?

**Comment by ariffb25** [comment]
1. toimg emng ga support di linux, makanya itu udh lama w buat toimg2 tuh
2. v.replace harusnya sih gmslh

**Comment by BochilGaming** [comment]
> ![Screenshot_20210917_192611](https://user-images.githubusercontent.com/80300921/133782776-754f1954-4631-494e-a513-04a0294008ef.jpg)
> 
> Saya temui eror pada tiktok!?
> Karna tidak merespon
> 
> Info : saya run di heroku
> 
> Tulisan eror yang ditampilkan pada pesan..
> 
> <title>api.xteam.xyz | 522: Connection timed out</title>
> ```
> <div id="cf-error-details" class="p-0">
>     <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
>         <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
>           
>           <span class="cf-error-type">Error</span>
>           <span class="cf-error-code">522</span>
>         </h1>
>         <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 690253e3fc3c57c7 &bull;</span>
>         <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">2021-09-17 12:27:47 UTC</span>
>         <h2 class="text-gray-600 leading-1.3 text-3xl font-light">Connection timed out</h2>
>     </header>
>     
>     <div class="my-8 bg-gradient-gray">
>         <div class="w-240 lg:w-full mx-auto">
>             <div class="clearfix md:px-8">
> ```
> 
> You
> ### Browser
> Working
> Ashburn
> ### Cloudflare
> Working
> api.xteam.xyz
> ### Host
> Error
> ```
>             </div>
>           
>         </div>
>     </div>
> 
>     <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
>         <div class="clearfix">
>             <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
>                 <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
>                 <p>The initial connection between Cloudflare's network and the origin web server timed out. As a result, the web page can not be displayed.</p>
>             </div>
>           
>             <div class="w-1/2 md:w-full float-left leading-relaxed">
>                 <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
>                       <h3 class="text-15 font-semibold mb-2">If you're a visitor of this website:</h3>
>   <p class="mb-6">Please try again in a few minutes.</p>
> 
>   <h3 class="text-15 font-semibold mb-2">If you're the owner of this website:</h3>
>   <p><span>Contact your hosting provider letting them know your web server is not completing requests. An Error 522 means that the request was able to connect to your web server, but that the request didn't finish. The most likely cause is that something on your server is hogging resources.</span> <a rel="noopener noreferrer" href="https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522">Additional troubleshooting information here.</a></p>
>             </div>
>         </div>
>           
>     </div>
> 
>     <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
> ```
> 
> Cloudflare Ray ID: **690253e3fc3c57c7** • Your IP: 3.216.123.98 • Performance & security by [Cloudflare](https://www.cloudflare.com/5xx-error-landing)
> 
> ```
> </div>
> ```
> 
> Saya memakai Apikey sebagian premium untuk x team premium kenapa eror atau dari server nya?

itu web xteam nya down

**Comment by Bintangp02** [comment]
> > ![Screenshot_20210917_192611](https://user-images.githubusercontent.com/80300921/133782776-754f1954-4631-494e-a513-04a0294008ef.jpg)
> > Saya temui eror pada tiktok!?
> > Karna tidak merespon
> > Info : saya run di heroku
> > Tulisan eror yang ditampilkan pada pesan..
> > <title>api.xteam.xyz | 522: Connection timed out</title>
> > ```
> > 
> >     
> >         # 
> > ```
> >       <span class="cf-error-type">Error</span>
> >       <span class="cf-error-code">522</span>
> >     </h1>
> >     <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 690253e3fc3c57c7 &bull;</span>
> >     <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">2021-09-17 12:27:47 UTC</span>
> >     <h2 class="text-gray-600 leading-1.3 text-3xl font-light">Connection timed out</h2>
> > </header>
> > 
> > <div class="my-8 bg-gradient-gray">
> >     <div class="w-240 lg:w-full mx-auto">
> >         <div class="clearfix md:px-8">
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 
> > You
> > ### Browser
> > Working
> > Ashburn
> > ### Cloudflare
> > Working
> > api.xteam.xyz
> > ### Host
> > Error
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> >         </div>
> >       
> >     </div>
> > </div>
> > 
> > <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
> >     <div class="clearfix">
> >         <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
> >             <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
> >             <p>The initial connection between Cloudflare's network and the origin web server timed out. As a result, the web page can not be displayed.</p>
> >         </div>
> >       
> >         <div class="w-1/2 md:w-full float-left leading-relaxed">
> >             <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
> >                   <h3 class="text-15 font-semibold mb-2">If you're a visitor of this website:</h3>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> >   Please try again in a few minutes.
> >   ### If you're the owner of this website:
> >   Contact your hosting provider letting them know your web server is not completing requests. An Error 522 means that the request was able to connect to your web server, but that the request didn't finish. The most likely cause is that something on your server is hogging resources. [Additional troubleshooting information here.](https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522)
> >             
> >         
> > ```
> > </div>
> > 
> > <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 
> > Cloudflare Ray ID: **690253e3fc3c57c7** • Your IP: 3.216.123.98 • Performance & security by [Cloudflare](https://www.cloudflare.com/5xx-error-landing)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > ```
> > Saya memakai Apikey sebagian premium untuk x team premium kenapa eror atau dari server nya?
> 
> itu web xteam nya [down](https://github.com/Nurutomo/wabot-aq/issues/488#issuecomment-869091138)

Oke bang mungkin x team suruh jadi Prem dulu🙃
