### ISSUE TITLE
Website xteam kok skrg sering banget error?

### ISSUE THREAD

**Issue by Andika856** [Nurutomo/wabot-aq#780]
![Screenshot_2021-09-17-18-57-35-56](https://user-images.githubusercontent.com/78887981/133779090-a2eb7731-5db2-4e2d-8c09-06d8804d7dbd.jpg)

Ini udh terjadi dua kali sama gw
Ini kenapa ya?

**Comment by unx21** [comment]
> ![Screenshot_2021-09-17-18-57-35-56](https://user-images.githubusercontent.com/78887981/133779090-a2eb7731-5db2-4e2d-8c09-06d8804d7dbd.jpg)
> 
> Ini udh terjadi dua kali sama gw
> Ini kenapa ya?

bukan cuma anda...

**Comment by ariffb25** [comment]
donasi bng

**Comment by jauhari21** [comment]
> ![Screenshot_2021-09-17-18-57-35-56](https://user-images.githubusercontent.com/78887981/133779090-a2eb7731-5db2-4e2d-8c09-06d8804d7dbd.jpg)
> 
> Ini udh terjadi dua kali sama gw
> Ini kenapa ya?

Bantu donasi bang, beli premium biar ga eror

**Comment by Andika856** [comment]
> > ![Screenshot_2021-09-17-18-57-35-56](https://user-images.githubusercontent.com/78887981/133779090-a2eb7731-5db2-4e2d-8c09-06d8804d7dbd.jpg)
> > Ini udh terjadi dua kali sama gw
> > Ini kenapa ya?
> 
> Bantu donasi bang, beli premium biar ga eror

Masalahnya saya freebie bang ._.

**Comment by Bintangp02** [comment]
> donasi bng

Hehe bruh

**Comment by frmdeveloper** [comment]
> ![Screenshot_2021-09-17-18-57-35-56](https://user-images.githubusercontent.com/78887981/133779090-a2eb7731-5db2-4e2d-8c09-06d8804d7dbd.jpg)
> 
> Ini udh terjadi dua kali sama gw
> Ini kenapa ya?

tanya ama pembuat domain
Jangan tanya kepada pemilik xteam
Hehe

**Comment by Bintang73** [comment]
Saya usahakan gak akan down lagi, xteam belakangan ini diserang sama bocil hekel. Terimakasih
