### ISSUE TITLE
Fix Undefined?

### ISSUE THREAD

**Issue by muthzzz** [Nurutomo/wabot-aq#781]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BochilGaming** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Version [e.g. 22]
> 
> **Additional context**
> Add any other context about the problem here.

detailnya mana? apaanya yang undefined?, command apa yang ngebug?, kalau error full error nya mana?

**Comment by oneechan123** [comment]
> > **Describe the bug**
> > A clear and concise description of what the bug is.
> > **To Reproduce**
> > Steps to reproduce the behavior:
> > 
> > 1. Go to '...'
> > 2. Click on '....'
> > 3. Scroll down to '....'
> > 4. See error
> > 
> > **Expected behavior**
> > A clear and concise description of what you expected to happen.
> > **Screenshots**
> > If applicable, add screenshots to help explain your problem.
> > **Desktop (please complete the following information):**
> > 
> > * Browser [e.g. chrome, safari]
> > * Version [e.g. 22]
> > 
> > **Smartphone (please complete the following information):**
> > 
> > * Device: [e.g. iPhone6]
> > * OS: [e.g. iOS8.1]
> > * Version [e.g. 22]
> > 
> > **Additional context**
> > Add any other context about the problem here.
> 
> detailnya mana? apaanya yang undefined?, command apa yang ngebug?, kalau error full error nya mana?

Di fitur .grouplist

**Comment by BochilGaming** [comment]
> > > **Describe the bug**
> > > A clear and concise description of what the bug is.
> > > **To Reproduce**
> > > Steps to reproduce the behavior:
> > > 
> > > 1. Go to '...'
> > > 2. Click on '....'
> > > 3. Scroll down to '....'
> > > 4. See error
> > > 
> > > **Expected behavior**
> > > A clear and concise description of what you expected to happen.
> > > **Screenshots**
> > > If applicable, add screenshots to help explain your problem.
> > > **Desktop (please complete the following information):**
> > > 
> > > * Browser [e.g. chrome, safari]
> > > * Version [e.g. 22]
> > > 
> > > **Smartphone (please complete the following information):**
> > > 
> > > * Device: [e.g. iPhone6]
> > > * OS: [e.g. iOS8.1]
> > > * Version [e.g. 22]
> > > 
> > > **Additional context**
> > > Add any other context about the problem here.
> > 
> > 
> > detailnya mana? apaanya yang undefined?, command apa yang ngebug?, kalau error full error nya mana?
> 
> Di fitur .grouplist

restat botnya aja :v
