### ISSUE TITLE
Error npm install

### ISSUE THREAD

**Issue by qisyana** [Nurutomo/wabot-aq#782]
Termux ku version 0.117 pass bagian npm install error'

**Comment by qisyana** [comment]
![Screenshot_2021-09-19-07-36-41-450_com termux](https://user-images.githubusercontent.com/79745902/133911935-d70bb9ac-2be3-41eb-bfaf-b838ff2a2b15.jpg)

**Comment by Bintangp02** [comment]
Git clone atau dwonlod Script baru npm i..?

**Comment by qisyana** [comment]
> Git clone atau dwonlod Script baru npm i..?

git clone

**Comment by Bintang73** [comment]
Update node js ke versi terbaru
