### ISSUE TITLE
Apa fungsi dari (document/restrict/nyimak/pconly/gconly/swonly/viewonce) coba jelasin satu persatu dong

### ISSUE THREAD

**Issue by ghost** [Nurutomo/wabot-aq#783]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lord-Gaming** [comment]
Lah itu kan udh di jelasin :/

**Comment by Adhwa9981** [comment]
Tapi gw ga ngerti lgi

**Comment by BochilGaming** [comment]
> Tapi gw ga ngerti lgi

baca readme.md

**Comment by Bintangp02** [comment]
> Tapi gw ga ngerti lgi

Baca aja di readme.md itu semua bahasa Inggris Kalau ngak faham Mending lu translate kalau gw agak mudenk🐈

**Comment by Rizxyu** [comment]
Translate lah, masa punya hp g tau translate

> Tapi gw ga ngerti lgi
