### ISSUE TITLE
Cara gunain -db gimana?

### ISSUE THREAD

**Issue by nobar123** [Nurutomo/wabot-aq#785]
Cara gunain  -DB gimana diheroku?

**Comment by aniq12** [comment]
procfile nya di edit

**Comment by Bintangp02** [comment]
> procfile nya di edit

DB itu fungsinya untuk apa bang jelasin dong yang di readme.md binggung :v

**Comment by Lord-Patrick** [comment]
buat database :v

**Comment by Rizxyu** [comment]
> buat database :v

Bukan untuk ngocor:v
