### ISSUE TITLE
(closed connection, reason lost, reconnecting in a few seconds...) WELPPPP!!!

### ISSUE THREAD

**Issue by Rizen111** [Nurutomo/wabot-aq#786]
![Screenshot (13)](https://user-images.githubusercontent.com/67272351/134565631-b7e8ca03-42a8-4a97-a3bc-df0cf929b2ca.png)
 WELPPPP!

**Comment by BochilGaming** [comment]
> ![Screenshot (13)](https://user-images.githubusercontent.com/67272351/134565631-b7e8ca03-42a8-4a97-a3bc-df0cf929b2ca.png)
> WELPPPP!

internetmu ngelag

**Comment by unx21** [comment]
> > ![Screenshot (13)](https://user-images.githubusercontent.com/67272351/134565631-b7e8ca03-42a8-4a97-a3bc-df0cf929b2ca.png)
> > WELPPPP!
> 
> internetmu ngelag

wkwkk

**Comment by Bintang73** [comment]
Your internet has a problem
