### ISSUE TITLE
Mohon Bantuan nya makasih*

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#787]
Jadi bot saya jalan di heroku untuk semua fitur work😐
Tetapi Bot saya Tidak Bisa menampilkan menu ke Tika di ran heroku, Buildpacks udah lengkap saya udah lihat di yt ariffb, kenapa ngak bisa munculkan menu nya aja!?
![Screenshot_20210924_204610](https://user-images.githubusercontent.com/80300921/134752977-9a5dcc83-40cc-4370-b0ee-96aa7d8d6b3d.jpg)

**Comment by aniq12** [comment]
liat error di logs nya coba

**Comment by Bintangp02** [comment]
> liat error di logs nya coba

Saya run di heroku bang di view logs ngak muncul eror nya tapi pesan yang saya kirim ke bot masuk bang tapi ngak di bales otomatis sama bot..

**Comment by BochilGaming** [comment]
> > liat error di logs nya coba
> 
> Saya run di heroku bang di view logs ngak muncul eror nya tapi pesan yang saya kirim ke bot masuk bang tapi ngak di bales otomatis sama bot..

botnya udh run?
