### ISSUE TITLE
Run di replit

### ISSUE THREAD

**Issue by botstylee** [Nurutomo/wabot-aq#788]
Bruh ada yang tau gak cara install modul imagemagick ffmpeg sama webp-converter di replit gw soal gagal Mulu gak mau ke baca modulnya yg udh gw install

**Comment by frmdeveloper** [comment]
di replit jangan pakek nodejs
Pakailah bash.
disitu udah ada apt ffmpeg, imagemagick
Tapi gak ada libwebp
