### ISSUE TITLE
Bagai mana menyimpan nya?

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#789]
[Aku run di heroku kenapa data base nya ngak ke add ke github, heroku github github heroku gimana tu tolong bantuin gw agar database nya bisa ke add otomatis ke github kita ,dan bisa berkolaborasi dengan heroku🐈](https://github.com/bintangp02)

**Comment by BochilGaming** [comment]
> [Aku run di heroku kenapa data base nya ngak ke add ke github, heroku github github heroku gimana tu tolong bantuin gw agar database nya bisa ke add otomatis ke github kita ,dan bisa berkolaborasi dengan heroku🐈](https://github.com/bintangp02)

ya up manual lah
