### ISSUE TITLE
Kesalahan Module(node index.js) 

### ISSUE THREAD

**Issue by Paudgans** [Nurutomo/wabot-aq#791]
![Screenshot_2021-09-28-22-18-20-432_com termux](https://user-images.githubusercontent.com/80304381/135128743-a3b6a014-0d92-421d-b919-9cbecd54d812.jpg)

Min Knapa Pas Node index.js nya eror mulu, module nya not found

**Comment by unx21** [comment]
install lewat mana?

**Comment by Paudgans** [comment]
Saya coba termux biasa, termux ubuntu ttp eror module nya gk mau kebaca, tolong penjelasanya bang

**Comment by unx21** [comment]
ada whatsapp? saya memiliki beberapa kenalan yang mungkin bisa membantu anda

**Comment by Paudgans** [comment]
Kalo ada yang salah, tolong di benarkan min, saya pusing hehe

**Comment by Paudgans** [comment]
089644906925
Wa.me//6289644906025

**Comment by Paudgans** [comment]
Mohon bimbinganya bang

**Comment by BochilGaming** [comment]
> Mohon bimbinganya bang

```bash
npm install -g npm@6.14.14
npm install
node .
```

**Comment by Bintang73** [comment]
> > Mohon bimbinganya bang
> 
> ```shell
> npm install -g npm@6.14.14
> npm install
> node .
> ```

sudah dijawab
