### ISSUE TITLE
MP3 eror

### ISSUE THREAD

**Issue by nobar123** [Nurutomo/wabot-aq#794]
Cara mengatasi ini gimana ?
![Screenshot_2021-09-29-17-42-50-94](https://user-images.githubusercontent.com/75187306/135253790-cf20ba27-c74b-49f9-b0df-b58174b3fec4.png)

**Comment by BochilGaming** [comment]
> Cara mengatasi ini gimana ? ![Screenshot_2021-09-29-17-42-50-94](https://user-images.githubusercontent.com/75187306/135253790-cf20ba27-c74b-49f9-b0df-b58174b3fec4.png)

File tersebut tidak ada

**Comment by ariffb25** [comment]
gada folder tmp sih biasanya, coba cek dir nya

**Comment by nobar123** [comment]
Jadi harus gimana?

**Comment by nobar123** [comment]
> gada folder tmp sih biasanya, coba cek dir nya

Cek bagian mana dir nya?
Maklum masih newbie

**Comment by unx21** [comment]
> Jadi harus gimana?

berdo'a bang sambil berusaha fix in

**Comment by nobar123** [comment]
> > Jadi harus gimana?
> 
> berdo'a bang sambil berusaha fix in

Udah lah bang🤗😆🙏

**Comment by unx21** [comment]
> > > Jadi harus gimana?
> > 
> > 
> > berdo'a bang sambil berusaha fix in
> 
> Udah lah bang🤗😆🙏

wokeh, silahkan berusaha

**Comment by nobar123** [comment]
> > > > Jadi harus gimana?
> > > 
> > > 
> > > berdo'a bang sambil berusaha fix in
> > 
> > 
> > Udah lah bang🤗😆🙏
> 
> wokeh, silahkan berusaha

Langsung ketemu
Wkwk,tq bang,tq semua🤗🙏😆
