### ISSUE TITLE
Wabot-aq kok jarang update bang?

### ISSUE THREAD

**Issue by Bintang73** [Nurutomo/wabot-aq#796]
Kenapa Wabot-aq jarang update?

1. Nurutomo ke pondok (gak tau sampai kapan).
2. Semua orang pasti mempunyai titik jenuh.
3. Tentunya gak ada profit, bahkan donasi pun tidak ada sama sekali.

Sekarang Repository ini milik bersama. Jika ingin menambahkan fitur baru, tinggal pull request aja.

Terimakasih.
~xteam

**Comment by frmdeveloper** [comment]
Pull request saya belum di terima

**Comment by Bintang73** [comment]
> Pull request saya belum di terima

udah

**Comment by Fadhlursz** [comment]
bang xteam down?

**Comment by Bintang73** [comment]
> bang xteam down?

udah normal kembali

**Comment by mnikrsa21** [comment]
kapan kapan kalo ada rezeki aku donasi bang:)

**Comment by Ftwrr** [comment]
kalo misalnya ada yang req terus ngegantiin/ngehapus plugin yang menggunakan api xteam gimana?

**Comment by unx21** [comment]
> kalo misalnya ada yang pull req terus ngegantiin/ngehapus plugin yang menggunakan api xteam gimana?

pukulin wkwkkwk

**Comment by SanzGantengz** [comment]
> > kalo misalnya ada yang pull req terus ngegantiin/ngehapus plugin yang menggunakan api xteam gimana?
> 
> pukulin wkwkkwk

Online?:v

**Comment by frmdeveloper** [comment]
> > kalo misalnya ada yang pull req terus ngegantiin/ngehapus plugin yang menggunakan api xteam gimana?
> 
> pukulin wkwkkwk

Pukulnya pakek jasa pengiriman apa ?
Ninja express ?

**Comment by unx21** [comment]
> > > kalo misalnya ada yang pull req terus ngegantiin/ngehapus plugin yang menggunakan api xteam gimana?
> > 
> > 
> > pukulin wkwkkwk
> 
> Pukulnya pakek jasa pengiriman apa ? Ninja express ?

jasa T&T wkwkwk

**Comment by Mrifkiauliap** [comment]
info dong api.xteam gk ada lagi kah?
