### ISSUE TITLE
Bantuuu recommend Aku dongg :)

### ISSUE THREAD

**Issue by unknowkzr** [Nurutomo/wabot-aq#797]
Kira2 bagusan yg mana?
wabot
stikerin

2 nya sama2 pake plugins

**Comment by Bintang73** [comment]
> Kira2 bagusan yg mana? wabot stikerin
> 
> 2 nya sama2 pake plugins

tinggal gabungin jadi satu, kalau bisa pull request ke sini

**Comment by unknowkzr** [comment]
> ke
Gabungin kah??
hmm
kenapa harus pull request
kan kamu bisa gabungin sendiri

**Comment by unx21** [comment]
> Kira2 bagusan yg mana? wabot stikerin
> 
> 2 nya sama2 pake plugins

sama" bagus, tinggal tergantung niatmu mau pake yang mana

**Comment by qisyana** [comment]
Aku aja di gabungin
wabot, stickerin, games-wabot
ke 3 nya itu cuma di ubah beberapa biar jadi sama

**Comment by unknowkzr** [comment]
> > Kira2 bagusan yg mana? wabot stikerin
> > 2 nya sama2 pake plugins
> 
> sama" bagus, tinggal tergantung niatmu mau pake yang mana


Niatku gamau ngebot sama sekali
gimana dong

aku cuma mau nunjukin bot buat project sekolah
bukan buat orang asing mainin

intinya tujuanku cuma menjadikan bot sebagai project

Jurusan IR hehe

**Comment by unknowkzr** [comment]
> Aku aja di gabungin wabot, stickerin, games-wabot ke 3 nya itu cuma di ubah beberapa biar jadi sama




Tujuan mu ngebot apa?

**Comment by Bintang73** [comment]
> > ke
> > Gabungin kah??
> > hmm
> > kenapa harus pull request
> > kan kamu bisa gabungin sendiri

Ya saya sebenernya bisa gabungin semua SC itu, tapi maaf, saya ga ada waktu buat itu semua.

Saya harus kuliah + ngurus xteam + ada beberapa yang sewa fix bot. 
Sedangkan nurutomo sudah pergi ke pondok
