### ISSUE TITLE
Error Ga Detect Owner Nya

### ISSUE THREAD

**Issue by Adhwa9981** [Nurutomo/wabot-aq#800]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BochilGaming** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

detail?

**Comment by Lord-Patrick** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

Eror di mananya, error apanya, code nya mana, detail dikit napa

**Comment by NanaaXYZ** [comment]
Eh bang, Fitur Warn nya kok ga bisa yah ?🙂

Pada tanggal Jum, 1 Okt 2021 6.29 PM, Lord-Patrick ***@***.***>
menulis:

**Comment by unx21** [comment]
> > **Describe the bug** A clear and concise description of what the bug is.
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. Go to '...'
> > 2. Click on '....'
> > 3. Scroll down to '....'
> > 4. See error
> > 
> > **Expected behavior** A clear and concise description of what you expected to happen.
> > **Screenshots** If applicable, add screenshots to help explain your problem.
> > **Desktop (please complete the following information):**
> > 
> > * Browser [e.g. chrome, safari]
> > * Version [e.g. 22]
> > 
> > **Smartphone (please complete the following information):**
> > 
> > * Device: [e.g. iPhone6]
> > * OS: [e.g. iOS8.1]
> > * Version [e.g. 22]
> > 
> > **Additional context** Add any other context about the problem here.
> 
> Eror di mananya, error apanya, code nya mana, detail dikit napa

sabar om

**Comment by Bintang73** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

Pasti wan ini, pahami dulu makannya
