### ISSUE TITLE
Cara buat suatu perintah owner/premium only gmn?

### ISSUE THREAD

**Issue by Andika856** [Nurutomo/wabot-aq#806]
Cara buat perintah cuma bisa dipakai owner / premium gmn?

**Comment by qisyana** [comment]
> Cara buat perintah cuma bisa dipakai owner / premium gmn?

handler.premium = true
handler.owner = true

**Comment by Andika856** [comment]
> > Cara buat perintah cuma bisa dipakai owner / premium gmn?
> 
> handler.premium = true handler.owner = true

Makasih.
