### ISSUE TITLE
Scnya ada fitur fitnah gk sih?

### ISSUE THREAD

**Issue by nanasns** [Nurutomo/wabot-aq#81]

**Comment by Nurutomo** [comment]
Ada, coba cek folder plugins

**Comment by nanasns** [comment]
Cara pakenya gimana ya klo boleh tau?

**Comment by ariffb25** [comment]
/fitnah teks @tag teks

atau

/fitnah halo @0 njir whatsapp

/fitnah si nanas udah absen bu @tagdigrup iya tuh betul bu
