### ISSUE TITLE
Tutorial pake apikey neko dari xteam

### ISSUE THREAD

**Issue by elssword** [Nurutomo/wabot-aq#84]
Udah coba coba tapi yg keluar file bin
![Screenshot_2021-03-02-00-47-09-720_com gbwhatsapp](https://user-images.githubusercontent.com/48546605/109536890-d9d09f80-7af0-11eb-99fc-c1fb36bfd3a8.jpg)

**Comment by Nurutomo** [comment]
Mungkin formatnya nggk kedeteksi, resultnya image langsung?

**Comment by elssword** [comment]
Iya makasih bang ku kira url
