### ISSUE TITLE
ytmp4/ytmp3/play/play2 link download nya boleh pake bit ly atau link shortener aja g?

### ISSUE THREAD

**Issue by Uzoy** [Nurutomo/wabot-aq#846]
![Screenshot_2021-10-15-22-40-39-02_6012fa4d4ddec268fc5c7112cbb265e7](https://user-images.githubusercontent.com/78887981/137515385-4e53dc93-7d04-498a-ab88-fcbf31c58457.jpg)
Boleh bikin jadi kalo kita lakukan perintah ytmp4/ytmp3/play/play2 menjadi bitly link atau shortener link supaya ga cover semua screen dengan link download nya

**Comment by Bintang73** [comment]
bisa dong

**Comment by ariffb25** [comment]
boleh
