### ISSUE TITLE
Tag <br /> tidak ter replace di brainly.js

### ISSUE THREAD

**Issue by mnikrsa21** [Nurutomo/wabot-aq#847]
![IMG_20211016_232741](https://user-images.githubusercontent.com/90595322/137595050-8f13ca10-1780-4e34-84d7-b8589fa40ba6.jpg)

tag <br /> yang menganggu apakah bisa di replace?

**Comment by unx21** [comment]
> ![IMG_20211016_232741](https://user-images.githubusercontent.com/90595322/137595050-8f13ca10-1780-4e34-84d7-b8589fa40ba6.jpg)
> 
> tag yang menganggu apakah bisa di replace?

kalo gabisa di hapus berarti emang dari sana nya
