### ISSUE TITLE
Ada yang tau masalahnya? Tiba" ga bisa kirim pidio

### ISSUE THREAD

**Issue by ghost** [Nurutomo/wabot-aq#851]
![Screenshot_2021-10-18-05-54-31-42](https://user-images.githubusercontent.com/81492529/137829197-40940aca-f9fb-4e76-a215-5dc03a960701.jpg)

**Comment by unx21** [comment]
> > itu short video yt??
> 
> Video pendek?

iya, video pendek di yutub kan?
