### ISSUE TITLE
req fitur gitclone

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#857]
![WhatsApp Image 2021-10-19 at 9 45 32 PM](https://user-images.githubusercontent.com/76021496/138029822-33bf124a-89b5-4cd1-8b59-f62ef57f4687.jpeg)

**Comment by syahrularranger** [comment]
.git nya keikut ga itu?

**Comment by Ftwrr** [comment]
> .git nya keikut ga itu?

gatahuw

**Comment by WahyuPR0** [comment]
Itu dah lama ada di github bikin kek gitu dah dari 2018
