### ISSUE TITLE
Fitur .sticker kadang wm muncull kadang kosong.

### ISSUE THREAD

**Issue by Aidils60** [Nurutomo/wabot-aq#861]
Itu kenapa ya?
Di scriptnya ada global.package/author tapi pas di generate, rata² stickernya gak menampilkan wm? Apa memang seperti itu? Klo wmnya mau dimunculin terus gimana?
(Khusus stickermaker biasa /.s/.stiker/.sticker)

**Comment by Aidils60** [comment]
> pake wsf

wsf apa bang? 🙃

**Comment by Aidils60** [comment]
gapaham

**Comment by Caliph91** [comment]
> > pake wsf
> 
> wsf apa bang? 🙃

wa-sticker-formatter

**Comment by BochilGaming** [comment]
> Device ku android arm64v8 ga support wa-sticker-formatter kah? Tpi di stikerin bisa install kok di wabot gabisa ya?

WSF pakek modules sharp dimana sharp gk support termux

**Comment by Netshh** [comment]
> > Device ku android arm64v8 ga support wa-sticker-formatter kah? Tpi di stikerin bisa install kok di wabot gabisa ya?
> 
> WSF pakek modules sharp dimana sharp gk [support termux](https://github.com/Nurutomo/wabot-aq/pull/197#issuecomment-826475098)

Jadi apakah ada solusinya biar sticker tetap ada watermark nya? untuk termux

**Comment by Bintang73** [comment]
karena fitur webpmux/libwebp gak bisa di termux makannya itu sticker prosesnya biar ada wm ke api xteam
