### ISSUE TITLE
Kok pas ketik Ubuntu dibilang permission denied?

### ISSUE THREAD

**Issue by Uzoy** [Nurutomo/wabot-aq#864]
Jadi saya sedang menggunakan istruksi readme utk ubuntu-termux tapi yg aneh nya pas saya ketik "Ubuntu" nanti malah muncul permission denied padahal saya sudah termux-setup-storage.
![Screenshot_2021-10-21-15-16-08-46](https://user-images.githubusercontent.com/78887981/138239676-2adbe3dd-3c66-485a-b1af-382ce6a76d68.jpg)

**Comment by Andika856** [comment]
> Udah di setup storage?

Udh
