### ISSUE TITLE
Error tictactoe

### ISSUE THREAD

**Issue by Adhwa080901** [Nurutomo/wabot-aq#873]
this.parseMention is not a function

**Comment by Andika856** [comment]
![Screenshot_2021-11-01-19-09-18-49_6012fa4d4ddec268fc5c7112cbb265e7](https://user-images.githubusercontent.com/78887981/139669393-4c50ddb2-aab8-40b7-b783-077214729659.jpg)
Sama

**Comment by qisyana** [comment]
Aku ga error, aku pakai sc ttt yg lama 😁

**Comment by Andika856** [comment]
..masih eror ._.

**Comment by Bintang73** [comment]
ganti this menjadi conn
