### ISSUE TITLE
chess

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#874]
catur kaya yang di https://github.com/Synthesized-infinity/whatsapp-botto-void 
@Nurutomo

**Comment by Bintang73** [comment]
var ChessImageGenerator = require('chess-image-generator');

var imageGenerator = new ChessImageGenerator({
    size: 720,
    light: 'rgb(200, 200, 200)',
    dark: '#333333',
    style: 'merida'
});
