### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Adhwa080901** [Nurutomo/wabot-aq#876]
Dulu gw pernah lihat fitur yang bisa copy teks dari foto dan paste jadi teks wa, coba nambah itu

Rasanya ada di sc ini https://github.com/RyzRdy/termux-whatsapp-bot

**Comment by Bintang73** [comment]
const tesseract = require("node-tesseract-ocr")

const config = {
  lang: "eng",
  oem: 1,
  psm: 3,
}

tesseract
  .recognize("image.jpg", config)
  .then((text) => {
    console.log("Result:", text)
  })
  .catch((error) => {
    console.log(error.message)
  })
