### ISSUE TITLE
Baileys update version

### ISSUE THREAD

**Issue by qisyana** [Nurutomo/wabot-aq#882]
Ganti version terbaru [2, 2140, 12]

**Comment by AoiShiroi** [comment]
> Ganti version terbaru [2, 2140, 12]

edit nya file mana?

**Comment by qisyana** [comment]
node_modules
@adiwajsing
baileys
lib
WAConnect
0.Base.js

Cari di bagian
/** The version of WhatsApp Web we're telling the servers we are */
        this.version = [2, 2140, 12];
