### ISSUE TITLE
Cara ban orang dan ban group

### ISSUE THREAD

**Issue by Netshh** [Nurutomo/wabot-aq#885]
Ada yang tau cara banned tanpa harus tag orangnya?

**Comment by Patrick12a** [comment]
Tinggal .ban @siapa

**Comment by Netshh** [comment]
> Tinggal .ban @siapa

Tanpa tag orangnya bisa gak? Contoh : !ban 628xxxx

**Comment by oneechan123** [comment]
> > Tinggal .ban @siapa
> 
> Tanpa tag orangnya bisa gak? Contoh : !ban 628xxxx

Bisa

**Comment by Netshh** [comment]
Gimana tu caranya, udah nyoba !ban 6221xxxx dari pc bot langsung malah wa ku ke banned alhasil unban via wa botnya

**Comment by Uhdahlah** [comment]
> Ada yang tau cara banned tanpa harus tag orangnya?

Coba aja .banchat ke kontak/grub
