### ISSUE TITLE
Cara tambah limit

### ISSUE THREAD

**Issue by Patrick12a** [Nurutomo/wabot-aq#886]
Cara nambahin limit seseorang/i ada yg tau ga? Database.js udah ku obrak abrik tetep gabisa

**Comment by BochilGaming** [comment]
> Cara nambahin limit seseorang/i ada yg tau ga? Database.js udah ku obrak abrik tetep gabisa

```js
Object.entries(global.db.data.users).map(([user, data]) => data.limit += 99999)
```

**Comment by Patrick12a** [comment]
> > Cara nambahin limit seseorang/i ada yg tau ga? Database.js udah ku obrak abrik tetep gabisa
> 
> ```js
> Object.entries(global.db.data.users).map(([user, data]) => data.limit += 99999)
> ```

Itu dmn bang?

**Comment by BochilGaming** [comment]
> > > Cara nambahin limit seseorang/i ada yg tau ga? Database.js udah ku obrak abrik tetep gabisa
> > 
> > 
> > ```js
> > Object.entries(global.db.data.users).map(([user, data]) => data.limit += 99999)
> > ```
> 
> Itu dmn bang?

Ketik aja di wa 
```js
=> Object.entries(global.db.data.users).map(([user, data]) => data.limit += 99999)
```

**Comment by FadliDarmawan** [comment]
> Cara nambahin limit seseorang/i ada yg tau ga? Database.js udah ku obrak abrik tetep gabisa

=> db.data.users[siapa].limit += 100

siapa bisa di ganti jadi string, contoh
db.data.users['6281100000@s.whatsapp.net'].limit += 100
atau bisa 
db.data.users[m.quoted.sender].limit =+ 100
(m.sender = yang ngirim, m.quoted.sender yang di reply)

-= ngurangin limit dengan jumlah
+= nambahin limit dengan jumlah
= ngubah data jadi 
kalau += 100 itu data nambah 100, -= 100 itu data ngurang 100, = 100 itu data jadi 100
