### ISSUE TITLE
Ini kenapa?

### ISSUE THREAD

**Issue by oneechan123** [Nurutomo/wabot-aq#895]
![Screenshot_2021-11-05-21-33-16-65_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/73242335/140527637-9bac1981-066a-4334-bcbb-615dcdb0636e.jpg)
Cara benerinya gimana?

**Comment by FadliDarmawan** [comment]
npm i

**Comment by BochilGaming** [comment]
> ![Screenshot_2021-11-05-21-33-16-65_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/73242335/140527637-9bac1981-066a-4334-bcbb-615dcdb0636e.jpg) Cara benerinya gimana?

anda ngapain pakek module canvas?, canvas gk support termux

**Comment by Cosmic-Bug** [comment]
I think this error is caused by npm... Give it another try using installing nethunter in termux works fine.😇

**Comment by Bintang73** [comment]
termux-setup-storage

or

npm install -g npm@6.14.14 && npm install && node .
