### ISSUE TITLE
Ini kenapa ya?

### ISSUE THREAD

**Issue by Ridwan010230** [Nurutomo/wabot-aq#898]
Ini kenapa yaa?

**Additional context**
![Screenshot_20211106-193955](https://user-images.githubusercontent.com/93825736/140610010-d29065da-61ae-4f13-8b8c-b63a98c332c8.png)

**Comment by Ridwan010230** [comment]
> **Additional context** Add any other context about the problem here. ![Screenshot_20211106-193955](https://user-images.githubusercontent.com/93825736/140610010-d29065da-61ae-4f13-8b8c-b63a98c332c8.png)

**Comment by BochilGaming** [comment]
> Ini kenapa yaa?
> 
> **Additional context** Add any other context about the problem here. ![Screenshot_20211106-193955](https://user-images.githubusercontent.com/93825736/140610010-d29065da-61ae-4f13-8b8c-b63a98c332c8.png)

#900

**Comment by Bintang73** [comment]
npm install -g npm@6.14.14 && npm install && node .
