### ISSUE TITLE
Npm install fails

### ISSUE THREAD

**Issue by ahsaassy** [Nurutomo/wabot-aq#900]
npm install

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated axios@0.20.0: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410

npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/data/data/com.termux/files/home/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.

npm ERR! npm ERR! Exit handler never called!
npm ERR!
npm ERR! npm ERR! This is an error with npm itself. Please report this error at:
npm ERR! npm ERR!     <https://github.com/npm/cli/issues>

npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-11-07T05_05_50_969Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-11-07T05_05_58_704Z-debug.log

Log: https://mega.nz/file/Pc51XQIA#Pg0qBPjKWRDfveMJClm7LmUzsctIEstRxo7HwkW4MBM

**Comment by BochilGaming** [comment]
> npm install
> 
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details. npm WARN deprecated request@2.88.2: request has been deprecated, see [request/request#3142](https://github.com/request/request/issues/3142) npm WARN deprecated axios@0.20.0: Critical security vulnerability fixed in v0.21.1. For more information, see [axios/axios#3410](https://github.com/axios/axios/pull/3410)
> 
> npm ERR! code 1 npm ERR! git dep preparation failed npm ERR! command /data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/data/data/com.termux/files/home/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run npm ERR! npm WARN using --force Recommended protections disabled.
> 
> npm ERR! npm ERR! Exit handler never called! npm ERR! npm ERR! npm ERR! This is an error with npm itself. Please report this error at: npm ERR! npm ERR! https://github.com/npm/cli/issues
> 
> npm ERR! npm ERR! npm ERR! A complete log of this run can be found in: npm ERR! npm ERR! /data/data/com.termux/files/home/.npm/_logs/2021-11-07T05_05_50_969Z-debug.log
> 
> npm ERR! A complete log of this run can be found in: npm ERR! /data/data/com.termux/files/home/.npm/_logs/2021-11-07T05_05_58_704Z-debug.log
> 
> Log: https://mega.nz/file/Pc51XQIA#Pg0qBPjKWRDfveMJClm7LmUzsctIEstRxo7HwkW4MBM

```sh
npm install -g npm@6.14.14
npm install
node .
````

**Comment by Ridwan010230** [comment]
Masih ga ngerti bang, barang kali bisa ngasih WA buat bantu bantu sedikit

**Comment by BochilGaming** [comment]
> Masih ga ngerti bang, barang kali bisa ngasih WA buat bantu bantu sedikit

ketik aja di termux bang

**Comment by Ridwan010230** [comment]
> > Masih ga ngerti bang, barang kali bisa ngasih WA buat bantu bantu sedikit
> 
> ketik aja di termux bang

npm install -g npm@6.14.14
npm install
node .

Oo ketik ini bang?

**Comment by BochilGaming** [comment]
> > > Masih ga ngerti bang, barang kali bisa ngasih WA buat bantu bantu sedikit
> > 
> > 
> > ketik aja di termux bang
> 
> npm install -g npm@6.14.14 npm install node .
> 
> Oo ketik ini bang?

iy
