### ISSUE TITLE
Anti Spam

### ISSUE THREAD

**Issue by anggita13** [Nurutomo/wabot-aq#901]
Bang bisa tolong tambahkan bot.number = 085xxxxx gitu di config.js
Karena kalau aktifkan fitur anti spam, bot nya ngebanned diri sendiri bukan user yang melakukan spam

**Comment by unx21** [comment]
> Bang bisa tolong tambahkan bot.number = 085xxxxx gitu di config.js Karena kalau aktifkan fitur anti spam, bot nya ngebanned diri sendiri bukan user yang melakukan spam

kode dalam antispam nya yang di ubah kalo gitu  :v

**Comment by BochilGaming** [comment]
> Bang bisa tolong tambahkan bot.number = 085xxxxx gitu di config.js Karena kalau aktifkan fitur anti spam, bot nya ngebanned diri sendiri bukan user yang melakukan spam

buat ngedapetin number bot mu pakek
```js
conn.user.jid.split('@')[0]
```

**Comment by anggita13** [comment]
Oke bang, makasih jawaban nya
