### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by Andika856** [Nurutomo/wabot-aq#902]
.changelog

Karna skrg kalo ketik .update nodejs malah bikin bot nya restart pas ada update baru, jadinya bot gaada kasi pesan tentang apa yg baru.

![Screenshot_2021-11-08-07-31-51-50_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/78887981/140668182-e8000c23-24b9-4c69-972b-615ad0bab732.jpg)

**Comment by BochilGaming** [comment]
> .changelog
> 
> Karna skrg kalo ketik .update nodejs malah bikin bot nya restart pas ada update baru, jadinya bot gaada kasi pesan tentang apa yg baru.
> 
> ![Screenshot_2021-11-08-07-31-51-50_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/78887981/140668182-e8000c23-24b9-4c69-972b-615ad0bab732.jpg)

restat aja
