### ISSUE TITLE
Ada yg tau kenapa?

### ISSUE THREAD

**Issue by Ridwan010230** [Nurutomo/wabot-aq#904]
Ko gini ya brainlynya?

![Screenshot_20211108-175658](https://user-images.githubusercontent.com/93825736/140730390-9067d4b5-a773-4154-9d31-a56bd98c4168.png)

**Comment by qisyana** [comment]
Brainly lagi error , 
brainly-scraper (error)
brainly-scraper-v2 (error)

**Comment by BochilGaming** [comment]
> Ko gini ya brainlynya?
> 
> ![Screenshot_20211108-175658](https://user-images.githubusercontent.com/93825736/140730390-9067d4b5-a773-4154-9d31-a56bd98c4168.png)

https://github.com/hansputera/brainly-scraper-languages/issues/9

**Comment by Bintang73** [comment]
jika ini tidak bisa, bisa menggunakan api xteam karena brainly nya full scrape tidak memakai modul apapun

**Comment by hansputera** [comment]
> Brainly lagi error , brainly-scraper (error) brainly-scraper-v2 (error)

up.
