### ISSUE TITLE
Error login karena habis hapus apk whatsapp

### ISSUE THREAD

**Issue by Netshh** [Nurutomo/wabot-aq#907]
Ada yang tau cara fixnya gimana? Biar data data yang sudah dibuat/diedit gak hilang

![Screenshot_2021-11-11-13-44-47-166_com termux](https://user-images.githubusercontent.com/93586570/141254157-9f306fbb-ea05-4319-92d4-8139e717399d.jpg)

**Comment by Netshh** [comment]
Di wa, perangkat tertautnya juga hilang jadi kayanya harus scan ulang. Tapi gak tau caranya gimana...

**Comment by Kokoronationz** [comment]
Hapus session.data.json nya

**Comment by BochilGaming** [comment]
> Ada yang tau cara fixnya gimana? Biar data data yang sudah dibuat/diedit gak hilang
> 
> ![Screenshot_2021-11-11-13-44-47-166_com termux](https://user-images.githubusercontent.com/93586570/141254157-9f306fbb-ea05-4319-92d4-8139e717399d.jpg)

```sh
rm -rf session.data.json
```

**Comment by Netshh** [comment]
> 

Thanks bang, work
