### ISSUE TITLE
Self Only

### ISSUE THREAD

**Issue by usoajwj** [Nurutomo/wabot-aq#91]
bang cara biar kita doang gimana, jadi orng lain gk bs make

**Comment by ariffb25** [comment]
tambahin aja setiap command 

handler.owner = true

biar gamuncul message nya bisa hapus aja di
[https://github.com/Nurutomo/wabot-aq/blob/236c057c980b9c831de5175b9ec1333ecfda0c78/handler.js#L298](https://github.com/Nurutomo/wabot-aq/blob/236c057c980b9c831de5175b9ec1333ecfda0c78/handler.js#L298)

**Comment by usoajwj** [comment]
> tambahin aja setiap command
> 
> handler.owner = true
> 
> biar gamuncul message nya bisa hapus aja di
> https://github.com/Nurutomo/wabot-aq/blob/236c057c980b9c831de5175b9ec1333ecfda0c78/handler.js#L298

bang trus kalau biar cara gk ush git clone pake termux gimana bang

**Comment by ariffb25** [comment]
kalo udah git clone kan udah kedownload di folder termuxnya

**Comment by usoajwj** [comment]
> kalo udah git clone kan udah kedownload di folder termuxnya

tapi mau recode bang hehe

**Comment by Netsh1** [comment]
> > kalo udah git clone kan udah kedownload di folder termuxnya
> 
> tapi mau recode bang hehe

Pake aplikasi Acode paling mudah

**Comment by Nurutomo** [comment]
> tambahin aja setiap command
> 
> handler.owner = true
> 
> biar gamuncul message nya bisa hapus aja di
> https://github.com/Nurutomo/wabot-aq/blob/236c057c980b9c831de5175b9ec1333ecfda0c78/handler.js#L298

Paling mudah sih saat run...
Pake argumen `--self`

Contoh:
`node . --self`
