### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by Caliph91** [Nurutomo/wabot-aq#910]
![Screenshot_20211112-093649_GBWhatsApp](https://telegra.ph/file/8135003fb4fafbdabd65b.jpg)

Tiap Download YouTube Shorts kok Invalid URL mulu ya

**Comment by BochilGaming** [comment]
> ![Screenshot_20211112-093649_GBWhatsApp](https://camo.githubusercontent.com/e1fb85d95a53bfbd9b2e812474fa778415615af2e80bcacbb55275a071bb1b91/68747470733a2f2f74656c656772612e70682f66696c652f3831333530303366623466616662646162643635622e6a7067)
> 
> Tiap Download YouTube Shorts kok Invalid URL mulu ya

short belum support
