### ISSUE TITLE
ttt error

### ISSUE THREAD

**Issue by Andika856** [Nurutomo/wabot-aq#912]
![139669393-4c50ddb2-aab8-40b7-b783-077214729659](https://user-images.githubusercontent.com/78887981/141664639-74b14cce-c095-4f0f-a9dd-3a4fe44e8214.jpg)
Jadi ttt sbnrnya Masi bisa bekerja tapi yg anehnya yg munculnya itu malah this.parsemention is not a function pas mau main di awal, tolong baikin bang makasih

**Comment by BochilGaming** [comment]
> ![139669393-4c50ddb2-aab8-40b7-b783-077214729659](https://user-images.githubusercontent.com/78887981/141664639-74b14cce-c095-4f0f-a9dd-3a4fe44e8214.jpg) Jadi ttt sbnrnya Masi bisa bekerja tapi yg anehnya yg munculnya itu malah this.parsemention is not a function pas mau main di awal, tolong baikin bang makasih

maybe ubah 
```js
this
```
ke 
```js
conn
```

**Comment by Netshh** [comment]
> > ![139669393-4c50ddb2-aab8-40b7-b783-077214729659](https://user-images.githubusercontent.com/78887981/141664639-74b14cce-c095-4f0f-a9dd-3a4fe44e8214.jpg) Jadi ttt sbnrnya Masi bisa bekerja tapi yg anehnya yg munculnya itu malah this.parsemention is not a function pas mau main di awal, tolong baikin bang makasih
> 
> maybe ubah
> 
> ```js
> this
> ```
> 
> ke
> 
> ```js
> conn
> ```

Work ni thanks
