### ISSUE TITLE
Nodemon error

### ISSUE THREAD

**Issue by Graffian** [Nurutomo/wabot-aq#913]
~/wabot-aq $ npm start

> wabot-aq@2.5.1 start /data/data/com.termux/files/home/wabot-aq
> nodemon -x node index.js || touch index.js

sh: 1: nodemon: not found
![Screenshot_20211114-082141_Termux](https://user-images.githubusercontent.com/89790082/141665588-d1090412-9e0c-48d3-919a-6d3188983ae3.jpg)

This error comes everytime i have tried installing nodemon still it doesn't work

**Comment by BochilGaming** [comment]
> ~/wabot-aq $ npm start
> 
> > wabot-aq@2.5.1 start /data/data/com.termux/files/home/wabot-aq
> > nodemon -x node index.js || touch index.js
> 
> sh: 1: nodemon: not found ![Screenshot_20211114-082141_Termux](https://user-images.githubusercontent.com/89790082/141665588-d1090412-9e0c-48d3-919a-6d3188983ae3.jpg)
> 
> This error comes everytime i have tried installing nodemon still it doesn't work

```sh
npm install -g npm@6.14.14
npm install
npm start
```
