### ISSUE TITLE
How to deploy in heroku?

### ISSUE THREAD

**Issue by dev-bug2debug** [Nurutomo/wabot-aq#919]
How to deploy in heroku..
I have created in termux but i want to deploy it in heroku, but i don't know where i should find and create session file.. please tell me the procedure to di this.

**Comment by BochilGaming** [comment]
> How to deploy in heroku.. I have created in termux but i want to deploy it in heroku, but i don't know where i should find and create session file.. please tell me the procedure to di this.

if you scan it automatic create session.data.json

**Comment by dev-bug2debug** [comment]
Now we have to upload and deploy it in heroku ???

**Comment by dev-bug2debug** [comment]
> > How to deploy in heroku.. I have created in termux but i want to deploy it in heroku, but i don't know where i should find and create session file.. please tell me the procedure to di this.
> 
> if you scan it automatic create session.data.json

Now we have to upload that session in github and deploy it in heroku ???

**Comment by BochilGaming** [comment]
> > > How to deploy in heroku.. I have created in termux but i want to deploy it in heroku, but i don't know where i should find and create session file.. please tell me the procedure to di this.
> > 
> > 
> > if you scan it automatic create session.data.json
> 
> Now we have to upload that session in github and deploy it in heroku ???

fork this repo and upload to your repo and deploy

**Comment by dev-bug2debug** [comment]
> > > > How to deploy in heroku.. I have created in termux but i want to deploy it in heroku, but i don't know where i should find and create session file.. please tell me the procedure to di this.
> > > 
> > > 
> > > if you scan it automatic create session.data.json
> > 
> > 
> > Now we have to upload that session in github and deploy it in heroku ???
> 
> fork this repo and upload to your repo and deploy

We do not need to make repo in private na ??

**Comment by BochilGaming** [comment]
> > > > > How to deploy in heroku.. I have created in termux but i want to deploy it in heroku, but i don't know where i should find and create session file.. please tell me the procedure to di this.
> > > > 
> > > > 
> > > > if you scan it automatic create session.data.json
> > > 
> > > 
> > > Now we have to upload that session in github and deploy it in heroku ???
> > 
> > 
> > fork this repo and upload to your repo and deploy
> 
> We do not need to make repo in private na ??

you just fork and upload your session to the repo you fork

**Comment by dev-bug2debug** [comment]
Ohk thanku so much
