### ISSUE TITLE
Play server issue

### ISSUE THREAD

**Issue by dev-bug2debug** [Nurutomo/wabot-aq#922]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

![Screenshot_20211118-073823_WhatsAppBusiness](https://user-images.githubusercontent.com/62154454/142338495-675e2a7c-b13a-4ee3-8783-1913426acda7.jpg)
What is the issue i am getting while downloading songs..? In heroku

**Comment by DwiRizqiH** [comment]
looks like the heroku server you are using is in a country/region that y2mate doesn't support.
Like in germany, the y2mate server has been disabled there

try another downloader, like savefrom.net or ytop1.com

![image](https://user-images.githubusercontent.com/69355492/142409895-20b2f6e2-3ba8-4302-bfb6-6bc3affaf91b.png)
