### ISSUE TITLE
Heroku issue 

### ISSUE THREAD

**Issue by dev-bug2debug** [Nurutomo/wabot-aq#923]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![Screenshot_20211118-081156_Chrome](https://user-images.githubusercontent.com/62154454/142341962-f2f8b18a-931b-4ff9-9266-d5c177106438.jpg)
In heroku, process is again & again exited , and i can't able to access my bot and when i deploy again it works.. what is the issue ?

**Comment by BochilGaming** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here. ![Screenshot_20211118-081156_Chrome](https://user-images.githubusercontent.com/62154454/142341962-f2f8b18a-931b-4ff9-9266-d5c177106438.jpg) In heroku, process is again & again exited , and i can't able to access my bot and when i deploy again it works.. what is the issue ?

ping your website every 5 minute, but your heroku is free
