### ISSUE TITLE
(HELP) Is it possible to use Bot on Iphone? (iOS)

### ISSUE THREAD

**Issue by lilnext01** [Nurutomo/wabot-aq#928]
help me pls

**Comment by Gimenz** [comment]
it's possible if u want just for host account, not running code on iOS

**Comment by lilnext01** [comment]
> you need a vps/rdp which can run code for 24 hours. and ios only scan the qr

do you know any vps that can do this?

**Comment by Gimenz** [comment]
> > you need a vps/rdp which can run code for 24 hours. and ios only scan the qr
> 
> do you know any vps that can do this?

you can try heroku, it’s free. but limited for many times.
if want good vps/rdp you can buy on linode, digital ocean, contabo, or etc.
