### ISSUE TITLE
Bantu dong, Tiba² Error

### ISSUE THREAD

**Issue by Aidils60** [Nurutomo/wabot-aq#933]
![Screenshot_20211124-174258108](https://user-images.githubusercontent.com/38816724/143214035-b595e72f-32b8-4c27-be36-ee653a6ef22e.jpg)

Ini errornya dimana ya? 
Ngatasinnya gimana? 
Perasaan gak pernah diapa²in tiba² error.

**Comment by janganlahkau** [comment]
sama bjerr

**Comment by BochilGaming** [comment]
> ![Screenshot_20211124-174258108](https://user-images.githubusercontent.com/38816724/143214035-b595e72f-32b8-4c27-be36-ee653a6ef22e.jpg)
> 
> Ini errornya dimana ya? Ngatasinnya gimana? Perasaan gak pernah diapa²in tiba² error.

```sh
rm -rf session.data.json
node index.js
```

**Comment by Aidils60** [comment]
> > ![Screenshot_20211124-174258108](https://user-images.githubusercontent.com/38816724/143214035-b595e72f-32b8-4c27-be36-ee653a6ef22e.jpg)
> > Ini errornya dimana ya? Ngatasinnya gimana? Perasaan gak pernah diapa²in tiba² error.
> 
> ```shell
> rm -rf session.data.json
> node index.js
> ```

Sudah hapus session masih error bang.
![IMG_20211125_005603](https://user-images.githubusercontent.com/38816724/143286767-29c0b470-6492-4acc-ab4a-668127f0db50.jpg)

**Comment by BochilGaming** [comment]
> > > ![Screenshot_20211124-174258108](https://user-images.githubusercontent.com/38816724/143214035-b595e72f-32b8-4c27-be36-ee653a6ef22e.jpg)
> > > Ini errornya dimana ya? Ngatasinnya gimana? Perasaan gak pernah diapa²in tiba² error.
> > 
> > 
> > ```shell
> > rm -rf session.data.json
> > node index.js
> > ```
> 
> Sudah hapus session masih error bang. ![IMG_20211125_005603](https://user-images.githubusercontent.com/38816724/143286767-29c0b470-6492-4acc-ab4a-668127f0db50.jpg)

Database mu corrupt

**Comment by Aidils60** [comment]
> > > > ![Screenshot_20211124-174258108](https://user-images.githubusercontent.com/38816724/143214035-b595e72f-32b8-4c27-be36-ee653a6ef22e.jpg)
> > > > Ini errornya dimana ya? Ngatasinnya gimana? Perasaan gak pernah diapa²in tiba² error.
> > > 
> > > 
> > > ```shell
> > > rm -rf session.data.json
> > > node index.js
> > > ```
> > 
> > 
> > Sudah hapus session masih error bang. ![IMG_20211125_005603](https://user-images.githubusercontent.com/38816724/143286767-29c0b470-6492-4acc-ab4a-668127f0db50.jpg)
> 
> Database mu corrupt

Cara fixnya gimana bang?
saya sudah copy file database.js & low.js , jsonfile.js sama seperti yg ada di repo tpi masih sama hasilnya, error

**Comment by BochilGaming** [comment]
> > > > > ![Screenshot_20211124-174258108](https://user-images.githubusercontent.com/38816724/143214035-b595e72f-32b8-4c27-be36-ee653a6ef22e.jpg)
> > > > > Ini errornya dimana ya? Ngatasinnya gimana? Perasaan gak pernah diapa²in tiba² error.
> > > > 
> > > > 
> > > > ```shell
> > > > rm -rf session.data.json
> > > > node index.js
> > > > ```
> > > 
> > > 
> > > Sudah hapus session masih error bang. ![IMG_20211125_005603](https://user-images.githubusercontent.com/38816724/143286767-29c0b470-6492-4acc-ab4a-668127f0db50.jpg)
> > 
> > 
> > Database mu corrupt
> 
> Cara fixnya gimana bang? saya sudah copy file database.js & low.js , jsonfile.js sama seperti yg ada di repo tpi masih sama hasilnya, error

Hapus file database.json dan run nanti ke fix tapi db ke reset
