### ISSUE TITLE
Cara benerin brainly gimana?

### ISSUE THREAD

**Issue by Ridwan010230** [Nurutomo/wabot-aq#937]
![Screenshot_20211125-111341](https://user-images.githubusercontent.com/93825736/143378751-9b07f4ab-994c-48e5-979e-d3c814e04ca2.png)

Brainly kenapa jadi error gini yaa?

**Comment by Bintang73** [comment]
pake api xteam

**Comment by FadliDarmawan** [comment]
> pake api xteam

promosi moment

**Comment by Uhdahlah** [comment]
> pake api xteam

Gw dah beli cuman masalahnya masih sama

**Comment by Bintang73** [comment]
> > pake api xteam
> 
> Gw dah beli cuman masalahnya masih sama

Ah masa sih, di bot ku bisa soalnya

**Comment by Uhdahlah** [comment]
> > > pake api xteam
> > 
> > 
> > Gw dah beli cuman masalahnya masih sama
> 
> Ah masa sih, di bot ku bisa soalnya

Nggk bisa di gw padahal dah beli apikey, semua fitur work kecuali brainly bisa pw in bot lu nggk?
