### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by peraaxd** [Nurutomo/wabot-aq#939]
Kenapa yh bang setiap di deploy di heroku sekitar 10-30 menitan bot nya mati sendiri

**Comment by unx21** [comment]
Gak usah tanya kenapa, coba berlangganan kalo mau nyala terus

**Comment by Lord-Patrick** [comment]
> Kenapa yh bang setiap di deploy di heroku sekitar 10-30 menitan bot nya mati sendiri

Procfile nya pake worker jgn pake web

**Comment by peraaxd** [comment]
> 

Ok bang makasih udh gk matj lagi sekarang
