### ISSUE TITLE
Fitur wm sticker error

### ISSUE THREAD

**Issue by Netshh** [Nurutomo/wabot-aq#940]
Fitur wm stickernya error pas mau ngasih wm ke sticker gif dan muncul "Conversion Failed" kalo stiker biasa normal

**Comment by Netshh** [comment]
Kadang juga gak muncul wmnya sama kaya pas bikin stiker lewat !stiker kadang muncul kadang gak, mau make wsf tapi gak support di termux

**Comment by BochilGaming** [comment]
> Fitur wm stickernya error pas mau ngasih wm ke sticker gif dan muncul "Conversion Failed" kalo stiker biasa normal

coba img nya di aploud di telegraph dulu terus di convert ke sticker pakek param link
