### ISSUE TITLE
Bagaimana cara ganti wabot jadi bisa muncul lagi Qr code nya?

### ISSUE THREAD

**Issue by Andika856** [Nurutomo/wabot-aq#941]
Kalo WhatsApp saya reset, terus buka perangkat tertaut/WhatsApp web. baileys nya gada di perangkat tertaut, gmn cara bikin QR code nya muncul lagi ?

**Comment by unx21** [comment]
> Kalo WhatsApp saya reset, terus buka perangkat tertaut/WhatsApp web. baileys nya gada di perangkat tertaut, gmn cara bikin QR code nya muncul lagi ?

Hapus session.json nya om :v

**Comment by BochilGaming** [comment]
> Kalo WhatsApp saya reset, terus buka perangkat tertaut/WhatsApp web. baileys nya gada di perangkat tertaut, gmn cara bikin QR code nya muncul lagi ?

rm -rf session.data.json

**Comment by Andika856** [comment]
> > Kalo WhatsApp saya reset, terus buka perangkat tertaut/WhatsApp web. baileys nya gada di perangkat tertaut, gmn cara bikin QR code nya muncul lagi ?
> 
> rm -rf session.data.json

Makasih
