### ISSUE TITLE
Ni knp bang

### ISSUE THREAD

**Issue by prioprast** [Nurutomo/wabot-aq#945]
![Screenshot_2021-11-30-22-50-10-610_com termux](https://user-images.githubusercontent.com/74879576/144080810-cce3c8e6-7a24-4917-a76c-d148edf4ca9c.jpg)

**Comment by BochilGaming** [comment]
> ![Screenshot_2021-11-30-22-50-10-610_com termux](https://user-images.githubusercontent.com/74879576/144080810-cce3c8e6-7a24-4917-a76c-d148edf4ca9c.jpg)

Coba up versi nodejs mu pakek pkg update && pkg upgrade, terus coba npm install lagi

**Comment by prioprast** [comment]
Udah bwang, tetep kaya gitu lagi, aku tadi coba buat baru juga sama banh

**Comment by Kokoronationz** [comment]
> Udah bwang, tetep kaya gitu lagi, aku tadi coba buat baru juga sama banh

Coba pake apt bukan pkg

**Comment by unx21** [comment]
> > Udah bwang, tetep kaya gitu lagi, aku tadi coba buat baru juga sama banh
> 
> Coba pake apt bukan pkg

 What's the difference?

**Comment by BochilGaming** [comment]
> Udah bwang, tetep kaya gitu lagi, aku tadi coba buat baru juga sama banh

install pakek yarn

**Comment by VISION-DARK** [comment]
> gw make yarn juga g bisa bg . Td awalny pas make npm cfont not found katany skrg make yarn malah gitu v:

Error: Cannot find module '/data/data/com.termux/files/home/wabot-aq/node_modules/@adiwajshing/baileys/lib/index.js'. Please verify that the package.json has a valid "main" entry

**Comment by VISION-DARK** [comment]
> > Udah bwang, tetep kaya gitu lagi, aku tadi coba buat baru juga sama banh
> 
> install pakek yarn


gw make yarn juga g bisa bg . Td awalny pas make npm cfont not found katany skrg make yarn malah gitu v:

Error: Cannot find module '/data/data/com.termux/files/home/wabot-aq/node_modules/@adiwajshing/baileys/lib/index.js'. Please verify that the package.json has a valid "main" entry

**Comment by Bintang73** [comment]
npm install -g npm
npm cache clean
npm update
npm install
