### ISSUE TITLE
Bang klo ad kode gini gimana yg harus saya lakuin bang? 

### ISSUE THREAD

**Issue by VISION-DARK** [Nurutomo/wabot-aq#946]
Pas npm install
Kodenya gini :
CANNOT LINK EXECUTABLE "node": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/bin/node"...

**Comment by ilmanhdyt** [comment]
> Pas npm install Kodenya gini : CANNOT LINK EXECUTABLE "node": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/bin/node"...

pkg update && pkg upgrade
