### ISSUE TITLE
Caklontong, trigger, dan kick error.

### ISSUE THREAD

**Issue by Andika856** [Nurutomo/wabot-aq#948]
![Screenshot_2021-12-02-21-41-16-67](https://user-images.githubusercontent.com/78887981/144443767-c6ccb37f-335a-4d3c-8912-875fb956d480.jpg)
Dan fitur .kick gabisa bekerja sama sekali.

**Comment by BochilGaming** [comment]
> ![Screenshot_2021-12-02-21-41-16-67](https://user-images.githubusercontent.com/78887981/144443767-c6ccb37f-335a-4d3c-8912-875fb956d480.jpg) Dan fitur .kick gabisa bekerja sama sekali.

```sh
node index.js --restrict 
```
buat aktiffin kick,add,dll

**Comment by Andika856** [comment]
> > ![Screenshot_2021-12-02-21-41-16-67](https://user-images.githubusercontent.com/78887981/144443767-c6ccb37f-335a-4d3c-8912-875fb956d480.jpg) Dan fitur .kick gabisa bekerja sama sekali.
> 
> ```shell
> node index.js --restrict 
> ```
> 
> buat aktiffin kick,add,dll

caklontong & trigger gmn

**Comment by BochilGaming** [comment]
> > > ![Screenshot_2021-12-02-21-41-16-67](https://user-images.githubusercontent.com/78887981/144443767-c6ccb37f-335a-4d3c-8912-875fb956d480.jpg) Dan fitur .kick gabisa bekerja sama sekali.
> > 
> > 
> > ```shell
> > node index.js --restrict 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > buat aktiffin kick,add,dll
> 
> caklontong & trigger gmn

https://github.com/Nurutomo/wabot-aq/blob/e8c39ea67d0798e710f873e233ba64ccaadc4715/plugins/caklontong.js#L5
hapus `= []` , kalau triger ¯\_( ͡❛ ͜ʖ ͡❛)_/¯

**Comment by Andika856** [comment]
> > > > ![Screenshot_2021-12-02-21-41-16-67](https://user-images.githubusercontent.com/78887981/144443767-c6ccb37f-335a-4d3c-8912-875fb956d480.jpg) Dan fitur .kick gabisa bekerja sama sekali.
> > > 
> > > 
> > > ```shell
> > > node index.js --restrict 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > buat aktiffin kick,add,dll
> > 
> > 
> > caklontong & trigger gmn
> 
> https://github.com/Nurutomo/wabot-aq/blob/e8c39ea67d0798e710f873e233ba64ccaadc4715/plugins/caklontong.js#L5
> 
> 
> hapus `= []` di line tersebut, kalau triger ¯\_( ͡❛ ͜ʖ ͡❛)_/¯

Sudah ketemu g solusiny
