### ISSUE TITLE
New game mode

### ISSUE THREAD

**Issue by lilnext01** [Nurutomo/wabot-aq#95]
Add new game mode (sloots) pleasee

**Comment by lilnext01** [comment]
![20210307_041857](https://user-images.githubusercontent.com/74841546/110232409-42a68600-7efc-11eb-97aa-2b87a90eaf61.jpg)

**Comment by lilnext01** [comment]
Whoever wins, is awarded an amount in XP, as well as in Math mode

**Comment by RC047** [comment]
I have a slot game feature, it's just a little different. If you want me to give it, just chat on my WhatsApp wa.me/62895337278647

**Comment by Nurutomo** [comment]
# Small Logic
This will rotate 3 array simultaneously ain random times, then transpose them
```js
function rotateArr(arr, i=1) {
 i = Math.floor(i)
 i %= arr.length
 return [...arr.slice(i), ...arr.slice(0, i)]
}
const transposeArr = arr => arr.map((_,r)=>arr.map((_,c)=>arr[c][r]))

const slots = ['🍎','🍊','🍋','🍏','🫐','🍇']
let [a,b,c] = [...'   '].map(v=>Math.floor(Math.random()*50)%slots.length)
let arr = transposeArr([
  rotateArr(slots, a).slice(0, 3),
  rotateArr(slots, b).slice(0, 3),
  rotateArr(slots, c).slice(0, 3)
])

let score = (a==b&&b==c)?2:(a==b||b==c||a==c)?1:0

const winMessages = ['Kalah', 'Lumayan', 'JACKPOT']
print(score)
return `
*VIRTUAL SLOTS*
${arr.map(v=>v.join('|')).join('\n')}

${winMessages[score]}`
```

**Comment by lilnext01** [comment]
Thank you very much! But I don't know how to add :( Thank you very much if you can help me, again

**Comment by lilnext01** [comment]
![Uploading Screenshot_20210308-051035_MT Manager.jpg…]()

**Comment by lilnext01** [comment]
![Uploading Screenshot_20210308-051035_MT Manager.jpg…]()

**Comment by lilnext01** [comment]
const transposeArr = arr => arr.map((_,r)=>arr.map((_,c)=>arr[c][r]))
const slots = ['🍎','🍊','🍋','🍏','🫐','🍇']
let [a,b,c] = [...'   '].map(v=>Math.floor(Math.random()*50)%slots.length)
let arr = transposeArr([
  rotateArr(slots, a).slice(0, 3),
  rotateArr(slots, b).slice(0, 3),
  rotateArr(slots, c).slice(0, 3)
])

let score = (a==b&&b==c)?2:(a==b||b==c||a==c)?1:0
let handler = async (m, { conn, text }) => {
const winMessages = ['Perdeu', 'Nada mal', 'PRÊMIO MÁXIMO!']
return `
*VIRTUAL SLOTS*
${arr.map(v=>v.join('|')).join('\n')}

${winMessages[score]}`

handler.help = ['slots']
handler.tags = ['game']
handler.command = /^jogo/i
handler.owner = false
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null
handler.limit = true

module.exports = handler

function rotateArr(arr, i=1) {
  i = Math.floor(i)
  i %= arr.length
  return [...arr.slice(i), ...arr.slice(0, i)]
}

**Comment by lilnext01** [comment]
ERROR [2021-03-08 08:31:30.305 +0000] (2692): syntax error while loading 'jogoslot.js'                                                                                           jogoslot.js:42                                                                                                        ^                                                          ParseError: Unexpected token

**Comment by lilnext01** [comment]
Help me, I can't fix it😑

**Comment by lilnext01** [comment]
> ERROR [2021-03-08 08:31:30.305 +0000] (2692): syntax error while loading 'jogoslot.js' jogoslot.js:42 ^ ParseError: Unexpected token

Help me, I can't fix it😑

**Comment by lilnext01** [comment]
function rotateArr(arr, i=1) {
  i = Math.floor(i)
  i %= arr.length
  return [...arr.slice(i), ...arr.slice(0, i)]
}
const transposeArr = arr => arr.map((_,r)=>arr.map((_,c)=>arr[c][r]))
const slots = ['🍎','🍊','🍋','🍏','🫐','🍇']
let [a,b,c] = [...'   '].map(v=>Math.floor(Math.random()*50)%slots.length)
let arr = transposeArr([
  rotateArr(slots, a).slice(0, 3),
  rotateArr(slots, b).slice(0, 3),
  rotateArr(slots, c).slice(0, 3)
])


let handler = async (m, { conn }) => {
let score = (a==b&&b==c)?2:(a==b||b==c||a==c)?1:0
const winMessages = ['Perdeu', 'Nada mal', 'PRÊMIO MÁXIMO!']
return `
*VIRTUAL SLOTS*
${arr.map(v=>v.join('|')).join('\n')}

${winMessages[score]}`
}

handler.help = ['jogar']
handler.tags = ['game']
handler.command = /^jogar/i
handler.owner = false
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null
handler.limit = true

module.exports = handler

**Comment by lilnext01** [comment]
> function rotateArr(arr, i=1) {
> i = Math.floor(i)
> i %= arr.length
> return [...arr.slice(i), ...arr.slice(0, i)]
> }
> const transposeArr = arr => arr.map((_,r)=>arr.map((_,c)=>arr[c][r]))
> const slots = ['🍎','🍊','🍋','🍏','🫐','🍇']
> let [a,b,c] = [...' '].map(v=>Math.floor(Math.random()*50)%slots.length)
> let arr = transposeArr([
> rotateArr(slots, a).slice(0, 3),
> rotateArr(slots, b).slice(0, 3),
> rotateArr(slots, c).slice(0, 3)
> ])
> 
> let handler = async (m, { conn }) => {
> let score = (a==b&&b==c)?2:(a==b||b==c||a==c)?1:0
> const winMessages = ['Perdeu', 'Nada mal', 'PRÊMIO MÁXIMO!']
> return `
> _VIRTUAL SLOTS_
> ${arr.map(v=>v.join('|')).join('\n')}
> 
> ${winMessages[score]}`
> }
> 
> handler.help = ['jogar']
> handler.tags = ['game']
> handler.command = /^jogar/i
> handler.owner = false
> handler.mods = false
> handler.premium = false
> handler.group = false
> handler.private = false
> 
> handler.admin = false
> handler.botAdmin = false
> 
> handler.fail = null
> handler.limit = true
> 
> module.exports = handler

He is not returning the result to me, can you help me?

**Comment by lilnext01** [comment]
Helppp plsss

**Comment by lilnext01** [comment]
![20210308_232559](https://user-images.githubusercontent.com/74841546/110409384-f37c6480-8065-11eb-835c-a41a8553bbc0.jpg)

**Comment by lilnext01** [comment]
Bagaimana cara membuatnya memberikan sejumlah XP tertentu kepada pengguna yang menjalankannya? contoh: Jika dia menang: + 10000 XP Jika dia kalah: + 100 XP

**Comment by Netsh1** [comment]
Bagus ni fiturnya tambahin xp reward kalo jackpot

**Comment by Gimenz** [comment]
tambahin bet pake xp mantep :v
