### ISSUE TITLE
Bang nodemon not found?? 

### ISSUE THREAD

**Issue by VISION-DARK** [Nurutomo/wabot-aq#950]
Pas npm start kodenya gini :
> wabot-aq@2.5.1 start
> nodemon -x node index.js || touch index.js

sh: 1: nodemon: not found

**Comment by BochilGaming** [comment]
> Pas npm start kodenya gini :
> 
> > wabot-aq@2.5.1 start
> > nodemon -x node index.js || touch index.js
> 
> sh: 1: nodemon: not found

npm install -g nodemon

**Comment by Bintang73** [comment]
npm i -g nodemon
