### ISSUE TITLE
Eror! This is what happened..

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#957]
Kepada developer dan pengembangan terhadap bot WhatsApp, saya menemukan beberapa kali eror dalam menjalankan Script dari codingan anda..
![BP_BOT_OFFICIAL](https://user-images.githubusercontent.com/80300921/144977175-30e38c59-3c95-4f54-8ebe-2c3bbc21d274.jpg)

**Comment by anggita13** [comment]
> Kepada developer dan pengembangan terhadap bot WhatsApp, saya menemukan beberapa kali eror dalam menjalankan Script dari codingan anda.. ![BP_BOT_OFFICIAL](https://user-images.githubusercontent.com/80300921/144977175-30e38c59-3c95-4f54-8ebe-2c3bbc21d274.jpg)

Folder lib dan file  di Baileys nya gak ada tuh kak, sama seperti saya kasus nya, saya mengambil folder lib & file nya dari node_module lain dan berhasil.

Barangkali ingin mencoba
File https://www.mediafire.com/file/wv68zu5e3020g2s/lib.zip/file

Extract ke : node_modules/@adiwajshing/Baileys/disini

**Comment by Bintangp02** [comment]
Apakah anda bisa membantu?
Makasih developer wabot-aq

![Bintangofc](https://user-images.githubusercontent.com/80300921/145005047-40cdf525-c2f3-4262-bc50-6936145f7c6a.jpg)

**Comment by rishabh-modi2** [comment]
First do npm install

**Comment by Bintangp02** [comment]
> First do npm install

Saya sudah melakukan ny

**Comment by rishabh-modi2** [comment]
Update node version
Or use https://github.com/rishabh-modi2/jazza
Just a fork may be it works for you
