### ISSUE TITLE
Help me :)

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#958]
Bagai mana cara mengatasi nya..
How to handle it

![SUBSCRIBE_BPBOT_ON_YOUTUBE](https://user-images.githubusercontent.com/80300921/145005771-405f3cf0-80dd-4a50-92da-8295f281114f.jpg)

**Comment by Bintangp02** [comment]
#957

**Comment by Lord-Patrick** [comment]
`npm i -g npm@6.14.14 && npm install`

Trus run

**Comment by Bintangp02** [comment]
> 

Bagai mana jika nodedemon yg eror?

**Comment by Bintang73** [comment]
> > 
> 
> Bagai mana jika nodedemon yg eror?

`npm i -g nodemon`
