### ISSUE TITLE
Upload a media/file from Vps

### ISSUE THREAD

**Issue by rishabh-modi2** [Nurutomo/wabot-aq#961]
Can you please add a features so that we can
Upload a file present in the the same directory where bot is running to the WhatsApp.

**Comment by ariffb25** [comment]
https://nodejs.org/api/fs.html

use writeFileSync ?

**Comment by rishabh-modi2** [comment]
how to export this function to handler

**Comment by Bintang73** [comment]
> how to export this function to handler

`description`

understand and learn the "fs" module. don't forget to sort the file type. in the form of documents, music images or others. if you have tried and succeeded, you can do a pull request.

`Example code`

> const fs = require("fs")
const mediaData = ( from data file doc, img, other )
const loc = ( the location you will save ) ex ../myDoc.pdf
fs.writeFileSync(mediaData, loc)

Thanks
