### ISSUE TITLE
Bagaimana cara delete semua yg ada di listmsg/image/video/sticker ?

### ISSUE THREAD

**Issue by Andika856** [Nurutomo/wabot-aq#962]
Gmn cara delete semua yg ada di listmsg/video/image/stiker tanpa delete satu-satu?

**Comment by Andika856** [comment]
> ketik di wa
> 
> ```
> => delete db.data.msgs
> ```
> 
> atau
> 
> ```
> => db.data.msgs = {}
> ```

![Screenshot_2021-12-11-08-23-31-45](https://user-images.githubusercontent.com/78887981/145658874-f50363f2-0f2d-47d7-8609-8b6d37143401.jpg)

**Comment by Bintang73** [comment]
> > ketik di wa
> > ```
> > => delete db.data.msgs
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > atau
> > ```
> > => db.data.msgs = {}
> > ```
> 
> ![Screenshot_2021-12-11-08-23-31-45](https://user-images.githubusercontent.com/78887981/145658874-f50363f2-0f2d-47d7-8609-8b6d37143401.jpg)

Pake exec bukan command
Pake => bukan #

**Comment by Andika856** [comment]
> > > ketik di wa
> > > ```
> > > => delete db.data.msgs
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > atau
> > > ```
> > > => db.data.msgs = {}
> > > ```
> > 
> > 
> > ![Screenshot_2021-12-11-08-23-31-45](https://user-images.githubusercontent.com/78887981/145658874-f50363f2-0f2d-47d7-8609-8b6d37143401.jpg)
> 
> Pake exec bukan command Pake => bukan #

![IMG_20211222_225857](https://user-images.githubusercontent.com/78887981/147120503-593b71f0-51c5-4d49-b0e1-2958c6bb1647.jpg)

Uhhh gw harus buat paan y

**Comment by ariffb25** [comment]
{} itu udh kosong, langsung aja cek listmsg

**Comment by Andika856** [comment]
> {} itu udh kosong, langsung aja cek listmsg

Kalo cmd gmn?

**Comment by unx21** [comment]
> > {} itu udh kosong, langsung aja cek listmsg
> 
> Kalo cmd gmn?

Yaa tinggal .delmsg A

**Comment by Andika856** [comment]
> 

![Screenshot_2021-12-27-12-54-21-62](https://user-images.githubusercontent.com/78887981/147439219-b9385faa-9633-4d85-949b-bdb97fb2f508.jpg)
Masalahnya itu listmsg di bot saya kosong padahal ada msg nya yg tersimpan jadi gw gabisa tau apa aja msg nya yg tersimpan

**Comment by unx21** [comment]
Waw
