### ISSUE TITLE
cara dapet apikey gmn webnya apinya gabisa dibuka

### ISSUE THREAD

**Issue by aqlabriyan** [Nurutomo/wabot-aq#963]
![image](https://user-images.githubusercontent.com/78632978/145507548-ba97a35c-564a-4a2e-a20a-76a9f4c43cf6.png)

**Comment by unx21** [comment]
Tunggu aja, nanti juga balik web nya

**Comment by Bintang73** [comment]
> ![image](https://user-images.githubusercontent.com/78632978/145507548-ba97a35c-564a-4a2e-a20a-76a9f4c43cf6.png)

Silahkan di cek kembali, maaf sudah menunggu.
