### ISSUE TITLE
HEROKU CAN'T DEPLOY

### ISSUE THREAD

**Issue by XstepAhead** [Nurutomo/wabot-aq#964]
-----> Building on the Heroku-20 stack
-----> Determining which buildpack to use for this app
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 14.x...
       Downloading and installing node 14.18.2...
       Using default npm version: 6.14.15
       
-----> Installing dependencies
       Installing node modules (package.json)
       
       > @adiwajshing/baileys@3.5.3 prepack /tmp/npmcache.8Nisj/_cacache/tmp/git-clone-68d835cd
       > tsc
       
       sh: 1: tsc: not found
       npm ERR! premature close
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.8Nisj/_logs/2021-12-10T03_47_28_284Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by Bintangp02** [comment]
> -----> Building on the Heroku-20 stack -----> Determining which buildpack to use for this app -----> Node.js app detected
> 
> -----> Creating runtime environment
> 
> ```
>    NPM_CONFIG_LOGLEVEL=error
>    NODE_VERBOSE=false
>    NODE_ENV=production
>    NODE_MODULES_CACHE=true
> ```
> 
> -----> Installing binaries engines.node (package.json): unspecified engines.npm (package.json): unspecified (use default)
> 
> ```
>    Resolving node version 14.x...
>    Downloading and installing node 14.18.2...
>    Using default npm version: 6.14.15
> ```
> 
> -----> Installing dependencies Installing node modules (package.json)
> 
> ```
>    > @adiwajshing/baileys@3.5.3 prepack /tmp/npmcache.8Nisj/_cacache/tmp/git-clone-68d835cd
>    > tsc
>    
>    sh: 1: tsc: not found
>    npm ERR! premature close
>    
>    npm ERR! A complete log of this run can be found in:
>    npm ERR!     /tmp/npmcache.8Nisj/_logs/2021-12-10T03_47_28_284Z-debug.log
> ```
> 
> -----> Build failed
> 
> ```
>    We're sorry this build is failing! You can troubleshoot common issues here:
>    https://devcenter.heroku.com/articles/troubleshooting-node-deploys
>    
>    Some possible problems:
>    
>    - Node version not specified in package.json
>      https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
>    
>    Love,
>    Heroku
> ```
> 
> ! Push rejected, failed to compile Node.js app. ! Push failed

Perlu anda ketahui sebelum anda run terlebih dahulu anda harus menambahkan Heroku Buildpacks ,
Buildpacks yang di pakai adalah 
[FFMPEG](https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest)
[IMAGEMAGICK](https://github.com/DuckyTeam/heroku-buildpack-imagemagick)

There are more questions maybe me or someone else can help

**Comment by XstepAhead** [comment]
sama aja ga bisa
