### ISSUE TITLE
why is this

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#965]
Saya sudah meng-install semua nya 
Kenapa masih saja eror seperti ini?

![SUBSCRIBE_YT_BPBOTOFFICIAL_2021](https://user-images.githubusercontent.com/80300921/145665339-a5b2a352-e96f-428b-86f8-53e1b0ff5d9f.jpg)

**Comment by Bintang73** [comment]
npm cache clean
npm i -g nodemon
