### ISSUE TITLE
Ini kenapa?

### ISSUE THREAD

**Issue by WanAdhwa9981** [Nurutomo/wabot-aq#969]
![Screenshot_2021-12-12-19-46-22-72](https://user-images.githubusercontent.com/95233141/145711317-936a8019-ec78-4be8-bb93-769039d27898.png)

**Comment by Adiixyz** [comment]
pake npm versi berapa?

**Comment by NugrahaMP** [comment]
sama bang, gw juga gitu. padahal udah npm update, tapi tetep aja

**Comment by qisyana** [comment]
termux-setup-storage
  pkg upgrade
  pkg update
  pkg install nodejs
  pkg install git
  pkg install libwebp
  pkg install ffmpeg
  pkg install imagemagick
  pkg install tesseract
  pkg install wget
  pkg install mc

  git clone https://github.com/Nurutomo/wabot-aq/
  cd wabot-aq
  npm -g install npm@6.14.10
  npm i
  npm start

**Comment by NugrahaMP** [comment]
![Screenshot_2021-12-14-01-25-05-641_com termux](https://user-images.githubusercontent.com/86095279/145859470-11eca9da-f486-465d-a9d8-25c269e41e6f.jpg)

masih sama aja bang

**Comment by qisyana** [comment]
npm i github:melcanz/baileys

**Comment by Bintangp02** [comment]
> npm i github:melcanz/baileys

Wabot-aq mengunakan [github](https://github.com/adiwajshing/Baileys)
Bukan mengunakan github dari melcanz/baileys dan yang mengunakan melcanz/baileys adalah Setikerin

**Comment by qisyana** [comment]
> > npm i github:melcanz/baileys
> 
> Wabot-aq mengunakan [github](https://github.com/adiwajshing/Baileys) Bukan mengunakan github dari melcanz/baileys dan yang mengunakan melcanz/baileys adalah Setikerin

Aku pakai file wabot-aq tapi install  npm i github:melcanz/baileys ga ada yg error? Node modules nya tuh aman

**Comment by qisyana** [comment]
Nih ku buat video tentang memasang termux :)

**Comment by NugrahaMP** [comment]
iya nih, perlu video juga untuk pemasangan nya
