### ISSUE TITLE
Bang Kok Gw Module Not Found? Padahal gw udh ngikutin cara di github abg udh npm start DLL

### ISSUE THREAD

**Issue by Purwandani14** [Nurutomo/wabot-aq#972]
![Screenshot_20211214_141553](https://user-images.githubusercontent.com/81657050/145950818-25fe4b96-5e55-4d3f-afdc-e9c31437d524.png)

**Comment by DwiRizqiH** [comment]
Sudah `npm i` ?

kalo sudah, coba `npm i cfonts`

**Comment by Purwandani14** [comment]
Udh bg

**Comment by DwiRizqiH** [comment]
coba `npm i cfonts`

trus start botnya

**Comment by DwiRizqiH** [comment]
Sama-Sama.

Dimohon Issuenya di close.
