### ISSUE TITLE
Apa yang menjadi masalah ?

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#973]
![YT_BPBOT_OFFICIAL](https://user-images.githubusercontent.com/80300921/146002533-92f5b0ec-6b2c-4bc1-b99c-b31ab5f1f232.png)

Bagai mana bisa eror?, 
Bagai mana cara mengatasinya? 
Saya sudah meng-install semua nya otomatis dari docker file !

What's the solution?

Mohon bantuan nya :>
Thanks

Maslah ini hampir sama dengan issue #969

**Comment by Lord-Patrick** [comment]
ya itu sama solusi nya

**Comment by Bintang73** [comment]
npm i @adiwajshing/baileys@^3.5.3

**Comment by NugrahaMP** [comment]
gabisa pake "npm i @adiwajshing/baileys@^3.5.3" bang. hasilnya sama aja

**Comment by unx21** [comment]
cd wabot-aq
bash install.sh


Barangkali work, semalam saya udah coba dan hasilnya oke aja

**Comment by NugrahaMP** [comment]
nope, ga ada yg berubah sama sekali

**Comment by NugrahaMP** [comment]
![Uploading Screenshot_2021-12-16-13-41-14-024_com.termux.jpg…]()

**Comment by unx21** [comment]
?

**Comment by unx21** [comment]
> nope, ga ada yg berubah sama sekali

Hmm bingung sih, w udah ikutin semua yang di tulis di README.md nya, pertama emang error tapi waktu bash install.sh udah work instalansi nya

**Comment by tes8924** [comment]
> bash install.sh

masih aja eror


internal/modules/cjs/loader.js:305
      throw err;
      ^

Error: Cannot find module '/home/tes_83_84_6/wabot-aq/node_modules/@adiwajshing/baileys/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:297:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:528:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:27)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/tes_83_84_6/wabot-aq/main.js:2:41)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/tes_83_84_6/wabot-aq/node_modules/@adiwajshing/baileys/package.json',
  requestPath: '@adiwajshing/baileys'
}
Exited with code: 1


eror saat saya run ke vps,rdp,google console,

kalau termux work work aja

**Comment by tes8924** [comment]
> gabisa pake "npm i @adiwajshing/baileys@^3.5.3" bang. hasilnya sama aja

sama di termux work work aja wkwkw semoga di perbaki oleh Collaborator nya nurutomo
