### ISSUE TITLE
???????

### ISSUE THREAD

**Issue by prioprast** [Nurutomo/wabot-aq#974]
Mau nanya, caranya ambil session buat deploy ke heroku caranya gimana ya?

Sekalian beri tau langkah langkahnya menggunakan bot di heroku #pemula

**Comment by unx21** [comment]
> Mau nanya, caranya ambil session buat deploy ke heroku caranya gimana ya?
> 
> Sekalian beri tau langkah langkahnya menggunakan bot di heroku #pemula

Paling gampang nya itu nonton video di youtube aja sih, banyak yang upload cara pengambilan session maupun langkah² untuk penginstalan via heroku
