### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Andika856** [Nurutomo/wabot-aq#975]
Fitur utk ganti apikey bot pas bot masi jalan

**Comment by BochilGaming** [comment]
> Fitur utk ganti apikey bot pas bot masi jalan

Tinggal ganti aja di config.js

**Comment by ariffb25** [comment]
> > Fitur utk ganti apikey bot pas bot masi jalan
> 
> Tinggal ganti aja di config.js

Nice answer Istikmal, ya karena kan ngedit di config juga ga perlu restart, lagian ganti apikey juga ga tiap jam/menit kan. Pake exec juga bisa

**Comment by Bintang73** [comment]
Run this code 


`#> global.Apikey['https://api.xteam.xyz'] = 'apikeymu'`
