### ISSUE TITLE
kak eror sc nya di aku ada bs bntu gk

### ISSUE THREAD

**Issue by fitzgntngxd** [Nurutomo/wabot-aq#977]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Lord-Patrick** [comment]
error apa nya anjir, lebih jelas dikin anjir

anjir anjir anjir

**Comment by DwiRizqiH** [comment]
Ga jelas, error apanya?

Kalo ngasih judul/pendapat yang benar, dipikir dulu!
Kata² **Rusak** ,  membuat orang yang ikut berkontribusi/membuat SC ini Merasa Tersinggung/Terhina, Termasuk saya

Lebih baik memakai kata² **Error!** Daripada **Rusak**


Dan juga kalau membuat issue yang bener dikit **NGOTAK!,** kasih error apanya
Lu kira yang Berkontribusi/membuat SC ini langsung tau kalau yang error apa, cuman modal kata² **njir**


Kalu lu cuman becanda, bukan tempatnya.
Github ini tempatnya orang² professional

**Comment by fitzgntngxd** [comment]
Minta dong WA nya soal nya di gw eror lo

Pada tanggal Rab, 22 Des 2021 08.03, Dwi Rizqi ***@***.***>
menulis:

**Comment by DwiRizqiH** [comment]
wa.me/6281358181668

**Comment by Bintang73** [comment]
Lain kali deskripsikan error yang bener
