### ISSUE TITLE
.ig Command not working 

### ISSUE THREAD

**Issue by Cosmic-Bug** [Nurutomo/wabot-aq#978]
The .ig command is returning media not found output. why?
Tried with both public & private accounts but not working.

**Comment by ariffb25** [comment]
@Bintang73 looks like it needs to be fixed

https://xteam.xyz/dl/ig?url=https://www.instagram.com/p/CQKtlbLpbTA/?utm_medium=copy_link&APIKEY=
```
{
    "code": 400,
    "status": false,
    "message": "Media Tidak Ditemukan!"
}
```

**Comment by DwiRizqiH** [comment]
I have .ig with scrape method.

Wait, I'll make it, I'll pull the request later

**Comment by Bintang73** [comment]
> @Bintang73 looks like it needs to be fixed
> 
> https://xteam.xyz/dl/ig?url=https://www.instagram.com/p/CQKtlbLpbTA/?utm_medium=copy_link&APIKEY=
> 
> ```
> {
>     "code": 400,
>     "status": false,
>     "message": "Media Tidak Ditemukan!"
> }
> ```

Wait i forgot my python on xteam,..

**Comment by Bintang73** [comment]
> @Bintang73 looks like it needs to be fixed
> 
> https://xteam.xyz/dl/ig?url=https://www.instagram.com/p/CQKtlbLpbTA/?utm_medium=copy_link&APIKEY=
> 
> ```
> {
>     "code": 400,
>     "status": false,
>     "message": "Media Tidak Ditemukan!"
> }
> ```

Use igv2

https://api.xteam.xyz/dl/igv2?url=https://www.instagram.com/p/CAAZ1VcA2OA/&APIKEY=APIKEYMU

**Comment by Cosmic-Bug** [comment]
> > @Bintang73 looks like it needs to be fixed
> > https://xteam.xyz/dl/ig?url=https://www.instagram.com/p/CQKtlbLpbTA/?utm_medium=copy_link&APIKEY=
> > ```
> > {
> >     "code": 400,
> >     "status": false,
> >     "message": "Media Tidak Ditemukan!"
> > }
> > ```
> 
> Use igv2
> 
> https://api.xteam.xyz/dl/igv2?url=https://www.instagram.com/p/CAAZ1VcA2OA/&APIKEY=APIKEYMU

Where do i put this piece of code?

**Comment by unx21** [comment]
> > > @Bintang73 looks like it needs to be fixed
> > > https://xteam.xyz/dl/ig?url=https://www.instagram.com/p/CQKtlbLpbTA/?utm_medium=copy_link&APIKEY=
> > > ```
> > > {
> > >     "code": 400,
> > >     "status": false,
> > >     "message": "Media Tidak Ditemukan!"
> > > }
> > > ```
> > 
> > 
> > Use igv2
> > https://api.xteam.xyz/dl/igv2?url=https://www.instagram.com/p/CAAZ1VcA2OA/&APIKEY=APIKEYMU
> 
> Where do i put this piece of code?

fetch maybe ?

**Comment by Cosmic-Bug** [comment]
> > > > @Bintang73 looks like it needs to be fixed
> > > > https://xteam.xyz/dl/ig?url=https://www.instagram.com/p/CQKtlbLpbTA/?utm_medium=copy_link&APIKEY=
> > > > ```
> > > > {
> > > >     "code": 400,
> > > >     "status": false,
> > > >     "message": "Media Tidak Ditemukan!"
> > > > }
> > > > ```
> > > 
> > > 
> > > Use igv2
> > > https://api.xteam.xyz/dl/igv2?url=https://www.instagram.com/p/CAAZ1VcA2OA/&APIKEY=APIKEYMU
> > 
> > 
> > Where do i put this piece of code?
> 
> fetch maybe ?

Did anyone fix the ig command ?

@Bintang73 @DwiRizqiH @ariffb25 @unx21
