### ISSUE TITLE
Bang kok tetep gak bisa?

### ISSUE THREAD

**Issue by fuadxtps23** [Nurutomo/wabot-aq#979]
![Screenshot (25)](https://user-images.githubusercontent.com/93533757/147109955-22b418eb-a151-4a92-bb7c-244ee8469583.png)

**Comment by fuadxtps23** [comment]
padahal udah `npm i` sama `npm i cfonts`

**Comment by ariffb25** [comment]
ubah di package.json bagian dependencies

github:melcanz/Baileys

**Comment by fuadxtps23** [comment]
![Screenshot (26)](https://user-images.githubusercontent.com/93533757/147124459-3af44158-26fa-438e-a60e-d6a4831aa9aa.png)

Udah `npm install` sama `npm update` tetep gak bisa bang, gimana ni?

**Comment by fuadxtps23** [comment]
tar gw berubah pikiran harusnya gini ya bang udah work jadi di close ya

```
  "dependencies": {
    "@adiwajshing/baileys": "github:melcanz/baileys"
```
