### ISSUE TITLE
cara biar semuanya ga perlu make prefix gimana?

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#98]
(no prefix)

**Comment by elssword** [comment]
handler.customPrefix =/menu|help/i
Kayak gitu kah yg di maksud

**Comment by Ftwrr** [comment]
> handler.customPrefix =/menu|help/i
> Kayak gitu kah yg di maksud

ngga bukan gitu yang aku maksud
kalo digituin ribet
maksudnya tuh biar semuanya(semua command) ga perlu make prefix kayak selfbot gitu

**Comment by Nurutomo** [comment]
global.prefix = new RegExp

**Comment by Ftwrr** [comment]
> ```js
> global.prefix = new RegExp
> ```

dimana

**Comment by RC047** [comment]
> 
> 
> > ```js
> > global.prefix = new RegExp
> > ```
> 
> dimana

di main.js
