### ISSUE TITLE
Introduce chatbot 

### ISSUE THREAD

**Issue by Cosmic-Bug** [Nurutomo/wabot-aq#985]
A chatbot if enabled, talks like a bot with random msgs or something.

**Comment by DwiRizqiH** [comment]
Like SimSimi or AI?

**Comment by Bintang73** [comment]
Use simsimi xteam, unlimited request with premium account

**Comment by Cosmic-Bug** [comment]
While using simsimi every time user have to type .simsimi then the msg, i was not saying abt that.

If the option is enabled the bot will reply with some coversations with the user like in some other wapp bots

**Comment by ariffb25** [comment]
> While using simsimi every time user have to type .simsimi then the msg, i was not saying abt that.
> 
> If the option is enabled the bot will reply with some coversations with the user like in some other wapp bots

hmm okay, just wait

**Comment by unx21** [comment]
Yatta, new feature again

**Comment by Cosmic-Bug** [comment]
> > While using simsimi every time user have to type .simsimi then the msg, i was not saying abt that.
> > If the option is enabled the bot will reply with some coversations with the user like in some other wapp bots
> 
> hmm okay, just wait
> 
> but its already on my repository

Please share and tell me how to integrate that module to this.

**Comment by ariffb25** [comment]
> > > While using simsimi every time user have to type .simsimi then the msg, i was not saying abt that.
> > > If the option is enabled the bot will reply with some coversations with the user like in some other wapp bots
> > 
> > 
> > hmm okay, just wait
> > but its already on my repository
> 
> Please share and tell me how to integrate that module to this, or can i add it by just copying the module to plugins folder.

https://github.com/Nurutomo/wabot-aq/commit/585b63483bc23c41aaa1bcc8f22f46b38caaf79f

**Comment by Cosmic-Bug** [comment]
> > > > While using simsimi every time user have to type .simsimi then the msg, i was not saying abt that.
> > > > If the option is enabled the bot will reply with some coversations with the user like in some other wapp bots
> > > 
> > > 
> > > hmm okay, just wait
> > > but its already on my repository
> > 
> > 
> > Please share and tell me how to integrate that module to this, or can i add it by just copying the module to plugins folder.
> 
> [585b634](https://github.com/Nurutomo/wabot-aq/commit/585b63483bc23c41aaa1bcc8f22f46b38caaf79f)

Ah okay just need to update i think

**Comment by Cosmic-Bug** [comment]
> > > > While using simsimi every time user have to type .simsimi then the msg, i was not saying abt that.
> > > > If the option is enabled the bot will reply with some coversations with the user like in some other wapp bots
> > > 
> > > 
> > > hmm okay, just wait
> > > but its already on my repository
> > 
> > 
> > Please share and tell me how to integrate that module to this, or can i add it by just copying the module to plugins folder.
> 
> [585b634](https://github.com/Nurutomo/wabot-aq/commit/585b63483bc23c41aaa1bcc8f22f46b38caaf79f)

This is not working bro, repeatedly giving an error '521 undefined' 

@ariffb25
