### ISSUE TITLE
Auto reply

### ISSUE THREAD

**Issue by Cosmic-Bug** [Nurutomo/wabot-aq#986]
If enables replies with sticker from the local database corresponding to the msg another user sends in the grp or in pchat.
We can set the  sticker by replying or caption the sticker.

**Comment by Bintang73** [comment]
Nice feature, @ariffb25 can create it

**Comment by ariffb25** [comment]
I think it already exists, using the .setcmd command.
can u describe more Mr Cosmic-Bug?

**Comment by Cosmic-Bug** [comment]
> I think it already exists, using the .setcmd command. can u describe more Mr Cosmic-Bug?

How to set auto reply using .setcmd i am getting error when using the .setcmd "SHA256 Hash missing" this error

What i was saying is that we can upload stickers or txt msgs to local db which will be snd/replied by the bot whenever the matching query is snd by some user in the group or in Pm. Example if a person sends hello in thr pm of bot, the bot replies with Hello/Hey.

**Comment by ariffb25** [comment]
reply message to be used as answer bot, then use .addmsg command

for example I use my girlfriend's bot XD https://github.com/melcanz/melcanz-bot have the same with wabot-aq, but im the dev

![image](https://user-images.githubusercontent.com/76026450/147226535-233c0256-58e8-4137-8111-edcf36814a6c.png)

![image](https://user-images.githubusercontent.com/76026450/147226552-b1db3b83-d06d-40d3-a355-faa5446e599a.png)

maybe this is what you mean?

**Comment by Cosmic-Bug** [comment]
> reply message to be used as answer bot, then use .addmsg command
> 
> for example I use my girlfriend's bot XD https://github.com/melcanz/melcanz-bot have the same with wabot-aq, but im the dev
> 
> ![image](https://user-images.githubusercontent.com/76026450/147226535-233c0256-58e8-4137-8111-edcf36814a6c.png)
> 
> ![image](https://user-images.githubusercontent.com/76026450/147226552-b1db3b83-d06d-40d3-a355-faa5446e599a.png)
> 
> maybe this is what you mean?

Yes some what like this bt not forwarding, the msg should come as it is snd by the bot without forwarded caption.

**Comment by unknowkzr** [comment]
> > reply message to be used as answer bot, then use .addmsg command
> > for example I use my girlfriend's bot XD https://github.com/melcanz/melcanz-bot have the same with wabot-aq, but im the dev
> > ![image](https://user-images.githubusercontent.com/76026450/147226535-233c0256-58e8-4137-8111-edcf36814a6c.png)
> > ![image](https://user-images.githubusercontent.com/76026450/147226552-b1db3b83-d06d-40d3-a355-faa5446e599a.png)
> > maybe this is what you mean?
> 
> Yes some what like this bt not forwarding, the msg should come as it is snd by the bot without forwarded caption.

The F

**Comment by unx21** [comment]
> > reply message to be used as answer bot, then use .addmsg command
> > for example I use my girlfriend's bot XD https://github.com/melcanz/melcanz-bot have the same with wabot-aq, but im the dev
> > ![image](https://user-images.githubusercontent.com/76026450/147226535-233c0256-58e8-4137-8111-edcf36814a6c.png)
> > ![image](https://user-images.githubusercontent.com/76026450/147226552-b1db3b83-d06d-40d3-a355-faa5446e599a.png)
> > maybe this is what you mean?
> 
> Yes some what like this bt not forwarding, the msg should come as it is snd by the bot without forwarded caption.

Damnn

**Comment by CodeLover-001** [comment]
> > reply message to be used as answer bot, then use .addmsg command
> > for example I use my girlfriend's bot XD https://github.com/melcanz/melcanz-bot have the same with wabot-aq, but im the dev
> > ![image](https://user-images.githubusercontent.com/76026450/147226535-233c0256-58e8-4137-8111-edcf36814a6c.png)
> > ![image](https://user-images.githubusercontent.com/76026450/147226552-b1db3b83-d06d-40d3-a355-faa5446e599a.png)
> > maybe this is what you mean?
> 
> Yes some what like this bt not forwarding, the msg should come as it is snd by the bot without forwarded caption.

Damn 😂

**Comment by Cosmic-Bug** [comment]
> > > reply message to be used as answer bot, then use .addmsg command
> > > for example I use my girlfriend's bot XD https://github.com/melcanz/melcanz-bot have the same with wabot-aq, but im the dev
> > > ![image](https://user-images.githubusercontent.com/76026450/147226535-233c0256-58e8-4137-8111-edcf36814a6c.png)
> > > ![image](https://user-images.githubusercontent.com/76026450/147226552-b1db3b83-d06d-40d3-a355-faa5446e599a.png)
> > > maybe this is what you mean?
> > 
> > 
> > Yes some what like this bt not forwarding, the msg should come as it is snd by the bot without forwarded caption.
> 
> Damn 😂 Just add `context { forwardScore: 2, isForwarded: true }`

where?
