### ISSUE TITLE
User verification and registration

### ISSUE THREAD

**Issue by Cosmic-Bug** [Nurutomo/wabot-aq#987]
Introduce the verification method from "moo-d" (github username) whatsapp-bot with the currently available .reg feature.
It will be more easy method and less complex 

https://github.com/moo-d/termux-whatsapp-bot

**Comment by CodeLover-001** [comment]
> Introduce the verification method from "moo-d" (github username) whatsapp-bot with the currently available .reg feature. It will be more easy method and less complex
> 
> https://github.com/moo-d/termux-whatsapp-bot

Already reg feature is there!

**Comment by unx21** [comment]
> > > Introduce the verification method from "moo-d" (github username) whatsapp-bot with the currently available .reg feature. It will be more easy method and less complex
> > > https://github.com/moo-d/termux-whatsapp-bot
> > 
> > 
> > Already reg feature is there! Just add:
> > ```
> > handler.register = true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In your plugin to make it "reg to use"
> 
> Where do i need to put that . in main menu.js or register.js file?

all files that, when you want to be used by others, will require registration first

**Comment by Cosmic-Bug** [comment]
> > > > Introduce the verification method from "moo-d" (github username) whatsapp-bot with the currently available .reg feature. It will be more easy method and less complex
> > > > https://github.com/moo-d/termux-whatsapp-bot
> > > 
> > > 
> > > Already reg feature is there! Just add:
> > > ```
> > > handler.register = true
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > In your plugin to make it "reg to use"
> > 
> > 
> > Where do i need to put that . in main menu.js or register.js file?
> 
> all files that, when you want to be used by others, will require registration first

Okay thankyou bro
