### ISSUE TITLE
[Help] cara mereset semua limit user ke 0

### ISSUE THREAD

**Issue by FadliDarmawan** [Nurutomo/wabot-aq#991]
Cara Mereset semua limit user yang ada di dalam database.json menjadi 0 tanpa menghapus database.json?

**Comment by ariffb25** [comment]
1. buat array objek dari global.db.data.users
2. lakukan perulangan
3. isi perulangan ```global.db.data.users[id].limit = 0```
4. selesai

**Comment by unknowkzr** [comment]
> 1. buat array objek dari global.db.data.users
> 2. lakukan perulangan
> 3. isi perulangan `global.db.data.users[id].limit = 0`
> 4. selesai

Gapaham bang
coba jelasin lebih detail

**Comment by unx21** [comment]
> > 1. buat array objek dari global.db.data.users
> > 2. lakukan perulangan
> > 3. isi perulangan `global.db.data.users[id].limit = 0`
> > 4. selesai
> 
> Gapaham bang coba jelasin lebih detail

Contoh nih yak

=> global.db.data.users['6288xxxxx@s.whatsapp.net'].limit = 0

Itu id nya diisi nomor yang mau di ubah limit nya atau bisa diisi juga dengan cara

=> global.db.data.users[m.quoted.sender].limit = 0

Cara nya tinggal reply/balas orang yang limit nya mau kamu hapus. ingat, *REPLY* bukan tag

**Comment by unknowkzr** [comment]
> > > 1. buat array objek dari global.db.data.users
> > > 2. lakukan perulangan
> > > 3. isi perulangan `global.db.data.users[id].limit = 0`
> > > 4. selesai
> > 
> > 
> > Gapaham bang coba jelasin lebih detail
> 
> Contoh nih yak
> 
> => global.db.data.users['[6288xxxxx@s.whatsapp.net](mailto:6288xxxxx@s.whatsapp.net)'].limit = 0
> 
> Itu id nya diisi nomor yang mau di ubah limit nya atau bisa diisi juga dengan cara
> 
> => global.db.data.users[m.quoted.sender].limit = 0
> 
> Cara nya tinggal reply/balas orang yang limit nya mau kamu hapus. ingat, _REPLY_ bukan tag

Kalo cuma satu² gw juga dah tau
yg gw pengen langsung semua user kereset gacuma 1
atau make semua orang 1 grup limitnya direset make groupMetadata.id

**Comment by FadliDarmawan** [comment]
> 1. buat array objek dari global.db.data.users
> 2. lakukan perulangan
> 3. isi perulangan ```global.db.data.users[id].limit = 0```
> 4. selesai 

Array objek db.data.users nya bagaimana?

**Comment by ariffb25** [comment]
```js
Object.entries(global.db.data.users) 
```

**Comment by unknowkzr** [comment]
> ```js
> Object.entries(global.db.data.users) 
> ```

terus abis itu?

**Comment by ariffb25** [comment]
exec aja tuh di chat wa
```js
> let users = Object.entries(db.data.users).map(v => v[0])
for (id of users) db.data.users[id].limit = 0
return 'done'
```

**Comment by unknowkzr** [comment]
> exec aja tuh di chat wa
> 
> ```js
> > let users = Object.entries(db.data.users).map(v => v[0])
> for (id of users) db.data.users[id].limit = 0
> return 'done'
> ```

Nahh ini yang saya inginkan
mereset limit tanpa delete
ini udah termasuk semua yg di database kan?.

**Comment by FadliDarmawan** [comment]
> exec aja tuh di chat wa
> ```js
> > let users = Object.entries(db.data.users).map(v => v[0])
> for (id of users) db.data.users[id].limit = 0
> return 'done'
> ```

Kalau bikin auto reset semisal jam 12 malem gimana bang?

**Comment by ariffb25** [comment]
asah lah logika sendiri, jgn spoon-fed

**Comment by FadliDarmawan** [comment]
> asah lah logika sendiri, jgn spoon-fed
Kalau ga salah pake node cron...
Oklh makasih bang

**Comment by unknowkzr** [comment]
> asah lah logika sendiri, jgn spoon-fed

Mudah dimengerti semoga harimu menyenangkan
