### ISSUE TITLE
Baileys Error

### ISSUE THREAD

**Issue by zaintech01** [Nurutomo/wabot-aq#992]
I Tried to Install On My Kali Linux When I Run It Shows Baileys Error Can not Connect To whatts App Web How to Fix It

**Comment by Cosmic-Bug** [comment]
> I Tried to Install On My Kali Linux When I Run It Shows Baileys Error Can not Connect To whatts App Web How to Fix It

Try  npm i github:adiwajshing/baileys

Inside the bot folder

**Comment by zaintech01** [comment]
when i put npm i on my terminal after 15 mins and installing some dependicies it ends up and show error

**Comment by Cosmic-Bug** [comment]
> when i put npm i on my terminal after 15 mins and installing some dependicies it ends up and show error

Wt error did you get? 
Is there any sshots?

**Comment by Geruays** [comment]
> > when i put npm i on my terminal after 15 mins and installing some dependicies it ends up and show error
> 
> Wt error did you get? Is there any sshots?
![error](https://user-images.githubusercontent.com/84316160/148367936-3de6792f-2a34-4548-b6a4-8fa86a24dcf2.PNG)

**Comment by Cosmic-Bug** [comment]
> > > when i put npm i on my terminal after 15 mins and installing some dependicies it ends up and show error
> > 
> > 
> > Wt error did you get? Is there any sshots?
> > ![error](https://user-images.githubusercontent.com/84316160/148367936-3de6792f-2a34-4548-b6a4-8fa86a24dcf2.PNG)

It's just becoz of the missing index.js file inside the node_modules/@adiwajshing/baileys/lib/  folder

**Comment by Geruays** [comment]
> 

how can i fix it??

**Comment by Cosmic-Bug** [comment]
> > 
> 
> how can i fix it??
> 

Try installing baileys script again, either the stable or most updated script.

**Comment by Geruays** [comment]
> > > 
> > 
> > 
> > how can i fix it??
> 
> Try installing baileys script again, either the stable or most updated script.

It didnt work

**Comment by Cosmic-Bug** [comment]
> > > > 
> > > 
> > > 
> > > how can i fix it??
> > 
> > 
> > Try installing baileys script again, either the stable or most updated script.
> 
> It didnt work

Try most updated script it will work!
