### ISSUE TITLE
ttp, attp, stiker, dan stickergif error

### ISSUE THREAD

**Issue by Andika856** [Nurutomo/wabot-aq#993]
![Screenshot_2021-12-26-08-55-38-32](https://user-images.githubusercontent.com/78887981/147396909-5a09df12-8f29-41cf-b0d2-49c50404952c.jpg)

attp kasi stiker kosong, ttp kasi error, stickergif dan stiker conversion failed mulu

**Comment by Cosmic-Bug** [comment]
> ![Screenshot_2021-12-26-08-55-38-32](https://user-images.githubusercontent.com/78887981/147396909-5a09df12-8f29-41cf-b0d2-49c50404952c.jpg)
> 
> attp kasi stiker kosong, ttp kasi error, stickergif dan stiker conversion failed mulu

Its working fine for me 🤷🏻‍♂️

**Comment by Cosmic-Bug** [comment]
> > ![Screenshot_2021-12-26-08-55-38-32](https://user-images.githubusercontent.com/78887981/147396909-5a09df12-8f29-41cf-b0d2-49c50404952c.jpg)
> > attp kasi stiker kosong, ttp kasi error, stickergif dan stiker conversion failed mulu
> 
![Screenshot_2021-12-26-15-53-28-593_com whatsapp](https://user-images.githubusercontent.com/54317137/147405346-4d391330-0200-4b03-8f0c-3ffcc0ae3f78.jpg)
![Screenshot_2021-12-26-15-53-25-442_com whatsapp](https://user-images.githubusercontent.com/54317137/147405354-03b7d66f-4709-4e82-9869-1a0f1d449c54.jpg)

**Comment by unx21** [comment]
> > > ![Screenshot_2021-12-26-08-55-38-32](https://user-images.githubusercontent.com/78887981/147396909-5a09df12-8f29-41cf-b0d2-49c50404952c.jpg)
> > > attp kasi stiker kosong, ttp kasi error, stickergif dan stiker conversion failed mulu
> 
> ![Screenshot_2021-12-26-15-53-28-593_com whatsapp](https://user-images.githubusercontent.com/54317137/147405346-4d391330-0200-4b03-8f0c-3ffcc0ae3f78.jpg) ![Screenshot_2021-12-26-15-53-25-442_com whatsapp](https://user-images.githubusercontent.com/54317137/147405354-03b7d66f-4709-4e82-9869-1a0f1d449c54.jpg)

How can the sticker you made to stickergif?

**Comment by Cosmic-Bug** [comment]
What matters is, it working or not🤷🏻‍♂️

@unx21 @Andika856 

![IMG_20211227_113343](https://user-images.githubusercontent.com/54317137/147439795-20ba8c48-5cfb-46f9-bffb-51bfc6feb6ac.jpg)

**Comment by unx21** [comment]
Yeah
