### ISSUE TITLE
Brainly error

### ISSUE THREAD

**Issue by Andika856** [Nurutomo/wabot-aq#998]
![Screenshot_2021-12-27-19-49-18-60_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/78887981/147524189-63315bd4-ebdb-42ba-8e7a-a75e74a276c2.jpg)

**Comment by Cosmic-Bug** [comment]
Working fine for me😇
Try changing the file with the one in this repo🤷🏻‍♂️
