### ISSUE TITLE
Pls help me

### ISSUE THREAD

**Issue by Wahyudianshar** [Nurutomo/wabot-aq#999]
![Screenshot_2021_1228_171912](https://user-images.githubusercontent.com/77173960/147552479-2e801ded-a028-4455-9bbe-e3599b0c027e.jpg)
Bagaimana cara mengatasinya?
Sudah ku masukan module tapi masih saja begitu,, help me

**Comment by Cosmic-Bug** [comment]
Which module u have conflict ?

**Comment by Wahyudianshar** [comment]
> 

I don't know,, I can't Npm install

**Comment by Cosmic-Bug** [comment]
Npm install what? Which lib?

**Comment by Bintangp02** [comment]
```
 npm i && npm update
 ```

**atau**

```
 pkg install yarn && yarn
 ```

**Comment by Wahyudianshar** [comment]
Sudah lama bisanya bang,, cuma ini fitur brainly eror padahal banyak yg butuh fitur brianly :(
